### ISSUE TITLE
Crash due to java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by Armstark** [paulevsGitch/BetterNether#1]
So I just had my game crash due to this error in a custom modpack I'm working on, according to the log it was caused by Better Nether and Biomes O' Plenty from what I can see.

Anyway, I decided to make a new profile with only these two installed and sure enough, it crashed again.

I don't know if that's important, but it didn't happen during the initial worldgen but after I already had explored a bit into the nether.

It doesn't seem to crash like this without BoP, so seems to be some kind of incompatibility

More details from latest.log, beginning at the error and ending with the crash report:
https://pastebin.com/ucwUSi5V

**Comment by paulevsGitch** [comment]
I fixed it (I think), download new version from curseforge page
