### ISSUE TITLE
Nether Jellyfish disappear upon spawning in.

### ISSUE THREAD

**Issue by EnderBro123** [paulevsGitch/BetterNether#100]
Don't really need to say anything. Nether Jellyfish simply can't spawn, regardless of the difficulty. They instantaneously disappear upon doing so. Naturally and via egg.

Using the latest Better Nether version via Curse (2.7.3).

Also, not sure if you use Discord or not, but I could easily tell you if there's issues way more quickly.

**EDIT:** Apparently your "Render Fix" makes them completely invis.

**Comment by paulevsGitch** [comment]
Do you use snapshot version or 1.15 version?

**Comment by EnderBro123** [comment]
No. Why?

(Sorry for the late answer, was asleep at the time)

**Comment by paulevsGitch** [comment]
Looks like there are some changes in 20w19a API, I will fix it

**Comment by EnderBro123** [comment]
Ty. About your Discord though?

**Comment by paulevsGitch** [comment]
Personally I use Discord, but I don't think that my mod need a server in it. For now, I don't have enough time to support it. Probably later, if many players will ask me about it.

**Comment by EnderBro123** [comment]
Oh.

Well, for me it'd make reporting bugs a bit easier.

**Comment by paulevsGitch** [comment]
Mojang changed mob rendering and tracking a lot, most common mobs group are now related to their classes. I changed some values and now this is fixed. I will publish release soon.

**Comment by EnderBro123** [comment]
Ty.

**Comment by paulevsGitch** [comment]
2.7.4 is out, bug is fixed

**Comment by EnderBro123** [comment]
Ty.
