### ISSUE TITLE
BetterNether crashes on 20w20a/b

### ISSUE THREAD

**Issue by EnderBro123** [paulevsGitch/BetterNether#101]
No crash report is given. Mojang did more technical changes, thus, breaking the mod yet again.

**Comment by paulevsGitch** [comment]
I already know, mod is not working on 20w20a/b

**Comment by EnderBro123** [comment]
Oh.

**Comment by paulevsGitch** [comment]
New version was released, it should work fine

**Comment by EnderBro123** [comment]
Oh, ty
