### ISSUE TITLE
BetterNether server crashes (MinecraftFabric-1.16-pre-release-2)

### ISSUE THREAD

**Issue by Persival1488** [paulevsGitch/BetterNether#107]
[latest.log](https://github.com/paulevsGitch/BetterNether/files/4754671/latest.log)

**Comment by paulevsGitch** [comment]
I tried to fix this error many times and it still comes back. Sometimes config loads later than other content and drops everything with null pointer. I will try to fix it again

**Comment by paulevsGitch** [comment]
This error is floating, you can try to start again and it probably will be fine. I probably will upload new build tomorrow

**Comment by paulevsGitch** [comment]
Fixed in 2.7.8-1.16pre3. If issue still happens please reopen this issue.

**Comment by Jerome226** [comment]
This issue is present in better-nether-2.9.2-1.16rc1

**Comment by paulevsGitch** [comment]
I tried this now, the issue is different, but I will fix it

**Comment by paulevsGitch** [comment]
Now the reason is that one of recipe manager methods became client-side. I will release fix in a half of an hour

**Comment by paulevsGitch** [comment]
I released new version, it must work fine
