### ISSUE TITLE
[Suggestion] Minor flying pig addition

### ISSUE THREAD

**Issue by theishiopian** [paulevsGitch/BetterNether#108]
I love the new flying pig mob, almost exactly as i envisioned it. It is missing one thing though, it needs 2 stubby  little legs and a tail piece.for the tail, you can just do a single quad with a tail texture on it, at a slight angle to give the illusion of curling. You could even randomize its rotation a bit to give each pig more uniqueness. For the legs, jsut two little boxes towards the back would go a long way.

Other than that, I adore these new mobs, the wings are amazingly well done.

**Comment by paulevsGitch** [comment]
Thank you for additions, I will make them.

**Comment by paulevsGitch** [comment]
![2020-06-16_13 40 29](https://user-images.githubusercontent.com/17707380/84764854-08483200-afd7-11ea-8c8e-9e2d2fa9a013.png)
![2020-06-16_13 40 33](https://user-images.githubusercontent.com/17707380/84764862-0b432280-afd7-11ea-8615-3ccbb63f10fb.png)

**Comment by paulevsGitch** [comment]
This is in a new version now

**Comment by theishiopian** [comment]
Much better, thanks!
