### ISSUE TITLE
[Suggestion] New sub-biome

### ISSUE THREAD

**Issue by Fireface677** [paulevsGitch/BetterNether#109]
Hi paulevs, i have a new idea for a  sub-biome of the soulsand-valley.

- a new type of soul soil with a more blue/purple like color (a bit like obsidian in coloration) spawning in patches

- green fire spawning on the block above (would be a nice contrast)

- stalagmites/stalagtites made of some transparent quartz (like quartz glas but with a more crystal like texture)

- netherrack and glowstone stalagmites/stalagtites are not generated here

**Comment by paulevsGitch** [comment]
Same biome was implemented in [Biomes You Go](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric) mod

**Comment by Fireface677** [comment]
Yeah, thats right. I wrote that comment before i knew BYG and forgot to close this issue. But I still think that crystaline stalagmites would be a good idea. Maybe for a new biome in the future.
