### ISSUE TITLE
[Suggestion] Add Willow Leaves Block

### ISSUE THREAD

**Issue by EnderBro123** [paulevsGitch/BetterNether#110]
(Just wondering)

**Comment by paulevsGitch** [comment]
Probably yes

**Comment by paulevsGitch** [comment]
![2020-06-20_05 42 09](https://user-images.githubusercontent.com/17707380/85189565-d8d84480-b2b8-11ea-90d2-44b641149f9c.png)

**Comment by EnderBro123** [comment]
Oh.

Btw, will the hanging bulb things ever have a use?

**Comment by paulevsGitch** [comment]
Perhaps, but later

**Comment by EnderBro123** [comment]
Ok.

**Comment by paulevsGitch** [comment]
Now leaves are in mod

**Comment by EnderBro123** [comment]
Cool.
