### ISSUE TITLE
Jungle sound issues

### ISSUE THREAD

**Issue by theishiopian** [paulevsGitch/BetterNether#111]
The new jungle bg noise is very nice, a sort of more threatening version of the fungal forest. However, there are some minor issues with it. The first is that its too loud. Without touching the volume settings, the noise is about 1 and 1/2 times as loud as the normal ambiance. The second issue is that the sound, for lack of a better term, is "too close". It feels like I'm in a tiny room with a speaker making jungle noises. I'm not sure how to fix that, maybe more reverb, or some other filter? Anything so it sounds like its not just coming from 5 feet away, but from everywhere.

Other than these issues, the sound is fine, definitely a good choice for a jungle.

**Comment by paulevsGitch** [comment]
Thank you, I'm preparing some enhancements for jungle sound. I also made another variation of it, with leaves and more nether-like creatures sounds.
I will make it less loud and add more reverberation, so it will feel like big cave.
[Sound Itself](https://yadi.sk/d/-vyNAQf7j5LbRg)

**Comment by theishiopian** [comment]
that sounds awesome, I think those changes will really make the jungle feel unique

**Comment by paulevsGitch** [comment]
Now it is in mod

**Comment by theishiopian** [comment]
the new sound is much better, well done
