### ISSUE TITLE
[suggestion] Nether biome ideas

### ISSUE THREAD

**Issue by Brickboss-tech** [paulevsGitch/BetterNether#113]
Hi, I really like this mod, I have some biome suggestions.

1. Sulfurous fields (a biome made out of sulfur blocks, a notable feature would be clouds of sulfurous gas that floats around all over the biome and would be about 5-10 blocks in diameter. Walking through the clouds would give the player blindness and a new effect called suffocation. The fog colour for this biome would be yellow).

2. Magma canyon (a biome made out of netherrack or if you want a new block but it would be like a mesa biome with giant canyons and flowing lava rivers at the bottom. What would be even cooler is if the lava actually flowed and lead into one of the lava oceans. The colour of the fog would be dark red or light grey).

3. Fiery mountains (a biome that connects to the magma canyons. This biome would be made out of magma blocks and netherrack and lava would flow off the magma blocks as if it was melting into the lava. As the lava flows deeper down, it would form/enter the magma canyons. Fog colour would be dark grey).

4.Blazing inferno (a biome filled with fire and soul fire. It would also have plants that can set players on fire and would also have a new block called ash. Also, maybe a new mob called the the scorched and magma cubes could spawn there. Fog colour would be bright orange or red).

5. Fiery bamboo forest (a biome filled with fiery bamboo trees that can also be used for scaffolding. The ground would be made up of soul soil or nether moss. The fog colour would be dark green).

6. Sizzling redwood forest (a biome filled with fiery redwood trees that would grow on nether moss or soul soil. The trees would have fiery vines and the fog colour would be a bright red).

Next, I have some lava ocean biomes. I was thinking maybe you could add a potion that would allow you to see more clearly in and swim through lava.

1. Sizzling coral biome (a biome with fiery coral reefs under the lava that can be used as decorational blocks or maybe for potions. Fog colour would be pink).

2. Lava spikes (a biome in the lava ocean with spikes made up of netherrack, magma blocks, and obsidian that jut out the lava. They would have chests that make them worth exploring. Fog colour would be black).

Next, I have some sub-biome ideas.

1. Soulsand dessert (a sub-biome for the soulsand valley made up of soulsand and would contain shriveled cacti and withered cacti. The main mob would be wither skeletons and the fog colour would be light blue or light brown). I thought this was a good ideas since you have sub-biomes for all the other vanilla biomes.

2. Mega swampland (a sub-biome for the swampland biome filled with with giant willow trees instead of the small ones. The ground would be made up of nether moss and the fog colour would be dark pink.

Anyway, I hope you take these ideas into consideration as I feel they would make this mod even better.

Thank you for reading this.

**Comment by quiqueck** [comment]
Moving to our Enhancement List.
