### ISSUE TITLE
[Suggestion] Egg plants should burst when stepped on

### ISSUE THREAD

**Issue by theishiopian** [paulevsGitch/BetterNether#115]
Egg plants look like they are filled with something poisonous, at least to me. When you step on them and get poisoned, they should burst like a balloon, leaving a small lingering poison cloud behind.

**Comment by paulevsGitch** [comment]
Technically, this can be done, but I don't like idea of plant destruction. It is better if it will become inactive, change its shape and will recover over time.

**Comment by theishiopian** [comment]
yeah, i was thinking it could leave behind some leaves, then maybe regenerate after a few minutes.

**Comment by paulevsGitch** [comment]
Done in 3.0.1
