### ISSUE TITLE
These look like they could be called Lava Cactus 

### ISSUE THREAD

**Issue by EnderBro123** [paulevsGitch/BetterNether#116]
I think instead of just calling them Nether Cactus, they could be called Lava or Burning Cactus, hence their gray and orange look, and they could deal fire or half the amount of damage that lava does.
![2020-06-21_08 41 28](https://user-images.githubusercontent.com/51277766/85228886-20370180-b39b-11ea-8889-ee3ee0938a28.png)

Also, you kind of messed up the names for the quartz glass, it should be [Color] Quartz Glass,
not Quartz Glass [Color].
![2020-06-21_08 48 26](https://user-images.githubusercontent.com/51277766/85229016-1f529f80-b39c-11ea-9fa0-162e0b016d2a.png)

**Comment by paulevsGitch** [comment]
Fixed glass names, the name of Nether Cactus probably will stay the same
