### ISSUE TITLE
[Compatibility] Cinderscapes support

### ISSUE THREAD

**Issue by Wtoll** [paulevsGitch/BetterNether#121]
Hi I'm from the Cinderscapes team. I'm looking into a way that we might be able to ensure compatibility between our mods going forward. It's my understanding that BetterNether completely rewrites the current nether biome generator, leaving custom added biomes excluded from the new generation. (Slight tangent I looked into the impl and it also looks like the soul sand valley biome is missing. Not sure if that's intentional or not). Anyways we would like to look into a way that we can get these two mods working together and we had a couple different ideas as to how to approach the issue.

### Option 1
The first option is that we just create a simple pull request that specifically adds Cinderscapes' biomes to your already existing generator impl. This would definitely work but it would require updating every time a new biome was added, or if another mod that's not Cinderscapes would like to add a nether biome.

### Option 2
The second option solves the shortcomings of the first option. The plan would be to use the fabric api nether biome api to automatically add custom nether biomes to your custom generator when they're added through fabric api. This solution would be fairly elegant as it wouldn't require any extra overhead from mod developers and it would just magically work

### Option 3
The third option is a little more intense but we feel might ultimately be beneficial to all parties looking to add custom nether biomes, and that would be to write a separate library that rewrites the biome generator. We presume that the reason BetterNether overwrites the default vanilla generator is because frankly the default vanilla generator is kind of gross and uses nondescript and ineffective mixed noise points. We've noticed the same short comings but saw creating an entirely new generator as greater than the scope of our single project. For option 3 we propose the that custom nether biome generator functionality from BetterNether get moved into its own library that you and us here at the Terraformer's team can work collaboratively to develop. With a separate library it would reduce conflict between nether biome mods, ensure that all mods can work together instead of against one another, and provide the tools necessary to effectively modify biomes in the nether.

Let us know kind of what you think about which option we should pursue. We're looking forward to ensuring compatibility between our two projects.

**Comment by Prospector** [comment]
Do note, option 2 may require a new hook in fabric api in order to get all the biomes registered, I believe it is currently write-only. And option 3 would likely want to include bits of option 2 for compat with mods that wouldn't want to implement direct support in the lib.

**Comment by paulevsGitch** [comment]
Good day. I am glad that you think about the compatibility of our mods, and I have some remarks:

> leaving custom added biomes excluded from the new generation

It's wrong. In the [code](https://github.com/paulevsGitch/BetterNether/blob/master/src/main/java/paulevs/betternether/registry/BiomesRegistry.java#L90) you can see that each mod biome will get its wrapper and config options. Probably this function must be called after all mods loaded as registry may be incomplete at this stage, I will call it from another place (probably when server world is initiated). Wrappers doesn't replace original biomes, they are used only at generation stage.

>  like the soul sand valley biome is missing

It's also wrong, it is wrapped like all other biomes with same function and can be founded in game. It doesn't have its own constant in Registry as its generation is untouched.

![2020-06-25_09 13 40](https://user-images.githubusercontent.com/17707380/85665583-38bd5980-b6c4-11ea-9664-0c0285aaaa7b.png)


Actually you can just adds biomes with fabric api (or in any other way), their populators will be handled with this [code](https://github.com/paulevsGitch/BetterNether/blob/master/src/main/java/paulevs/betternether/mixin/common/ChunkPopulateMixin.java#L29) and they should generate correctly (or they will when I move wrapper function call to other place).

You can also use BetterNether biome registry if you want (for example if BetterNether is installed in pack). BetterNether has its own systems for many things like proper structure generation with collision boxes, plants & structures API, sub-biome system and many else.

The idea of a library seems interesting to me. This will allow many other mods to use this system, but the code will be slightly different from the current realization. I think this can probably be done in some weeks or faster

**Comment by Prospector** [comment]
Check out the `RegistryEntryAddedCallback` added by `fabric-registry-sync-v0` in Fabric API. If you loop over the Biome registry and then register a callback to call the same code, you can catch all the biomes that are registered after you already collected the existing ones.

**Comment by paulevsGitch** [comment]
I made it in more simple way - [code 1](https://github.com/paulevsGitch/BetterNether/blob/snapshots/src/main/java/paulevs/betternether/mixin/common/ServerWorldMixin.java#L31), [code 2](https://github.com/paulevsGitch/BetterNether/blob/snapshots/src/main/java/paulevs/betternether/registry/BiomesRegistry.java#L91).
It works. I don't know is it worse or better solution, but on server world start all biomes exists.

![2020-06-25_10 07 37](https://user-images.githubusercontent.com/17707380/85672721-dbc5a180-b6cb-11ea-8249-f1c5a6c01ad8.png)

And fog have a strange issue with density (a bit offsetted position from previous screenshot)

![2020-06-25_10 07 41](https://user-images.githubusercontent.com/17707380/85672797-ee3fdb00-b6cb-11ea-9f8f-876f768f885f.png)

**Comment by Wtoll** [comment]
Awesome thank you for how speedily that was implemented. That last part about the fog density is actually intentional though. However, it only applies to that specific biome.

**Comment by paulevsGitch** [comment]
Interesting

![2020-06-25_10 14 12](https://user-images.githubusercontent.com/17707380/85673529-a5d4ed00-b6cc-11ea-8ceb-cbe8100ce0d3.png)
![2020-06-25_10 16 06](https://user-images.githubusercontent.com/17707380/85673806-edf40f80-b6cc-11ea-8990-a618fd537df2.png)

**Comment by paulevsGitch** [comment]
> That last part about the fog density is actually intentional though. However, it only applies to that specific biome.

It's probably better to make fog density transition between biomes, like fog color

**Comment by Wtoll** [comment]
Yeah it’s on our todo list

**Comment by paulevsGitch** [comment]
If you are interested [here](https://github.com/paulevsGitch/BetterNether/blob/master/src/main/java/paulevs/betternether/mixin/client/BackgroundRenderMixin.java) is realization of fog rendering distance in BetterNether. It actually changes vanilla fixed fog rendering distance to configurable one, and makes distance a bit larger by default.

**Comment by paulevsGitch** [comment]
Looks like Overworld music plays in Cinderscapes nether biomes

**Comment by paulevsGitch** [comment]
In the latest version I fixed some issues with other mods biome (when some biomes registered twice) and added some [API for external biome](https://github.com/paulevsGitch/BetterNether/blob/snapshots/src/main/java/paulevs/betternether/registry/BiomesRegistry.java#L253) registration. This is needed only for specific features (like sub-biome or edge biome), or implementing BetterNether structure generator.

I'm still thinking about the library, it would be nice if it worked for any world/dimension. This will also allow to add volumetric biomes to the Overworld (for example - for caves)

**Comment by paulevsGitch** [comment]
After fix biomes are more uniform (before fix they were too scattered)

![2020-06-27_19 38 45](https://user-images.githubusercontent.com/17707380/85927338-1f780100-b8ae-11ea-9e0f-b9fe697b16a1.png)

**Comment by paulevsGitch** [comment]
Actually there is one important thing - plants from Better Nether couldn't grow on Cinderscapes ground and Cinderscapes plant couldn't grow on Better Nether ground. I think the best solution is to create custom block tags.

I suggest:
* **"nether_ground"** (for all nether ground materials);
* **"nether_ground_rock"** (for rocky ones);
* **"nether_ground_spread"** (for materials acting like nylium);
* **"nether_ground_soul"** (for soul-sand like material).

Probably there should be another tags. Names probably could be better. Suggestions are welcome

**Comment by EnderBro123** [comment]
My god @paulevsGitch @Wtoll your biomes looks EVER BETTER when combined! We want this compat!

**Comment by Wtoll** [comment]
I like the idea of adding tags, for us as long as the ground is put in the minecraft:nylium tag it can be placed on it, but given the fact that new blocks aren't necessarily nylium it makes sense to add additional tags. The only potential issue might be implementing them for vanilla blocks.

**Comment by paulevsGitch** [comment]
Actually adding tags for vanilla blocks is not very hard, the simplest way - add them with JSON. [Here](https://github.com/paulevsGitch/BetterNether/blob/snapshots/src/main/java/paulevs/betternether/NetherTags.java) is a small implementation, that works. If tag is missing it will be created.
In JSON structure is simple:
![image](https://user-images.githubusercontent.com/17707380/85969071-4b3ed800-b9cf-11ea-8714-b390ef48f97b.png)
It is marked not to override existing tag. Actually we must only consider what vanilla blocks must be in tags and add them in each mod JSON. (Better realization is to add them through code, actually for mod blocks, but I couldn't figure out how to do that)

Here is a little test for some blocks on server world load:
* [Code](https://github.com/paulevsGitch/BetterNether/blob/snapshots/src/main/java/paulevs/betternether/mixin/common/ServerWorldMixin.java#L37)
* Output:

![image](https://user-images.githubusercontent.com/17707380/85968872-dc617f00-b9ce-11ea-939f-d75b842001b5.png)

**Comment by Wtoll** [comment]
You’re right, adding the tags is easy, but implementing them so that vanilla vegetation can be placed on the custom blocks in a way that makes sense is a little more difficult. Same with theoretically making it work with vegetation added by nether mods in the future.

**Comment by paulevsGitch** [comment]
At this time vanilla plants are growing on nylium, probably all surface like mushroom mycelium must be nylium, and they will grow on it. Otherwise, we can use mixins, like I did for red and brown mushroom.

**Comment by paulevsGitch** [comment]
So actually "nether_ground_spread" can be just "minecraft:nylium" as it actually uses same functionality.

**Comment by paulevsGitch** [comment]
Probably tags can be like this:

* **fabric:soul_ground** - my example tag, for Soul Sand and Soul Soil (and anything like that);
* **fabric:nether_ground** - for all nether ground types (for plants that grow everywhere) - all types of nylium, soul-blocks, nethrrack-ones, etc.;
* **fabric:mycelium** - for only mushroom-like plants, that shouldn't grow on nylium or anywhere else - Mycelium from otherworld (and Nether Mycelium from BN);

I suggest use "fabric" namespace as universal one. Other tags can be added in the future

**Comment by paulevsGitch** [comment]
And probably tag like "**fabric:netherrack**" is needed. For plants growing on netherrack-like materials. With probably [this list](https://github.com/paulevsGitch/BetterNether/blob/master/src/main/java/paulevs/betternether/BlocksHelper.java#L51) of materials.

**Comment by paulevsGitch** [comment]
With tags thing look a lot easier (grass bonemeal mixin, for example). [Here](https://github.com/paulevsGitch/BetterNether/tree/snapshots/src/main/resources/data/fabric/tags/blocks) are suggested tags JSONs

**Comment by Wtoll** [comment]
For us, in terms of features for our mod we only need the nylium tag because that’s the only thing that our custom vegetation uses at the moment, but I do like the idea of adding extra tags. For most things there’s a general understanding that instead of using Minecraft or fabric as the namespace the c namespace is used (c for common), so I’d recommend using c:soul_ground etc.

**Comment by paulevsGitch** [comment]
Maybe "common" is better than "c"? It's longer, but easier to perceive

**Comment by paulevsGitch** [comment]
I decided to use "common" namespace

**Comment by EnderBro123** [comment]
Soo... Will this ever be done? XD

**Comment by Wtoll** [comment]
@EnderBro123 I believe that Cinderscapes is done on our end, we’re just waiting for whatever Better Nether has planned.

**Comment by paulevsGitch** [comment]
I updated tags logic and now plants can grow on Cinderscapes ground:

![2020-07-01_12 37 13](https://user-images.githubusercontent.com/17707380/86228885-a0c5e100-bb97-11ea-98fe-e80f6fb3077f.png)

And I fixed bonemeal mixin, ground spreading and plant growing are not conflicting anymore.
I decided to remove tag "nether_ground", it's now a tag combination. This will also fix some possible incompatibilities.

Biomes are generated as intended, so it's fine.
Probably I will make some recipes from Cinderscapes colored quartz as BetterNether has a colored quartz glass.
At this time this is all, probable more integrations will be in the future.

P.S. Cinderscapes biomes still have Overworld music. Actually music for Nether biomes should be specified, by default there is 5 music variants

**Comment by Wtoll** [comment]
I believe the music issue was fixed a couple updates ago

**Comment by paulevsGitch** [comment]
I couldn’t see any music specified, for example [here](https://github.com/TerraformersMC/Cinderscapes/blob/1.16/src/main/java/com/terraformersmc/cinderscapes/biome/AshyShoalsBiome.java)

**Comment by paulevsGitch** [comment]
[Here](https://github.com/paulevsGitch/BetterNether/blob/master/src/main/java/paulevs/betternether/biomes/BiomeDefenition.java#L118) is an example

**Comment by Wtoll** [comment]
iirc loopSound, moodSound, and additionSound is all we need and those are defined in the call to the super constructor. If there’s something else I can throw it in but in the most recent version I haven’t experienced any overworld music

**Comment by paulevsGitch** [comment]
Loop, mood and additional are only ambient sound. The music is specified with “music”, all vanilla nether biomes have it, and each one have a unique music

**Comment by Wtoll** [comment]
Okay, gotcha. I’ll go ahead a push a fix and it’ll ship in the next release. Thanks with all your help working on compatibility.

**Comment by EnderBro123** [comment]
@Wtoll @paulevsGitch So do these officially work with each other now?

**Comment by Wtoll** [comment]
@EnderBro123 I don’t want to speak for the developer but from what it sounds like when the next version of better nether releases they will in fact be compatible.

**Comment by EnderBro123** [comment]
It looks like it is actually.

**Comment by paulevsGitch** [comment]
Current version of BetterNether is fully compatible. Probably needs some more enhancements like quartz glass crafting, but it's not direct compatibility

**Comment by Wtoll** [comment]
Even better

**Comment by Wtoll** [comment]
Maybe we ditch this issue and close it now that basic compatibility is done, but I'd still like to discuss a more community based nether generator in another issue if that's cool.

**Comment by paulevsGitch** [comment]
Actually we need new Nether generator as separate library. There are some new mods already. I am thinking of making a repository for this library. I am still thinking about some points (for example, whether it should be a separate mod or included in each separately)

(Road is from Better Nether)

![2020-07-04_01 12 10](https://user-images.githubusercontent.com/17707380/86499396-a720ac80-bd93-11ea-92da-dba48e6a6e3c.png)

**Comment by Wtoll** [comment]
I was going to say Supercoder (a member of our team) has started working on a new nether biome generator. The idea is that it would be a separate, recommended, but not required mod that way it’s recommended that players install it for maximum compatibility but it’s not necessarily required. The project is called Smolder and you can find it on GitHub [here](http://github.com/TerraformersMC/Smolder) If you’d like to contribute you can make a PR or an issue with any changes. It is still a work in progress so the api is not final or anything, but it’s a start at the very least.

**Comment by paulevsGitch** [comment]
I looked into this library and its looks like it uses 2d biomes without sub-biomes or variations (only edges)

**Comment by paulevsGitch** [comment]
I suggest taking my generator as a basis. It uses cell automata instead of vanilla layers. This means that you could specify not only biome weight, but also their size, edges with other biomes (for biomes that shouldn't have edge together), their sub-biomes or variation, and all this in 3d (this means for example that biomes in top of the Nether will be different from bottom. This is actually used in BetterNether and will be more uses in future — I'm planning to add something interesting above Nether ceiling, probably a new big cave, with a portal to it).

In fact, the current code can already be used, you just need to slightly change the way you clear the cache.

[Here](https://github.com/paulevsGitch/BetterNether/blob/snapshots/src/main/java/paulevs/betternether/world/BiomeMap.java) is volumetric map, that stores biomes and [here](https://github.com/paulevsGitch/BetterNether/blob/snapshots/src/main/java/paulevs/betternether/world/BiomeChunk.java) is a biome chunk that actually generates biomes. I think this can be modified a bit to be always in 3d and have more functional (like biome size which is actually a number of iterations in automata).

**Comment by paulevsGitch** [comment]
There is also a problem with wrapper registration. In current implementation it will start on mod load, and if mod will load after library (common way) - its biomes will not be registered (and will not generate). In my code I call registration on server start or on client start, probably there should be a proper way to do it

**Comment by Wtoll** [comment]
Okay well, we’re open to suggestions and contributions if you want to make a PR with specifically what you think would work the best. Those definitely sound like legitimate concerns.

**Comment by paulevsGitch** [comment]
Ok, I will make a small fork and will try implement some ideas

**Comment by SuperCoder7979** [comment]
Hi! I'm currently working on adding sub-biome (kind of like hills in the overworld) and biome variants to Smolder. Would you like to join [our discord](https://discord.gg/jEGF5fb) so we can communicate what exactly to add to make it smooth to add compat between our mods? 😅

**Comment by paulevsGitch** [comment]
Actually I'm not good at English, so it's better to post here, I think.

I made a small fork of library and I want to implement enhanced cellular automata as a biome generator and a bit different system of biome registration

**Comment by paulevsGitch** [comment]
[Here](https://github.com/paulevsGitch/Smolder/tree/paulevs_dev) is a first prototype. I implemented biomes, sub-biomes, edges and height distribution. It's not tested yet, I think I will write a small app to look on generation (as I done for BN before)

(This is how that app looked like, a very old version)

<img src="https://user-images.githubusercontent.com/17707380/86520212-9aab5b00-be4a-11ea-979e-484ff841750d.png" width="400" height="400" />

**Comment by paulevsGitch** [comment]
@SuperCoder7979, I joined discord server, is there a place where I can write about my progress?

**Comment by SuperCoder7979** [comment]
Just the #general chat would be fine 😄

**Comment by EnderBro123** [comment]
> Actually we need new Nether generator as separate library. There are some new mods already. I am thinking of making a repository for this library. I am still thinking about some points (for example, whether it should be a separate mod or included in each separately)
> 
> (Road is from Better Nether)
> 
> ![2020-07-04_01 12 10](https://user-images.githubusercontent.com/17707380/86499396-a720ac80-bd93-11ea-92da-dba48e6a6e3c.png)

What are those bamboo things? Nether Bamboo?

**Comment by paulevsGitch** [comment]
This is from Biomes You Are
