### ISSUE TITLE
Crash on startup on 1.15.2

### ISSUE THREAD

**Issue by Moonflowey** [paulevsGitch/BetterNether#123]
So, this is the crash i have been experiencing in 1.15.2 as soon as i try to start the game:
https://pastebin.com/Thpc6R0J

Loader version: 0.8.8+build.202
FabricAPI version: 0.13.1+build.316

I havent changed anything in the config cuz, well, the config didnt even generate yet.

**Comment by paulevsGitch** [comment]
I tried this configuration on clean client, and all launches fine. Can you try to start without Java-tags?
You are using a bit outdated Fabric API, the latest is [Fabric API 0.13.1 build 316](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/2985282), I recommend you use the latest one

**Comment by Moonflowey** [comment]
Sorry -- I forgot to mention that i tried various fabric versions that worked and i still got the crash.
Also, What do you mean by "Java-tags" ? Sorry again, i am quite oblivious about those things.

**Comment by paulevsGitch** [comment]
Java tags are launch arguments for JVM. They probably can affect class loading order.

![image](https://user-images.githubusercontent.com/17707380/85803744-8a132a80-b750-11ea-85d1-b704a46095fd.png)

Other possible reason can be reading/writing rights in Minecraft folder.
What launcher do you use? I tested this on MultiMC

**Comment by Moonflowey** [comment]
Oh, those. Pretty sure those come with the launcher i am using.
Alright, i switched to MultiMC and that seems to have fixed the problem somehow. I was using TLauncher, wonder why it didnt work. Still kinda weird betternether was the only mod i had problems with, though.

**Comment by paulevsGitch** [comment]
It can be probably an issue of launcher itself. Some launchers can define how Minecraft should start and this can break Fabric pipeline of block registration (this is a reason of your issue — block get it properties before it actually created and this crashes the game). I couldn't affect this order as it is defined by Minecraft itself.

Glad to see that you managed to find a way out.

**Comment by paulevsGitch** [comment]
I think this issue was relative to [this](https://github.com/paulevsGitch/BetterNether/issues/141#issuecomment-657205540), probably it will be fixed

**Comment by Moonflowey** [comment]
Hey, so, to add up onto my issue, it might not have been an issue within the mod but with fabric itself. I tried cinderscapes, another mod that adds biomes to the nether, and i had the same issue. I will try the new version in a bit, though.

**Comment by paulevsGitch** [comment]
In you crash log there is also a "mıddle" with "ı" instead of "i". I think this is relative to current language and JVM. I will probably update 1.15 version a bit later to fix it, in 1.16 it is fixed.

**Comment by Moonflowey** [comment]
Yup, that seems to have fixed it all. Thanks!
