### ISSUE TITLE
[Suggestion] Cincinnasite bucket

### ISSUE THREAD

**Issue by Worgrick** [paulevsGitch/BetterNether#130]
it would be like a 2 use thing. lava up lava, down. no bucket.

**Comment by paulevsGitch** [comment]
You actually can [make a normal bucket](https://github.com/paulevsGitch/BetterNether/blob/master/src/main/resources/data/betternether/recipes/bucket.json) from cincinnasite. I avoid adding custom one as it will probably be non-functional with modded liquids.

**Comment by Worgrick** [comment]
I missed that hey thanks
