### ISSUE TITLE
ghast blimps and magma ships

### ISSUE THREAD

**Issue by Worgrick** [paulevsGitch/BetterNether#131]
When I was playing your mod I ran across a nether city, with a ghast hive above it, and across the lava sea was a bastion and a fortress. the piglen and the wither would fight and ghasts would fly from the war zone to the city back and forth. it inspired this idea. what if you put more inter actions, between humanoid creatures, like trades and buildings for that faction. specific armors, and new taming abilities. because it would be really awesome to go ride my ghast into war against some withers or vice versa.

**Comment by paulevsGitch** [comment]
There is a plan to add controllable airship, but not controllable ghasts - they must stay as a danger from above
