### ISSUE TITLE
lava conduit

### ISSUE THREAD

**Issue by Worgrick** [paulevsGitch/BetterNether#132]
in minecraft there are not enough golems;snowman, iron golem, wither boss, totems;totem of undying, ranged wepons;crossbow,bow, potion snow ball,trident ability builds; beacon, conduite.  with the nether update it would be a great time to add something like the lava conduite. Maybe it lets you put water in the nether, maybe not. my point is people love trying different setups so maybe instead of redstone(flushed out idea) farming(its the basics) potions/enchanting. lava conduite instead of flying machine to remove lava. red stone mucks up the mid evil feel. using golems/w signs to tell them what to do would be dope. its like /walk froward 10, /remove minecraft:netherrack 10 1 1000, 19 20 343. several days latter and its done. the golem bit is probably unrealistic but it sounds really cool. oo hey what if you put made it so signs named places, it would make places on the map matter more. can you see it golems walking along highways between cities while different factions fight. ghasts flying goods and transport above, along with the occasional thing on pig bat, striders, and cubes pulling large cargo and passengers respectively. all because of signs, nametags, ability builds, species interplay.
Its awesome because if we want it to feel like a different place then the over world there needs to be a different way most things happen. how do you get water in the nether through brewing and trading enough gold to get enough iron to craft a cauldron and a bucket. you get the best food by walking into the plains, the best thing are had through trade and theft. See it make sense with this update. if you dont want to add this maybe metion it to some one you think would.

**Comment by paulevsGitch** [comment]
Too chaotic proposal, probably I will not consider it
