### ISSUE TITLE
[suggestion] new biome ideas

### ISSUE THREAD

**Issue by Brickboss-tech** [paulevsGitch/BetterNether#133]
1. Acidic plains (a biome made up of titanium sand which would have a sandy metallic texture. There would be pools of acid in this biome which can be icked up with a new bucket called the titanium bucket. Picking up acid with a regular bucket would cause it to break. Acid could be used to put you out if you’re on fire but would still inflict some damage. The acid pools would also contain skeletal fish.

Hellbound roots (a biome made out of netherrack but kt would have a block called hellbound roots which would stick up out of the ground spaced 10-20 blocks apart. Underground though, these roots would be connected like a web.

Rotten clearing (a biome made of rotten flesh blocks whick when broken would drop itself and like and iron block would give the player 9 rotten flesh. This biome would also contain bone blocks in thnshape of teeth and pools of blood or saliva. Both liquids can put out lava but the saliva would give you slowness for about a minute.

Glowing woods (a new forest made of glowing nylium and filled with glowing fungi and giant glowing fungi. These would have the same shape as the warped and crimson giant fungi. The biome would also contain glowing roots which would give off light. The giant fungi wouldn’t have shroomlight’s as they already glow.

Sub biomes:

Wart plains (sub biome for the wart forest without giant wart trees. Theground would be covered in nether wart and red mold.

Soulsand mountains (soulsand valley but mountainous.

Extra large jungle (Nether jungle variant with bigger tress and more foliage. Basically a really dense jungle. It would contain a new mob called the the dionaea muscipula which would be like a chomper from plants vs zombies.

Dead warped woods (sub biome for warped forest with no leaves just the stems.

I hpe you like these ideas and thank you for reading.

**Comment by Brickboss-tech** [comment]
Sorry, I forgot one thing. The wart plains would contain a flower that when eaten or placed in a brewing stand would give the player the lava swimming effect which would allow the llayer to swim in lava like it was water.

**Comment by paulevsGitch** [comment]
Acidic plains will not be added (probably);
Hellbound roots is similar to Anchor Tree in 4.0.0;
Rotten clearing probably does not fit into current themes of BN;
Glowing woods is similar to Glowing Crimson Forest;
Wart plains already exists;
Soulsand mountains - mountains will not fit into caves world;
Extra large jungle - similar to Upside-Down Forest and Old-themed biomes;
Dead warped woods - unnecessary biome;

Actually most things are already implemented, other probably will not be implemented at current development stage
