### ISSUE TITLE
[bug/issue]

### ISSUE THREAD

**Issue by Brickboss-tech** [paulevsGitch/BetterNether#134]
So I’m trying to use the better nether mod with oh the biomes you’ll go and cinderscapes but the most recent version have a problem. The biomes from better nether don’t spawn. Cinderscapes and byg are fine and this wasn’t an issue with some of the older files. What’s weird is that there are features from better nether like stalactites and other structures but no biomes. Will this be fixed in the future.

**Comment by paulevsGitch** [comment]
Looks like this problem is on "oh the biomes you’ll go" side, without this mod it works. Previous version worked fine

**Comment by Brickboss-tech** [comment]
Ok, I’ll ask the creator of byg. Thank you for the response.

**Comment by paulevsGitch** [comment]
Now all works as intended
