### ISSUE TITLE
[bug/issue] crafting tables

### ISSUE THREAD

**Issue by DraigRygbi** [paulevsGitch/BetterNether#135]
The recipes for 6 crafting tables are the same as the ones for trapdoors.

**Comment by paulevsGitch** [comment]
Thank you, I will fix it soon

**Comment by paulevsGitch** [comment]
Looks like everything is ok, what is a bug actually?

![2020-07-05_21 26 13](https://user-images.githubusercontent.com/17707380/86539579-5b424480-bf06-11ea-9210-29d18eae934a.png)

![2020-07-05_21 26 10](https://user-images.githubusercontent.com/17707380/86539578-5a111780-bf06-11ea-8c72-044487756b6f.png)

![2020-07-05_21 26 21](https://user-images.githubusercontent.com/17707380/86539580-5b424480-bf06-11ea-9f42-327e63987ddd.png)

**Comment by DraigRygbi** [comment]
It looks like stalagnate and reeds are the only ones that don't have an issue.
![2020-07-06_09 27 13](https://user-images.githubusercontent.com/54636340/86598349-fa008c80-bf6a-11ea-924b-cda0df76b60f.png)



![2020-07-06_09 20 02](https://user-images.githubusercontent.com/54636340/86598055-90807e00-bf6a-11ea-9dab-c25c71e18d9f.png)
![2020-07-06_09 22 55](https://user-images.githubusercontent.com/54636340/86598126-abeb8900-bf6a-11ea-9d87-fb277d70996a.png)
![2020-07-06_09 23 29](https://user-images.githubusercontent.com/54636340/86598140-b27a0080-bf6a-11ea-9bbf-c32425c3fed0.png)
![2020-07-06_09 23 53](https://user-images.githubusercontent.com/54636340/86598151-b4dc5a80-bf6a-11ea-9fcc-00e372dd9696.png)

**Comment by paulevsGitch** [comment]
Fixed
