### ISSUE TITLE
[Suggestion] Feather ferns

### ISSUE THREAD

**Issue by theishiopian** [paulevsGitch/BetterNether#139]
Currently, the only way to get feathers for arrows in the nether is baby zombie piglins that spawn on chickens. This is likely a bug, and as such isn't a reliable source of arrow fetching. I propose a new plant, which can be found in jungles and swamps, called the feather fern. Its fronds are very similar to feathers, and as such can be used to make arrows and writable books. Like ink bushes and magma flowers, it can be farmed.

**Comment by paulevsGitch** [comment]
Added in 3.3.0
