### ISSUE TITLE
[Crash] NPE in SPacketSoundEffect processing in Nether

### ISSUE THREAD

**Issue by duely** [paulevsGitch/BetterNether#14]
WIth Better Nether installed (and I've gotta say, I absolutely love the mod), and thankfully Vanilla Fix which allowed me to continue playing, I'm getting the occasional crash near BetterNether things or after harvesting BetterNether things: https://pastebin.com/fFCBX9Wx

Additionally, you have licensed this under the terms of the GPL but you don't have the source anywhere visible. I'd like to help out in pin-pointing the root cause of the issue, but... yeah.

**Comment by paulevsGitch** [comment]
As I saw your log doesn't contain directly links to this error. My mod doesn't modify Minecraft sound system anywhere and it uses common forge block registration method, so I guess crash is result of another mod, that changes Minecraft sound system. Need more logs (especially client logs near crash) to point problem.

Source cod will be in this repository, but a bit later. To be honest I don't have enough time to do it quickly, but it will be uploaded in next few months.

**Comment by duely** [comment]
That's totally fine! I'll try to do some more data-gathering to make sure that it is indeed an issue with your mod and not an interaction with something else that just happens to coincide with breaking Better Nether blocks -- although I don't believe anything in the pack specifically alters sound.

**Comment by duely** [comment]
I've looked into it a little more and I'm actually now positive that this issue is entirely unrelated to Better Nether, as I've realised that EvilCraft also has mobs which make a large variety of strange noises, so it is more likely to be related to this than Better Nether. Sorry for the confusion! I should've double-checked my logic.

**Comment by duely** [comment]
Okay, looking deeper into this issue after suffering a similar problem with another mod, where I was only registering the sound events on the client side but the server was the one sending them, it appears as though the FLY_SOUND SoundEvent is never registered (from what I can tell, either in this repository or in a decompiled jar), it's just instantiated in the EntityFirefly. 

As such, it has no associated id with it, and when it's read back by the client and a SoundEvent is looked up by that id, it returns null.

SoundEvents need to be registered the same as items, blocks, etc, using a similar registry hook. SoundEvents returned by entities for ambient sounds, etc must be registered on both the client and the server side otherwise there's a disparity between packets.
