### ISSUE TITLE
1.16.1 - chests destroyed when breaking

### ISSUE THREAD

**Issue by bessiq** [paulevsGitch/BetterNether#140]
better-nether-3.2.5.jar

Hi,

All of the Better Nether chests are destroyed when breaking them. I used vanilla iron and diamond axes to test, which I assume are the appropriate tool? (Sorry, new to Better Nether!) Also, I was in survival mode. They do drop any items inside when destroyed.

I checked my log and there are no messages during the time I was placing and breaking the chests. Let me know if you need more info. Thanks!

**Comment by paulevsGitch** [comment]
Fixed in 3.3.0
