### ISSUE TITLE
Eyeball blocks will replace blocks when created

### ISSUE THREAD

**Issue by Katorone** [paulevsGitch/BetterNether#142]
When an eyeball vine grows it has a chance to grow one block too large, replacing any block in the floor.

![image](https://user-images.githubusercontent.com/918422/87246136-8c150300-c44b-11ea-9b56-f410d1330fa9.png)

**Comment by paulevsGitch** [comment]
Fixed in code, will be in 3.3.0. They will always leave 1 block of air below

![2020-07-12_16 27 30](https://user-images.githubusercontent.com/17707380/87247467-b0c5a680-c45c-11ea-8f14-81c94e3f934f.png)

**Comment by Katorone** [comment]
Thank you!

**Comment by paulevsGitch** [comment]
Fixed in 3.3.0
