### ISSUE TITLE
[Suggestion] Pyramids should be less common

### ISSUE THREAD

**Issue by Moonflowey** [paulevsGitch/BetterNether#143]
I am not a professional, but dont they spawn a bit too often?
https://www.youtube.com/watch?v=pHvm6eg16tU (sorry for the fps drops i only record once in awhile)

I feel like they should generate less often. Everytime i see polished basalt i get excited but when i see the full structure i feel like "oh, yeah, that thing, welp". They should generate less often so 1. They dont look weird on lava oceans in groups and 2. It should be more exciting to find one of these. They are far too common at the moment and they dont feel special.

**Comment by paulevsGitch** [comment]
Actually this is partly a bug, must be fixed soon

**Comment by Moonflowey** [comment]
Oh, theyre called pyramids...
I think it would be perfect if pyramids could only generate once within a biome.

**Comment by paulevsGitch** [comment]
I will separate lava structures density from all other structures density, and make it much lower. This will result as more rare lava structures, including pyramids

**Comment by paulevsGitch** [comment]
Ironically I tried to make them more common before, as they don't generate in most cases

**Comment by paulevsGitch** [comment]
Done, update to 3.3.1. There is also mobs bug fixed
