### ISSUE TITLE
Mega Trees and Mushrooms

### ISSUE THREAD

**Issue by MagmaBro123** [paulevsGitch/BetterNether#144]
Allow mushrooms in a 2x2 area to be grown into the giant mega shroom found in the Mushroom Forest biome, as well as allowing a 2x2 willow tree to be grown the same way. The Giant Willow tree would basically just be a much larger version of the usual tree.

**Comment by paulevsGitch** [comment]
Yes, I think this is a good ides

**Comment by paulevsGitch** [comment]
Implemented Giant Willows in 4.0.0

**Comment by quiqueck** [comment]
Moving to our Enhancement List.
