### ISSUE TITLE
[Suggestion] More Fire Bowls

### ISSUE THREAD

**Issue by cybercat5555** [paulevsGitch/BetterNether#146]
A simple idea, a few new types of Fire Bowls:
Basalt Fire Bowl
Nether Brick Fire Bowl

As well as variants for all three made with Soul Soil rather than Netherrack, which causes them to have blue fire when ignited rather than the typical orange.

**Comment by EnderBro123** [comment]
You mean More Fire Variants. There's no bowl items besides a Stalagemate bowl.

**Comment by cybercat5555** [comment]
I mean these blocks 
![2020-07-20_18 06 02](https://user-images.githubusercontent.com/17956808/87991230-b4d47280-cab3-11ea-9b8c-03b080bed769.png)

They currently only come in a Cincinnasite version

**Comment by EnderBro123** [comment]
Oh.

Well, more fire variants would be cool too tbh. Also BetterNether now has a Discord. If you want the invite then lemme know.

**Comment by cybercat5555** [comment]
Already there lol, just posting the suggestion here due to changes on the discord's suggestion channel.

**Comment by EnderBro123** [comment]
Oh.

You can just use -suggest <Suggestion>.

**Comment by paulevsGitch** [comment]
Added in 4.0.0
