### ISSUE TITLE
Mobs won't walk over BetterNether trapdoors

### ISSUE THREAD

**Issue by Shreddys** [paulevsGitch/BetterNether#148]
So far I've tested it by scaring creepers with cats and luring zombie piglins with turtle eggs. Neither of those will try walking over an open trapdoor made with BetterNether materials.

Edit: Forgot to mention I'm in Minecraft 1.16.1 and running BetterNether v3.3.0

**Comment by paulevsGitch** [comment]
Please try v3.4.2 and reply if bug is still present. Actually it can be relative to vanilla path finder and be unfixable (or very hard to fix)

**Comment by Shreddys** [comment]
Right, I forgot to check for a new version.
Tested again in v3.4.2 and the issue is still present.

**Comment by paulevsGitch** [comment]
Fixed in 3.5.0 (probably, please test it, if not - please reopen this issue)
