### ISSUE TITLE
[Bug] Jellyfish mushrooms render improperly with Sodium installed

### ISSUE THREAD

**Issue by theishiopian** [paulevsGitch/BetterNether#153]
Sodium is an open source performance boosting mod. When it is installed along side better nether, the heads of the newly added jellyfish mushrooms render incorrectly.

![2020-07-24_18 37 42](https://user-images.githubusercontent.com/8585975/88446278-7a354780-cddd-11ea-8314-4843d8dc10f4.png)

Link to sodium: https://github.com/jellysquid3/sodium-fabric

**Comment by theishiopian** [comment]
It should be noted that this issue is not present with single block jellyfish mushrooms, only the 2 block mushrooms experience this issue.

**Comment by paulevsGitch** [comment]
Actually I couldn't control render replacements from sodium, I can only make block "cutout" instead of "translucent" if sodium is installed

**Comment by paulevsGitch** [comment]
Fix (or something like that). Marking them "cutout" works. They will render like that only if Sodium is installed.

![image](https://user-images.githubusercontent.com/17707380/88449984-fff3da00-ce53-11ea-9cad-e7fa53f82fae.png)

**Comment by EnderBro123** [comment]
So if Sodium isnt installed then this is broken?

**Comment by paulevsGitch** [comment]
Yes, sodium replaces block renderers. I make a simple "hotfix", but the mushroom will not be translucent with Sodium

**Comment by paulevsGitch** [comment]
Sodium has [same issue](https://github.com/jellysquid3/sodium-fabric/issues/38) with another blocks

**Comment by theishiopian** [comment]
This is a decent stopgap, sounds like the issue is on his end.

**Comment by paulevsGitch** [comment]
"Fixed" in 3.5.1
