### ISSUE TITLE
[Suggestion|Bug] Make code recipes available to override

### ISSUE THREAD

**Issue by Afrocntrik** [paulevsGitch/BetterNether#155]
- Plank Recipes Missing
- Crafting Tables Recipes Missing
- Netherrack, Basalt & Blackstone Furnace Recipes Missing 
- Furnace Recipes Give 0 XP
These additions to name a few would be really helpful, thank you for your time

**Comment by paulevsGitch** [comment]
Most recipes done in code. Data folder doesn't need more files.
- "Plank Recipes Missing" - checked, all recipes work fine;
- "Crafting Tables Recipes Missing" - checked, all recipes work fine;
- "Netherrack, Basalt & Blackstone Furnace Recipes Missing" - checked, all recipes work fine;
- "Furnace Recipes Give 0 XP" - recipes doesn't need to give any xp

![2020-07-26_00 49 03](https://user-images.githubusercontent.com/17707380/88466935-13498880-ceda-11ea-8fa6-c3f80be798dc.png)

![2020-07-26_00 50 21](https://user-images.githubusercontent.com/17707380/88466936-147ab580-ceda-11ea-8fe1-48115e5280d0.png)

![2020-07-26_00 50 28](https://user-images.githubusercontent.com/17707380/88466937-15134c00-ceda-11ea-929e-54a6222ac5a0.png)

**Comment by Afrocntrik** [comment]
Sorry that's not what I meant to say, you cannot use a datapack to override a recipe that doesn't exist the data folder. Hence causing errors like this Item: betternether:quartz_stained_glass_pink does not exist

**Comment by Afrocntrik** [comment]
Or the recipe remains the same I just tried it out with the Crimson Crafting Table I can solve it with Polymorph but I cant change the recipe

**Comment by paulevsGitch** [comment]
Actually they already must be available to override, I will check this

**Comment by paulevsGitch** [comment]
Tested this today, recipes can be overridden with datapacks. You probably give wrong name to the recipes.

![2020-07-27_10 40 34](https://user-images.githubusercontent.com/17707380/88516290-b3480480-cff5-11ea-9e93-20de0d1b349a.png)

![2020-07-27_10 40 48](https://user-images.githubusercontent.com/17707380/88516293-b511c800-cff5-11ea-8f82-bc488678319e.png)

**Comment by paulevsGitch** [comment]
Here is an example datapack, that overrides netherrack furnace recipe:
[test.zip](https://github.com/paulevsGitch/BetterNether/files/4980632/test.zip)

**Comment by Afrocntrik** [comment]
Yes but this happens as well with other recipes 
![2020-07-27_13 27 07](https://user-images.githubusercontent.com/11052983/88572521-4b051d00-d00d-11ea-856c-9bc1536f1309.png)

**Comment by Afrocntrik** [comment]
However I did have the wrong item name for the netherrack furnace I got it working though

**Comment by Afrocntrik** [comment]
and here's the datapack recipe name crafting_table_crimson.json

**Comment by Afrocntrik** [comment]
which is the ingame item id and texture name so you must have it as something else

**Comment by paulevsGitch** [comment]
Names for most recipes will be source_id_result_id (to prevent duplicating names), for crimson crafting table it will be "crimson_planks_crafting_table_crimson.json"

**Comment by paulevsGitch** [comment]
Recipes for walls, colored blocks, furnaces, signs, barrels, ladders, taburetes, chairs, bar stools will be named with only result_id, for example "basalt furnace.json"

**Comment by paulevsGitch** [comment]
Probably [this mod](https://www.curseforge.com/minecraft/mc-mods/kubejs-fabric) can help with recipe changing

**Comment by Afrocntrik** [comment]
I totally understand it's all good, I still think some kind of recipe adjustment compatibilty is needed as in the modpack I've been working on changing and unifying all logs to give 2 planks instead of 4 has been more difficult then anticipated.

**Comment by Afrocntrik** [comment]
I just miss Crafttweaker :(

**Comment by paulevsGitch** [comment]
I think KubeJS can replace some features from CraftTweaker, as I know it can manipulate recipes, with some JS features like conditions and loops.

I think I will make procedural recipes configurable, so you will be able to switch them off in the config

**Comment by paulevsGitch** [comment]
WIP:

![image](https://user-images.githubusercontent.com/17707380/88808292-5dbd5480-d1bb-11ea-800a-0f6a76a8bb34.png)
