### ISSUE TITLE
[Suggestion] Cincinnasite cauldron + collecting drops/particles

### ISSUE THREAD

**Issue by Katorone** [paulevsGitch/BetterNether#156]
A Cincinnasite cauldron could be used to collect certain drops or particles from Better Nether plants and environments.

Putting the cauldron some blocks under an eye vine could be collecting water, or even a slime block eventually.
Surrounding a cauldron that collects water with nether warts could create awkward liquid that can be bottled into awkward potions.

In general, being able to collect _stuff that drips_ makes for fun gameplay, I think.

**Comment by theishiopian** [comment]
this is similar to iron cauldrons collecting rain, so there is some precedent.

**Comment by paulevsGitch** [comment]
The process is very slow for the game balance

![2020-09-20_01 27 48](https://user-images.githubusercontent.com/17707380/93690397-8a695a80-fae0-11ea-9565-45023e2dcf65.png)

**Comment by Katorone** [comment]
That looks great, thank you!

**Comment by paulevsGitch** [comment]
Added in 4.1.0
