### ISSUE TITLE
Unification Of Block Id's & Typo Fix

### ISSUE THREAD

**Issue by Afrocntrik** [paulevsGitch/BetterNether#157]
![2020-07-27_14 27 27](https://user-images.githubusercontent.com/11052983/88577729-7d1a7d00-d015-11ea-8231-adbe15e77778.png)
![2020-07-27_14 27 23](https://user-images.githubusercontent.com/11052983/88577775-902d4d00-d015-11ea-821c-48c08cef3031.png)
Stripped Wood or Bark, I'm willing to make a tag for the woods I'll submit it when I finish

**Comment by paulevsGitch** [comment]
Mushroom fir is only one wood, that was named "wood" instead of "bark". Probably I will change this, but I will need a converter for old world data

**Comment by quiqueck** [comment]
This should be fixed with 5.3.5. Please re-open the issue if there are still inconsitencies.
