### ISSUE TITLE
[Suggestion] Walkers

### ISSUE THREAD

**Issue by theishiopian** [paulevsGitch/BetterNether#158]
Walkers are a new type of mob, and are related to striders, both having evolved from a common ancestor. Walkers look like smaller, blue striders. They cannot be ridden, but can have a chest placed on top of their heads. Like llamas, walkers will follow each other, allowing you to form walker caravans. In the wild, walkers spawn in small groups, spawning wherever striders spawn.

Gameplay wise, the main purpose of the walker is to give the player a way to bring more items with them across lava, as you can not put a chest on a strider.

**Comment by paulevsGitch** [comment]
One of first strider design looked like so, probably this is how walkers can look (with large redesign) - more legs allows them to transport large masses effectively on lava surface

![image](https://user-images.githubusercontent.com/17707380/93482220-23914900-f908-11ea-8e4d-dba61aa0306b.png)

**Comment by theishiopian** [comment]
I like the design, but the name "walker" doesn't really  apply as well to it. I'd suggest the name "crawler", since they move more like an insect than a strider. 

Also, does it have four eyes? Because I am totally up for it having four eyes.

**Comment by quiqueck** [comment]
Moving to our Enhancement List.
