### ISSUE TITLE
[Suggestion] Nether reed alternative product, agave output

### ISSUE THREAD

**Issue by noobanidus** [paulevsGitch/BetterNether#16]
I've noticed that there are a lot of agave plants around and have personally been using CraftTweaker to make it possible to convert these into 2-3 sugar. They don't seem to be renewable so I felt that this was an appropriate cost; it feels as though it would make sense for this to be a core part of the mod (as other plants have uses as well).

In addition, I feel that getting sugar from the nether reeds seems contrary to the idea of something specifically grown through lava, which I imagine would be hot and spicy. Personally, I have been using CraftTweaker to convert them into "tiny pile of blaze powder", of which you need 4 (or possibly 9?) to actually make blaze powder. Them being craftable into paper still makes sense, however -- just certainly paper I wouldn't want to lick my fingers while touching!

**Comment by paulevsGitch** [comment]
Agave was designed as decorative plants, maybe this will be changed in the future. Nether reeds was originally designed as source of sugar and paper for nether, I don't think they need changes. If you don't like these recipes — you can do as you done — replace them with craft tweaker or just editing .json's for them.

**Comment by theishiopian** [comment]
Agave plants kind of remind me of spiky aloe vera plants, perhaps they could be used for a weak healing item?

**Comment by paulevsGitch** [comment]
Cactuses need enhancements, including agave, as they get more uses

**Comment by paulevsGitch** [comment]
Now agave used for medicines, barrel cactus - for enchantments, and both have 4 growth stages

![2020-09-20_03 24 30](https://user-images.githubusercontent.com/17707380/93691664-0ec3d980-faf1-11ea-9a00-0794d4b339a5.png)

**Comment by paulevsGitch** [comment]
Added in 4.1.0
