### ISSUE TITLE
Mobs from spawners in new dungeon don't drop any loot

### ISSUE THREAD

**Issue by Katorone** [paulevsGitch/BetterNether#160]
Related to spawners in this dungeon:
![image](https://user-images.githubusercontent.com/918422/89549754-047fa180-d809-11ea-925b-57ffc539615e.png)

When killing the spawned mobs, they did not drop any loot.

We have a mod that allows us to silk touch spawners, these spawners didn't stack with other spawners of the same mob.  The loot issue happened before we silk touched any spawner.

Affected spawners that we've found:
- nagas
- wither skeletons
- magma cubes
- blazes

**Comment by paulevsGitch** [comment]
This is a feature to prevent making large mob farm from dungeon. Spawners in pyramid are customized more than common ones

**Comment by EnderBro123** [comment]
Blaze spawners should remain untouched. This completely breaks Blaze farms.

**Comment by paulevsGitch** [comment]
This is not relative to fortress spawners

**Comment by EnderBro123** [comment]
Oh, sorry.

**Comment by Katorone** [comment]
This makes sense.  Thanks for the quick reply and your work on this great mod!
