### ISSUE TITLE
Enhancement: smokers, geysers and under-water behavior

### ISSUE THREAD

**Issue by Katorone** [paulevsGitch/BetterNether#162]
Soul sand creates bubbles that push and magma block creates bubbles that pull. The geyser could have a small area of affect (3-4 blocks) that pulls entities towards it, where the smoker would have a small area of effect that pushes entities away.

Currently both blocks remove water sources.  The geyser seems to create particles under-water, while the smoker does not.

![image](https://user-images.githubusercontent.com/918422/89699174-882eb080-d925-11ea-9687-373048d80e43.png)

Alternatively, if under-water activity isn't intended, having them both be idle or even pop off would be consistent as well.

**Comment by EnderBro123** [comment]
I don't think any BetterNether blocks are waterloggable.

**Comment by Katorone** [comment]
That's why i'm proposing an enhancement, and do not consider this a bug by any means.

**Comment by EnderBro123** [comment]
Oh, ok.

You could join the BetterNether Discord for faster support if wanted, btw.

**Comment by quiqueck** [comment]
Moving to our Enhancement List.
