### ISSUE TITLE
Disable Nether fog

### ISSUE THREAD

**Issue by Madis0** [paulevsGitch/BetterNether#163]
Could you add an option to disable the Nether Fog entirely? I've tried adjusting the fog setting within the UI limits and outward (e.g. 15) but the fog is still very visible. 

Also tried a different mod NoFog, but it crashed, presumably because BetterNether modifies the same classes as that.

Using BetterNether 3.5.4 on Fabric for MC 1.16.1

**Comment by paulevsGitch** [comment]
Try to set fog density to 0.0 in the mod config

![image](https://user-images.githubusercontent.com/17707380/89733781-84ec0f80-da60-11ea-8cac-7a8607b15a04.png)

**Comment by paulevsGitch** [comment]
About NoFog - BetterNether [modifies code with Inject](https://github.com/paulevsGitch/BetterNether/blob/master/src/main/java/paulevs/betternether/mixin/client/BackgroundRenderMixin.java#L23), that is a safe compatible way if other mods use injects. Probably NoFog uses a different approach (for example overriding), it makes it incompatible with other mods (like sodium or optifine), this must be reported to its author.

**Comment by paulevsGitch** [comment]
Since there isn't any response for a long time, I close this
