### ISSUE TITLE
No endermen spawn in the Warped Forest

### ISSUE THREAD

**Issue by dranorter** [paulevsGitch/BetterNether#165]
I just tried out this mod in combination with Cinderscapes. I don't see any endermen spawn in the Warped Forest anymore. Endermen still spawn in the Cinderscapes biome "Luminous Grove", but not in vanilla Warped Forest.

**Comment by dranorter** [comment]
If I comment out all the custom entity registration lines in your EntityRegistry.java, I get endermen again. This leads me to believe the issue is just due to relative weights or densities of different mobs (I don't really get how weights and densitiies work). However, I don't know why the Cinderscapes Luminous Grove is unaffected; it has the same weight and density settings.

**Comment by dranorter** [comment]
Update: I tried excluding everything but fireflies from the Warped Forest, then building a nether ceiling enderman farm up near build limit. Still no endermen spawning. (I admit I only waited a minute or two.) Removing Warped Forest from the firefly biomes list finally got me some endermen.

**Comment by EnderBro123** [comment]
Join the official BetterNether Discord, you could get faster and easier support there.

https://discord.gg/fS35Ck2

**Comment by dranorter** [comment]
Clarification for anyone else who might read this: after much more thorough testing, I find that endermen will, very occasionally, spawn if I kill off any other entities in the area (using \kill @e[!minecraft:player]). So if this is a bug, the bug is that they are much rarer than they should be. For me this is still a bug because the way I think of the Warped Forest is that it's "warped" by the presence of the endermen; thus the absence of other mobs there. The workaround for me was to compile a custom version of the mod where BetterNether mobs don't get added to Warped Forest. (Except fireflies, which I changed to an "ambient" mob so they're under a separate cap.)

**Comment by paulevsGitch** [comment]
Fixed in 4.0.0-alpha
