### ISSUE TITLE
[Bug] Structures often overlap

### ISSUE THREAD

**Issue by Fireface677** [paulevsGitch/BetterNether#167]
BN structures (temples, cities) seem to have some generation bugs if BYG is used too. The structures are very often overlapping or completely broken (at chunk borders?) 8/10 nether cities were broken because they generated in temples, fortresses or bastions so this definitly needs some work.

I don´t know if this is a problem of BN or BYG or both mods.

**Comment by paulevsGitch** [comment]
Please send some screenshots or seed

**Comment by paulevsGitch** [comment]
Please send some screenshots or seed

**Comment by paulevsGitch** [comment]
Fixed in 4.1.0
