### ISSUE TITLE
Biome in overwirld? 

### ISSUE THREAD

**Issue by Esjaibear** [paulevsGitch/BetterNether#168]
I'm not sure if this is a bug or not, but I have a Better Nether biome (mushroom forest edge) in the overworld. It's not a huge deal, except it is constantly spawning ghast which threatens to destroy my tree farm. I have version 1.16.1. Thank you for this great mod.

**Comment by paulevsGitch** [comment]
My mod use its own generator for the Nether, and biomes are not added into overworld. Do you use another world gen mods?

To change biomes in existing world you can use a [World Painter](https://www.worldpainter.net/) tool. It has an option to replace biomes and merge only biomes with existing map.

**Comment by Esjaibear** [comment]
Yes, I use Cinderscapes, terrestria, traverse, and Biomes You'll Go. When I
use F3 in the biome in question, it shows the biome as
"betternether:nether_mushroom_forest_edge". Thank you for your
quick response.

**Comment by paulevsGitch** [comment]
So, actually I'm not controlling overworld generation. I hope WorldPainter can help you
