### ISSUE TITLE
Cincinnasite Forge bugs out when powered by an IE External Heater

### ISSUE THREAD

**Issue by nihiltres** [paulevsGitch/BetterNether#17]
If you place an External Heater from Immersive Engineering adjacent to the Cincinnasite Forge, power the Heater, and place a smeltable object in the smelting slot of the Forge, the smelting fails to complete, and ticks up its progress bar indefinitely, with the progress bar eventually overflowing the furnace GUI.

Based on my analysis of the bug, I expect that it also occurs with any other blocks that would accelerate the speed of furnaces, but this is the particular example with which I discovered it.

This can probably be fixed very easily: on line 249 of TileEntityForge.java, replace
`if (this.cookTime == this.totalCookTime)` with `if (this.cookTime >= this.totalCookTime)` to make sure recipes complete. As I only did a superficial skim of the code, there might be other fixes needed, but that sticks out as a problem.

**Comment by paulevsGitch** [comment]
Some functions of forge will be redone in next release including this enhancement, thanks.
