### ISSUE TITLE
Skipped 1.16.2?

### ISSUE THREAD

**Issue by MechanosG** [paulevsGitch/BetterNether#170]
Is the latest 1.16.3 version compatible with 1.16.2?  I hear 1.16.2 and 1.16.3 are very similar and many mods are compatible between the 2.  But attempting to use the latest BetterNether with 1.16.2 results in Fabric refusing to load due to BetterNether being tagged as only 1.16.3 compatible.  Twitch/Curseforge launcher isn't allowing new 1.16.3 profiles yet, so I figured I'd ask, just in case Twitch takes their time.

**Comment by paulevsGitch** [comment]
It was marked 1.16.3 as I build it on 1.16.3. Technically it is probably compatible with 1.16.2, but I'm not sure. You can change "fabric.mod.json" inside "better-nether...jar" and replace 1.16.3 to 1.16.2. This will allow you to launch on 1.16.2

**Comment by MechanosG** [comment]
Interesting.  Aight, I'll give that a shot and see what happens.
