### ISSUE TITLE
Enhancement: Brown Large Mushroom textures don't match Jappa textures

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#174]
The textures for the Brown Large Mushroom's cap and stem resemble the pre-Texture Update textures, and look out of place when juxtaposed to the vanilla large mushrooms or the massive mushrooms seen in the Old Fungiwoods biome. This also affects the Red Large Mushroom, but its cap doesn't look as out of place due to being smaller than the vanilla large mushrooms or the giant ones in the Old Fungiwoods.

I would suggest that these fungi be retextured to resemble the Texture Update brown mushroom cap and stem block textures, just as the current textures resembled these textures before the Texture Update.~

![2020-09-29_21 17 54](https://user-images.githubusercontent.com/69029346/94642852-3c034b00-029a-11eb-9619-ba6f1a7f0c31.png)

**Comment by paulevsGitch** [comment]
That's by design. I will change some parts of textures, but only for brown mushrooms
