### ISSUE TITLE
Piglins spawned in basalt temple structures are unarmed, unarmoured and fight the Wither skeletons

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#175]
Within the various basalt temple structures this mod adds are Piglin spawners. These Piglins spawn completely unarmed, which is unnatural for these mobs, who typically spawn with golden swords or crossbows, and sometimes armour, to make themselves threatening. What's more problematic is that these Piglins seek out and attack the Wither skeletons that spawn in the highest floor of the temples. One would expect the mobs in this structure to not only have proper equipment, but also to not be of directly conflicting factions that fight amongst themselves, instead fighting as one force against the player.

I would honestly recommend simply removing Piglins from the temples entirely, for the reasons above, and because Piglins already have their own structures, the vanilla bastion remnants. Their spawners could instead spawn more Blazes, Naga, or Wither skeletons, or perhaps even this mod's skull mobs.

**Comment by paulevsGitch** [comment]
I replaced piglins with magma cubes

**Comment by paulevsGitch** [comment]
Fixed in 4.1.3
