### ISSUE TITLE
Wither skeletons spawned in basalt temple structures take fall damage immediately and are unarmed

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#176]
As per the title, the Wither skeleton spawners that generate as part of the basalt temple structures not only spawn the Wither skeletons without their signature weapons, but also spawn them in midair, causing them to be weakened before the player even reaches the uppermost floor where they reside.

I would suggest moving their spawner to a lower height to where the spawned skeletons don't take fall damage, or perhaps configuring it to spawn Wither skeletons with a couple of seconds of arbitrarily high Resistance effect to combat this fall damage. I would also suggest configuring the spawners to spawn the skeletons with their stone swords. I read that mobs spawned in the basalt temples don't drop items to combat a very low effort farm design, but stone swords are nigh useless to begin with, so, if the issue is that they would drop stone swords if they carried them, I feel that this is balanced.~

**Comment by paulevsGitch** [comment]
Fixed in 4.1.3
