### ISSUE TITLE
"Stripped" spelled as "Striped" for every stripped block

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#177]
Every single stripped log or wood block this mod adds has the same typo: "Stripped" is spelled as "Striped". The latter means "having stripes", which is very much not these blocks' defining characteristic~ :p
In all seriousness, I hope that this can be fixed.~

Vanilla "stripped" woods:
![2020-09-29_23 08 00](https://user-images.githubusercontent.com/69029346/94649022-a6bb8300-02a8-11eb-9331-31fc0d546b31.png)
Better Nether "striped" woods:
![2020-09-29_23 07 04](https://user-images.githubusercontent.com/69029346/94648954-84296a00-02a8-11eb-84a1-155374778bd9.png)

**Comment by paulevsGitch** [comment]
Fixed in 4.1.3
