### ISSUE TITLE
Enhancement: Blocks with the same names as vanilla blocks

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#178]
I've noticed that this mod has three blocks with the exact same names as vanilla blocks. While this isn't a critical issue, it does make things seem a little bit less polished. I would suggest finding alternate names for these blocks to distinguish them:
- The **Smoker** and the vanilla Smoker. Off the top of my head, I can think of **Smoke Vent**, **Smoke Jet**, **Smoking Column**, **Smoking Pillar*...
- The **Nether Brick Wall** and the vanilla Nether Brick Wall. I couldn't find the recipe for the Better Nether Nether brick wall to determine if this would be accurate to other chiselled blocks, but **Chiselled Nether Brick Wall** could do, or perhaps **Ornate Nether Brick Wall**...?
- The **Bone Block** and the vanilla Bone Block. This mod actually acknowledges the rift between these two and allows conversion from the vanilla bone block to the Better Nether one, but having them have the same name still feels unpolished. Off the top of my head, I can think of **Bone Chunk**, or possibly renaming the vanilla one to **Bone Pillar** or **Block of Bonemeal**.

These are all just ideas, so take them or leave them.~

![2020-09-29_23 19 40](https://user-images.githubusercontent.com/69029346/94650906-66f69a80-02ac-11eb-8f58-bb6f1e5103f0.png)
![2020-09-29_23 20 42](https://user-images.githubusercontent.com/69029346/94650923-6c53e500-02ac-11eb-8549-8ee90b7c17a0.png)
![2020-09-29_23 21 08](https://user-images.githubusercontent.com/69029346/94650927-6d851200-02ac-11eb-8cdf-8ba3c9e42e48.png)

**Comment by paulevsGitch** [comment]
All this names appeared before Mojang introduced their blocks. Probably they will stay the same as before

**Comment by saltyseadoggo** [comment]
I understand. However, having blocks with the same names as eachother can be confusing, and also feels unpolished. I would stress that I would like to see this issue fixed to be able to easily distinguish between these blocks, especially the bone block and nether brick wall, which look quite similar to their vanilla counterparts in the inventory.
