### ISSUE TITLE
[Bug] Structures overlap fortresses

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#179]
The massive mushrooms in the Old Fungiwoods biome generate over all blocks of Nether Fortresses: bricks, fences and air alike. One would expect the Fortress to cut through them, as it does with terrain blocks.
![2020-09-29_23 24 14](https://user-images.githubusercontent.com/69029346/94650824-48909f00-02ac-11eb-9d38-7fb889228f34.png)
![2020-09-29_23 24 32](https://user-images.githubusercontent.com/69029346/94650830-49293580-02ac-11eb-97aa-2d85f91cf8bf.png)

**Comment by paulevsGitch** [comment]
This is a result of generation order - fortress generation runs earlier than plants generation. Large mushrooms are structures and couldn't check each block on placement, so there is a fast check with air volume in the area where the structure will be placed. It works for most cases, but not for all. For now this is unfixable, but I will think how this can be done

**Comment by saltyseadoggo** [comment]
Groovy. I'll also put it on record that this issue occurs with Crimson Pinewood fungi as well.
![2020-10-02_16 49 01](https://user-images.githubusercontent.com/69029346/94977808-4a867800-04cf-11eb-85f0-f7e3285d4508.png)

**Comment by paulevsGitch** [comment]
In the latest versions this bug was probably almost fixed. If it still exists please reopen it on a new BN issue tracker
