### ISSUE TITLE
Crash When Entering Nether

### ISSUE THREAD

**Issue by Darkfiend009** [paulevsGitch/BetterNether#18]
I am creating a new modpack and testing the mods/dimensions before releasing it. When i try to enter the Nether with BetterNether installed, my client crashes. Here is the crash report:

https://pastebin.com/X4CARhgD

If i remove BetterNether from the modpack, i am able to enter the Nether without issues. I was hoping to include this mod in the pack, however, because i thought it added some unique aspects to the dimension!

Let me know if i can help in any way.

**Comment by paulevsGitch** [comment]
I can't point the bug of mod in these logs. “Exception ticking world” can be result of not enough memory or something similar.

**Comment by Darkfiend009** [comment]
After replicating that error multiple times, i did a little config tweaking and was able to come up with a little more specific error in the Nether:

https://pastebin.com/kmyucJzw

**Comment by paulevsGitch** [comment]
This is the same error as [here](https://github.com/paulevsGitch/BetterNether/issues/9), will be fixed in next release, at this time mod is incompatible with Apotheosis.
