### ISSUE TITLE
[Suggestion] Piglins attack players who give them Cincinnasite Ingots

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#180]
Forged Cincinnasite closely resembles gold, and can be seen as a *"fool's gold"* akin to pyrite in the real world, so I thought it could be a fun quirk for Piglins to be briefly fooled if the player throws them a Cincinnasite Ingot, only to then become hostile after the amount of time it would take them to process a barter. This could possibly extend to them picking up any Cincinnasite items they find on the ground, similarly to how they pick up any gold items, only to drop them in disgust after observing them closely, setting some sort of internal timer until they can be fooled by this again to prevent them from picking up and dropping the same Cincinnasite item repeatedly in quick succession. It would also act as a bit of lore to explain why the Piglins haven't moved into the Nether Cities this mod adds.

**Comment by quiqueck** [comment]
See also #253

**Comment by quiqueck** [comment]
We keep this in mind as part of #253
