### ISSUE TITLE
[Bug] Respawner Statue drops in Creative mode if broken at the top

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#181]
**Expected Behaviour**
In Creative mode, if the player breaks either the top or bottom block of a Respawner Statue, the statue should not drop an item, matching how block breaking works in Creative mode.

**Actual Behaviour**
In Creative mode, breaking the top block of a Respawner Statue causes it to drop the Respawner Statue item, as if it was broken in Survival mode. Breaking the bottom half of the statue causes it to not drop anything.

**Steps to Reproduce**
- Create a new world in Creative mode.
- Obtain and place two Respawner Statues.
- Break one statue's bottom block; the entire statue will drop nothing.
- Break the other statue's top block; the entire statue will drop one Respawner Statue item.

**Comment by paulevsGitch** [comment]
Fixed same issue with chairs

**Comment by paulevsGitch** [comment]
Fixed in 4.1.3
