### ISSUE TITLE
[Enhancement] [Suggestion] Black Apple does not resemble Texture Update apple sprite

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#182]
**Expected Behaviour**
The Black Apple item's sprite would have the same basic shape as the vanilla Apple and Golden Apple.

**Actual Behaviour**
The Black Apple item's sprite does not have the same basic shape as the vanilla Apple and Golden Apple. Instead, it has the same basic shape as the pre-Texture Update apple sprite.

**Attachments**
![2020-09-30_17 09 04](https://user-images.githubusercontent.com/69029346/94752915-6e1bb800-0341-11eb-93c6-c63ea75d799c.png)

**Comment by paulevsGitch** [comment]
Black Apple is not apple actually, texture will stay the same
