### ISSUE TITLE
[Bug] Mobs are scarce due to Fireflies and Skulls spawning above the bedrock ceiling

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#183]
**Expected Behaviour**
All mobs added by Better Nether would not spawn on the Nether's bedrock ceiling, abiding by the same rules vanilla Nether mobs do, to prevent them from building up on the ceiling and filling up mob caps.

**Actual Behaviour**
The *Firefly* and *Skull* mobs can spawn on the Nether ceiling, as verified by the *Carpet* mod. Because spawning spaces are plentiful on the Nether ceiling, they spawn in abundance here, filling up the *Monster* mob cap, and noticeably resulting in drastically fewer hostile mobs compared to the vanilla Nether, which is what motivated me to investigate the issue. I consider this to be a *major detriment* to playing with this mod, as it makes the Nether less dangerous and exciting due to the lack of hostile mobs.

**Attachments**
This is the data generated by the *Carpet* mod regarding what can spawn on bedrock in the Nether with this mod enabled. Note that no vanilla mobs can spawn on bedrock in the nether. Also note the Fireflies in the distance.
![2020-09-30_18 39 36](https://user-images.githubusercontent.com/69029346/94756781-4f232300-034d-11eb-9d29-d118940ab4c0.png)

**Comment by paulevsGitch** [comment]
Fireflies and skulls are not spawning on bedrock, they are spawning in the air. I can fix it limiting their spawn to world height

**Comment by paulevsGitch** [comment]
Fixed in 4.1.3

**Comment by ElKameleon** [comment]
Skulls still spawn above the bedrock ceiling. Better Nether 5.0.0

**Comment by saltyseadoggo** [comment]
I would recommend opening a new issue, as I can't seem to reopen this one.
