### ISSUE TITLE
[Bug] Fireflies and Hydrogen Jellyfish considered Monsters and fill up their mob cap

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#184]
**Expected Behaviour**
Due to being a source of ambience and not hostile to players, Fireflies and Hydrogen Jellyfish would be considered *Ambient* mobs, and would fill the *Ambient* mob cap.

**Actual Behaviour**
As verified by the Carpet mod (see the screenshot in #183 ), Fireflies and Hydrogen Jellyfish are considered *Monster* mobs. This means that they count towards the *Monster* mob cap, and, by existing, prevent hostile mobs such as Piglins, Zombified Piglins, Hoglins and Ghasts from spawning as frequently as they do in vanilla. This contributes to the lack of hostile mobs that can be seen in the Nether with this mod enabled, which is also affected by #183 .

**Comment by paulevsGitch** [comment]
Any mob categories except monsters will not spawn in the nether (except vanilla striders) in 1.16+. This is not bug

**Comment by saltyseadoggo** [comment]
Okay. Is there any way to change that, so other mob categories can spawn in the Nether? I feel that such changes to the Nether's spawning patterns are not past the scope of this mod, given how it already makes extensive modifications to its world generation. If such would be possible, it would avoid the issue of fireflies and hydrogen jellyfish preventing other hostile mobs from spawning, and removing some of the excitement of facing the hostile mobs by making them less common.

**Comment by paulevsGitch** [comment]
Probably, for now it is not possible. I will look at this again, but I don't think that I could change spawn mechanics. I implemented spawn configuration for my mobs, so you can change them to lower values for now
