### ISSUE TITLE
[Enhancement] Make nylium block selection random on bonemealing

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#185]
**Expected Behaviour**
In vanilla Minecraft, bonemealing _netherrack_ that is next to both _crimson_ and _warped nylium_ causes the netherrack to become either crimson or warped nylium with equal chance of either. One would expect this behaviour to remain the same with _Better Nether_ enabled, and would expect it to also apply to the _Better Nether_ blocks _mushroom grass_, _sepian mushroom grass_, _jungle grass_ and _nether mycelium_, all of which have the same bonemealing mechanic as the vanilla nylium and share the _minecraft:nylium_ tag.

**Actual Behaviour**
Bonemealing netherrack that is next to any combination of the vanilla nylium blocks, mushroom grass, sepian mushroom grass, jungle grass or nether mycelium will always turn it into the same block. Which block it chooses depends on the directions in which the nylium/grass/mycelium blocks are placed in relatively to the netherrack, and how many of which types are present, but using bonemeal on the netherrack will always produce the same block.

**Steps to reproduce**
- Start Minecraft under vanilla 1.16.3 and create a new world of any type in Creative mode.
- Place one block of netherrack anywhere with air above it, then place one crimson and one warped nylium directly adjacent to it on any two of the four cardinal directions.
- Bonemeal the netherrack. The netherrack will turn into one of the two nylium types.
- Replace the new nylium block with netherrack, and bonemeal it again. Repeat this step many times. The netherrack will turn into crimson nylium about 50% of the time, and warped nylium about 50% of the time. :heavy_check_mark:
- Start Minecraft under Fabric with _Better Nether_ loaded, and load the world created in step one.
- Replace the middle nylium block in the earlier experiment with netherrack and bonemeal it as you did in step four. No matter how many times you do this, it will always turn into the same nylium block. :x: 
- Place one block of netherrack anywhere with air above it, then place any of the following directly adjacent to it: crimson nylium, warped nylium, mushroom grass, sepian mushroom grass, jungle grass, Nether mycelium.
- Bonemeal the netherrack. No matter how many times you replace and bonemeal the netherrack, it will always turn into the same block. :x:

**Comment by paulevsGitch** [comment]
Added in 4.1.3
