### ISSUE TITLE
BN walls next to vanilla walls reveal model gaps

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#189]
**Expected Behaviour**
_Better Nether_'s intricate wall designs would have inner faces show when placed next to vanilla walls, whose shapes don't line up with theirs.
**Actual Behaviour**
Soul Sandstone, Cincinnasite, Bone and _[BN]_ Nether Brick walls show gaps in their models when placed next to vanilla walls. Curiously, they don't show these gaps when _Better Nether_ walls of different shapes are placed next to each other.
**Attachments**
The model gaps:

![2020-10-02_17 03 29](https://user-images.githubusercontent.com/69029346/94978375-f4ff9a80-04d1-11eb-9f09-f52a31f5de74.png)
![2020-10-02_17 03 42](https://user-images.githubusercontent.com/69029346/94978376-f5983100-04d1-11eb-8ab5-48daf832504d.png)
![2020-10-02_17 03 57](https://user-images.githubusercontent.com/69029346/94978379-f630c780-04d1-11eb-982c-b4a4271f3c48.png)
![2020-10-02_17 04 13](https://user-images.githubusercontent.com/69029346/94978380-f6c95e00-04d1-11eb-8627-6bb9097e189a.png)

The other side of this interaction, demonstrated with the bone wall. Note that the vanilla wall shows an inner face to prevent this issue.

![2020-10-02_17 05 19](https://user-images.githubusercontent.com/69029346/94978408-11033c00-04d2-11eb-8059-94bad6a9fbb7.png)

Two differently shaped _Better Nether_ walls next to each other, which, curiously, avoid triggering this issue.

![2020-10-02_17 06 14](https://user-images.githubusercontent.com/69029346/94978433-32fcbe80-04d2-11eb-980a-fd1cff6c7a87.png)
![2020-10-02_17 06 17](https://user-images.githubusercontent.com/69029346/94978435-33955500-04d2-11eb-890b-4310fd9debd0.png)

**Comment by paulevsGitch** [comment]
Fixed in 4.1.4
