### ISSUE TITLE
[Enhancement, Suggestion] Have Bone, Cincinnasite, Better Nether Brick walls stack more nicely

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#190]
I was examining this mod's wall models, and noticed that three of them- the Bone, Cincinnasite and [Better Nether] Nether Brick walls- have gaps between their middle, straight sections when stacked vertically. This is in contrast with vanilla walls and the Soul Sandstone and Basalt walls, which stack without gaps to create a smooth, flush combined wall.

I would like to see these walls change models to close the gaps between them when stacked vertically. I think this would be a nice touch.~

**Attachments**
![2020-10-02_17 14 54](https://user-images.githubusercontent.com/69029346/94978724-8f141280-04d3-11eb-9f17-849bb79c52e4.png)
![2020-10-02_17 15 26](https://user-images.githubusercontent.com/69029346/94978725-8faca900-04d3-11eb-93a4-d7ddecdae571.png)
![2020-10-02_17 15 40](https://user-images.githubusercontent.com/69029346/94978726-90453f80-04d3-11eb-9c7c-9f41a419bd24.png)

**Comment by quiqueck** [comment]
Moving to our Enhancement List.
