### ISSUE TITLE
[Bug] /locate betternether:nether_city doesn't work

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#191]
**Expected behaviour**
Running the command
_/locate betternether:nether_city_
would always find the nearest Nether City and return its coordinates, as it does with vanilla structures.

**Actual Behaviour**
Running the command
_/locate betternether:nether_city_
never finds Nether Cities, even if the player is _standing in one_.

**Attachments**
![2020-10-02_19 14 02](https://user-images.githubusercontent.com/69029346/94981043-e326f300-04e3-11eb-95b3-ea89ce1ff9e1.png)

**Comment by paulevsGitch** [comment]
/locate command doesn't work properly for 1.16.2 and 1.16.3, probably as a result of biomes and structures changes. I can fix it at least for cities as I have my own functions to find them

**Comment by paulevsGitch** [comment]
Fixed in 4.1.4
