### ISSUE TITLE
[Generation Bug] Ghast Hives can generate in lava

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#192]
**Expected Behaviour**
Ghast Hives would never generate partially submerged in lava, or, if they did, the lava would flood them evenly.

**Actual Behaviour**
Ghast Hives can generate partially submerged in lava. When they do, the lava does not flood them; the air and decoration blocks, such as wart seeds and nether moss, override the lava, creating an uneven effect.

**Attachments**
This hive was found at the coordinates **40, 32, -63** in worlds with the seed **3977722039072752422**.
![2020-10-02_19 18 51](https://user-images.githubusercontent.com/69029346/94981136-94c62400-04e4-11eb-8497-5f81d70be3b9.png)
![2020-10-02_19 18 58](https://user-images.githubusercontent.com/69029346/94981137-95f75100-04e4-11eb-938c-9f41fb3b132f.png)

**Comment by paulevsGitch** [comment]
Fixed in 4.1.4
