### ISSUE TITLE
[Generation Bug] Nether City building #13's drawers don't rotate to match the building

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#193]
**Expected Behaviour**
Chests of Drawers generated in Nether city buildings would face the correct way in every instance.

**Actual Behaviour**
The Chests of Drawers in Nether city building betternether:city_building_13 do not rotate to match the building's rotation. This can be observed in cities where this building generates, or by generating it via structure block with 90*, 180* or 270* rotation.

**Attachments**
Chests of drawers in betternether:city_building_13 generated via structure block with rotation 0:

![2020-10-02_19 50 16](https://user-images.githubusercontent.com/69029346/94981696-220b7780-04e9-11eb-99ef-1a14b521b4dc.png)
![2020-10-02_19 50 22](https://user-images.githubusercontent.com/69029346/94981697-22a40e00-04e9-11eb-8099-bdd78dcc092f.png)

Chests of drawers in betternether:city_building_13 generated via structure block with rotation 180 (the other set is the same):
![2020-10-02_19 50 05](https://user-images.githubusercontent.com/69029346/94981702-351e4780-04e9-11eb-9a1c-9bef2c9cb457.png)

**Comment by paulevsGitch** [comment]
Fixed in 4.1.4
