### ISSUE TITLE
Game Crashes When Entering The Nether

### ISSUE THREAD

**Issue by A-a-ron717** [paulevsGitch/BetterNether#194]
I'm not sure if this is an issue with the mod or with my game, but my game crashes on the "Loading terrain..." screen when going through a nether portal. Here's the crash report.
[crash-2020-10-07_16.37.55-server.txt](https://github.com/paulevsGitch/BetterNether/files/5343731/crash-2020-10-07_16.37.55-server.txt)

**Comment by EnderBro123** [comment]
Listing the mods and such might be helpful.

**Comment by A-a-ron717** [comment]
Adventurez
Allure
armored elytra
autoconfig
beenfo
bettercaves
better dispensers
better nether
biomepicker
blockshifter
blockus
boringbackgrounds
bow infinity fix
Biomes you'll go (BYG)
Cardinal Components
Carpet & Carpet tis addition
cave biomes
chains link
clothesline
cmdkeybind
colorbricks
cultivation
custom portals
Dungeons mod
durability viewer
Voxelmap
factory
falling tree
fast furnace
gildedarmor
golems galore
gotta climb fast
Hot Furnace
Hwyla
illuminations

**Comment by EnderBro123** [comment]
That’s a lot of mods... Anyway, put 1 in at a time till your game crashes.

**Comment by A-a-ron717** [comment]
I'll do that, but I deleted that comment because I missed a ton of mods by mistake, this is the full list if one stands out
clothesline-fabric-0.3.0+1.16.3-all.jar
cmdkeybind-1.4.5-1.16.jar
colorbricks-fabric-1.16.2-0.4.0.jar
config-2-4.8.2.jar
cultivation-0.0.72.jar
custom-portals-1.3.0.jar
DungeonsMod-1.16.2-1.0.0.0.jar
durabilityviewer-1.16.2-fabric0.17.2-1.8.7.jar
fabric-api-0.22.1+build.409-1.16.jar
fabric-carpet-1.16.3-1.4.12+v201001.jar
fabric-language-kotlin-1.4.0+build.1.jar
fabric-language-scala-0.3.2.12-fat.jar
fabricmod_VoxelMap-1.10.11_for_1.16.3.jar
factory-fabric-1.16.2-1.3.0.jar
FallingTree-Fabric-1.16.3-rc1-2.3.1.jar
fastfurnace-2.3.jar
gildedarmor-1.0.0.jar
golemsgalore-0.2.0+mc.1.16.2.jar
gottaclimbfast-1.0.jar
HotFurnace-1.16.3-1.1.1.jar
Hwyla-fabric-1.16.2-1.9.23-79(1).jar
illuminations-1.1.jar
ironchest-1.16.3-11.2.6.jar
kibe-1.16.3-1.4.4-BETA.jar
lambdynamiclights-fabric-1.3.1+1.16.3.jar
lapisreserve-1.0.6.jar
lengthyladders-1.0.1.jar
libblockattributes-all-0.8.1.jar
libcd-3.0.2+1.16.2.jar
litematica-fabric-1.16.3-0.0.0-dev.20200913.215807.jar
lithium-fabric-mc1.16.3-0.5.6.jar
lock_minecart_view-for-MC1.16.2-1.2.1.jar
malilib-fabric-1.16.3-0.10.0-dev.21+arne.1.jar
medievalweapons-1.0.0.jar
Mo-Glass-1.4-MC1.16.3.jar
modmenu-1.14.6+build.31 (1).jar
MoEnchantments-1.13.7.jar
mooblooms-1.3.2.jar
more_crafting_tables_v0.1.3_1.16.x.jar
mostructures-1.0.0-pre3+mc.1.16.2.jar
nbtcrafting-2.0.0+mc1.16.2-pre1.jar
NE-1.16.3-Fabric-1.1.4.jar
noambientmobs-1.0.0+1.16.2.jar
NoFog-1.16.2b1-Fabric.jar
Patchouli-1.16.2-44-FABRIC.jar
phosphor-fabric-mc1.16.1-0.6.0+build.7.jar
quickshulker-1.1.8-1.16.jar
randompatches-1.16.2-1.22.1.2.jar
red-bits-1.2.0.jar
renlava-fabric-1.16.3-0.0.4.jar
repurposed_structures-1.16.3-1.6.2.jar
rotten-1.2.2.jar
RoughlyEnoughItems-5.6.1.jar
Skin_Swapper_1.16.3-2.0.1+.jar
sodium-fabric-mc1.16.3-0.1.0.jar
sponges-plus-1.0.1.jar
telepistons-1.0.1.jar
traverse-3.0.0-beta+build.4.jar
trumpet-skeleton-fabric-1.1.3.jar
Tumble+Dryer-2.0.jar
vanilla-hammers-2.0.8-1.16.2.jar
vanillaenhanced-1.3.0.jar
vanillaexcavators-2.1.2-1.16.2.jar
vanillautomated-1.1.5.jar
woodenhoppers-1.0.0.jar
wraith-silkspawners-1.0.1.jar

**Comment by paulevsGitch** [comment]
Same as #169 issue. It is not related to BN

**Comment by paulevsGitch** [comment]
![2020-10-08_09-59-50](https://user-images.githubusercontent.com/17707380/95425530-17b80600-094d-11eb-8463-069012964f5e.png)

**Comment by theishiopian** [comment]
reading the stack trace, this seems to occur when better nether attempts its cleaning pass. A quick fix might be to disable the pass, at the cost of rougher terrain.

**Comment by A-a-ron717** [comment]
Oh! I will take it up with them, then. Sorry for taking up your time and thank you for helping!
