### ISSUE TITLE
[bug] Generation issue with old world

### ISSUE THREAD

**Issue by ASingleMelon** [paulevsGitch/BetterNether#197]
**the issue**
On older worlds, none of the modded biomes would generate. this repeated for 3 other worlds, structures such as the ghast hives, all the basalt temples, glowstone and netherrack stalactites would still generate.
Upon the generation of a new world, the new biomes would succesfully generate.

Is there a way to fix these worlds or are they unsalvagable?

**Comment by paulevsGitch** [comment]
Mojang overwritten how biomes work. You can try make world with same seed and then copy its level.dat to an old folder

**Comment by ASingleMelon** [comment]
that did the trick, thank you for the tip!
