### ISSUE TITLE
Crash due to disabling some blocks/biomes

### ISSUE THREAD

**Issue by cybercat5555** [paulevsGitch/BetterNether#2]
As it says in the title. I use another mod that adds more biomes and blocks to the nether, and disabled some of BN's blocks/biomes as to no chock up the other one. The game loaded fine at first, but after editing the config, it crashed.

Crash log: https://pastebin.com/bju2NywH

**Comment by paulevsGitch** [comment]
It seems like you disable block, but not disable stairs from it. Stairs from null block will crash the game. I will fix block registration in next release. If you want disable any block now - you must also disable all its variants (like stairs or slabs).

**Comment by paulevsGitch** [comment]
Block registration system was rewritten, so in next version problem will be solved.

**Comment by paulevsGitch** [comment]
Fixed in new release
