### ISSUE TITLE
[Suggestion] Other Config Suggestions

### ISSUE THREAD

**Issue by SureinDragon** [paulevsGitch/BetterNether#20]
Heyo! Big fan of this mod, but I'm hoping for a bit more configurable options.

Edit TL/DR: After tinkering with the mod more, my biggest hope for the mod is to be able to configure biome rarity and or spawn weights. Or, even individual biome size would suffice. 

Would it be possible in the future to add a config for the rarity of mini-structures, and the ability to enable/disable fireflies?

Edit: The original main point of this post was to reduce nether wart density, but the mod author let me know that biome density is not biome rarity, but plant matter per biome density. xD So I have re purposed this thread. 

Thanks for reading, happy modding!

**Comment by paulevsGitch** [comment]
Now the structures' density can be changed in the config (not released yet). The size of biomes and their frequency are still not customizable in actual generator, although I now know how to do it.

**Comment by paulevsGitch** [comment]
Now it is implemented in new version
