### ISSUE TITLE
Crash with Better Slabs mod

### ISSUE THREAD

**Issue by cs127** [paulevsGitch/BetterNether#203]
Better slabs mod:
https://www.curseforge.com/minecraft/mc-mods/better-slabs
https://github.com/Eilux/BetterSlabs

Crash report:
[crash-2020-10-23_22.18.35-client.txt](https://github.com/paulevsGitch/BetterNether/files/5431321/crash-2020-10-23_22.18.35-client.txt)

**Comment by paulevsGitch** [comment]
I couldn't see anything relative to Better Nether
