### ISSUE TITLE
/locate command for modded/datapack structures fails when BetterNether is on

### ISSUE THREAD

**Issue by TelepathicGrunt** [paulevsGitch/BetterNether#204]
When BetterNether is on, the /locate command will fail to return any modded/datapack structure added to nether biomes despite the structures actually spawning like so:
![image](https://user-images.githubusercontent.com/40846040/97065210-135d3100-157a-11eb-83f2-afed16222256.png)
The issue was reported to me on here: https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/issues/38

The good news is I seen this issue before and I know exactly how to fix it. Basically in the Biome Source's constructor, you need to take the passed in registry, pull out all the biomes your Biome Source will spawn from it, and pass that list of biomes into the super call.
https://github.com/paulevsGitch/BetterNether/blob/f996cccbb5985d19b57063b386ede1a1d146474e/src/main/java/paulevs/betternether/world/NetherBiomeSource.java#L30

The reason for this is when one does /locate, the game goes to the chunkgenerator and the chunkgenerator asks the biome source if it has any biome with the given structure. If the list of biomes the biome source has does not have a biome with the structure, the chunkgenerator aborts and tells the user that the structure cannot be found. If it is found, then it does the chunk checking for the actual position of the structure.

The key thing is, you have to make the list of spawnable biomes by pulling them from the registry parameter. This is because the registry is the dynamicregistry and it has the finalized versions of all biomes. Attempting to make a list of valid biomes elsewhere could leads to the /locate issue persisting as pre-made biome lists might contain instances of biomes that don't get modified by other mods/datapacks when the dynamicregistry has the modified version.

This issue has affected several people so this isn't a new thing. But the fix should be simple! I hope this helps!

**Comment by paulevsGitch** [comment]
Fixed in 4.1.6
