### ISSUE TITLE
Compatibility with Packed Storage

### ISSUE THREAD

**Issue by McAchi** [paulevsGitch/BetterNether#205]
The mod Packed Storage makes storage, well, more packed, and is a really essential mod for me.
It makes chests have different wood types, makes them upgradable, as well as for barrels, and adds a new type of storage that nicely completes the mod.
Since the Better Nether mod also adds new types of chests and barrels, it would be really nice if they were upgradable in the same way, as well as having the new type of storage in the new woods.

Here's the mod: https://www.curseforge.com/minecraft/mc-mods/packed-storage

The Vanillas Hammer compatibility was a good thing to see; so please, pretty please, if you don't mind.
Thanks.

**Comment by quiqueck** [comment]
This mod is not available for 1.17 or 1.18, so sadly I'll close this issue for now.
