### ISSUE TITLE
Game crash upon startup 1.16.3

### ISSUE THREAD

**Issue by anderfels** [paulevsGitch/BetterNether#206]
Game crashes before it can finish starting up with Better Nether (and Better End, for some reason) installed, works regularly if I disable it. Tried on both MultiMC and the regular MC launcher and retained the same crash report, even after disabling all my other mods and had just Better Nether (version 4.1.5) and Fabric API (version 0.24.2+build.413). I also tried updating Java and reinstalling both the API and the mod itself, but the crash stays the same: [Crash report](https://pastebin.com/DyC3C6P3)

**Comment by anderfels** [comment]
ah... It seems Better Nether is actually not up to date with build 413 of Fabric API, hehe. I switched to build 412 and it loads fine. I feel a bit silly.

**Comment by paulevsGitch** [comment]
Fixed in 4.1.7
