### ISSUE TITLE
Block name translation errors [en_us]

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#212]
Whilst combing through this mod's en_us to see the fixes in 4.1.8, I noted several block names that are grammatically incorrect or inconsistent with vanilla naming conventions, so I thought that I would bring your attention to them here.
The following entries have these issues:

	"block.betternether.red_large_mushroom": "Red Large Mushroom",
	"block.betternether.brown_large_mushroom": " Brown Large Mushroom",
Should be "Large Red Mushroom" and "Large Brown Mushroom", as the first adjective denotes a variant of the thing described by the second adjective; these two aren't _red and brown variants of one large mushroom_, they are _large variants of the red and brown mushrooms_.

	"block.betternether.obsidian_bricks_stairs": "Obsidian Bricks Stairs",
	"block.betternether.obsidian_bricks_slab": "Obsidian Bricks Slab",
	"block.betternether.blue_obsidian_bricks_stairs": "Blue Obsidian Bricks Stairs",
	"block.betternether.blue_obsidian_bricks_slab": "Blue Obsidian Bricks Slab",
	"block.betternether.basalt_bricks_stairs": "Basalt Bricks Stairs",
	"block.betternether.basalt_bricks_slab": "Basalt Bricks Slab",
	"block.betternether.basalt_bricks_wall": "Basalt Bricks Wall",
_Bricks_ should be _Brick_ in all of these to match vanilla naming conventions for vanilla stone, Nether, Prismarine, End stone and blackstone brick stairs and slabs.

	"block.betternether.bricks_fire_bowl": "Bricks Fire Bowl",
As per the above, _Bricks_ should be _Brick_, but it should actually be _Nether Brick_ in this case to denote that this bowl is made from Nether bricks as opposed to regular bricks.

	"block.betternether.cincinnasite_fire_bowl_soul": "Soul Cincinnasite Fire Bowl",
	"block.betternether.bricks_fire_bowl_soul": "Soul Bricks Fire Bowl",
	"block.betternether.netherite_fire_bowl_soul": "Soul Netherite Fire Bowl",
Should be "Cincinnasite Soul Fire Bowl, "Nether Brick Soul Fire Bowl" and "Netherite Soul Fire Bowl", respectively. Once again, the first adjective describes a variant, so these aren't fire bowls made of _soul Cincinnasite_ or the likes, they're soul fire bowls made of the regular materials. The Nether brick bowl has the same issues as the regular fire bowl above as well.

	"block.betternether.brick_pot": "Brick Pot",
Should be "Nether Brick Pot" to denote the material and separate it from the vanilla bricks.

	"block.betternether.soul_sandstone_cut_stairs": "Cutted Soul Sandstone Stairs",
	"block.betternether.soul_sandstone_cut_slab": "Cutted Soul Sandstone Slab",
Should be "Cut Soul Sandstone Stairs" and "Cut Soul Sandstone Stairs", as the past tense of _cut_ is usually still _cut_. This also matches naming conventions for vanilla cut sandstone and red sandstone. The name for cut soul sandstone itself is correct.

	"block.betternether.obsidian_tile_small": "Obsidian Small Tile",
	"block.betternether.blue_obsidian_tile_small": "Blue Obsidian Small Tile",
Should be "Small Obsidian Tile" and "Small Blue Obsidian Tile" for the grammar reasons listed with the mushrooms, as well as to match _Small Nether Brick Tile_ and _Small Cincinnasite Tile_.

	"block.betternether.striped_bark_anchor_tree": "Anchor Tree Stripped Bark",
	"block.betternether.striped_log_anchor_tree": "Anchor Tree Stripped Log",
	"block.betternether.striped_bark_nether_sakura": "Nether Sakura Stripped Bark",
	"block.betternether.striped_log_nether_sakura": "Nether Sakura Stripped Log",
Should have _Stripped_ before the rest of the name instead of before _bark_ or _log_ to match how vanilla stripped logs and bark are named. The rest of the stripped logs and bark do not have this issue.

Since I took the time to find all of these, I figured I would submit a pull request with the fixes, as it wouldn't take much time. That should be coming shortly.~

**Comment by paulevsGitch** [comment]
Thanks, translation will be updated in 5.0.1

**Comment by saltyseadoggo** [comment]
You're welcome! By the way, I realised that I missed one entry in the pull request:

	"block.betternether.cincinnasite_carved": "Cincinnasite Carved",
should be


	"block.betternether.cincinnasite_carved": "Carved Cincinnasite",
.~

**Comment by paulevsGitch** [comment]
Fixed in 5.0.1
