### ISSUE TITLE
Player on seats snaps to south-facing position, and body lags behind head when turning

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#215]
Whilst testing the three chair offerings added by Better Nether, I noticed that the player model visible via F5 or another player's perspective has issues with the player's body not facing the same way the head is. The player's body seems to always want to face south, and, when the player turns their camera, the head follows perfectly, but the body lags behind more and more the further the camera goes from dead south. When facing dead north, there is a point where the body flips 180* instantly when continuing to turn around. This issue also means that chairs that don't face south have the player seated with their legs clipping through the back of the chair by default.
I would hope that this issue can be fixed for a lovelier sitting-down experience.~
**Attachments**
Facing dead south.
![2020-11-02_18 30 46](https://user-images.githubusercontent.com/69029346/97944889-c546eb00-1d3a-11eb-91ea-3f16fdd14a84.png)
Turning away from south, the body lags behind, about halfway between where the head is facing and south.
![2020-11-02_18 30 52](https://user-images.githubusercontent.com/69029346/97944890-c710ae80-1d3a-11eb-8cdc-82238fc12306.png)
This picture is right on the edge of where the body would flip, facing north.
![2020-11-02_18 31 03](https://user-images.githubusercontent.com/69029346/97944892-c7a94500-1d3a-11eb-8753-68be2b683bba.png)

**Comment by paulevsGitch** [comment]
This is MC sitting behavior on some entities, I tried to fix that, but failed

**Comment by saltyseadoggo** [comment]
Might I suggest taking a look at the code for the lawn chairs added by TerraformersMC's Campanion? https://github.com/TerraformersMC/Campanion I was playing with this mod when I noticed that their lawn chairs do not have this issue, nor the horse healthbar.~

**Comment by paulevsGitch** [comment]
Fixed in 5.0.1
