### ISSUE TITLE
Seat entities have horse health bar visible

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#216]
When a player is sitting on any of the chairs, stools or barstools added by Better Nether, an orange healthbar matching the one shown when riding horses, donkeys, mules or llamas appears. This is strange, visually, given that these furniture items are not alive. Is there perhaps some property of the minecart, which does not show its health, that can be applied to the seats to hide this?

**Comment by paulevsGitch** [comment]
Fixed in 5.0.1
