### ISSUE TITLE
Farmland sides become invisible across chunk boundaries

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#217]
Better Nether's farmland _(as opposed to vanilla farmland)_ has strange culling issues on its green side pieces when the player views the block across chunk boundaries. The green sides that correspond to the boundary the block is being viewed across become invisible. See the attached screenshots.
This bug was discovered with a Sodium client, and was not tested with a vanilla client, so, if this can't be replicated, it may be a Sodium issue.

![2020-11-02_18 52 57](https://user-images.githubusercontent.com/69029346/97945621-ead4f400-1d3c-11eb-8a64-acd3f03e3f0e.png)
![2020-11-02_18 53 03](https://user-images.githubusercontent.com/69029346/97945637-f1fc0200-1d3c-11eb-81f1-76d04d52c0ea.png)
![2020-11-02_18 53 16](https://user-images.githubusercontent.com/69029346/97945639-f32d2f00-1d3c-11eb-9fb4-1407e47cd236.png)
![2020-11-02_18 53 26](https://user-images.githubusercontent.com/69029346/97945643-f45e5c00-1d3c-11eb-80e7-24cd9c011664.png)

-

**Comment by paulevsGitch** [comment]
Looks like this is Sodium block culling, I couldn't control this

**Comment by paulevsGitch** [comment]
I think you can disable this in sodium config

![image](https://user-images.githubusercontent.com/17707380/97976053-21614c00-1ddb-11eb-9080-ab29863f4546.png)
