### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Blazer4Hire** [paulevsGitch/BetterNether#22]
I really enjoy your mod and the feel of it, but I have a request for an option or way to disable or modify the mushrooms 3D texture. I really love the 3D texture but if I use any custom textures it tries to use the custom texture and splices the texture across the model.
![2019-05-14_21 02 55](https://user-images.githubusercontent.com/50091501/57745956-3a34e980-769d-11e9-957f-ee20a4afe8fe.png)

**Comment by paulevsGitch** [comment]
New version will not have custom mushrooms

**Comment by Blazer4Hire** [comment]
NO NO, You don't have to remove custom mushrooms! I think if you were to change the texture for the mushroom to use whatever mushroom block and stem texture is present it should be compatible with other custom textures because it is using a block that is textured as a block when customized while mushrooms tend to be textured as flat objects causing splicing of textures like this.
