### ISSUE TITLE
Terrestria Rainbow Rainforest biome changed to Better Nether biome

### ISSUE THREAD

**Issue by ElKameleon** [paulevsGitch/BetterNether#222]
Not sure who's issue this is, but I had a Terrestria biome (rainbow rainforest) somehow change IDs to a Better Nether biome, this only happened after I had entered the nether for the first time and could not figure out why I was getting spawns in my overworld afterwards.

Minecraft 1.16.4 Fabric
Traverse 3.0.0
Terrestria 2.1.4
Better Nether 5.0.0

![2020-11-05_22 30 35](https://user-images.githubusercontent.com/25694405/98326966-1dd6ec00-1fb8-11eb-95dc-252cc53926bd.png)

**Comment by paulevsGitch** [comment]
This is biome id shift. It can occur if you add/remove mods in already played world, update it from old version and other some other reasons. It is not a mod issue actually and I can't control it. To fix area with shifted biome you can use [WorldEdit](https://www.curseforge.com/minecraft/mc-mods/worldedit) (as a mod) or a [WorldPainter](https://www.worldpainter.net/) (external tool) to replace incorrect biome. All new world chunks will generate as normal ones
