### ISSUE TITLE
Overworld wood furniture can't burn in Furnace

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#223]
**Expected Behaviour**
The Oak, Spruce, Birch, Jungle, Acacia and Dark Oak chairs, stools and barstools can be used as fuel in a furnace, mirroring all of the blocks made with these wood types in vanilla Minecraft.
**Actual Behaviour**
The Oak, Spruce, Birch, Jungle, Acacia and Dark Oak chairs, stools and barstools cannot be used as fuel in a furnace.

Given that the new wood types added by this mod as well as Crimson and Warped woods cannot be used as furnace fuel due to being fireproof, their furniture items shouldn't burn either, so their behaviour makes sense.~

**Comment by paulevsGitch** [comment]
Added in 5.0.1
