### ISSUE TITLE
Compatibility with Sandwichable

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#224]
Sandwichable is a lovely mod made by FoundationGames that adds many new food items and blocks to process them all centered around making custom sandwiches. One of the things Sandwichable adds are _cutting boards_ for all eight of the vanilla wood types. I would love to see this mod's wood types be able to be made into their own cutting boards to match these.~

**Comment by saltyseadoggo** [comment]
When I suggested similar cross-compatibility to the developers of Cinderscapes, they suggested that I take the case to Sandwichable's devs, FoundationGames, who, in turn, said that they have been thinking about this, but would need to work past server compatibility issues. If they add an infrastructure for compatibility with other mods, intervention on your part may not be necessary. Something to keep an eye on.~

**Comment by quiqueck** [comment]
Moving to our Enhancement List.
