### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by Eilux** [paulevsGitch/BetterNether#225]
Hello, I'm the developer of another mod and your is currently incompatible with mine for reasons unknown, in trying to add your mod to my build.gradle using jitpack for testing reasons I get the error:
 `Mixin apply failed betternether.mixins.client.json:PlayerArmorMixin -> net.minecraft.client.render.entity.PlayerEntityRenderer: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Invalid descriptor on betternether.mixins.client.json:PlayerArmorMixin->@Inject::onInit(Lnet/minecraft/client/render/entity/EntityRenderDispatcher;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V! Expected (Lnet/minecraft/client/render/entity/EntityRenderDispatcher;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (Lnet/minecraft/client/render/entity/EntityRenderDispatcher;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V [INJECT Applicator Phase -> betternether.mixins.client.json:PlayerArmorMixin -> Apply Injections ->  -> Inject -> betternether.mixins.client.json:PlayerArmorMixin->@Inject::onInit(Lnet/minecraft/client/render/entity/EntityRenderDispatcher;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V]` 
do you have any idea as to why this happens?

MC version: 1.16.4
Yarn Mappings: 1.16.4+build.6
Loader Version: 0.10.6+build.214
Fabric Version: 0.25.1+build.416-1.16
Short Commit Hash of your mod: 22903b13b3

**Comment by EnderBro123** [comment]
Hi!

I'm not the dev of this mod, but I am one of the Admins of the Discord.
If you wanna join, then lemme know and I'll hand you the invite link.

**Comment by paulevsGitch** [comment]
Looks like mixin tries to handle the wrong function, this can be bug in mixin lib, as this mixin works correctly in dev environment and in game. You can try build BN from sources and add its -dev.jar as a library, this may help

**Comment by Eilux** [comment]
yep that worked thank you for your help
