### ISSUE TITLE
[Bug] Config options reset at startup

### ISSUE THREAD

**Issue by Dimerite** [paulevsGitch/BetterNether#226]
betternether.json resets to default at game startup

Workaround: Setting the file to read only prevents the reset

Fabric 1.16.4
BetterNether 5.0.0

**Comment by paulevsGitch** [comment]
You can set "rewrite_on_version_update[def: true]": false in "config" category to prevent this

**Comment by paulevsGitch** [comment]
Fixed in 5.0.1
