### ISSUE TITLE
Compatibility with Traverse

### ISSUE THREAD

**Issue by RjayTheDoggo** [paulevsGitch/BetterNether#229]
when you use this mod the Better nether biomes dont work as they should they show up as biomes but dont spawn any block structures anything. would love to see both of them work together

**Comment by EnderBro123** [comment]
Both work together just fine.

Are yo using the latest versions of everything? (Fabric API as well.)

**Comment by RjayTheDoggo** [comment]
My bad i checked the wrong mod that made the issue i changed the title so it works now
