### ISSUE TITLE
[Tweak/Suggestion] Updated Netherrack-based textures

### ISSUE THREAD

**Issue by cybercat5555** [paulevsGitch/BetterNether#23]
As the title says, I created several textures based off the new netherrack textures, for later use and for those who are using the updated vanilla textures. Possibly they could be added as a config toggle, or could be used when this mod updates to 1.13/1.14 and higher. Here is a links to the textures:  https://drive.google.com/open?id=170GakngZt_q8Lt6Eb5Ak4YaBXlLVwhao

**Comment by paulevsGitch** [comment]
Textures and block models is not configurable thing, to change them for others a resource-pack must be used. Thank you for textures, but I will make my own, as I have their sources, when start updating to 1.13 and 1.14 (or only 1.14, I not decided yet)
