### ISSUE TITLE
Nether

### ISSUE THREAD

**Issue by Tatteredsteel** [paulevsGitch/BetterNether#230]
Hey there I have a question about the mod. So I have installed it onto a multiplayer world which most of it works. The biomes seems to have not generated. I tried resetting the nether but it is the same thing. We found a beautiful build from the mod but just no vegetation or bimoes from what I can see. I loaded the same seed into a single player world and it looks much different at the same cords.  Not sure if anyone knows what might be causing this but I'm glad to have all the help.
Thanks

**Comment by paulevsGitch** [comment]
As I know this question now has an answer, so I can close it
