### ISSUE TITLE
[Possible Bug] Unable to locate BetterNether biomes.

### ISSUE THREAD

**Issue by TheD0ct0r101** [paulevsGitch/BetterNether#232]
So after deleting DIM-1 for an existing world and loading in with BetterNether 1.16.3 Fabric, all I can find are the vanilla Nether biomes with the BetterNether ores and stalactites and such. Even after dropping the vanilla biome weight to 0.10 and betternether biome weight to 3.00, I am unable to locate the new biomes.

I will try to set the weight to 0 for the old biomes. If the problem is fixed, ill edit this post. If its not fixed, will also edit.

EDIT: Setting vanilla biome weight to 0 does not solve the issue. So this definitely seems like a problem.

**Comment by saltyseadoggo** [comment]
You said that you deleted DIM-1 to refresh the Nether in hopes of seeing BetterNether's content. I did this as well, but this doesn't update the Nether's generation settings, so you won't get a Nether generated by BetterNether. You will need to download NBTExplorer to modify your world's level.dat and change the Nether generator to BetterNether's to fix this. You need to:
- Create a new world with Better Nether installed; this will give you a world whose level.dat contains BetterNether's generation settings for the Nether.
- Open NBTExplorer, go File > Open..., and navigate the new world's save's folder, then to its level.dat.
- In NBTExplorer's window, go Data/WorldGenSettings/dimensions/minecraft:the_nether: 2 entries/generator: 4 entries/biome_source: 2 entries and click on type:betternether:nether_biome_source, then copy it.
- Go File > Open once more, this time selecting the level.dat in your old world's save folder.
- Go to the same directory you went to above, click on type:minecraft_multi_noise, delete it, and paste in the type:betternether:nether_biome_source you copied from the new world.~

**Comment by TheD0ct0r101** [comment]
> You said that you deleted DIM-1 to refresh the Nether in hopes of seeing BetterNether's content. I did this as well, but this doesn't update the Nether's generation settings, so you won't get a Nether generated by BetterNether. You will need to download NBTExplorer to modify your world's level.dat and change the Nether generator to BetterNether's to fix this. You need to:
> 
> * Create a new world with Better Nether installed; this will give you a world whose level.dat contains BetterNether's generation settings for the Nether.
> * Open NBTExplorer, go File > Open..., and navigate the new world's save's folder, then to its level.dat.
> * In NBTExplorer's window, go Data/WorldGenSettings/dimensions/minecraft:the_nether: 2 entries/generator: 4 entries/biome_source: 2 entries and click on type:betternether:nether_biome_source, then copy it.
> * Go File > Open once more, this time selecting the level.dat in your old world's save folder.
> * Go to the same directory you went to above, click on type:minecraft_multi_noise, delete it, and paste in the type:betternether:nether_biome_source you copied from the new world.~

Thank you so much! That did it!
