### ISSUE TITLE
[Suggestion] Config option for Simplified Block Models

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#233]
Many of BetterNether's blocks use a modelling style that is high in element count. This is lovely, but some players may find that this style clashes with vanilla Minecraft's minimalist block models. What I mean by this is that, for example, vanilla doors have one cube for each half of the door that the texture is applied to, whereas BetterNether's doors all use many elements to add detail. In addition to this, the extra level of detail can cause a decrease in performance on weaker hardware when one is near Nether cities or biomes such as the Nether mushroom forest which use these high detail block models frequently.

What I would like to suggest is a configuration option for simplified, vanilla-style versions of these block models. Ideally, this would mean that, with this option enabled, blocks like doors, walls and leaves would use the single-cube models their vanilla counterparts use, and other high-detail models, like the various mushrooms and Cincinnasite decor, would have simplified, vanilla style models as well.

If you like this idea, I would be honoured to help with creating these models, as I have a fair bit of practice with modelling in Blockbench. This idea isn't here to criticize your own modelling style, rather to provide the option for those who would prefer a more vanilla style or are struggling with frames in places like Nether cities, which they would otherwise have to disable outright.~

**Comment by theishiopian** [comment]
You could probably just make a resource pack, you could even link it on the main page with paul's permission.

**Comment by paulevsGitch** [comment]
It’s too problematic to make a config option for models, use resourcepack instead

**Comment by saltyseadoggo** [comment]
Would you be interested in @theishiopian's suggestion of a main page linked resource pack for this option, @paulevsGitch? I don't want to spend potentially hours on such a project if it is unwanted.
