### ISSUE TITLE
Nether reeds don't provide block updates like vanilla sugar cane

### ISSUE THREAD

**Issue by ElKameleon** [paulevsGitch/BetterNether#235]
Tried to build your basic nether reed farm with a observer and piston, but when the nether reed grows in front of the observer, there is no block update, basically making this unfarmable.

Minecraft 1.16.4
Better Nether 5.0.0

**Comment by ElKameleon** [comment]
Looks like alot of the nether flora doesn't provide a block update, tried to use stalagnate in a tree farm and couldn't get it to work properly either.

**Comment by paulevsGitch** [comment]
Fixed in 5.0.1
