### ISSUE TITLE
Cincinnasite, Nether ruby & lapis ores cannot be obtained using Silk Touch

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#237]
**Expected Behaviour**
Like other ores, Cincinnasite and Nether ruby and lapis ores would be able to be obtained using a tool enchanted with Silk Touch.
**Actual Behaviour**
Cincinnasite and Nether ruby and lapis ores cannot be gathered using Silk Touch. This was tested using a Tech Reborn sapphire pickaxe.

**Comment by saltyseadoggo** [comment]
This also applies to Nether ruby ore. I have updated the issue.~

**Comment by saltyseadoggo** [comment]
This also applies to Nether lapis lazuli ore.

**Comment by paulevsGitch** [comment]
Fixed in 5.0.1
