### ISSUE TITLE
corrupted enchantment table

### ISSUE THREAD

**Issue by MinCrin** [paulevsGitch/BetterNether#24]
![2019-05-29_14 33 40](https://user-images.githubusercontent.com/29803007/58585842-58632380-821f-11e9-8c8d-e0a008a9ec53.png)
![2019-05-29_14 37 10](https://user-images.githubusercontent.com/29803007/58585844-58632380-821f-11e9-9f1d-9f66ce1f5c6d.png)

the f3 debug menu identifies it as "air", and the menu can't open properly without immediately closing out.

**Comment by paulevsGitch** [comment]
Related to #9
