### ISSUE TITLE
Blocks and items with tags can't be disabled

### ISSUE THREAD

**Issue by Afrocntrik** [paulevsGitch/BetterNether#244]
When disabling the Warped & Crimson Ladder in the block config file, world is unable to startup

**Comment by paulevsGitch** [comment]
It is known issue. It couldn't be fixed for now. I know how to fix it actually, but this will require large code refactoring

**Comment by paulevsGitch** [comment]
This issue will be fixed in an upcoming year as a part of large refactoring

**Comment by paulevsGitch** [comment]
This should work fine now
