### ISSUE TITLE
Mushrooms float off of mooshrooms

### ISSUE THREAD

**Issue by muzikbike** [paulevsGitch/BetterNether#246]
![2020-11-17_21 49 54](https://user-images.githubusercontent.com/52297970/99454864-edc80b00-291e-11eb-95f4-6ad2242ace47.png)
![2020-11-17_21 50 02](https://user-images.githubusercontent.com/52297970/99454872-ef91ce80-291e-11eb-915d-ddf93c9cccb3.png)

**Comment by saltyseadoggo** [comment]
That would be a side effect of replacing the vanilla mushroom models.

**Comment by paulevsGitch** [comment]
Fixed in 5.0.4
