### ISSUE TITLE
Suggestion: More Nether mob heads?

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#248]
I find the More Mob Heads datapack by the Vanilla Tweaks team to be a fun addition to the game, as it allows all mobs that do not have a head block in vanilla to rarely drop a player head retextured to look like their own head. However, these heads, being the basic player head model, look strange for mobs that do not have heads shaped like this, such as Hoglins, and, more relevantly, it is not compatible with modded creatures.

What I would suggest is to create new mob head blocks for some of the Nether's creatures as rare drops, so players can have fun headhunting in the wilds of the Nether! These blocks would ideally have models matching the proper shape of the mob's head instead of being retextured vanilla player heads, to resolve the datapack's issue with this. Imagine wall-mounted Hoglin heads for Piglin-inspired builds, for example!

Of course, some mobs, like the firefly or hydrogen jellyfish, do not have proper heads due to the shapes of their bodies, so I think these mobs would make the most sense for this feature:
- Blaze
- Piglin
- Zombified Piglin
- Hoglin
- Zoglin
- Flying Pig
- Naga
- Skull
- Jungle Skeleton

**Comment by quiqueck** [comment]
Moving to our Enhancement List.
