### ISSUE TITLE
Suggestion: Firefly in a Jar

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#249]
I've one simple suggestion: right-clicking on a firefly while holding a glass bottle could give a _firefly jar_ block! Breaking this block without Silk Touch after breaking it could destroy the jar and release the firefly within.~

Here's a visual mock-up, created using the pickle jar added by Sandwichable:
![2020-11-18_22 08 04](https://user-images.githubusercontent.com/69029346/99628384-e40bd980-29ea-11eb-941d-b1ce574b2649.png)

**Comment by quiqueck** [comment]
Moving to our Enhancement List.
