### ISSUE TITLE
Better Nether slabs do not block light

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#250]
**Expected Behaviour**
Vanilla bottom slabs block light from below, top slabs from above, and double slabs from all sides; see below. *BetterNether* slabs would behave the same way.
![2020-11-21_14 57 06](https://user-images.githubusercontent.com/69029346/99889494-bf8e4800-2c0a-11eb-9f82-b9b519cbfdab.png)
**Actual Behaviour**
*BetterNether* slabs do not block light at all. This was tested with almost all slab varieties added by the mod and with bottom and double slabs.
![2020-11-21_14 57 14](https://user-images.githubusercontent.com/69029346/99889517-e51b5180-2c0a-11eb-80c4-a7c0ed2b87e0.png)

**Comment by paulevsGitch** [comment]
Fixed in 5.0.4
