### ISSUE TITLE
[Bug] Regular fire generates on soul sand/soil in the Soul Plain

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#254]
As per the title, regular fire generates on top of soul sand and soil in the *Soul Plain* biome. When this fire recieves any block update, it turns into soul fire, as it is supposed to be. Perhaps there is something the vanilla Soul Sand Valley is doing to generate soul fire properly that you have missed?

![2020-11-29_22 43 22](https://user-images.githubusercontent.com/69029346/100577203-8d2cbc80-3294-11eb-9025-322ab537cf14.png)
Removing an adjacent soul grass tuft gives the fire a block update and turns it into soul fire.
![2020-11-29_22 43 24](https://user-images.githubusercontent.com/69029346/100577205-8e5de980-3294-11eb-8807-8a34562ac6d8.png)

**Comment by paulevsGitch** [comment]
This issue will be fixed when I start large mod refactoring (probably in a new year)

**Comment by paulevsGitch** [comment]
This will not be a problem in new version (1.17+) as it will use modern MC function instead of legacy ones to generate biomes
