### ISSUE TITLE
Flying mobs stuttering

### ISSUE THREAD

**Issue by BoshaNova** [paulevsGitch/BetterNether#257]
Flying mobs added from mod, except the hydrogen jellyfish which hardly moves at all, stutter as they move. Most notable with the fireflies and flying pigs.

**Comment by EnderBro123** [comment]
If you were on the Discord, then you'd know that this is a already known issue.

Revert to version 5.0.0.

**Comment by paulevsGitch** [comment]
Thank you, this issue is actually my fault in optimization. It is already fixed in dev code

**Comment by paulevsGitch** [comment]
Fixed in 5.0.4
