### ISSUE TITLE
[Suggestion] Toggle for Density of Plants

### ISSUE THREAD

**Issue by cybercat5555** [paulevsGitch/BetterNether#26]
It would be nice if we had a toggle for density of the netherwarts, mushrooms, reeds, etc, including a way to fully disable them from natural spawns, such as if we only want the netherwarts to spawn in fortresses instead of in "the wild", but still have a way to grow the plants themselves, such as if found as loot or in structures or something (for modpacks), but not fully disable the feature.

**Comment by paulevsGitch** [comment]
There are per-biome plant density and total plant density. Plant generation can be disabled if you disable plant in config (as block). Nether wart generation will be controllable in future updates.

**Comment by cybercat5555** [comment]
Sorry if this wasn't clear before, but what if I don't want say, Reeds to generate naturally, but I do want them to appear as part of structures, such as in the garden structure?

**Comment by paulevsGitch** [comment]
Actually there are structures with reeds (small farm). There will be more later.
