### ISSUE TITLE
Skulls have very low attack cooldown

### ISSUE THREAD

**Issue by P03W** [paulevsGitch/BetterNether#262]
Currently, if a skull is colliding with a player, they attack constantly (6 2/3 times a second)
this leads to several issues such as

- Attempting to shield them rapidly deteriorates the shield
- Attempting to tank them rapidly deteriorates armor
- They deal significantly more damage than intended, often times doing upwards of 4 damage instead of the intended 1

**Comment by paulevsGitch** [comment]
Fixed in 5.0.5
