### ISSUE TITLE
[Bug] Doors have no hardness? Breaks instantly

### ISSUE THREAD

**Issue by wmboeckman** [paulevsGitch/BetterNether#263]
**Version**: 5.0.4 Fabric

All Doors seems to not have any hardness value, as they break with a single click rather than take time to break.

For more context, Im trying to make a modpack. This means it could be another mod causing this, but Doors for Better End seem to work just fine. 

Here is my modlist: [mods.txt](https://github.com/paulevsGitch/BetterNether/files/5692361/mods.txt)

Here is a full log, in case you need it: [log.txt](https://github.com/paulevsGitch/BetterNether/files/5692370/log.txt)

**Comment by paulevsGitch** [comment]
Fixed in 5.0.5
