### ISSUE TITLE
Cant Find New Biomes

### ISSUE THREAD

**Issue by ImKilbey** [paulevsGitch/BetterNether#265]
Hello, i cant seem to find the new biombs but i can find little structures and the ores and the content is there but no matter how far i go i cant find them. Please Help

**Comment by paulevsGitch** [comment]
Probably your world is missing BetterNether biome source. [Here](https://www.curseforge.com/minecraft/mc-mods/betternether?comment=1116) is the solution. I will put this into FAQ later
