### ISSUE TITLE
[Suggestion] Composters for Crimson, Warped and BN wood types

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#266]
You recently added composters of every wood type in Better End to that mod, and I thought that it would be lovely to see Better Nether do this with its wood types as well. Since Better Nether also adds barrel types for crimson and warped planks, I thought it could add crimson and warped composters as well.~

**Comment by paulevsGitch** [comment]
I will add them in a new year (I have plans for large enhancements and refactoring for BetterNether)

**Comment by quiqueck** [comment]
Moving to our Enhancement List.
