### ISSUE TITLE
5.0.4 crashed on MC 1.16.4 with or without Hydrogen (by JellySquid3)

### ISSUE THREAD

**Issue by heyjudek** [paulevsGitch/BetterNether#267]
Since I saw the topic on a potential conflict with Hydrogen, I decided to remove it to see if it works. But it is the same. The screen turns black but instead of the game starting to load, it just crashes to desktop. 

---- Minecraft Crash Report ----
// But it works on my machine.

Time: 2020-12-22 05:43:36 CET
Description: Initializing game

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $.variants.
    at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.7)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
    at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
    at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
    at com.google.gson.Gson.fromJson(Gson.java:887)
    at com.google.gson.Gson.fromJson(Gson.java:952)
    at com.google.gson.Gson.fromJson(Gson.java:925)
    at dev.bodner.jack.betterslabs.client.BetterslabsClient.lambda$createPack$0(BetterslabsClient.java:48)
    at com.swordglowsblue.artifice.impl.ArtificeResourcePackImpl.<init>(ArtificeResourcePackImpl.java:80)
    at com.swordglowsblue.artifice.api.ArtificeResourcePack.ofAssets(ArtificeResourcePack.java:128)
    at com.swordglowsblue.artifice.api.Artifice.registerAssets(Artifice.java:50)
    at com.swordglowsblue.artifice.api.Artifice.registerAssets(Artifice.java:29)
    at dev.bodner.jack.betterslabs.client.BetterslabsClient.createPack(BetterslabsClient.java:32)
    at net.minecraft.client.MinecraftClient.handler$bbc000$MinecraftClient(MinecraftClient:7866)
    at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:592)
    at net.minecraft.client.main.Main.main(Main:177)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $.variants.
    at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:162)
    at com.google.gson.internal.bind.JsonTreeReader.beginObject(JsonTreeReader.java:87)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
    ... 24 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Initialization --

-- System Details --
  Minecraft Version: 1.16.4
  Minecraft Version ID: 1.16.4
  Operating System: Windows 7 (amd64) version 6.1
  Java Version: 1.8.0_271, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 6314080576 bytes (6021 MB) / 7516192768 bytes (7168 MB) up to 7516192768 bytes (7168 MB)
  CPUs: 8
  JVM Flags: 11 total; -Xmn128M -Xmx7000M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xmx7G
  Suspected Mods: Betterslabs (betterslabs), Artifice (artifice), Fabric Loader (fabricloader)
  Fabric Mods: adorn: Adorn 1.12.2+1.16.4
               advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
               afarmk: AFarmK 0.4
               amecsapi: Amecs API 1.1.1+mc1.16-rc1
               appleskin: AppleSkin 1.0.11
               architectury: Architectury 1.1.55
               artifice: Artifice 0.13.2+1.16.3
               astromine: Astromine 1.11.4+fabric-1.16.3
               astromine-core: Astromine: Core 1.11.4+fabric-1.16.3
               astromine-discoveries: Astromine: Discoveries 1.11.4+fabric-1.16.3
               astromine-foundations: Astromine: Foundations 1.11.4+fabric-1.16.3
               astromine-technologies: Astromine: Technologies 1.11.4+fabric-1.16.3
               astromine-transportations: Astromine: Transportations 1.11.4+fabric-1.16.3
               autoconfig1u: Auto Config v1 Updated 3.3.1
               bedspreads: Bedspreads 1.3.0-1.16.4
               bettercaves: YUNG's Better Caves 1.16.2-1.0.3
               betternether: Better Nether 5.0.4
               betterslabs: Betterslabs 1.1.1
               blade: Blade 2.0.0
               cactusleather: Cactus Leather 1.0.1
               campanion: Campanion 1.2.0+build.39
               cardinal-components: Cardinal Components API 2.6.0
               cardinal-components-base: Cardinal Components API (base) 2.6.0
               cardinal-components-block: Cardinal Components API (blocks) 2.6.0
               cardinal-components-chunk: Cardinal Components API (chunks) 2.6.0
               cardinal-components-entity: Cardinal Components API (entities) 2.6.0
               cardinal-components-item: Cardinal Components API (items) 2.6.0
               cardinal-components-level: Cardinal Components API (world saves) 2.6.0
               cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.6.0
               cardinal-components-util: Cardinal Components API (utilities) 2.6.0
               cardinal-components-world: Cardinal Components API (worlds) 2.6.0
               carpet: Carpet Mod in Fabric 1.4.12
               carpet-extra: Carpet Extra 1.4.8
               carpet-tis-addition: Carpet TIS Addition 1.6.1
               cavebiomes: Cave Biomes 0.5.1
               ce_foodstuffs: Common Expansion: Foodstuffs 1.1.1
               charcoalblock: Charcoal Block 1.0.1
               cherry: Cherry 1.3.1
               chickenfeathers: Chicken Feathers 1.2.1
               cleancut: CleanCut mc1.16-2.1-fabric
               cloth-armor-api-v1: Cloth Armor API v1 1.4.8
               cloth-basic-math: Cloth Basic Math 0.5.1
               cloth-client-events-v0: Cloth Client Events v0 1.4.9
               cloth-common-events-v1: Cloth Common Events v1 1.4.8
               cloth-config2: Cloth Config v4 4.8.3
               cloth-datagen-api-v1: Cloth Datagen v1 1.4.8
               cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.8
               cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.8
               coloredcraftingstations: ColoredCraftingStations 1.0.0
               cotton: Cotton 1.1.0
               cotton-cauldron: Cotton Cauldron 1.1.0
               cotton-commons: Cotton Commons 1.0.4
               cotton-config: Cotton Config 1.0.0-rc.7
               cotton-datapack: Cotton Datapack 1.0.7
               cotton-logging: Cotton Logging 1.0.0-rc.4
               cotton-player-events: Cotton Player Events 1.0.2
               craftable: Craftable+ 3.0
               craftycuisine: Crafty Cuisine b1.1
               croptopia: Croptopia 1.0.6-1.16.4-FABRIC
               dawn: Dawn API 1.5.3
               demeter: Demeter 2.0.0
               dynamicfps: Dynamic FPS 1.2.1
               dynamicsoundfilters: Dynamic Sound Filters 1.1.3+1.16.2
               dynamo_api: Dynamo API 1.0.0+1.16.4
               engilib: EngiLib 1.0.0+1.16.4
               fabric: Fabric API 0.28.3+1.16
               fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
               fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
               fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
               fabric-commands-v0: Fabric Commands (v0) 0.2.0+6a2618f53a
               fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
               fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
               fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
               fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+6a2618f53a
               fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
               fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
               fabric-language-scala: Fabric Language Scala 0.3.2.12
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
               fabric-models-v0: Fabric Models (v0) 0.1.1+6a2618f53a
               fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
               fabric-networking-v0: Fabric Networking (v0) 0.3.1+2a4333d33a
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
               fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.3+be155ae23a
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+6a2618f53a
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db23a
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
               fabric-rendering-v1: Fabric Rendering (v1) 1.4.0+6a2618f53a
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.2+1944f3e03a
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
               fabric-structure-api-v1: Fabric Structure API (v1) 1.1.1+f1d8af063a
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
               fabric-textures-v0: Fabric Textures (v0) 1.0.5+a4467d2a3a
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
               fabrication: Fabrication 1.2.3_02
               fabricloader: Fabric Loader 0.10.8
               falling_tree: FallingTree 2.8.1
               fermion: Fermion 2.1.191
               fermion-modkeys: Fermion Modifier Keys 1.8.180-snapshot
               fiber: fiber 0.23.0-2
               fiber2cloth: Fiber To Cloth 3.0.1
               fluidphysics: Fluid Physics 1.3.8+fabric-1.16.4
               foodtweaks: Food Tweaks 2.0-1.16.3
               foundation: Foundation 1.0.0
               functionapi: Function API 3.7.0-1.16.3
               functionapi_common: Function API COMMON 1.0.0-SNAPSHOT
               functionapi_common_scripting: Function API COMMON Scripting 1.0.0-SNAPSHOT
               glassdoors: Glass Doors 0.0.2
               glassential: Glassential 1.16.1-1.1.4
               harvest: Harvest 1.2.12
               horizontal-glass-panes: Horizontal Glass Panes 1.0.0
               indrev: Industrial Revolution 1.7.15-BETA
               industrialexpansion: Industrial Expansion 1.0.0
               item-pickup-customization: Item Pickup Customization 1.1.1-1.16.1
               jankson: Jankson 3.0.1+j1.2.0
               kirin: Kirin UI 1.7-1.16.2
               kubejs: KubeJS 1.5.5
               libblockattributes: LibBlockAttributes 0.8.4
               libblockattributes_core: LibBlockAttributes (Core) 0.8.4
               libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.4
               libblockattributes_items: LibBlockAttributes (Items) 0.8.4
               libcd: LibCapableData 3.0.3+1.16.3
               libgui: LibGui 3.2.2+1.16.3
               libstructure: LibStructure 1.5
               lightoverlay: Light Overlay 5.5.4
               lithium: Lithium 0.6.0
               lithium-api: Lithium API 0.6.0
               loadcatcher: Entrypoint Catcher 2.0.0
               lookingglass: Through the Looking Glass Release - 1.1.0
               magna: Magna 1.4.3-1.16.2
               malilib: MaLiLib 0.10.0-dev.21+arne.2
               mambience: MAmbience 2.1.0+1.16.2
               maybe-data: Maybe data 1.0.0-1.16.2
               mealapi: Meal API 0.1+1.16.2
               mechanicaltech: Mechanical Tech 0.2.0+1.16.4
               mesh: Mesh 0.5.5-alpha.17+1.16.4
               mesh_api: Mesh API 0.5.5-alpha.17+1.16.4
               minecraft: Minecraft 1.16.4
               ml3api: ML3API 1.3.3
               mm: Manningham Mills 2.1
               mo_glass: Mo Glass 1.5-MC1.16.4
               modern_industrialization: Modern Industrialization 0.3.9
               modmenu: Mod Menu 1.14.6+build.31
               moreberries: More Berries 1.3.3
               nbtcrafting: NBT Crafting 2.0.1+mc1.16.4
               notenoughcrashes: Not Enough Crashes 2.1.4+1.16.4
               org_codehaus_groovy_groovy: groovy 3.0.3
               org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
               org_jetbrains_annotations: annotations 20.0.0
               org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
               org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
               org_joml_joml: joml 1.9.25
               patchouli: Patchouli 1.16.2-44-FABRIC
               phosphor: Phosphor 0.7.0+build.10
               piglib: Piglib 1.0.1
               plantable_pots: Plantable Flower Pots 0.0.2-SNAPSHOT
               plantinajar: Plant In A Jar 1.8.1
               polymorph: Polymorph 0.0.5-1.16.3
               presencefootsteps: Presence Footsteps r28+1.16.2
               pugh_lib: Pugh Lib 1.0.2
               pushtocraft: Push To Craft 1.0.4+mc1.16.1
               rainbucket: Rain Bucket 1.0.0
               reach-entity-attributes: Reach Entity Attribute 1.0.1
               reborncore: Reborn Core 4.5.0+build.84
               resourceful_tools: Resourceful Tools 1.0.39
               rocks_rdil_simpleconfig: simpleconfig 2.0.0
               roughlyenoughitems: Roughly Enough Items 5.8.3
               roughlyenoughitems-api: REI (API) 5.8.3
               roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.3
               roughlyenoughitems-runtime: REI (Runtime) 5.8.3
               sand_dust: Sand Dust 1.2.0
               shapes: Shapes 2.0.0+build.10
               sheepconsistency: Sheep Consistency 1.0.2
               shelf: Shelf 1.0.0
               slight-gui-modifications: 'Slight' GUI Modifications 1.6.1
               sodium: Sodium 0.1.0
               statement: Statement 4.0.0+1.16.2
               team_reborn_energy: Energy 0.1.1
               techreborn: Tech Reborn 3.6.1+build.143
               terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.0+build.1
               terraform-config-api-v1: Terraform Config API (v1) 1.0.0+build.1
               terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.0+build.1
               terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.0+build.1
               terraform-tree-api-v1: Terraform Tree API (v1) 1.0.1+build.2
               terraform-wood-api-v1: Terraform Wood API (v1) 1.0.0+build.1
               tillitbreaks: Till it Breaks 0.1
               toomanybinds: Too Many Binds 0.3.0+1.16.3
               traverse: Traverse 3.1.0+build.15
               uncraftable: Uncraftables 1.3.4-1.16.1
               underwatergrass: UnderwaterGrass 1.1.1
               unknownrecipes: UnknownRecipeSilencer 1.0.0
               usefulutilities: Useful Utilities 1.4.0
               veggie_way: The Veggie Way 1.0.35
               waterphysics: Dihydrogen Monoxide Reloaded 2.1.0+1.16.2
               wrenchable: Wrenchable 1.0.0+1.16.1
               xaerominimap: Xaero's Minimap 20.29.1
               xaeroworldmap: Xaero's World Map 1.11.4
               yosbr: YOSBR 0.1.1
  Patchouli open book context: n/a
  Launched Version: fabric-loader-0.10.8-1.16.4
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: GeForce GTX 680M/PCIe/SSE2 GL version 4.5.0 NVIDIA 373.06, NVIDIA Corporation
  GL Caps: Using framebuffer using OpenGL 3.0
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  CPU: 8x Intel(R) Core(TM) i7-4900MQ CPU @ 2.80GHz

**Comment by paulevsGitch** [comment]
Looks like this is Better Slabs issue:
- at dev.bodner.jack.betterslabs.client.BetterslabsClient.lambda$createPack$0(BetterslabsClient.java:48)
- at dev.bodner.jack.betterslabs.client.BetterslabsClient.createPack(BetterslabsClient.java:32)

**Comment by paulevsGitch** [comment]
Betterslabs 1.1.1 is outdated, newer version (1.1.3) works correctly
