### ISSUE TITLE
Server crash when players enter the nether for the first time,

### ISSUE THREAD

**Issue by Mizhok** [paulevsGitch/BetterNether#27]
https://pastebin.com/u6gwVqgs

There's actually two issues that occur when players enter the Nether for the first time.
1) The server crashes if the Nether isn't generated when the player tries to get in there. 
2) No nether portal is generated in the nether.

**Comment by paulevsGitch** [comment]
This is same problem as [here](https://www.reddit.com/r/Minecraft/comments/320b14/server_crashing_can_you_help/)

**Comment by Mizhok** [comment]
Thank you!
