### ISSUE TITLE
fire_small texture is limiting mip level

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#272]
*Texture betternether:block/fire_small with size 8x8 limits mip level from 4 to 3
minecraft:textures/atlas/blocks.png: dropping miplevel from 4 to 3, because of minimum power of two: 8*
This warning appears in the log during startup with only Better Nether and the Fabric API installed. This was tested using the latest version of the Fabric API at the time I am reporting this (0.29.3) and Fabric 0.10.8.

I do not know what this warning affects, but I thought I would report it for your information.~

**Comment by paulevsGitch** [comment]
I rescaled this texture in one of the update, I will change scale back

**Comment by paulevsGitch** [comment]
Fixed in 5.0.5
