### ISSUE TITLE
Method overwrite conflict with Better End and Roughly Enough Items

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#273]
*Method overwrite conflict for method_8132 in betterend.mixins.common.json:RecipeManagerMixin, previously written by paulevs.betternether.mixin.common.RecipeManagerMixin. Skipping method.*

This warning appears in the game log during startup when this mod, Better End and Roughly Enough Items are installed concurrently. This was tested with just these three mods installed, using the latest version of the Fabric API at the time I am reporting this (0.29.3) and Fabric 0.10.8.

I do not know what this warning affects, but I thought I would report it for your information.~

**Comment by paulevsGitch** [comment]
This message means that both mods use same name for mixin function, I will fix this adding suffix to function

**Comment by paulevsGitch** [comment]
Fixed in 5.0.5
