### ISSUE TITLE
[Compatibility] Nether Brewing Stand should accept Biome Makeover Soul Embers as fuel

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#274]
*Biome Makeover* (https://github.com/Lemonszz/Biome-Makeover) adds the new *Soul Embers* item as an alternative fuel for brewing stands. *Better Nether's* Nether Brewing Stand does not accept them as fuel. I would like to see this be made possible.~

**Comment by paulevsGitch** [comment]
Added in 5.0.5
