### ISSUE TITLE
Nether Portal won't take me anywhere

### ISSUE THREAD

**Issue by Boe-Bio** [paulevsGitch/BetterNether#275]
So I just built my nether portal today, excited to see the new nether. But after standing in the portal for about 15 seconds, I realized something was wrong. Help?

**Comment by paulevsGitch** [comment]
Probably your Nether dimension entry is missing, [this tutorial](https://github.com/paulevsGitch/BetterEnd/wiki/Tutorials#how-to-fix-missing-end-dimension) can probably help you (it is about the End, but for the Nether it will be similar)

Example of the Nether dimension entry with correct biome source:

![image](https://user-images.githubusercontent.com/17707380/104333977-de220880-5502-11eb-9a2b-a72482d71020.png)

**Comment by Boe-Bio** [comment]
alright. So I changed the file to the better nether one, but it still won't take me anywhere.

**Comment by paulevsGitch** [comment]
What messages are in the client logs?

**Comment by Boe-Bio** [comment]
Nevermind, I got it working! Thanks for the tip! Also, I love the mod! Although.... the skulls are very annoying.

**Comment by paulevsGitch** [comment]
Yes, you can disable their spawn in the config. The mod will be refactored when 1.17 will come out and I will update their behaviour

**Comment by paulevsGitch** [comment]
As the problem was solved I will close this issue
