### ISSUE TITLE
Pressure plates have collision

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#276]
**Expected Behaviour**
When standing on a Better Nether pressure plate, the player would pass through it, as they do vanilla pressure plates.
**Actual Behaviour**
When standing on a Better Nether pressure plate, the player collides with it. This can be observed in the F3 menu by watching your y value as you walk over one: when walking over a vanilla pressure plate, it doesn't change, but, when walking over one of yours, it does.
In addition to being behaviourally inconsistent with vanilla, this issue is exacerbated with the mod [Plated](https://github.com/ChloeDawn/Plated), which allows pressure plates to be placed sideways. Notably, players can stand on Better Nether pressure plates when they are sideways with this mod installed.

**Comment by paulevsGitch** [comment]
This will be also in the BetterEnd, I'll fix it

**Comment by paulevsGitch** [comment]
Fixed in 5.0.5
