### ISSUE TITLE
Crash when breaking signs from BetterNether

### ISSUE THREAD

**Issue by andresmarver1** [paulevsGitch/BetterNether#277]
Only happens with BetterNether signs, can be placed and written, but not broken afterwards. Must use WorldEdit to remove them, as removing their supporting block leaves the sign floating.

[crash-2021-01-13_21.09.13-client.txt](https://github.com/paulevsGitch/BetterNether/files/5814650/crash-2021-01-13_21.09.13-client.txt)

**Comment by paulevsGitch** [comment]
Looks like this is a bug in gunpowder mod (?) mixin (class cast exception), probably you should report it to its authors (or if I can fix it from my side let me know). I will fix floating signes in the next version

**Comment by paulevsGitch** [comment]
Fixed in 5.0.5
