### ISSUE TITLE
[Compatibility] BN leaves do not work with CullLeaves

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#279]
When BetterNether is loaded alongside [CullLeaves](https://github.com/TeamMidnightDust/CullLeaves), BetterNether's new leaf types- Willow, Rubeus and Nether Sakura- do not work with CullLeaves' leaf block face culling. Given that they use their own, non-cube models, this makes sense for Anchor Tree leaves.

**Comment by paulevsGitch** [comment]
I think this is because my leaves are not instances of leaves block and have custom models, I don't know will it be possible to fix, I will look at this

**Comment by quiqueck** [comment]
Available in v5.3.5
