### ISSUE TITLE
[Suggestion] Cincinnasite Oregen Settings

### ISSUE THREAD

**Issue by legendblade** [paulevsGitch/BetterNether#28]
I'm in the process of trying to move all oregen in the modpack I'm working on to being handled by a single mod (GregTech Community Edition in this case) - and was trying to configure Cincinnasite to be the same only to realize that there's no config setting to disable the generation of the ore, just whether it exists or not.

Would it be possible to add an option to leave the ore in, but not place it in the world?

Thanks.

**Comment by paulevsGitch** [comment]
Yes, it is possible, maybe I will add this in next release
