### ISSUE TITLE
Basalt delta formations generate atop Nether cities

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#280]
If a Nether city generates in a basalt deltas biome, the basalt formations generate on top of and inside of some of the buildings.

A city found at 400, ~, 96 in a world generated with seed -7627560695279274830, and Cinderscapes loaded.
![2021-01-14_13 19 03](https://user-images.githubusercontent.com/69029346/104651214-30cb0400-566c-11eb-8771-96004dc537ef.png)
Inside of one of the buildings.
![2021-01-14_13 26 20](https://user-images.githubusercontent.com/69029346/104651219-332d5e00-566c-11eb-9f1e-72ac19b79359.png)
![2021-01-14_13 26 30](https://user-images.githubusercontent.com/69029346/104651220-33c5f480-566c-11eb-9716-0560c6923564.png)

**Comment by paulevsGitch** [comment]
This is known issue, I actually don’t know how to stop them and do it in compatible way. Actually the nether cities supposed to be abandoned, so probably this looks more natural

**Comment by paulevsGitch** [comment]
I think I will close this, in a new version (1.17+) Nether Cities will be remade
