### ISSUE TITLE
[Compatibility] Crashes with Hydrogen by JellySquid

### ISSUE THREAD

**Issue by Kizuati** [paulevsGitch/BetterNether#281]
Crashes with the following log. Really can't be bothered to debug dozens of mods,but considering it crashed on me before without major biome mods,it seems like a big issue tbh
[log.txt](https://github.com/paulevsGitch/BetterNether/files/5827373/log.txt)

**Comment by paulevsGitch** [comment]
You can try to disable hydrogen mod

**Comment by Kizuati** [comment]
Can confirm with [Hydrogen](https://github.com/jellysquid3/hydrogen-fabric) removed,the game does not crash. What does BN do to conflict with it anyway? A patch would be nice,especially for low RAM users.

**Comment by Kizuati** [comment]
[latest.log](https://github.com/paulevsGitch/BetterNether/files/5832316/latest.log)
Confirmed with latest _stable_  [Hydrogen release](https://github.com/jellysquid3/hydrogen-fabric/releases/tag/mc1.16.5-v0.2.0) crash log above.

**Comment by paulevsGitch** [comment]
The same issues: #270 #267 #264 #260
I don't know how Hydrogen works, but looks like it removes block data from memory. As a result this ends up with crashes. I think it not possible to fix right now

**Comment by paulevsGitch** [comment]
This is probably fixed in 5.0.6

**Comment by paulevsGitch** [comment]
If this issue will appear again please reopen it
