### ISSUE TITLE
Latest Release locked to 1.16.4

### ISSUE THREAD

**Issue by AzureDoom** [paulevsGitch/BetterNether#283]
Had installed Better Nether to test my mods in dev and noticed that it is locked to 1.16.4, where my dev is currently on 1.16.5. 
https://github.com/paulevsGitch/BetterNether/blob/master/src/main/resources/fabric.mod.json#L44 is the issue. I'd suggest something like `>=1.16.4` to allow 1.16.5 connect as well.

**Comment by paulevsGitch** [comment]
Fixed in 5.0.5
