### ISSUE TITLE
A wierd sky bug.

### ISSUE THREAD

**Issue by Stevekk11** [paulevsGitch/BetterNether#286]
![2021-01-20_21 24 12](https://user-images.githubusercontent.com/77753228/105230945-64bf9100-5b66-11eb-8f64-fd50d416e10d.png)
Does anyone has this issue?

**Comment by paulevsGitch** [comment]
This happens only on “fabulous” graphic settings, you can change it to “fancy” and rendering will be fine

**Comment by Stevekk11** [comment]
Thanks

**Comment by BL3U7073** [comment]
im getting a weird bug, idk what might be the cause of it. 
![2024-03-22_03 48 30](https://github.com/paulevsGitch/BetterNether/assets/135488897/fab64ddd-81da-4e5a-a416-bc4c2a670358)

**Comment by paulevsGitch** [comment]
Why did you report this into an issue which is 3+ years old?

**Comment by BL3U7073** [comment]
It was by accident, after this one i made a new post
