### ISSUE TITLE
[Enhancement] Block Minecraft message with experimental settings worlds

### ISSUE THREAD

**Issue by NebelNidas** [paulevsGitch/BetterNether#287]
When installing Better Nether 5.0.5 and creating a new world, this message is being displayed:
![image](https://user-images.githubusercontent.com/48808497/105365117-31304580-5bfe-11eb-84b1-5fa2e24ab661.png)

I've looked around the documentation a bit but couldn't find an explanation for this. Isn't the mod considered stable since at least around a year?

**Comment by NebelNidas** [comment]
Ah, I just found out that Minecraft now displays this message by default since 1.16.2 for all worlds created by mods using the new worldgen settings. The last version I played was 1.16.1, so I didn't encounter it before and thought the screen was implemented by BetterNether. 😅

For all users who also find this annoying, check out this mod: https://www.curseforge.com/minecraft/mc-mods/fabric-disable-custom-worlds-advice (perhaps it could be embedded into BetterNether by default, @paulevsGitch?)

**Comment by paulevsGitch** [comment]
Thank you, I will look at this, probably I can use similar method to disable message if BN or BE is installed and their world generator is the main generator

**Comment by quiqueck** [comment]
This was added as a configurable to BCLib 1.x (not for new worlds as the warning is apropriate when you first create a world), but when you load an existing world)
