### ISSUE TITLE
[Question] Removing Nether mobs via .json not working? (1.16.4)

### ISSUE THREAD

**Issue by TheBigSKIBBZ** [paulevsGitch/BetterNether#290]
Hey, so I'm not sure if it's even a real issue or the fact that I have zero coding knowledge or magically put a space somewhere where it shouldn't. Either way I would like to bring up that I tried changing the **_"true"_** value for the **_"skull"_** mobs (the flying skull ones) to false in the **_mobs.json_** file using Notepad++. Changing those values either crashes my launcher or re-adds a new line of code to the **_mobs.json_** file under **"chair[def: true]": true,**. 

That's the only mob that's annoying me from the Better Nether experience, other than that, hands down the best Nether generation mod out there.

![Qu7jycuboV](https://user-images.githubusercontent.com/77867078/105565876-9c594500-5cee-11eb-8460-56e3d66d2e0c.png)

**Note:** I am running several other mods but the launcher only crashes when I try and edit the values from **_true_** to **_false_** in the image above. This is the crash log below.

[crash-2021-01-22_20.16.42-client.txt](https://github.com/paulevsGitch/BetterNether/files/5859500/crash-2021-01-22_20.16.42-client.txt)

**Comment by paulevsGitch** [comment]
I cannot confirm this

**Comment by paulevsGitch** [comment]
Probably you edit the config when the game was launched or something interrupt configs

**Comment by paulevsGitch** [comment]
You can try the latest version as it works correctly in my tests

**Comment by TheBigSKIBBZ** [comment]
> 
> 
> You can try the latest version as it works correctly in my tests

Silly question, but does the 1.16.5 version work with 1.16.4? I've got several mods still not updated to 1.16.5 so I haven't updated it yet.
![NVIDIA_Share_DL01eFO6Fp](https://user-images.githubusercontent.com/77867078/105788352-f3a52280-5f45-11eb-8ed8-be61b38ff9ad.png)

**Comment by LuisRandomness** [comment]
1.16.5 just has a few crucial bug fixes, meaning any mod from 1.16.2 and up will work fine in 1.16.5 as long they don't have set it to only work under a version that isn't 1.16.5.
