### ISSUE TITLE
new biomes not spawning

### ISSUE THREAD

**Issue by LeHoly-Otter** [paulevsGitch/BetterNether#293]
We play on a 1.16.4 smp, recently we added the BetterNether mod and started exploring to try and find new biomes. Ores, structures and new volumetric generation worked fine however we couldn't find any of the biomes, after resorting to using /biomelocate to try and find any of the biomes the message that came up was "no biomes located in a reasonable distance". Does anyone have any suggestions or fixes for making the new biomes generate?

Also we can't alter nbt data to change the nether source, owing to the fact that it's a server ran by a separate company, we literally can't access the nbt data to fix it in that way

**Comment by paulevsGitch** [comment]
You need ti fix your biome source
https://github.com/paulevsGitch/BetterEnd/wiki/Tutorials#how-to-fix-wrong-biome-source
(This one is for the End, but for the Nether it will be the same, except biome source will be "betternether:nether_biome_source" and entry will be "minecraft:the_nether" instead of "minecraft:the_end")

**Comment by LeHoly-Otter** [comment]
> You need ti fix your biome source
> https://github.com/paulevsGitch/BetterEnd/wiki/Tutorials#how-to-fix-wrong-biome-source
> (This one is for the End, but for the Nether it will be the same, except biome source will be "betternether:nether_biome_source" and entry will be "minecraft:the_nether" instead of "minecraft:the_end"

We tried doing this, in doing so we can no longer enter the nether, literally whenever you try and enter a portal it just does the purple portal swirl continuously... any suggestions of how to fix?

**Comment by paulevsGitch** [comment]
Probably you done something wrong and you don't have entry for the Nether, you can fix it in this way (this one for the End, but for the Nether it will be the same):
https://github.com/paulevsGitch/BetterEnd/wiki/Tutorials#how-to-fix-missing-end-dimension
