### ISSUE TITLE
[Enhancement] Custom loot tables for chests in dungeons

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#295]
Opening the crimson wood chests inside of the basalt temple structures gives the vanilla War Pigs advancement to the player, which is inappropriate due to these structures not being affiliated with the Piglins. I would guess that they use one of the bastion remnant loot tables, which the War Pigs advancement .json, `loot_bastion.json`, checks for when the player opens a container.

For compatibility with mods such as Age of Exile or Tech Reborn that add their own items to the bastion remnant loot tables, is there perhaps a way to make these chests use a clone of these tables generated after other mods inject their items into them that doesn't trigger the advancement?

**Comment by paulevsGitch** [comment]
It is possible to make custom loot tables, I will do it as a part of refactoring

**Comment by quiqueck** [comment]
Moving to our Enhancement List.
