### ISSUE TITLE
Broken air blocks appearing in Nether Jungle

### ISSUE THREAD

**Issue by Igruola** [paulevsGitch/BetterNether#299]
![image](https://user-images.githubusercontent.com/62115650/108067597-071c4880-702f-11eb-97aa-22a8f305c9ae.png)
What it says on the tin. I was going through the Nether Jungle to see what blocks I didn't want because it looked a bit cluttered before, and I saw these spreading.

**Comment by Igruola** [comment]
I might add that this only happened in the Jungle - Never noticed it in any other biome.

**Comment by paulevsGitch** [comment]
This is a block with missing model, you can see what block it is on debug screen when looking at it (F3)

**Comment by Igruola** [comment]
> This is a block with missing model, you can see what block it is on debug screen when looking at it (F3)

Got it. Also, could this be closed? Figured out what it was.

**Comment by paulevsGitch** [comment]
Sure, thank you
