### ISSUE TITLE
Compatibility with NetherEx

### ISSUE THREAD

**Issue by WenXin20** [paulevsGitch/BetterNether#3]
It would be nice if plants could generate and be planted on blocks added by the NetherEx mod, such as its Hyphae (Nether Mycelium) and other custom Nether blocks, like the icy netherrack, if possible.

On a side note, I noticed that most blocks drop items when broken in creative.

**Comment by paulevsGitch** [comment]
Plants can be planted on NetherEx ground as noticed on Minecraftforum branch. If by a drop you mean seeds - it was designed so.
