### ISSUE TITLE
[Suggestion] Compatibility with BOP and possibly Nether Ex

### ISSUE THREAD

**Issue by Feranogame** [paulevsGitch/BetterNether#30]
Hello, I would like to suggest three main things for this compatibility, the main one is BOP Mycelial Netherrack or replacing it or being replaced and porting the functions, also another thing is that BOP biomes spawn a lot and Nether Reed does not spawn there. The third thing is mushroom models for BOP and Nether Ex, I did my versions for Nether Ex and would be happy to send if requested but basically the mushrooms contrast too much. Edit 1: Maybe even for Example Worlds (https://www.planetminecraft.com/mod/example-nether/) mod's mushroom too.

**Comment by Sunconure11** [comment]
Nether EX has a config that allows for support. I would advise contacting them and toying around with it @paulevsGitch

**Comment by paulevsGitch** [comment]
They are already compatible

**Comment by Sunconure11** [comment]
Wait, both NetherEX and Better Nether are?

**Comment by paulevsGitch** [comment]
Yes, it was posted in comments on CurseForge. BN was originally designed as compatible with both mods, but a month ago NetherEX broken compatibility, now it was restored again.
