### ISSUE TITLE
Blame Reports after Crashing

### ISSUE THREAD

**Issue by AlexisBloodwood** [paulevsGitch/BetterNether#300]
Ended up with a few Blame Reports after I crashed, thought it was just for Swamp Grass, turned out it was a few others as well.

https://0bin.net/paste/hwuDuNeA#gFd1M08fDoL+n2dUAEqmpmmtLVIq95HKfufyVc1Pguu

**Comment by paulevsGitch** [comment]
Looks like this mod tries to load loot tables for blocks that don't have loot tables
