### ISSUE TITLE
Broken loot tables for shearables?

### ISSUE THREAD

**Issue by Leo40Git** [paulevsGitch/BetterNether#301]
On a modded server, many people have reported that vanilla trees do not drop saplings. Or... any drops, really.
We assume this to be BetterNether's fault, since AFAIK it's the only mod we have installed that touches those loot tables.
I'm not sure if this is an incompatibility issue or what, but here's the [full mod list](https://github.com/paulevsGitch/BetterNether/files/6018183/mods.txt) just in case.

**Comment by paulevsGitch** [comment]
I think this is an old loot tables made before fabric added shears tag, I will remove them
(They were added to make cincinnasite shears work with leaves on 1.15)

**Comment by paulevsGitch** [comment]
Fixed in 5.1.0
