### ISSUE TITLE
Busted mob spawns

### ISSUE THREAD

**Issue by Leo40Git** [paulevsGitch/BetterNether#303]
Another report from Aki's Origins server: mob spawns in the Flooded Deltas (and possibly other biomes your mod adds) are apparently busted.
Ghast spawns are *extremely* common and have a tendency to spawn inside people, and subsequently yeet them off whatever they're currently on and into lava.
Also, the sheer amount of mobs murders TPS, so that's another thing to consider.

**Comment by paulevsGitch** [comment]
All MC mobs spaw values are directly from vanilla, probably another mod change spawn, but this is not BetterNether
