### ISSUE TITLE
[Enhancement] Replace fireproof wood fuel with another one and remove wood from fuel

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#307]
The following wooden blocks added by Better Nether are fireproof when placed in the world, but can be burned as furnace fuel, making their behaviour inconsistent with vanilla fireproof wood types (Crimson and Warped), as well as the other blocks of their own wood types.
- Stalagnate planks, slab
- Reeds slab
- Willow planks, slab
- Wart planks, slab
- Rubeus planks, slab
- Mushroom planks
- Mushroom Fir planks, slab
- Anchor Tree planks, slab

**Comment by paulevsGitch** [comment]
BetterNether wood appeared before Nether update, so its wood can be used as a fuel. I think I will add another fuel source for early game

**Comment by saltyseadoggo** [comment]
Groovy. I can't wait to see what you come up with! Just for the record, both vanilla Nether wood types and yours can be made into sticks for early game fuel.

**Comment by quiqueck** [comment]
Moving to our Enhancement List.
