### ISSUE TITLE
Small cincinnasite lantern and cincinnasite frame cannot be crafted

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#310]
I was wanting to use the small cincinnasite lantern in a build in survival, but REI returns no recipe for one, and I didn't find one in the mod's data folder either. This particular block appears to be uncraftable, and thus only obtainable in Nether cities.

**Comment by paulevsGitch** [comment]
Probably this is related to its ID as it had a recipe, I will look at this

**Comment by saltyseadoggo** [comment]
This also applies to the cincinnasite frame.

**Comment by paulevsGitch** [comment]
Fixed in 5.1.0
