### ISSUE TITLE
Stalagnate bowl is not returned when eating the last soup in a stack

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#311]
If the player eats a Better Nether mushroom stew, bowl with black apple, wart soup, agave medicine or herbal medicine, and there is only one of the soup in the stack, the stalagnate bowl is not returned. If the player eats one of these soups from a stack, the bowl is returned.

Steps to Reproduce:
- Create a new world in survival mode with cheats enabled.
- Run the following command to give yourself one Better Nether mushroom stew:
`/give @p betternether:stalagnate_bowl_mushroom`
- Run the following command to give yourself Hunger 51 to quickly lower hunger so you can eat the stew:
`/effect give @p hunger 60 50`
- Sprint and jump until the hunger bar starts dropping. Eat the mushroom stew. The bowl is not refunded.
- Run the following command to give yourself two Better Nether mushroom stew:
`/give @p betternether:stalagnate_bowl_mushroom 2`
- Eat one of the stews in this stack. The bowl is refunded. If you then eat the remaining stew, it will not be refunded.
- Repeat for the other four soups; they behave the same way.

**Comment by paulevsGitch** [comment]
Fixed in 5.1.0
