### ISSUE TITLE
[Missing feature] The mod ores do not drop experience?

### ISSUE THREAD

**Issue by SatDog92** [paulevsGitch/BetterNether#312]
What the title says: basically, the Nether Ruby Ore, the Nether Lapis Ore and the Cincinnasite Ore do not drop any experience when mined. The Nether Ruby and the Nether Lapis ores, even if able to be mined with Silk Touch, can't even be blasted or smelted, and when blasted/smelted, the Cincinnasite ore doesn't drop any experience either.

Shouldn't they drop as much experience as the Nether Quartz ore (except Cincinnasite, which might drop as much experience as the vanilla Nether Ore block, but it's just an idea and might have the same experience of the Nether Quartz ore), and get the same respective experience when blasted/smelted?

**Comment by quiqueck** [comment]
Available in v5.3.5
