### ISSUE TITLE
Compatibility problem with Cinderscapes

### ISSUE THREAD

**Issue by what56** [paulevsGitch/BetterNether#313]
I have Cinderscapes as well as Betternether installed although only Cinderscapes Biomes spawn. I tried finding one by using the Locate command and it says it is not findable in areasonable distance. I also tried it in adifferent world and couldn't find any betternether biomes. Am I missing something as other people don't seem to have this problem?

**Comment by paulevsGitch** [comment]
Your biome source is incorrect, you can fix it like described [here](https://github.com/paulevsGitch/BetterNether/issues/293)
