### ISSUE TITLE
Compatibility...

### ISSUE THREAD

**Issue by Akorian** [paulevsGitch/BetterNether#315]
I am running a server for me and a larger group of friends. We currently use Mo'structures, biome makeover and Repurposed Structures. Since those mods modify / will modify the nether with structures, I am curious if they blend ok with Better Nether.

**Comment by paulevsGitch** [comment]
BetterNether works with most mods, if you have already generated world don’t forget to change your biome source

**Comment by Akorian** [comment]
Changing my biome source? I can't find that in the wiki. Could you elaborate?

**Comment by paulevsGitch** [comment]
Description is [here](https://github.com/paulevsGitch/BetterNether/issues/293)
