### ISSUE TITLE
[Enhancement] Use mod chests in recipes that requires chests

### ISSUE THREAD

**Issue by IdrisQe** [paulevsGitch/BetterNether#317]
BetterNether chests can't be used to craft most modded and vanilla items that require chests.
An example being the backback from SimpleBackpack, which accepts BetterEnd chests, but doesn't accept BetterNether chests... Or for Vanilla, hoppers and shulker boxes, which can be crafted with BetterEnd chests.

...Which is weird, since you're the same author as BetterEnd.

**Comment by paulevsGitch** [comment]
Minecraft don't have a specific tag for the chest, in BE all recipes with chests were added manually and they have one of fabric common tags making them possible to use in another mods. BN chests are old with manual json tag system, and this tag actually doesn't exists when BN was updated. I will add it, so it will fix mod issues, recipes for vanilla will be added manually

**Comment by IdrisQe** [comment]
Just an addition to the issue of tags- BN leaves aren't tagged with minecraft:leaves, not allowing them to be used in anything expecting that.

**Comment by quiqueck** [comment]
Available in v5.3.5
