### ISSUE TITLE
Giant Molds grown from saplings immediately break; Anchor tree vines do the same

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#318]
When you grow a giant mold from a giant mold sapling, either by planting it and waiting or by bonemealing it, all of the stem blocks immediately break and drop on the ground. The stump always remains, and the fuzzy head part sometimes remains floating in the air, or sometimes breaks as well.

**Comment by saltyseadoggo** [comment]
A similar issue occurs when an anchor tree sapling grows: all of the vines break immediately, leaving behind only a few of the vine tips. This can cause a rather large lag spike when the tree grows as they all break at once.

![2021-03-04_13 18 56](https://user-images.githubusercontent.com/69029346/110031893-554a7080-7cec-11eb-941b-704120b96e6f.png)

**Comment by paulevsGitch** [comment]
Actually, all this is a result of fixing #235

**Comment by saltyseadoggo** [comment]
Ah. Probably something to do with each mold stem/vine block requiring support from adjacent ones, and maybe not recognising it in time?

**Comment by paulevsGitch** [comment]
I think yes, they update each other and break all together

**Comment by MagmaBro123** [comment]
> I think yes, they update each other and break all together

Also affect mushrooms.

**Comment by paulevsGitch** [comment]
Fixed in 5.1.0
