### ISSUE TITLE
[Enhancement] Make Nether plants compostable

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#319]
All of the organic blocks and items that one would expect to be compostable cannot be composted. They are as follows:
- Stalagnate Seed
- Nether Reed
- Willow Sapling, Torch and Leaves
- Rubeus Sapling, Cone and Leaves
- Soul Lily Sapling, Giant Mold Sapling, Jellyfish Mushroom Sapling, Mushroom Fir Sapling
- Orange Mushroom
- Red Mold, Grey Mold
- Lucis Spore, Giant Lucis
- Anchor Tree Sapling, Leaves
- Nether Sakura Sapling, Leaves
- Eye Seed
- Nether Grass, Swamp Grass, Soul Grass, Bone Grass, Sepian Bone Grass
- Jungle Plant
- Black, Golden, Blooming Vine
- Lumabus, Golden Lumabus Seed
- Soul Vein
- Bone Mushroom Spores
- Wart Seed, Ink Bush Seed, Magma Flower Seed
- Black Bush
- Egg Plant
- Feather Fern
- Moss Cover
- Neon Equisetum
- Hook Mushroom, Cooked Hook Mushroom
- Whispering Gourd Seeds, Whispering Gourd
- Barrel Cactus, Nether Cactus
- Wall Moss, Jungle Moss
- Wall Brown Mushroom, Wall Red Mushroom
- Black Apple Seed, Black Apple
- Agave Seed, Agave Leaf

**Comment by Mandalorian007** [comment]
@paulevsGitch I just got a few minutes and too a look into the BCLib to move the composter support there, but it seems like it exists already:
https://github.com/paulevsGitch/BCLib/blob/main/src/main/java/ru/bclib/mixin/common/ComposterBlockAccessor.java

And taking a look at BetterNether it looks like it's already supported:
https://github.com/paulevsGitch/BetterNether/blob/master/src/main/java/paulevs/betternether/registry/NetherTags.java#L43

Looks like I missed this on my first review. In which case I believe that this issue could be closed and maybe there should be an issue on BetterEnd to remove it's ComposterBockAccessor and rely on BCLibs?

**Comment by quiqueck** [comment]
Yep, that seems to be right. Not sure when that was migrated tho :D
