### ISSUE TITLE
Will there be a 1.14.4 version

### ISSUE THREAD

**Issue by Niosquare** [paulevsGitch/BetterNether#32]
This mod looks absolutely stunning. But I wanna play it on 1.14.4. will there ever be a 1.14.4?

**Comment by paulevsGitch** [comment]
There is a **[forum](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/wip-mods/2930448-better-nether)/[comments](https://www.curseforge.com/minecraft/mc-mods/betternether)** for such questions, GitHub is for issues/suggestions.
There will be version for 1.14, but not now.
