### ISSUE TITLE
Naga wither effect is too short to deal any damage

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#321]
When the player is hit by one of the Naga's projectiles, they recieve a Wither effect that is only one second long, and thus doesn't last long enough to deal any lasting damage like the Wither Skeleton in vanilla. I don't know whether this is intended or not.

**Comment by paulevsGitch** [comment]
Actually it should be strong enough to make reasonable damage, I will fix it

**Comment by paulevsGitch** [comment]
Implemented in 5.1.0
