### ISSUE TITLE
Stripped logs cannot be crafted into stripped wood

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#323]
In vanilla Minecraft, stripped logs can be crafted into stripped wood blocks, the blocks with the stripped side texture on all six sides.
![2021-03-04_13 15 09](https://user-images.githubusercontent.com/69029346/110031458-c9d0df80-7ceb-11eb-91aa-fccec4540bb2.png)
This is not possible with any of Better Nether's stripped logs. This means that the player has to make the regular wood block, place it, and then strip it, and unaware players trying to strip the logs and then make the wood are disappointed.
![2021-03-04_13 15 25](https://user-images.githubusercontent.com/69029346/110031483-d2c1b100-7ceb-11eb-886a-173884869f62.png)

**Comment by paulevsGitch** [comment]
Fixed in 5.1.0
