### ISSUE TITLE
Wrong mob spawn values in most biomes

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#324]
The glowing crimson forest and crimson pinewood biomes are variants of the vanilla crimson forest biome (I presume), but, unlike the crimson forest, these two don't spawn Hoglins, and, where the crimson forest spawns many Piglins and few zombified Piglins, these two biomes do the inverse, spawning many zombified Piglins and few regular Piglins, much like a Nether wastes biome.

I don't know what your vision is for the wildlife is in these biomes, so I can only compare to vanilla behaviour, and ask if this is intentional.

However, I can also bring up a concern: Piglins don't seem to spawn in most of the Better Nether biomes, if any, in my experience, and Hoglins don't seem to gain any new biomes to spawn in at all. This can make it harder to find either mob if the player is not lucky with their world generation, and can also make it hard to find a suitable biome for a Hoglin mob farm if they wish to build one.

This also doesn't account for the flying pig being a similar creature to the Hoglin, so I'd guess you might not want the two in the same biome. This is all just something for you to consider.

**Comment by paulevsGitch** [comment]
I think the reason is that biome code was ported directly from 1.15 and some spawn values are outdated, I will fix this

**Comment by paulevsGitch** [comment]
Fixed in 5.1.0
