### ISSUE TITLE
Can't enter nether

### ISSUE THREAD

**Issue by kajo0156** [paulevsGitch/BetterNether#325]
Since a day ago or so, the nether has been totally unavailable. I checked the server properties (Since this is a server) and nothing seems to be a miss, any help?

**Comment by paulevsGitch** [comment]
Your Nether dimension entry is missing, you need to restore it. [This tutorial](https://github.com/paulevsGitch/BetterEnd/wiki/Tutorials#how-to-fix-missing-end-dimension) will help you (it was written for the End, but for the Nether everything will be the same, except biome source - it should be "betternether:nether_biome_source")
