### ISSUE TITLE
Firefly emission and rendering problem

### ISSUE THREAD

**Issue by FLGOBon** [paulevsGitch/BetterNether#333]
Firefly doesn't render properly due to the halo around it, due to the firefly having emission it renders a round plain coloured 2D circle when shaders are applied.
![2021-03-28_18 21 24](https://user-images.githubusercontent.com/79541623/112761337-c121af80-8ff2-11eb-9a2a-7ee169dc11f2.png)

**Comment by paulevsGitch** [comment]
Looks like you are using shaders, shader rendering is not under mod control
