### ISSUE TITLE
Recipes

### ISSUE THREAD

**Issue by Sunekaer** [paulevsGitch/BetterNether#335]
Hi 

Consider using data generators instead of https://github.com/paulevsGitch/BetterNether/blob/master/src/main/java/paulevs/betternether/recipes/RecipesHelper.java

That will make it so modpack makers can change these recipes.

Thanks

**Comment by LatvianModder** [comment]
The recipes also break if you do /reload, because it seems like you inject them only in first world load

**Comment by paulevsGitch** [comment]
> Consider using data generators

Data generators are not used in game for anything, all data are pre-generated json files

> That will make it so modpack makers can change these recipes

Modpack already can change recipes - each recipe can be disabled in the config (recipes.json) or being overwritten

> The recipes also break if you do /reload

No, reload works correctly, if it is not working you probably have another mods that breaks it

> seems like you inject them only in first world load

Wrong, injection applied on resource reloading
