### ISSUE TITLE
Language fix and suggestion

### ISSUE THREAD

**Issue by CalaMariGold** [paulevsGitch/BetterNether#34]
Right-clicking a respawning statue should read "You must hold Glowstone Dust to set your spawn point here."

Also, it would be nice if we could have an option to adjust the spawn rate of structures.

**Comment by paulevsGitch** [comment]
Spawn rate of structures is configurable.
Glowstone will be consumed due to "respawning ritual", so I think most correct is "sacrifice" (sounds more "epic", as it is ritual)

**Comment by CalaMariGold** [comment]
Yeah that works too. The grammar is just incorrect and it bugged me. As for the spawn rate of structures, where is it in the config?

**Comment by paulevsGitch** [comment]
"StructureDensity" in "generator" group

**Comment by paulevsGitch** [comment]
I found where I made a mistake, I will fix it in next update
