### ISSUE TITLE
game keeps crashing

### ISSUE THREAD

**Issue by daws1354** [paulevsGitch/BetterNether#340]
whenever I try to start the game with the mod installed, it crashes. (I'm using TLauncher and have fabric loader installed of course)
these are the mods I have:
![Screenshot_1](https://user-images.githubusercontent.com/82961127/115583263-04a5cb80-a2ca-11eb-97e6-005ab3102adf.png)

**Comment by paulevsGitch** [comment]
Can you please attach a crashlog?

**Comment by daws1354** [comment]
> Can you please attach a crashlog?

sorry, I'm kind of new to this whole thing so could you please tell me where do I find a crash long and how to attach it?

**Comment by Fireface677** [comment]
There should be a crash-reports folder in your minecraft folder. The just look for the log with the date of the crash. Just take the right .txt file and add it here.

**Comment by daws1354** [comment]
> There should be a crash-reports folder in your minecraft folder. The just look for the log with the date of the crash. Just take the right .txt file and add it here.

alright, thanks a lot.

**Comment by daws1354** [comment]
> Can you please attach a crashlog?

here:
[crash-2021-04-21_16.59.53-client.txt](https://github.com/paulevsGitch/BetterNether/files/6360005/crash-2021-04-21_16.59.53-client.txt)

**Comment by paulevsGitch** [comment]
Looks like something makes a blockstate of registered block null or changes getSoundType method. Can you please try to disable mods one-by-one? (this is a possible mod conflict)

**Comment by daws1354** [comment]
> Looks like something makes a blockstate of registered block null or changes getSoundType method. Can you please try to disable mods one-by-one? (this is a possible mod conflict)

it conflicted with Origins Enhanced, a mod I realized I don't really need anyways because it adds very minor stuff
thanks for the help!
