### ISSUE TITLE
Cincinnasite nerf

### ISSUE THREAD

**Issue by RavagerRaven** [paulevsGitch/BetterNether#341]
Either make it more rare or nerf the diamond cincinnasite tools, because the sword is stronger than netherite (9.5 to 8) and stronger than an end sword i have (9.5 to 8.5)
I feel like cincinnasite is the iron of the nether with the spawnrate, maybe make it so that embedding it with ruby makes it stronger but not stronger than netherite.

**Comment by Fireface677** [comment]
This is known. Rebalancement will be done after the big revamps of this mod are finished. But first betterend 1.0 has to be released before paulevs works on BN again.

**Comment by paulevsGitch** [comment]
Duplicate of other issues
