### ISSUE TITLE
Z-fighting underneath bone walls

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#344]
There is z-fighting underneath the posts on bone walls, visible (albeit barely due to the similar colours) in the image below, which is of a chandelier in one of the Nether city houses.
![2021-05-06_21 29 22](https://user-images.githubusercontent.com/69029346/117398149-94469f00-aeb2-11eb-936f-36f8eb29eece.png)

**Comment by paulevsGitch** [comment]
Fixed in 5.1.0
