### ISSUE TITLE
Incompatibility with Terra

### ISSUE THREAD

**Issue by obj-obj** [paulevsGitch/BetterNether#349]
I'm just posting this to bring attention to this issue, perhaps it could be fixed on this end?
https://github.com/PolyhedralDev/Terra/issues/176

**Comment by obj-obj** [comment]
More info at this comment: https://github.com/PolyhedralDev/Terra/issues/176#issuecomment-840329654

**Comment by paulevsGitch** [comment]
> java.lang.ClassCastException: net.minecraft.class_3754 cannot be cast to com.dfsek.terra.fabric.generation.FabricChunkGeneratorWrapper

Means that NoiseChunkGenerator cannot be casted to Terra FabricChunkGeneratorWrapper, this is Terra bug as it doesn't check biome generator before casting.

I see that you have issue with empty Terra Nether biomes, if you want you can disable them in BetterNether config and they will not spawn in your world (just set their chance to zero)

**Comment by bubbaguy1234** [comment]
Where and how would I go about setting those changes to zero though? I’ve dug around a bit and can’t find anything that references those weird terra biomes.
