### ISSUE TITLE
Config change then crash

### ISSUE THREAD

**Issue by LukaPix** [paulevsGitch/BetterNether#35]
Well i edited the config and disabled bunch of stuff..
Then this, before the edit it worked fine and it starts up fine so i guess i didn't make any syntax errors ?

Log: https://paste.ubuntu.com/p/ZGt4JjWCDS/
Config; https://paste.ubuntu.com/p/x25THTVN4r/

Crash happens on world generation.

**Comment by paulevsGitch** [comment]
As I see this happens due to disabled city generation. I will fix this in next release

**Comment by LukaPix** [comment]
well this still happens...

**Comment by paulevsGitch** [comment]
Which version are you using?

**Comment by LukaPix** [comment]
latest 1.12.2 version 0.1.8.6

**Comment by LukaPix** [comment]
i have many blocks disabled, if one disabled the blocks generated in the netherstructures it crashes, because there is an air block instead and it cant set the properties for it.

**Comment by LukaPix** [comment]
nevermind it's not the same error, ignore this im sry.
