### ISSUE TITLE
bug in block breaking time with effciency enchantment

### ISSUE THREAD

**Issue by arva70000** [paulevsGitch/BetterNether#350]
tools with efficiency 5 breaks every block so quickly.i can mine dirt and gravel and wood with a efficiency 5 cincinnasite_diamond pickaxe so fast in my survival world. it actually doesnt make sense
a cincinnasite_diamond tool with efficiency 5 acts like a efficiency 5 axe,efficiency 5 pickaxe and a efficiency 5 shovel at the same time
please fix it.

**Comment by paulevsGitch** [comment]
This is bug of MC enchant calculation system, it is applied to all tools equally independent from tool origin. It is related to some tool values, there are plans for rebalancing of cincinnasite tools in refactoring

**Comment by Dual-Iron** [comment]
Additionally, pickaxes don't lose 2x as much durability from breaking wood, axes don't lose 2x as much durability from breaking stone, etc. This seems to be more than just an efficiency enchantment bug.

**Comment by quiqueck** [comment]
Fixed in v5.3.5
