### ISSUE TITLE
Music stopping as you leave biome

### ISSUE THREAD

**Issue by IMadeThisJustToPostThis** [paulevsGitch/BetterNether#351]
I love this mod and I love the new music added, but it is very jarring how the music will stop immediately when you leave a biome and enter the vanilla end biome. It would be very nice if music would keep playing even if you enter a new biome, and only change once that first song has finished

**Comment by Corvus20** [comment]
This would be a nice touch. I want to hear this mod's music all the way through, unhindered by biome changes.

**Comment by paulevsGitch** [comment]
This is BetterNether issue tracker, not BetterEnd. BN doesn't add any music. Stopping music between biomes is an intended behaviour in BE

**Comment by fwolle30** [comment]
This happens to Better Nether as well, even when better end is not installed. Could it be, that you use the same classes from better end here (e.G. BCLib) ?

**Comment by paulevsGitch** [comment]
No, this is related to vanilla music processing. In vanilla biomes can have different music, but vanilla don’t have any smooth transitions between biomes. If the music is different in one biome - you will get this effect

**Comment by fwolle30** [comment]
Okay, thanks for clarifying this.
