### ISSUE TITLE
Parity for Whispering Gourd

### ISSUE THREAD

**Issue by hugeblank** [paulevsGitch/BetterNether#353]
An REI search shows me that there's a whispering gourd lantern, but on testing all reasonable game mechanics to get it, there's no means of getting it. Additional examination of the source verifies my testing.

If parity with the pumpkin were the goal, then this is what is missing:
- [ ] Crafting recipe: Get 4 seeds from 1 whispering gourd
- [ ] Action: Shear gourd to get 4 seeds & carve the whispering gourd
- [ ] Crafting recipe: Get gourd lantern from torch & carved gourd

**Comment by quiqueck** [comment]
Moving to our Enhancement List.
