### ISSUE TITLE
[BUG][1.12.2-0.1.8.6] Cincinnasite Ore generation not following config + "Orange" Mushroom

### ISSUE THREAD

**Issue by Shazuli** [paulevsGitch/BetterNether#354]
***Hi***

Not sure if you do any maintenance of 1.12, but worth a shot:
I'm working on a pack that has custom ore generation and would like Cincinnasite Ore to match all other ores' ore generation, but to do that I need to first turn off the old world generation. There is no option to turn off the world generation as far as I could see, but you can configure its cluster density. First I tried setting it to '0', but that didn't do it. Then I tried '1', still no luck. So I think after trying both extremes it doesn't seem to work (tried '-1' just for giggles to see if I could get a different result).

I noticed you guys made a localization error with the Orange Mushroom, which is actually purple:
![2021-05-29_19 22 44](https://user-images.githubusercontent.com/9884180/120079519-813f7d00-c0b4-11eb-9ee6-5a024b52f92e.png)

Purple does fit better into the Nether, but I would recommend changing the Orange Mushroom localization to actually say "Purple Mushroom" (even though it will still be orange_mushroom in the game).

**Comment by paulevsGitch** [comment]
Hi, 1.12 is not supported, but configs should work (the value should be 0.0), otherwise you can try to replace this block in each chunk on population (some mods allows this).

Orange Mushroom is orange, purple is the color of its exudates emitting from top. This mushroom produce dyes of both colors

**Comment by Shazuli** [comment]
Hmm... just tried setting it to '0.0'. Short answer: didn't work. Do you have any recommendations of mods that can replace blocks on world gen?
And about the Orange Mushroom, how do you extract dyes from it? Could not find any usages for it in JEI. Is it some special mechanic in order to use it as a dye/extract a dye?

**Comment by paulevsGitch** [comment]
One of mods for replacing blocks on worldgen that I found [is here](https://www.curseforge.com/minecraft/mc-mods/worldgen-block-replacer)

Orange Mushroom will drop both dyes when it will reach adult stage and will be destroyed with any tool

There are also some tips how to run BN on 1.12 smoothly (as 1.12 v. can cause lag spikes):
> - if you have "single server tick took 60.00 seconds" crash you can do [this](https://github.com/paulevsGitch/BetterNether/issues/27).
> - If you have extreme nether generation time lag or "cascade worldgen error" you can do [this](https://github.com/paulevsGitch/BetterNether/issues/25).
> - If you have lags on world saving - disable nether cities generation in the config.

I can recommend you to disable Nether Cities anyway - there was not any official API for large structure generation on 1.12 and code that generates cities can produce large lags
