### ISSUE TITLE
All stripped log variants' block ID are incorrectly spelled with only one p (E.G. Striped Nether Sakura Log as oppposed to Stripped Nether Sakura Log)

### ISSUE THREAD

**Issue by enchanted-sword** [paulevsGitch/BetterNether#355]
![image](https://user-images.githubusercontent.com/81981111/120205685-9fb28f00-c200-11eb-8436-477803063804.png)

**Comment by paulevsGitch** [comment]
At this time changing ID structure is not possible. All ID namings can be fixed in the refactored version

**Comment by quiqueck** [comment]
Fixed in v5.3.5
