### ISSUE TITLE
Custom Sounds Issue

### ISSUE THREAD

**Issue by lilPNUTTY** [paulevsGitch/BetterNether#356]
All mobs with custom sounds make the same volume of noise regardless of distance, In the nether the skull mob gets very annoying when a bunch of them spawn and they are no where near me. There is the same problem in better end as well.

**Comment by paulevsGitch** [comment]
All sounds are defined the same way as in vanilla, but I will look at this

**Comment by paulevsGitch** [comment]
Fixed in 5.1.0
