### ISSUE TITLE
Entity: HydrogenJellyfish causes crashing on fabric server

### ISSUE THREAD

**Issue by Cwoodyard** [paulevsGitch/BetterNether#357]
[crash-2021-06-02_11.51.01-server.txt](https://github.com/paulevsGitch/BetterNether/files/6586620/crash-2021-06-02_11.51.01-server.txt)
[crash-2021-06-02_11.35.16-server.txt](https://github.com/paulevsGitch/BetterNether/files/6586621/crash-2021-06-02_11.35.16-server.txt)
[crash-2021-06-01_13.48.36-server.txt](https://github.com/paulevsGitch/BetterNether/files/6586622/crash-2021-06-01_13.48.36-server.txt)
[crash-2021-06-01_10.47.09-server.txt](https://github.com/paulevsGitch/BetterNether/files/6586623/crash-2021-06-01_10.47.09-server.txt)

**Comment by Cwoodyard** [comment]
Attached above are the crash logs. Let me know if you need system info and ill do the best i can to help. Its happening too often now and might try to remove the entity via console but this seems to be reoccurring. This is a modpack server.

Modpack: https://www.curseforge.com/minecraft/modpacks/manas-fabric-adventures

**Comment by Cwoodyard** [comment]
Temporarily disabled spawning the entity for now via config but would like to see this get addressed.

**Comment by paulevsGitch** [comment]
This is inner MC or java bug with async lists, I don’t know if it is possible to fix. It randomly happens with different entities

**Comment by paulevsGitch** [comment]
Fixed in 5.1.0
