### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by 3prm3** [paulevsGitch/BetterNether#358]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 6/3/21 4:47 PM
Description: Exception generating new chunk

java.lang.NullPointerException: No chunk exists at [11, 7]
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.9)
	at net.minecraft.world.ChunkRegion.getBlockState(ChunkRegion:1060)
	at paulevs.betternether.world.BNWorldGenerator.populate(BNWorldGenerator.java:205)
	at net.minecraft.world.gen.chunk.ChunkGenerator.handler$bio000$customPopulate(ChunkGenerator:1553)
	at net.minecraft.world.gen.chunk.ChunkGenerator.generateFeatures(ChunkGenerator)
	at net.minecraft.world.gen.chunk.NoiseChunkGenerator.generateFeatures(NoiseChunkGenerator:3371)
	at net.minecraft.world.chunk.ChunkStatus.method_12151(ChunkStatus:89)
	at net.minecraft.class_2806$$Lambda$2129/1112597751.doWork(Unknown Source)
	at net.minecraft.world.chunk.ChunkStatus.md8c6124$lambda$injectLightmapSetup$1$4(ChunkStatus:1546)
	at net.minecraft.class_2806$$Lambda$2130/142883344.doWork(Unknown Source)
	at net.minecraft.world.chunk.ChunkStatus.runGenerationTask(ChunkStatus:219)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage:568)
	at net.minecraft.class_3898$$Lambda$12436/1228488081.apply(Unknown Source)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage:562)
	at net.minecraft.class_3898$$Lambda$12433/1416007144.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17634(ChunkTaskPrioritySystem:58)
	at net.minecraft.class_3900$$Lambda$12315/1753634774.run(Unknown Source)
	at net.minecraft.util.thread.TaskExecutor.runNext(TaskExecutor:94)
	at net.minecraft.util.thread.TaskExecutor.runWhile(TaskExecutor:137)
	at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor:105)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Chunk to be generated --
Details:
	Location: 11,-2
	Position hash: -8589934581
	Generator: net.minecraft.class_3754@24c9d7f1
Stacktrace:
	at net.minecraft.class_3898.method_17225(class_3898.java:573)
	at net.minecraft.class_3898$$Lambda$12436/1228488081.apply(Unknown Source)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:562)
	at net.minecraft.class_3898$$Lambda$12433/1416007144.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3900$$Lambda$12315/1753634774.run(Unknown Source)
	at net.minecraft.class_3846.method_16907(class_3846.java:94)
	at net.minecraft.class_3846.method_16900(class_3846.java:137)
	at net.minecraft.class_3846.run(class_3846.java:105)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
-- Affected level --
Details:
	All players: 1 total; [class_3222['3prm3'/119, l='ServerWorld minecraft:the_nether 1337', x=24.70, y=84.30, z=79.24]]
	Chunk stats: ServerChunkCache: 2578
	Level dimension: minecraft:the_nether
	Derived: true
	Level spawn location: World: (280,64,239), Chunk: (at 8,4,15 in 17,14; contains blocks 272,0,224 to 287,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 25252 game time, 10940 day time
	Level name: 1337
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5370652368 bytes (5121 MB) / 10301210624 bytes (9824 MB) up to 13958643712 bytes (13312 MB)
	CPUs: 8
	JVM Flags: 13 total; -XX:-OmitStackTraceInFastThrow -Xms512M -Xmx4096M -XX:MetaspaceSize=256M -Xmx13G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=30 -XX:G1ReservePercent=30 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=512M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
	Suspected Mods: Better Nether (betternether)
	Fabric Mods: 
		addendum: Addendum 1.16.5-1.0.2
		adorn: Adorn 1.14.1+1.16.5
		advanced_runtime_resource_pack: Runtime Resource Pack 0.3.7
		amecs: Amecs 1.3.4+mc.1.16.3
		amecsapi: Amecs API 1.1.4+mc1.16.5
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		appleskin: AppleSkin 1.0.11
		arcana2plus: Arcana ++ 0.0.3+1.16-alpha
		arcanaflavor: Arcana Flavor 0.0.8+1.16-alpha
		architectury: Architectury 1.9.132
		arfo: Artificial Foliage 2.0
		arstheurgia: Ars Theurgia 1.0.6
		artifacts: Artifacts 3.2.1+fabric
		artifice: Artifice 0.14.6+1.16.5
		artofalchemy: Art of Alchemy: Memoriam 1.0.0-rc4+1.16.4
		astromine: Astromine 1.11.5+fabric-1.16.5
		astromine-core: Astromine: Core 1.11.5+fabric-1.16.5
		astromine-discoveries: Astromine: Discoveries 1.11.5+fabric-1.16.5
		astromine-foundations: Astromine: Foundations 1.11.5+fabric-1.16.5
		astromine-technologies: Astromine: Technologies 1.11.5+fabric-1.16.5
		astromine-transportations: Astromine: Transportations 1.11.5+fabric-1.16.5
		atbyw: All The Blocks You Want (ATBYW) 1.3.4
		autoconfig1u: Auto Config v1 Updated 3.3.1
		automated_crafting: Automated Crafting 1.3.21+MC1.16.2-1.16.5
		axesareweapons: Axes Are Weapons 1.1
		backslot: BackSlot 1.1.11
		bambootweaks: Bamboo Tweaks 2.0.5
		beachslimes: Beach Slimes 2.1.0+mc1.16.1
		beholdersvariations: Beholder's Variations 0.5.5
		better_withered_mobs: Better Withered Mobs 1.5.2
		betterbiomeblend: Better Biome Blend 1.16.4-1.1.4-fabric
		bettercaves: YUNG's Better Caves 1.16.5-1.2
		betterend: Better End 0.9.6-pre
		betterf3: BetterF3 1.1.3
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0.1
		betternether: Better Nether 5.0.7
		bettersodiumvideosettingsbutton: Better Sodium Video Settings Button 1.0.3.1
		betterstrongholds: YUNG's Better Strongholds 1.16.5-1.0
		betterthanmending: BetterThanMending 1.3.0
		betterthirdperson: Better Third Person 1.4.0
		biomeinfo: Biome Info 1.16.5-6
		biomemakeover: Biome Makeover 1.16.5-1.3.8
		biomepicker: Biome Picker 1.1
		bitsandchisels: BitsAndChisels 2.3.2
		blade: Blade 2.0.0
		blockus: Blockus 2.1.6+1.16.5
		blue_endless_jankson: jankson 1.2.0
		bookinit: BookinIt 1.0.0
		brewableluck: Liquid Luck(and unluck) 1.0.0
		builder_helper: BuilderHelper 0.1
		byg: BYG 1.1.8
		campanion: Campanion 1.3.5
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.0.2
		candlebackport: Candle Backport 1.0
		cardinal-components: Cardinal Components API 2.8.2
		cardinal-components-base: Cardinal Components API (base) 2.8.2
		cardinal-components-block: Cardinal Components API (blocks) 2.8.2
		cardinal-components-chunk: Cardinal Components API (chunks) 2.8.2
		cardinal-components-entity: Cardinal Components API (entities) 2.8.2
		cardinal-components-item: Cardinal Components API (items) 2.8.2
		cardinal-components-level: Cardinal Components API (world saves) 2.8.2
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.8.2
		cardinal-components-util: Cardinal Components API (utilities) 2.8.2
		cardinal-components-world: Cardinal Components API (worlds) 2.8.2
		carpet: Carpet Mod 1.4.37
		carpet-extra: Carpet Extra 1.4.34
		ccrp: Crazy Creepers 1.3.1
		cdsam: Survival Additions 1.3.2-Fabric-1.16.5
		chainmail: Chainmail 0.5.0
		charcoalblock: Charcoal Block 1.0.1
		charm: Charm 2.3.2
		chatplus: chatplus 1.0.1
		chestblocks: Chest Building Blocks 0.0.2
		chillager_mod: Chillager 1.1
		chime: Chime 1.1.3
		chiseldecor: Chisel Decor 1.1.3
		chord: Chord 1.7.1+1.16.5-fabric
		cinderscapes: Cinderscapes 1.3.3
		cloth-armor-api-v1: Cloth Armor API v1 1.5.47
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-common-events-v1: Cloth Common Events v1 1.5.47
		cloth-config2: Cloth Config v4 4.11.26
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.9
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.5.47
		cloth-utils-v1: Cloth Utils v1 1.4.5
		colormeoutlines: Color Me Outlines 1.0.0
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		command-block-ide: Command Block IDE 0.1.1
		computercraft: CC:Restitched 1.95.3-beta
		connected_block_textures: Connected Block Textures 0.1.3+1.16
		consistency_plus: Consistency Plus 0.3.0
		continuebutton: Continue Button 1.0.2
		controlling: Controlling For Fabric 1.1.2
		cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
		couplings: Couplings 1.3.3
		crowdin-translate: CrowdinTranslate 1.3+1.16
		crumbs: Crumbs 1.0.7
		ctm: ConnectedTexturesMod for Fabric 0.4.0
		curios: Curios API 0.0.13-1.16.5
		cursemods: Cursemods 1.0.2-fabric
		customportalapi: Custom Portals 0.0.1-beta32-1.16
		damagetilt: Damage Tilt 1.16-fabric-0.1.2
		darkpaintings: Dark Paintings 3.0.1
		dawn: Dawn API 1.8
		day_dream: Day Dream 1.0.1
		dazzle: Dazzle 2 1.0
		de_javagl_obj: obj 0.3.0
		dynamicfps: Dynamic FPS 2.0.2
		dynamicsoundfilters: Dynamic Sound Filters 1.2.0+1.16.5
		dynamo_api: Dynamo API 1.0.0+1.16
		earthtojavamobs: Earth2Java 1.7.1+1.16.4
		ecotones: Ecotones 0.7.2
		elementalcreepers: Elemental Creepers: Refabricated 1.3.0
		engilib: EngiLib 1.0.0+1.16.4
		enhanced_mushrooms: Enhanced Mushrooms 1.0.4
		expandedstorage: ExpandedStorage 5.6.33
		extraalchemy: Extra Alchemy 1.4.5
		extrainv: Extra Inventory 1.0.0
		fabric: Fabric API 0.34.6+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+84310a227d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.10+3661eaa17d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.0+kotlin.1.5.0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.3+e3c9d0627d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+2868a2287d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 0.1.0+7678d00a7d
		fabricloader: Fabric Loader 0.11.3
		fallflyinglib: FallFlyingLib 2.0.3
		fancymenu: FancyMenu 2.0.5
		farmersdelight: Farmer's Delight 1.16.5-0.0.3
		fasttransferlib: Fast Transfer Lib 0.4.1
		fermion: Fermion 2.1.191
		fermion-modkeys: Fermion Modifier Keys 1.10.218
		ferritecore: FerriteCore 2.0.4
		fiber: fiber 0.23.0-2
		figura: Figura 0.0.5
		flamboyant: Flamboyant Refabricated 1.16.4-1.0.1
		flytre_lib: FlytreLib 0.2.11
		framed: Framed 1.1
		frex: FREX 4.5.201
		gbfabrictools: GBfabrictools 1.3.2+1.16.4
		geckolib3: Geckolib 3.0.34
		gobber2: Gobber2 2.3.71
		goldensteak: Goldensteak 1.0.2
		grass_pass: Grass Bypass 1.0.0
		harmfulstonecutters: Harmful Stonecutters 1.0.2
		heartbond: Heartbond 1.0.0
		here-be-no-dragons: Here be no Dragons! 1.0.0
		homecamp: Home Camp 1.0.3
		horseinfo: Horse Info 0.2.2-1.16.1
		horsestatsvanilla: Horse Stats Vanilla 4.1.6
		human_reborn: Human Reborn 1.0.0
		imm_ptl_core: Immersive Portals Core 0.90
		immersive_portals: Immersive Portals 0.90
		indium: Indium 1.0.0
		indrev: Industrial Revolution 1.9.16-BETA
		isometric-renders: Isometric Renders 0.1.7
		ivan-carpet-addition: Ivan Carpet Addition 1.4.0+build.101
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		javax_vecmath_vecmath: vecmath 1.5.2
		json-model-extensions: JSON Model Extensions 1.20.179
		konkrete: Konkrete 1.1.7
		krypton: Krypton 0.1.2
		ksrch: Keybind Search 1.0.0
		lambdabettergrass: LambdaBetterGrass 1.0.3+1.16
		lambdynlights: LambDynamicLights 1.3.4+1.16
		lazydfu: LazyDFU 0.1.2
		leather-blocks: Leather Blocks 1.1.0
		legacy_bows: Legacy Bows 1.0.1
		lepton: Lepton-Fabric 1.16.5-1.0.0
		libblockattributes: LibBlockAttributes 0.8.8
		libblockattributes_core: LibBlockAttributes (Core) 0.8.8
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.8
		libblockattributes_items: LibBlockAttributes (Items) 0.8.8
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.4.0+1.16.5
		linkedstorage: Linked Storage 1.3.11-1.16
		lithium: Lithium 0.6.4
		luxfurnituremod: Lux's Furniture Mod 0.0.2
		magna: Magna 1.5.1-1.16.5
		malilib: MaLiLib 0.10.0-dev.21+arne.5
		marbles: Marbles 0.1.0+a153.fabric-1.16.5
		maybe-data: Maybe data 1.0.0-1.16.2
		mechanicaltech: Mechanical Tech 0.3.0+1.16
		megane: megane 4.1.2
		megane-art-of-alchemy: megane-art-of-alchemy 4.1.2+1.0.0-rc4-1.16.4
		megane-astromine: megane-astromine 4.1.2+1.11.4-fabric-1.16.3
		megane-base: megane-base 4.1.2
		megane-fast-transfer-lib: megane-fast-transfer-lib 4.1.2+0.3.1
		megane-industrial-revolution: megane-industrial-revolution 4.1.2+1.8.13-BETA
		megane-lib-block-attributes: megane-lib-block-attributes 4.1.2+0.8.7
		megane-modern-industrialization-4: megane-modern-industrialization-4 4.1.2+0.4.0-alpha.05
		megane-runtime: megane-runtime 4.1.2
		megane-team-reborn-energy: megane-team-reborn-energy 4.1.2+0.1.0
		megane-tech-reborn: megane-tech-reborn 4.1.2+3.8.2-build.220
		megane-vanilla: megane-vanilla 4.1.2+1.16.5
		mi: More Ice Mod 1.0.0
		mighty_mangoes: Mighty Mangoes 1.0.3
		milk_plus: Milk+ 1.0
		minecraft: Minecraft 1.16.5
		modern_industrialization: Modern Industrialization 0.4.0-alpha.06
		modid: 1.17 Raw Ores for 1.16 1.0.0
		modmenu: Mod Menu 1.16.9
		monster_in_the_closet: Monsters in the Closet 1.0.1+1.16
		moreblocksmod: More Blocks Mod 0.1.5
		moredrinks: More Drinks 1.0.0
		moremessages: MoreMessages 1.2.0
		morerespawnanchors: More Respawn Anchors 1.0.1
		moreslimemod: Moreslime Mod 1.5.2
		morevillagers-fabric: MoreVillagersFabric 1.3.0-SNAPSHOT
		mostructures: Mo' Structures 1.1.1+mc.1.16.5
		nccbyshoaibkhan: Numpad Camera Controls 1.0.4
		net_openhft_zero-allocation-hashing: zero-allocation-hashing 0.11
		net_shadew_ptg: ptg 2.0.0
		net_shadew_shwutil: shwutil 1.5.0
		netheritecarrots: Netherite Carrots 1.1.0
		nicephore: Nicephore fabric-1.16.x-1.1.5
		nmuk: No More Useless Keys 1.0.0+mc1.16.4
		nookbuild: NookBuild 1.4.0
		notenoughcrashes: Not Enough Crashes 3.2.0
		npcvariety: NPC Variety 1.2.4
		orderly: Orderly 2.0.0-alpha.10-1.16
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0-RC
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0-RC
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.0
		org_joml_joml: joml 1.10.0
		org_luaj_luaj-jse: luaj-jse 3.0.1
		oro_config: OroArmor Config 1.2.0
		overworld_two: Overworld 2 1.0.4
		paintingcycle: Painting Cycle 1.0.0
		patchouli: Patchouli 1.16.4-50-FABRIC
		pehkui: Pehkui 1.9.0+21w10a
		perspectivemod: Perspective Mod Redux 0.0.5
		pettable: Pettable 1.1.0
		phosphor: Phosphor 0.7.2+build.12
		piglib: Piglib 1.0.1
		playerabilitylib: Pal 1.2.2
		plume: Plume 0.5.6
		polymorph: Polymorph 0.0.10-1.16.5
		promenade: Promenade 2.0
		puddles: Puddles 1.1.0
		pugh_lib: Pugh Lib 1.1.0
		reach-entity-attributes: Reach Entity Attributes 1.1.1
		readyyourshovels: Ready Your Shovels 0.1.0+a88.1.16.5-fabric
		reborncore: Reborn Core 4.7.3+build.136
		redbits: Red Bits 1.8.0
		redstonebits: Redstone Bits 1.2.2
		redstonecookies: Redstone Cookies 1.0.0
		reeses-sodium-options: Reese's Sodium Options 1.0.1
		repurposed_structures: Repurposed Structures 1.16.5-1.10.5-fabric
		rfmagnet: RF Magnet 1.0.0
		riverredux: River Redux 0.1.6
		rotten: FleshZ 1.4.1
		roughlyenoughitems: Roughly Enough Items 5.11.218
		roughlyenoughitems-api: REI (API) 5.11.218
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.11.218
		roughlyenoughitems-runtime: REI (Runtime) 5.11.218
		sakurarosea: Sakura Rosea 1.6.0-MC1.16.3-fabric
		sarcs_suggestions: Sarcs Suggestions 1.0.0
		scarpet-additions: Scarpet Additions 1.16.5-1.4.29
		secretrooms: Secret Rooms 0.9.5+1.16.5
		seedy-behavior: Seedy Behavior 1.0.1
		signretain: Sign Retain 1.0.3
		simple_cobblestone_generator: Simple cobblestone generator 1.0.0
		skinnedlanterns: Skinned Lanterns 1.16.5-1.1.3
		smoothboot: Smooth Boot 1.16.5-1.6.0
		smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
		sodium: Sodium 0.1.1-SNAPSHOT
		sodium-extra: Sodium Extra 0.3.1
		spokenword: Spoken Word 1.2
		spruceui: SpruceUI 2.1.4+1.16
		stacc: Stacc 1.0.1
		staffofbuilding: Staff of Building 1.2.6-1.16.5
		stairdoors-fabric: StairDoors Fabric 2.1.0
		statuseffecttimer: Status Effect Timer 1.0.1
		stendhal: Stendhal 1.1.0
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stepup: StepUp 1.16.5-fabric0.30.0-1.1
		stoneholm: Stoneholm 1.2.1
		stuffz: StuffZ 2.3.0
		taxfreelevels: Tax Free Levels 1.1
		team_reborn_energy: Energy 0.1.1
		techreborn: Tech Reborn 3.8.4+build.236
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.4
		terraform-config-api-v1: Terraform Config API (v1) 1.0.3
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.1.3
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.3
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.3
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.5
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.3
		terrestria: Terrestria 2.2.0
		texp: Terran Expansion 1.1.2
		the_aether: The Aether 1.16.5-1.4.1
		timeandwind: Time & Wind 1.3.2
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.6
		torohealth: ToroHealth Damage Indicators 1.16.4-fabric-4
		traverse: Traverse 3.3.2
		trinkets: Trinkets 2.6.7
		truerooms: True Secret Rooms 1.1.3
		tweak-my-client: TweakMyClient 1.0.5+build.6
		unearthed: Unearthed 1.1.0
		upstream: Upstream 1.0.1
		vanillaenhanced: VanillaEnhanced 1.5.1
		villager_see_villager_do: Villager See, Villager Do 1.0.2+MC1.16.3-1.16.5
		villagernames: Villager Names 1.6.0
		voyager: Voyager 1.0.0
		wands: Wands Mod 1.4.5
		waterdripsound: Drip Sounds 0.2.1-1.16
		waystones: Waystones 1.1.1.1
		white_rabbit: White Rabbit 1.0.9+21w10a
		wildworld: Wild World 2.0.0+1.16.5
		winged: Winged Mod 1.16.5-2.1.2
		woods_and_mires: Woods and Mires 1.0.4+1.16.3
		wrenchable: Wrenchable 1.0.0+1.16.1
		wthit: wthit 2.10.0
		xlpackets: XLPackets 1.1
		yungsapi: YUNG's API 1.16.5-Fabric-5
	Patchouli open book context: n/a
	Player Count: 1 / 8; [class_3222['3prm3'/119, l='ServerWorld minecraft:the_nether 1337', x=24.70, y=84.30, z=79.24]]
	Data Packs: secretrooms:server_pack, vanilla, Fabric Mods, file/Death Coordinates.zip, file/Dig_Straight_Down.zip, file/Easier Evokers.zip, file/Easier_Stronghold_Locating.zip, file/Farming Orbs.zip, file/Movable Tile Entities.zip, file/Nether Portal Anchors.zip, file/Netherite_Hoe_Bartering.zip, file/Netherite_Recycling.zip, file/No Wild Chicken Eggs.zip, file/Quick Draw.zip, file/Smeltable Netherite.zip, file/Spawn with Empty Map.zip, file/TCC Datapack.zip, file/Vein Miner.zip, file/Void Totem.zip, file/Weather Forecast.zip, file/back v1.2.0.zip, file/cauldron concrete v2.0.3.zip, file/classic fishing loot v1.1.0.zip, file/custom villager shops v1.2.0.zip, file/double shulker shells v1.3.0.zip, file/dragon drops v1.3.0.zip, file/dreamland1-1.zip, file/elder-guardian-improvements-v1-2.zip, file/gem villagers v4.3.3.zip, file/gm4_better_armour_stands_1_16.zip, file/gm4_book_binders_1_16.zip, file/gm4_chairs_1_16.zip, file/gm4_cooler_caves_1_16.zip, file/gm4_custom_crafters_1_16.zip, file/gm4_dangerous_dungeons_1_16.zip, file/gm4_heart_canisters_1_16.zip, file/gm4_holographic_tags_1_16.zip, file/gm4_lightning_rods_1_16.zip, file/gm4_liquid_tanks_1_16.zip, file/gm4_master_crafting_1_16.zip, file/gm4_mending_tanks_1_16.zip, file/gm4_metallurgy_1_16.zip, file/gm4_moneo_shamir_1_16.zip, file/gm4_note_block_interface_1_16.zip, file/gm4_orbis_1_16.zip, file/gm4_particles_pack_1_16.zip, file/gm4_percurro_shamir_1_16.zip, file/gm4_phantom_scarecrows_1_16.zip, file/gm4_podzol_rooting_soil_1_16.zip, file/gm4_poses_pack_1_16.zip, file/gm4_potion_liquids_1_16.zip, file/gm4_potion_swords_1_16.zip, file/gm4_relocators_1_16.zip, file/gm4_resources.zip, file/gm4_smelteries_1_16.zip, file/gm4_speed_paths_1_16.zip, file/gm4_standard_crafting_1_16.zip, file/gm4_tnt_landmines_1_16.zip, file/gm4_tower_structures_1_16.zip, file/gm4_vertical_rails_1_16.zip, file/gm4_zauber_cauldrons_1_16.zip, file/gm4_zauber_liquids_1_16.zip, file/gm4_ziprails_1_16.zip, file/homes v1.4.1.zip, file/larger phantoms v1.2.1.zip, file/more mob heads v2.8.2.zip, file/more-fruitful-loot-1-4.zip, file/more-structures-e1111.zip, file/more_stuff_to_blast.zip, file/player head drops v1.1.0.zip, file/redstone rotation wrench v1.1.1.zip, file/relics-ruins-1-3-1-e2591.zip, file/seasons_dimension_1.16.3_v1.1.zip, file/shard-data.zip, file/spawn v2.3.0.zip, file/tag v2.1.0.zip, file/terracotta rotation wrench v1.1.1.zip, file/thunder shrine v1.1.0.zip, file/tpa v2.3.0.zip, file/treasure gems v1.2.2.zip, file/villager workstation highlights v1.1.0.zip, file/wandering trades hermit edition v1.4.0.zip, file/wandering-trader-heads-1.4.0-custom.zip, file/wandering-tweaks-e1960.zip (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by paulevsGitch** [comment]
> No chunk exists

This means that chunk is missing during generation. This is not directly BN bug, BN just uses chunk events to populate chunks and process fixing pass. Probably one of your mods alter chunk generation and this breaks BN generator

**Comment by paulevsGitch** [comment]
Now it will be checked that chunk is not null

**Comment by paulevsGitch** [comment]
Fixed in 5.1.0
