### ISSUE TITLE
Glitches

### ISSUE THREAD

**Issue by C0DEHADES** [paulevsGitch/BetterNether#363]
- Efficiency makes all nether tools break anything, example pickaxe breaks logs as an axe with Efficiency.
- Most of the custom blocks don't break with any of the pickaxes for example the netherrack furnace and other blocks.
- Weapon durability is shown even without unbreaking on them, and their durability values doesn't increase when you give it unbreaking.
- Biomes spawn wierd, and sometimes too far.

**Comment by rogi27** [comment]
@paulevsGitch same problems, any ETA for fixes?

**Comment by C0DEHADES** [comment]
I think that's it

**Comment by paulevsGitch** [comment]
First of all please split all bugs to a separate reports (one report = one bug). Second - please provide a bit more information - what BN & MC version you are yousing

**Comment by TBiscuit1** [comment]
This glitch is maybe cause of minecraft's 1.17 new tag? Since every block doesn't have a tool tag, any tool efficiency work somehow, so that could be why block can be either super hard to mine or super easy to mine since they have no tag for minability

**Comment by paulevsGitch** [comment]
Issue #364 is more clear than this one and is a reason of these bugs, so I'm closing this
