### ISSUE TITLE
Backport to 1.16.5

### ISSUE THREAD

**Issue by hugeblank** [paulevsGitch/BetterNether#366]
I've been excitedly waiting for all of the bugfixes to do with better nether to be put into a release, so I could do more in my 1.16.5 server. But because they all got bunched in with an update to 1.17 I can't. I know this is a lot to ask for coming from someone that's actively doing this with one of my own mods, but I do feel like there's a benefit. I, personally, don't want to play with all of the 1.17 features until part 2 of caves & cliffs. Having a version for those who share the same sentiment would be great for those people.

**Comment by Alkiasan** [comment]
+1 on this, with the current features from 1.17's update and the amount of mods that aren't updated to 1.17 yet, it's just not worth updating. Would love to be able to use the mod with all of 1.17's fixes on 1.16!

**Comment by paulevsGitch** [comment]
I can understand people who want fixes for 1.16 instead of 1.17 as it is most stable modded version right now. I will probably try to port some fixes on 1.16
