### ISSUE TITLE
Game crashes upon opening world.

### ISSUE THREAD

**Issue by Mysteriaa** [paulevsGitch/BetterNether#367]
https://paste.atlauncher.com/view/02772b60-f688-42db-a3b0-ee1dd65614ae Game crashes upon opening world, this mod appears to be the culprit. Fabric for 1.17.

**Comment by paulevsGitch** [comment]
Looks like something set world biomes to null or prevent them to be getted, this shouldn't happen in normal game, looks like you have a mod conflict

**Comment by paulevsGitch** [comment]
You can try to find what mods causes this by disabling them and using test world

**Comment by paulevsGitch** [comment]
Looks like there are some issues with terra and missing biomes, probably it causes this issue

![image](https://user-images.githubusercontent.com/17707380/123747215-54e96d00-d8bb-11eb-99c6-2818286e938b.png)

**Comment by paulevsGitch** [comment]
As there is no any response I'm closing this
