### ISSUE TITLE
Crash when rendering firefly entity

### ISSUE THREAD

**Issue by mcalzoney** [paulevsGitch/BetterNether#368]
The game crashes when trying to render the firefly entity in my server. It only crashes on the client side. It happens when I am close to a nether piglin city

Crash report:

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 7/2/21 1:15 AM
Description: Rendering entity in world

java.util.NoSuchElementException
	at com.google.common.collect.Iterators$1.next(Iterators.java:81)
	at us.potatoboy.fedora.client.features.HatRenderer.render(HatRenderer.java:96)
	at us.potatoboy.fedora.client.features.HatRenderer.method_4199(HatRenderer.java:28)
	at net.minecraft.class_922.method_4054(class_922.java:139)
	at net.minecraft.class_927.method_4072(class_927.java:43)
	at net.minecraft.class_927.method_3936(class_927.java:18)
	at net.minecraft.class_898.method_3954(class_898.java:261)
	at net.minecraft.class_761.method_22977(class_761.java:1459)
	at net.minecraft.class_761.method_22710(class_761.java:1219)
	at net.minecraft.class_757.method_3188(class_757.java:727)
	at net.minecraft.class_757.method_3192(class_757.java:546)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.google.common.collect.Iterators$1.next(Iterators.java:81)
	at us.potatoboy.fedora.client.features.HatRenderer.render(HatRenderer.java:96)
	at us.potatoboy.fedora.client.features.HatRenderer.method_4199(HatRenderer.java:28)
	at net.minecraft.class_922.method_4054(class_922.java:139)
	at net.minecraft.class_927.method_4072(class_927.java:43)
	at net.minecraft.class_927.method_3936(class_927.java:18)

-- Entity being rendered --
Details:
	Entity Type: betternether:hydrogen_jellyfish (paulevs.betternether.entity.EntityHydrogenJellyfish)
	Entity ID: 183009
	Entity Name: Hydrogen Jellyfish
	Entity's Exact location: 48.95, 61.02, 328.81
	Entity's Block location: World: (48,61,328), Chunk: (at 0,3,8 in 3,20; contains blocks 48,0,320 to 63,255,335), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.02, -0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: paulevs.betternether.entity.render.RenderHydrogenJellyfish@1eeec231
	Location: 26.34,7.30,-21.40 - World: (26,7,-22), Chunk: (at 10,0,10 in 1,-2; contains blocks 16,0,-32 to 31,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Rotation: 275.625
	Delta: 0.44005013
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:261)
	at net.minecraft.class_761.method_22977(class_761.java:1459)
	at net.minecraft.class_761.method_22710(class_761.java:1219)
	at net.minecraft.class_757.method_3188(class_757.java:727)

-- Affected level --
Details:
	All players: 1 total; [class_746['ColinMahoney'/183003, l='ClientLevel', x=22.61, y=52.10, z=350.22]]
	Chunk stats: SodiumChunkCache: 441
	Level dimension: minecraft:the_nether
	Level spawn location: World: (-262,67,-216), Chunk: (at 10,4,8 in -17,-14; contains blocks -272,0,-224 to -257,255,-209), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 7763499 game time, 8389594 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:699)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 779673800 bytes (743 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		adventurez: AdventureZ 1.2.6
		ag4tr: Ag4tr 0.1.5.12
		agape_space: Agape Space Mod 0.0.14
		alaskanativecraft: Alaska Native Craft 1.2.2
		angerable-patch: Angerable Patch 1.0.0-1.16.1
		autoconfig1u: Auto Config v1 Updated 3.3.1
		battletowers: Battle Towers 3.3.4-1.16.4
		beachslimes: Beach Slimes 2.1.0+mc1.16.1
		bedrockwaters: BedrockWaters 1.4.3+1.16.4
		bedspreads: Bedspreads 1.3.1-1.16.4
		betterdroppeditems: Better Dropped Items 1.2.4-1.16.2
		betterend: Better End 0.9.6-pre
		betternether: Better Nether 5.0.7
		biome_locator: Biome Locator 1.1.2
		biomemakeover: Biome Makeover 1.16.5-1.3.8
		blast: BLAST 1.5.2
		blockus: Blockus 2.1.8+1.16.5
		byg: BYG 1.1.8
		cardinal-components: Cardinal Components API 2.8.3
		cardinal-components-base: Cardinal Components API (base) 2.8.3
		cardinal-components-block: Cardinal Components API (blocks) 2.8.3
		cardinal-components-chunk: Cardinal Components API (chunks) 2.8.3
		cardinal-components-entity: Cardinal Components API (entities) 2.8.3
		cardinal-components-item: Cardinal Components API (items) 2.8.3
		cardinal-components-level: Cardinal Components API (world saves) 2.8.3
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.8.3
		cardinal-components-util: Cardinal Components API (utilities) 2.8.3
		cardinal-components-world: Cardinal Components API (worlds) 2.8.3
		ce_foodstuffs: Common Expansion: Foodstuffs 1.1.5
		chillager_mod: Chillager 1.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.11.26
		crawl: Crawl 0.8.4
		crimsonmoon: Crimson Moon 2.0.4-1.16.5
		curios: Curios API 0.0.13-1.16.5
		customportalapi: customportalapi 0.0.1-beta18-1.16
		dawn: Dawn API 1.8
		dehydration: Dehydration 1.1.4
		dual_riders: DualRiders 1.0.5
		earthtojavamobs: Earth2Java 1.7.1+1.16.4
		editsign: EditSign 2.2.1
		enchant_giver: Enchant Giver 1.0.3
		environmentz: EnvironmentZ 1.1.1
		extraalchemy: Extra Alchemy 1.4.5
		extradoors: ExtraDoors 1.8.2-1.16.2
		extraorigins: Extra Origins 1.16.5-12
		eymbra: Eymbra's Prehistoric Mod 1.0.0
		fabric: Fabric API 0.36.0+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+6aebe11a7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.10+3661eaa17d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.3+f941baf07d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.1+kotlin.1.5.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.3+e3c9d0627d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.3+0ef801b67d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+ca0ef93d7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabricloader: Fabric Loader 0.11.6
		fallflyinglib: FallFlyingLib 1.1.0
		fedora: Fedora 1.1.1-fabric-1.16.4
		fiber: fiber 0.23.0-2
		flytre_lib: FlytreLib 0.2.11
		geckolib3: Geckolib 3.0.40
		gobber2: Gobber2 2.3.71
		golemancy: Golemancy 1.0.1
		gravestones: Gravestones v1.9
		haema: Haema 1.7.0
		herobrinia: Herobrinia 4.6.1
		hwg: Happiness is a Warm Gun 1.0.15
		ironchest: Iron Chests 1.1.3
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.4.0+1.16.5
		libstructure: LibStructure 1.5
		lithium: Lithium 0.6.6
		magic_mirror: Magic Mirror 1.2.1
		mcda: MC Dungeons Armors 1.5.0
		mcsa: MC Story Mode Armor 2.3.2
		mimics: Mimics 0.1.4
		minecraft: Minecraft 1.16.5
		mm: Manningham Mills 2.2
		moborigins: Mob Origins 1.4.0
		mobropes: Mob Ropes 1.16.4+1.0.2
		mobz: MobZ 2.4.6
		modmenu: Mod Menu 1.16.9
		more_gems: More Gems 1.1.22
		nbtcrafting: NBT Crafting 2.0.17+mc1.16.4
		omega-config: OmegaConfig 1.0.4
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		origins: Origins 0.7.3
		origins-classes: Origins: Classes 1.1.1
		oro_config: OroArmor Config 1.2.0
		patchouli: Patchouli 1.16.4-51-FABRIC
		pehkui: Pehkui 2.2.1+1.14.4-1.17
		phosphor: Phosphor 0.7.2+build.12
		playerabilitylib: Pal 1.2.1
		programmerartinjector: Programmer Art Injector 1.2.1
		pugh_lib: Pugh Lib 1.1.0
		reach-entity-attributes: Reach Entity Attributes 1.1.1
		reborncore: Reborn Core 4.7.3+build.136
		roughlyenoughitems: Roughly Enough Items 5.11.218
		roughlyenoughitems-api: REI (API) 5.11.218
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.11.218
		roughlyenoughitems-runtime: REI (Runtime) 5.11.218
		satin: Satin 1.6.0-nightly.20w48a
		sodium: Sodium 0.1.0
		somnus: Somnus API 0.0.11-1.16.5
		static-content: Static Content 1.0.2-1.16.2
		staticdata: Static Data 1.1.2
		structure-helpers: Structure Helpers 3.0.0
		structurized: Structurized 1.2.0-1.16.5
		tacocraft: TacoCraft 1.5.2+mc.1.16.5
		team_reborn_energy: Energy 0.1.1
		techreborn: Tech Reborn 3.8.4+build.236
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.5
		things: Things 0.1.3
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.6
		torohealth: ToroHealth Damage Indicators 1.16.4-fabric-4
		trapexpansion: Trap Expansion 1.3.2
		trinkets: Trinkets 2.6.7
		unearthed: Unearthed 1.0.5
		voxelmap: VoxelMap 1.10.15
		waila: Hwyla 1.9.22
		waystones: Waystones 2.0.1
		weeping_angels: Weeping Angels Mod 1.0.3
		worldedit: WorldEdit 7.2.5+57d5ac9
		zoob: Monster Of The Ocean Depths 3.0.0
	Patchouli open book context: n/a
	Launched Version: fabric-loader-0.11.6-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics GL version 4.6.0 - Build 26.20.100.7926, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz

**Comment by paulevsGitch** [comment]
The bug is in Fedora rendering (as pointed in logs), I don’t know what causes this issue, but it probably should be reported to Fedora first

**Comment by mcalzoney** [comment]
Ok thank you for pointing this out to me! I guess I missed that.
