### ISSUE TITLE
World corrupted after generating new chunks in Nether

### ISSUE THREAD

**Issue by makosear** [paulevsGitch/BetterNether#369]
After a few moments on walking in a Nether (first time generating the dimension) in a new world, it crashed and corrupted my world. This mod seems to be causing the issue. Is there a way for me to stop this from happening again and / or recovering my world?

java.lang.IllegalArgumentException: Cannot set property class_2746{name=bottom, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{betternether:golden_vine}

https://spigot.pl/paste/?s=GADIibrQh5I1S8sbrUdumf0s-jc1hFGUB4D7JIjfqG7VuQ

**Comment by paulevsGitch** [comment]
This is not relative to BN, one of your mods blocks correct block initialisation

**Comment by makosear** [comment]
Is there a way for me to know which mod causes this?

**Comment by paulevsGitch** [comment]
Looks like it is Hydrogen
