### ISSUE TITLE
Updated wiki page

### ISSUE THREAD

**Issue by skyjay1** [paulevsGitch/BetterNether#37]
I noticed the wiki is incomplete, so I filled it in a little. Please review because I may have made mistakes. Also I skipped some plants because I haven't figured out what they do yet :P

[Plants.txt](https://github.com/paulevsGitch/BetterNether/files/4004554/Plants.txt)

**Comment by paulevsGitch** [comment]
Thank you, some information is missing or is incorrect, but most descriptions are good. I think I will finish plants page myself (this page was started yesterday), maybe add your descriptions.
