### ISSUE TITLE
Wood material shenanigans

### ISSUE THREAD

**Issue by LambdAurora** [paulevsGitch/BetterNether#371]
Hi,

I am working on a mod which one of its goal is to be as compatible as possible. I have then wrote a wood type detection system to automatically register my own blocks and do a lot of data-generation.

To challenge that system I usually grab some mods and launch the game in a dev environment to see if it does work, and it almost worked with Better Nether, it did detected the leaves and the planks, but not the logs.

My detection code checks if a block has its material set to `Material.WOOD` or `Material.NETHER_WOOD`.

[But somehow Better Nether decided to make its own wood material?](https://github.com/paulevsGitch/BetterNether/blob/master/src/main/java/paulevs/betternether/blocks/materials/Materials.java#L11)

I highly recommend to change it to `Material.NETHER_WOOD` to increase compatibility with other mods as this will definitely screw compatibility for quite a few mods, not only mine.

Hope this gets considered.

**Comment by paulevsGitch** [comment]
BetterNether appeared before Nether Update and it uses its own materials, I will change this when I start refactoring

**Comment by paulevsGitch** [comment]
I changed wood type before refactoring, but this will work only on 1.17

**Comment by paulevsGitch** [comment]
As this was implemented and 1.17+ is now the main version I'm closing this
