### ISSUE TITLE
[BUG] Crash on entering or generating any Nether Chunks

### ISSUE THREAD

**Issue by GamingInfinite** [paulevsGitch/BetterNether#374]
![image](https://user-images.githubusercontent.com/52724070/124511648-42c86c80-dd9c-11eb-9bd3-c63c287945a5.png)
This is the mod list I'm using that actively changes anything that could even remotely break something related to this mod.
![image](https://user-images.githubusercontent.com/52724070/124511809-9b980500-dd9c-11eb-9616-f3337e7f5a7e.png)
And this is where it crashed.
TL;DR:
For some reason, the game crashed on generating the nether chunks when it had a golden_vine in it.
There isn't anything else I just felt like putting TL;DR I have no idea what's going on.

**Comment by paulevsGitch** [comment]
One of your mods breaks correct block loading, is your mod list full? Error like this is a common bug with Hydrogen

**Comment by GamingInfinite** [comment]
Can confirm was a bug with Hydrogen/Sodium.  Any idea if the refactor of better nether would fix this, bc my current setup does not run well without these 2 mods.

**Comment by paulevsGitch** [comment]
Looks like for some reason working fix from 1.16 was not transfered to latest version, I'll fix this

**Comment by paulevsGitch** [comment]
Fixed in 5.1.2
