### ISSUE TITLE
Triumph Compatibility

### ISSUE THREAD

**Issue by CalaMariGold** [paulevsGitch/BetterNether#38]
Is there a "Feature ID" for Nether Cities, similar to Nether Fortresses? It would be nice if we could introduce an achievement for discovering a Nether City via Triumph. I assume this would include setting a Feature ID for Nether Cities, but I'm sure there are other ways too.

**Comment by paulevsGitch** [comment]
No, there is no feature ID for cities. Maybe I will add some advancement trigger later, or not, city can be detected by its position.

**Comment by CalaMariGold** [comment]
Would it be too difficult to add a feature ID for cities? It would open up many more possibilities with InControl, too.

**Comment by paulevsGitch** [comment]
Cities use another generation system, so they couldn't have it. However, they can be detected in other ways. As I see, Triumph uses a kind of wrapper around vanilla triggers, maybe it can do the same for mod triggers, this will be better (and proper) way to detect city. I will try to add it, maybe with achievement.

**Comment by paulevsGitch** [comment]
This suggestion is too old, 1.12 is not updating anymore, I will close it.
On 1.15+ Nether Cities have their feature ID
