### ISSUE TITLE
All block has the same tool level because of, again, a missing tag from 1.17

### ISSUE THREAD

**Issue by TBiscuit1** [paulevsGitch/BetterNether#381]
So you might have seen me say that there was a "mineable/tool" tag, but I also said that there is a tag for MINING LEVEL TOO and that one is missing

I can mine Ruby and Cincinnasite with a wood pickaxe, almost sure this is not what it's supposed to be

needs_stone_tools
needs_iron_tools
needs_diamond_tools

Here are the tags (there is none for wood tools since it's default and there is none for netherite level)

Also, y'all might check out Better End too, probably the same problem there

**Comment by paulevsGitch** [comment]
All ores have same level - the same as stone by default, this is not a tag issue

**Comment by paulevsGitch** [comment]
This can be changed in the future
