### ISSUE TITLE
cant locate biomes in Better Nethers

### ISSUE THREAD

**Issue by Julyoso** [paulevsGitch/BetterNether#382]
When i try to /Locate or /Locatebiome, it gives me red texts that it wont let me locate.  anywhere i go, whether its 10000 blocks or 3000 blocks away from where i came from in the nether.

**Comment by paulevsGitch** [comment]
You probably have incorrect biome source, you can check it and correct it if necessary like described [here](https://github.com/paulevsGitch/BetterNether/issues/293)

**Comment by paulevsGitch** [comment]
As this was opened 11 days ago and there is no response I'm closing this
