### ISSUE TITLE
[1.17.1] Nether biomes in overworld

### ISSUE THREAD

**Issue by kwpugh** [paulevsGitch/BetterNether#385]
Using latest version on 1.17.1

the nether jungle biome is in the middle of an ocean.

![2021-07-20_09 25 42](https://user-images.githubusercontent.com/8809210/126380167-cb1bb3f7-c022-4678-a0f4-8fae0f9aac87.png)

spawns occur
![2021-07-20_13 55 18](https://user-images.githubusercontent.com/8809210/126380172-d1d48188-a42a-4b36-aff2-3681523361a6.png)

**Comment by paulevsGitch** [comment]
Fix wrong biome IDs in world/data/fabricDynamicRegistry.dat with NBTExplorer

**Comment by kwpugh** [comment]
Well, thanks anyways, NBTExplorer does run on modern macOS.

**Comment by paulevsGitch** [comment]
You can try to find its alternative, there are other NBT editors

**Comment by paulevsGitch** [comment]
After fixing biome IDs (they probably will be zero) world became normal again

**Comment by paulevsGitch** [comment]
You can also try to create a new world and copy its fabricDynamicRegistry.dat to an old one

**Comment by kwpugh** [comment]
I could find any compatible with macOS 11 Big Sur.  Are you aware of one.

**Comment by kwpugh** [comment]
ok, thanks.

**Comment by paulevsGitch** [comment]
> I could find any compatible with macOS 11 Big Sur. Are you aware of one.

No, sorry
