### ISSUE TITLE
Insane naga spawn rates, config doesn't seem to change anything.

### ISSUE THREAD

**Issue by pionearly** [paulevsGitch/BetterNether#388]
As it says in the title, the moment I get one or two nagas down in the warped forest biome, I immediately get swarmed by 3 to 4 new ones. This doesn't add challenge, merely frustration. I tried changing the biomes.json, it didn't make much of a difference. Are they perhaps set to be 'ambient' creatures instead of monsters? Either way, they're **absolutely bloody everywhere.**

**Comment by paulevsGitch** [comment]
Did you change configs when the game was inactive? You can also disable any mob at all by changing mobs.json

**Comment by pionearly** [comment]
I turned the game off and back on between changes. Even setting min *and* max pack sizes to 0 didn’t change a thing. I ended up disabling nagas entirely in mobs.json which worked fine. Any clue why the mod isn’t reading the biomes.json?

**Comment by paulevsGitch** [comment]
Min and Max group sizes are not values that you need to change if you want to decrease mob spawning, you need to change weight value
