### ISSUE TITLE
Cincinnasite Forge

### ISSUE THREAD

**Issue by Zank82** [paulevsGitch/BetterNether#389]
5.1.3 Forge won't smelt any thing using coal. unless there's a special fuel I'm missing.

**Comment by koshernerd** [comment]
fuel source that I've tried and doesn't work: Lava bucket, gun powder, gun powder block, coal, coal nugget, coal block, blaze powder, blaze rod, firecharge, also placed the forge on top of a campfire, soul campfire, poured lava on top of the forge, and placed the forge in a lava pool. don't know of any other type of fuel source to use??

**Comment by mckean023** [comment]
Yeah, I have the same issue here it can't smelt anything at all and just stays off

**Comment by TwoPointInfinity** [comment]
Bump, I am also having this issue in 5.1.3
Other installed mods include https://pastebin.com/LMqzNCNQ

**Comment by Bullseye55** [comment]
Yep, came here to check if an issue was open on this. Having the no-fuel issue as well for the Cincinnasite Forge.

**Comment by quiqueck** [comment]
Fixed in v5.3.5
