### ISSUE TITLE
Game Breaking Crash on Servers

### ISSUE THREAD

**Issue by CalaMariGold** [paulevsGitch/BetterNether#39]
https://pastebin.com/GnS3wYbC

This occurs after entering the Nether in servers. I have Biomes O Plenty, Ruins, and NetherEx installed, but I suspect that BetterNether is a cause.

Please look into this when you have time, it affects all my players in servers. Thank you!

**Comment by MetalGaming** [comment]
I run the server where this issue was discovered. Attached is the log from the crash

[crash-2020-01-09_17.14.14-server.txt](https://github.com/paulevsGitch/BetterNether/files/4043513/crash-2020-01-09_17.14.14-server.txt)

**Comment by CalaMariGold** [comment]
Fixed by setting tick time in server.properties to -1...
