### ISSUE TITLE
Cincinnasite Shears do not work in dispenser [Edit: Also cincinn shears don't shear pumpkins]

### ISSUE THREAD

**Issue by KingAdam707** [paulevsGitch/BetterNether#390]
Cincinnasite shears don't work in dispensers like normal shears. Normal shears inside a dispenser would shear a sheep infront of it upon activation of dispenser. This is not the case with Cincinnasite shears; upon activation of the dispenser the cincinnasite shears would just drop.

**Comment by KingAdam707** [comment]
Cincinnasite shears also do not work on pumpkins. Normal shears used on pumpkins would make carved pumpkins but cincinnasite shears do not work on pumpkins.

**Comment by paulevsGitch** [comment]
Mojang just hardcoded shears everywhere, I'll fix that

**Comment by KingAdam707** [comment]
> Mojang just hardcoded shears everywhere, I'll fix that

Thank you for your time and effort; also I was wondering if you are putting this fix in 1.17, 1.16 or both? Asking because I play on the 1.16 version

**Comment by Venaf** [comment]
Probably the same issue, but I can confirm they also don't cut tripwires the same way, it still activates the tripwire hook unlike using vanilla shears.

**Comment by quiqueck** [comment]
Fixed in v5.3.5
