### ISSUE TITLE
The custom biomes from the mod wont spawn.

### ISSUE THREAD

**Issue by PedroMeira2006** [paulevsGitch/BetterNether#391]
The world im playing on was created before i added the mod, so i reseted the nether.
when i got in to the nether i used the /locatebiome command with every biome from the mod, none were found, but strutctures, ores, and stalactites did spwan.
I did the same thing with the better end mod, and it worked fine.

none of the other mods we are using changes world gen
Pls help

**Comment by paulevsGitch** [comment]
Fix you biome source like described [here](https://github.com/paulevsGitch/BetterNether/issues/293)

**Comment by PedroMeira2006** [comment]
Ok, i did the steps for corecting the end, but what do i do for the nether, like what do i put insted of "betterend:better_end_biome_source"

**Comment by PedroMeira2006** [comment]
i assume its just betternether:nether_biome_source but just to be sure

**Comment by paulevsGitch** [comment]
For the Nether it will be "betternether:nether_biome_source"
