### ISSUE TITLE
Nether Wart and Mob spawners in Fortresses not spawning 

### ISSUE THREAD

**Issue by GrumpyCatSplat** [paulevsGitch/BetterNether#392]
In 1.17 mobs like wither skeletons and blazes are not spawning. As well no blaze spawners are present. In addition where nether wart planters are supposed to be instead ice plants spawn. This makes getting nether wart impossible which breaks the game making it impossible to do any potion making.

**Comment by paulevsGitch** [comment]
> mobs like wither skeletons and blazes are not spawning

BetterNether don't affect fortresses and their mob spawning, all mobs uses only vanilla spawning mechanics

> ice plants spawn

What are ice plants?
