### ISSUE TITLE
[Balance] Nagas are too powerful for how common they are

### ISSUE THREAD

**Issue by Dual-Iron** [paulevsGitch/BetterNether#398]
Nagas remain a huge threat until you have almost full Protection gear. Despite this, they're extremely common, they shoot from far away, their projectiles cannot be blocked by a shield, and they're extremely persistent. They keep shooting even if their shots can't possibly hit you, so you learn to ignore their shooting sound effect, making them even more unpredictable.

My suggestion is either to make them much less common, or make the effect they inflict much less destructive, like brief `Wither I` and longer `Slowness I`. Warped forests are currently nigh impassable.

**Comment by paulevsGitch** [comment]
This is a new balance after #321

**Comment by Dual-Iron** [comment]
Yeah. Overcompensated a little.

**Comment by mnsnownutt** [comment]
You can go into the config file and adjust the weight for nagas in the biomes.  That is what I did and it made a huge difference.

**Comment by quiqueck** [comment]
5.3.5 adjusted the default spawn rate for Nagas
