### ISSUE TITLE
Soul Sandstone (and derivative blocks) do not share the same attributes of Soul Sand and Soul Soil

### ISSUE THREAD

**Issue by Brun333rp** [paulevsGitch/BetterNether#399]
So basically:

- They can't be used to summon The Wither;
- When ignited, regular Fire is created instead of Soul Fire;
- Walking in Soul Sandstone while using the Soul Speed enchantment doesn't increases the player speed

**Comment by paulevsGitch** [comment]
Sandstone != sand, they shouldn't have same abilities as soul sand and soil, except probably fire

**Comment by Brun333rp** [comment]
I think you are right, because Soul Sandstone has many derivative blocks. but Soul Fire should be a thing for them, and maybe even Soul Speed

**Comment by quiqueck** [comment]
Available in v5.3.5
