### ISSUE TITLE
Specific Plant Density?

### ISSUE THREAD

**Issue by Yourname942** [paulevsGitch/BetterNether#40]
Please add an option to let us decide the chance of specific blocks from spawning: 

I like the block_egg_plant, but they are all over the place. I don't want to reduce the overall density of biomes nor globally reduce everything, but rather only this plant. Thank you.

**Comment by paulevsGitch** [comment]
This is implemented in 1.15 version (not released yet, but will be during this month)

**Comment by Yourname942** [comment]
Will there be a 1.12.2 version?

**Comment by paulevsGitch** [comment]
Probably not, it requires large amount of work.

**Comment by paulevsGitch** [comment]
Now it is implemented in new version
