### ISSUE TITLE
[Feature Request] Nagas and Skulls should share the same attributes as Wither Skeletons

### ISSUE THREAD

**Issue by Brun333rp** [paulevsGitch/BetterNether#400]
Nagas and Skulls are closely similar (probably related) to Wither Skeletons and The Wither, they even inflict the wither effect when attacking (except for Skulls, perhaps for balance reasons). So because of this, the following attributes should be applied to them:

- Being immune to the Wither effect. While Nagas already are immune to it, Skulls aren't;
- Being able to spawn on Wither Roses. Not sure if this already applies to them, but either way I'm putting it here;
- Attacking the same mobs that are targeted by Wither Skeletons. This includes: Piglins, Piglin Brutes, Iron Golems and Baby Turtles;
- Being attacked by Wolves, since they are skeletal mobs;
- Retaliating when attacked by other mobs, since for some reason they don't;
- Making the same noises when indle or damaged (while retaining the unique noises they already make).

**Comment by quiqueck** [comment]
Moving to our Enhancement List.
