### ISSUE TITLE
Nagas are wayy too common 

### ISSUE THREAD

**Issue by rockdender** [paulevsGitch/BetterNether#401]
When i say common I mean way too common. I am stuck in my nether base because I'm in a warped forest biome so I constantly have around 10 - 20 naga's outside my nether base. Its a pain if I walk out for 2 secs I'm almost dead you cant even shield the attacks. When I kill the horde another horde just spawns again its just a loop. its easy wither skulls but what's the point if I cant even get blaze rods to the end. yeah I would suggest nerfing the spawn rate. 
(I have no idea how to change the spawn rate I'm not a coder I just made this GitHub account just for this)

**Comment by paulevsGitch** [comment]
You can edit spawn in the config

**Comment by rockdender** [comment]
> You can edit spawn in the config

I have no idea how

**Comment by paulevsGitch** [comment]
Open **/config/betternether/biomes.json** with text editor and edit mob spawn groups, exmple:

**Before:**
```
"naga": {
	"weight[def: 20]": 20,
	"min_group_size[def: 2]": 2,
	"max_group_size[def: 4]": 4
},
```

**After:**
```
"naga": {
	"weight[def: 20]": 1,
	"min_group_size[def: 2]": 1,
	"max_group_size[def: 4]": 1
},
```

**Comment by paulevsGitch** [comment]
Each biome has its own spawn groups

**Comment by rockdender** [comment]
thanks
