### ISSUE TITLE
Blazes Won't Drop Rods

### ISSUE THREAD

**Issue by SleepySagittarius** [paulevsGitch/BetterNether#404]
My friends and I play on the server with the origins mod, better end, better nether, and vanilla plus biomes mods. My friends found a fortress and blazes, but no matter what, blazes won't drop anything. Is this because of the better nether mod?

**Comment by paulevsGitch** [comment]
BetterEnd doesn't change vanilla mob drops, probably you just have a bad luck as blazes not always drop rods.
If there is a pyramid near and blaze are from pyramid (and not from fortress) - they have a custom loot table and they are created with custom spawners (without vanilla modification)
