### ISSUE TITLE
[Enhancement] Add hoglins into variants of vanilla biomes

### ISSUE THREAD

**Issue by MonsterTrex** [paulevsGitch/BetterNether#405]
I've been playing with this mod for several days now and noticed that zero hoglins are spawning? I see the Naga spawning like crazy all around the place. I'm using BetterNether 5.1.3 for Minecraft 1.17.1. I would fix this myself but I can't find a config which allows the spawning of hoglins to be adjusted or changed.

**Comment by paulevsGitch** [comment]
Hi, hoglins spawns only in crimson forests, this is a vanilla behaviour

**Comment by MonsterTrex** [comment]
Ah I just checked. The nether biome I thought was the crimson forest, was a crimson pinewood. I didn't really notice much of a difference really visually from what I usually saw in crimson forests
