### ISSUE TITLE
Crash when loading into new world, Connection Lost

### ISSUE THREAD

**Issue by sereneking** [paulevsGitch/BetterNether#411]
Howdy! I have a Fabric pack that I am making and am running into an issue when I add BetterNether (I also added BetterEnd and got the same issue) to it, I can no longer create single player worlds as it will get through preparing the world, but when it goes to load you in it instantly kicks me and says connection lost. It then leaves me on the multiplayer world selection. The actual error has something to do with a NBT value being larger than it should. I provided my log at the bottom. The pack runs just fine with no crashes or issues prior to me adding BE\BN. If there is something I am missing please let me know.

Here are the versions of the Core\API mods in the pack. 

Architectury API | 2.5.57
BCLib | 0.3.1
Cloth Config API | 5.0.38
Cloth API | 2.0.54
Fabric API | 40.00
Fabric Langauage Kotlin | 1.5.30
GeckoLib | 1.7.1
Patchouli | 1.17.54
Trinkets | 3.0.4
Balm | 1.3.0
Reese's Sodium Options | 1.2.0
Indium | 1.0.0
Better Beds | 1.2.0
Custom Fog | 1.6.0
Dynamic FPS | 2.0.5
EntityCulling | 1.3.3
FastChest | 1.20
FerriteCore | 3.0.3
Lazy DFU | 0.1.2
Lithium | 0.7.4
Smooth Boot | 1.6.5-1.6.0
Sodium | 0.3.2
Sodium Extra | 0.3.4
Flytre | 1.3.7
Attribute Fix | 1.0.3

Here is my log: https://pastebin.com/0wwH6A4A

There are errors in there regarding some recipe issues, but I was told by the mod author that those are fine and will not crash the pack and with that mod removed the issue still occurs.

**Comment by paulevsGitch** [comment]
Hi, the crash issue is too large NBT file:
> Encountered exception while handling in channel with name "fabric:registry/sync"

Looks like one of your mods try to send too large file via packet or have wrong NBT file

There are also some bugs like this:
> Couldn't parse loot table deepslatecutting:blocks/deepslate_slab
> Expected name to be an item, was unknown string 'deepslatecutting:deepslate_slab'

This means that one of your mods try to add/parse loot tables that are missing or have links to missing content.
So, this sounds like external mod bug, you can try to disable mods to find this one and then report to its authors

**Comment by sereneking** [comment]
Why would the too large NBT issue only happen after adding only BE\BN?

**Comment by sereneking** [comment]
I am going through and adding all my mods in one by one now to see what is causing it.

**Comment by sereneking** [comment]
Ok so I discovered that the issue is actually related to the number of blocks. When I remove the Chipped Mod it all works fine and they have a fix for using the XL Packets mod and that fixed the issue.
