### ISSUE TITLE
Player position on map of the nether does not update

### ISSUE THREAD

**Issue by JonnyOnSeSocks** [paulevsGitch/BetterNether#412]
I am playing 1.17.1 and have tested this with only betternether 5.1.3 and fabric api 0.40.0+1.17 / fabricloader 0.11.6 added.

When I use an empty map in the nether, the terrain is filled as I move around like in the overworld but the player position is stuck where the map was created and does not update anymore.

**Comment by quiqueck** [comment]
This will be fixed for the 1.18 releases
