### ISSUE TITLE
(1.16.5) Nether not accessible

### ISSUE THREAD

**Issue by Arymona** [paulevsGitch/BetterNether#414]
This happens while i try to enter the nether, when you stand on the portal in the overworld, the loading screen never shows up, i tried to destroy the portal and re-build it somewhere else, re-lighting it, downloading again the mod, but nothing happens. This happens only in this world, because in other saves it works normally. 

https://user-images.githubusercontent.com/90572773/132998693-a9a65a3a-e0b7-4fa6-9b4b-cb65bfe56f7d.mp4

**Comment by paulevsGitch** [comment]
You need to fix your dimension entry, it is missing. Here is a [small tutorial](https://github.com/paulevsGitch/BetterEnd/wiki/Tutorials#how-to-fix-missing-end-dimension), for the Nether it will be the same. Biome source for the Nether will be "betternether:nether_biome_source"
