### ISSUE TITLE
Suggestion: expand nether roof to 256

### ISSUE THREAD

**Issue by Trinsdar** [paulevsGitch/BetterNether#418]
I think the nether should generate terrain all the way to 256 instead of only going to 128, and it could be a config

**Comment by Toma400** [comment]
If it is disabled by default, then why not. But I'm definitely against it as a mandatory feature.

**Comment by gglobensky** [comment]
Having the option to raise it to 196 would be a good middle ground for those who like setting up farms on the Nether roof.

**Comment by quiqueck** [comment]
There is a Datapack (Amplified Nether, https://www.curseforge.com/minecraft/mc-mods/amplified-nether) for 1.18
