### ISSUE TITLE
Redstone in the nether

### ISSUE THREAD

**Issue by Sinogard** [paulevsGitch/BetterNether#419]
I was looking for a way to find Redstone in the nether as right now you can basically survive in the nether as your only dimension except I can't find Redstone. I think it would be really cool if we could cook something or that magma bug could drop it.  Just a suggestion.

**Comment by paulevsGitch** [comment]
> that magma bug

Magma bug?

**Comment by Sinogard** [comment]
oh its called a skull. I thought it looked like a magma beetle. lol sorry for the confusion.

**Comment by quiqueck** [comment]
Fixed in v5.3.5
