### ISSUE TITLE
Gen problem

### ISSUE THREAD

**Issue by Sedniel** [paulevsGitch/BetterNether#422]
Hi, i've just installed Better nether and it open and all... But the only thing that i got is stalactite and stalagmite... There are no plants, no nature at all...

Why there aren't all of what present in the youtube video ?

:(

**Comment by paulevsGitch** [comment]
Fix your biome source like described [here](https://github.com/paulevsGitch/BetterNether/issues/293)

**Comment by Sedniel** [comment]
I'm sorry... Ican't find the level.dat as asking in your guide...

**Comment by paulevsGitch** [comment]
It is in your world folder

**Comment by Sedniel** [comment]
How do i find my world folder ?

**Comment by Sedniel** [comment]
When i'm opening NBTExplorer, I'm facing all of my world created... Is it what i should have ?

**Comment by Sedniel** [comment]
![Capture](https://user-images.githubusercontent.com/92250415/136690775-59e5f134-4033-49ad-ab2c-274f9bae67d7.PNG)

**Comment by paulevsGitch** [comment]
You need to open only level.dat, not the whole worlds folder. Please, follow instructions on wiki

**Comment by Sedniel** [comment]
I found how to fix it and it's just amazing :) Thanks a lot ;)
