### ISSUE TITLE
Suggestion: Crafting recipe for Blue Obsidian

### ISSUE THREAD

**Issue by Mandalorian007** [paulevsGitch/BetterNether#432]
Blue obsidian is a pretty unique and awesome block. It would be great if it could be produced in bulk leveraging some kind of crafting option with obsidian and another farming resource. Piglins can provide renewable obsidian so it would be great to make this renewable as well.

**Comment by quiqueck** [comment]
I will add them (and the crying/weeping variant) to the loot tables for bartering and chests

Here are some other random thoughts:
- We could randomize the portals that are generated on "the other side" to be either blue or purple
- Water+lava could result in different kinds of obsidian (depending on depth or wether or not the sky is visible above the block? would that make sense?)
- I was thinking about baking obsidian -> crying -> weeping in the cin-forge
- I don't want it to be another block we just dye from purple to blue. I think that is boring :D
- We could use the drip-stone mechanic to drain the red from the purple ones to make the blue
- We could do some copper like aging, but only if the block is covered in soulsand (or something else)

**Comment by Mandalorian007** [comment]
The baking idea is really interesting 🤔 

Nether lapis is a thing so maybe the idea of something like the endstone smelter could be cool. Just like how iron and ender dust are "fused" for terminite. We could "fuse" something into the obsidian which would create the new blocks.

Maybe:

black apple + obsidian =  crying obsidian 
lapis/nether reed + obsidian = blue obsidian

For obsidian generation maybe if it was generated next to a certain block? That way farms could be made out of it. I know a few people who really like the obsidian options in this pack and would love to be able to acquire it in bulk

**Comment by quiqueck** [comment]
Hm, so maybe if the lava is above souldsand (because it burns blue) it will generate blue obsidian

**Comment by Mandalorian007** [comment]
That is an awesome idea!

**Comment by quiqueck** [comment]
Forgot to mention the issue in the commit, so this adds the blue-obsidian from lave above souldsand/stone 98a265c59abe857306c416143b8886df0a0829ea

**Comment by Mandalorian007** [comment]
Nice!!!
