### ISSUE TITLE
Bug: Cannot shift click ender pearls into ender dust in anvil

### ISSUE THREAD

**Issue by Mandalorian007** [paulevsGitch/BetterNether#435]
![image](https://user-images.githubusercontent.com/3373692/140386470-67b8835d-e350-4ca5-ab5d-90004a027ac8.png)

When using a normal anvil with an aeternium hammer and you attempt to shift click to fully craft the ender pearls it "glitches" the ui and only crafts one.  The expected behavior was that shift click should consume the 16 ender pearls and produce 16 ender dust.

Example of UI aft shift click:
![image](https://user-images.githubusercontent.com/3373692/140386743-2bb4825c-032e-4e96-b55b-9741d5bb2261.png)

if you click anywhere on the ui again it "resets" to only having crafted one:
![image](https://user-images.githubusercontent.com/3373692/140386853-c4bd3c2b-f07c-47b3-b9e1-db72ccafa709.png)

**Comment by quiqueck** [comment]
I am probably missing something here, so I am sorry for being blind here. But isn't that supposed to be an issue for BetterEnd?

**Comment by Mandalorian007** [comment]
Oh dang it you're right I opened this is the wrong place. I'll get this shifted over and closed out shortly

**Comment by Mandalorian007** [comment]
Okay moved the issue to:
https://github.com/paulevsGitch/BetterEnd/issues/339
