### ISSUE TITLE
world fix

### ISSUE THREAD

**Issue by AmonRay** [paulevsGitch/BetterNether#436]
after upgrading better-nether from 5.3.5-1.17.1 to 5.3.7-1.17.1, when loading the world, I am prompted to run "fixes", but apparently they do not work. Because every time you start the world, this window pops up again and again.

https://pastebin.com/VMfxGnKr

Any ideas?

**Comment by paulevsGitch** [comment]
Hm, this can happen if level.dat is locked for modification, but I neves see this before, looks like it require tests. Can you please send your level.dat from world folder?

**Comment by AmonRay** [comment]
[level.zip](https://github.com/paulevsGitch/BetterNether/files/7488601/level.zip)
sure

**Comment by quiqueck** [comment]
Could you also please send this file: playerdata\aa8d382d-dd4d-43c5-98f7-69d7298012a2.dat
Judging from the log, it also looks like this file could not be loaded (says currupted nbt)

**Comment by AmonRay** [comment]
[aa8d382d-dd4d-43c5-98f7-69d7298012a2.zip](https://github.com/paulevsGitch/BetterNether/files/7491032/aa8d382d-dd4d-43c5-98f7-69d7298012a2.zip)

**Comment by AmonRay** [comment]
updated to 5.3.8, I saw u added some additional logging. Probably it'll help u

https://pastebin.com/UtJweT7q

**Comment by quiqueck** [comment]
Thanks for the files. 

Looks like those player files are unexpectedly not in a compressed format. Just for our info, did you edit your level outside of Minecraft at some point?

The next Version of BCLib will ship with a fix for your Problem. Unfortunately, until then there is not much you can do (except re-saving those files with an external editor as compressed nbt).

**Comment by AmonRay** [comment]
> Looks like those player files are unexpectedly not in a compressed format. Just for our info, did you edit your level outside of Minecraft at some point?

yep, I used Amulet to move some chunks between worlds

OK, thanks. Waiting for release

**Comment by quiqueck** [comment]
Should work with latest BCLib (0.5.0) and BetterNether (5.3.9)
