### ISSUE TITLE
[Bug] composter can be filled with empty hand

### ISSUE THREAD

**Issue by MSandro** [paulevsGitch/BetterNether#442]
### What happened?

I can click the minecraft composter with empty hand to fill it up.
I am not sure, the issue can be reproduced with BetterEnd too.

### BetterNether

5.3.10

### BCLib

0.5.1

### Fabric API

0.42.1

### Fabric Loader

0.11.7

### Minecraft

1.17.1

**Comment by quiqueck** [comment]
Thanks for reporting, I'll have a look.

**Comment by MSandro** [comment]
![image](https://user-images.githubusercontent.com/10937159/141773201-2bf51151-0e42-4417-a504-9720d4a3a022.png)
I've now tested it in a clean installed instance and can reprodice this issue there too.

**Comment by MSandro** [comment]
same can be confirmed with this settup:
![image](https://user-images.githubusercontent.com/10937159/141773964-7380724e-14f9-427d-b5e8-85bb0362d960.png)
but if I install just BcLib it doesn't cause this issue.

**Comment by quiqueck** [comment]
It is fixed in BetterNether 5.3.11, and will be fixed in the next Version of BetterEnd.

**Comment by MSandro** [comment]
> It is fixed in BetterNether 5.3.11, and will be fixed in the next Version of **BetterEnd**.
Will the BetterEnd update be released this week?

**Comment by quiqueck** [comment]
Yes

**Comment by quiqueck** [comment]
Fixed in BE 0.12.3
