### ISSUE TITLE
[Bug] BCLib: "Errors while fixing world" screen, also some missing blocks

### ISSUE THREAD

**Issue by ChristopherJ123** [paulevsGitch/BetterNether#445]
### What happened?

I was trying to upgrade my world to the newest version of BCLib, BE&BN, then i got this weird error screen. I could still load the map but noticed that some blocks are missing (which includes: reeds blocks variants, nether wart logs, stripped nether sakura logs, etc). This world was once a server with a lot of mods and people in it (fabric 1.16.5).

Error Screen
![unknown](https://user-images.githubusercontent.com/86960084/142903937-4d136de7-3158-41b1-baa6-2f6e1bb46e36.png)
:

Missing blocks:
![2021-11-20_22 19 17](https://user-images.githubusercontent.com/86960084/142904010-dd0ac5cd-9119-4aff-a92a-25dd5dd45d26.png)
![2021-11-20_22 19 22](https://user-images.githubusercontent.com/86960084/142904022-05f6063e-3f0a-4b4e-a74b-e69b8ec5828c.png)
![2021-11-20_22 19 28](https://user-images.githubusercontent.com/86960084/142904027-0c38f993-7fc4-4d9f-94c0-763ad8761392.png)

Logs:
[latest.log](https://github.com/paulevsGitch/BetterNether/files/7583079/latest.log)

### BetterNether

5.3.11

### BCLib

0.5.1

### Fabric API

0.42.1

### Fabric Loader

0.11.7

### Minecraft

1.17.1

### Relevant log output

```shell
[latest.log](https://github.com/paulevsGitch/BetterNether/files/7583079/latest.log)
```

### Other Mods

```shell
- Better End 0.12.2
- Eden Ring 0.1.3
- Worldedit 7.2.7
- Optifabric 1.11.20
- Optifine 1.17.1_HD_U_G9
```

**Comment by quiqueck** [comment]
Thanks for opening the issue.

Could you please send us one of the playerdata-files (like `saves\BN BE main world\.\playerdata\e7118f0c-c6bd-436f-ba6a-51ec77256eec-8370623348579193098.dat`). Somehow there seem to be problems working with those.

**Comment by ChristopherJ123** [comment]
> Thanks for opening the issue.
> 
> Could you please send us one of the playerdata-files (like `saves\BN BE main world\.\playerdata\e7118f0c-c6bd-436f-ba6a-51ec77256eec-8370623348579193098.dat`). Somehow there seem to be problems working with those.

Here, i place some of it on a zip file, let me know if i need to do more.
[playerdata.zip](https://github.com/paulevsGitch/BetterNether/files/7587938/playerdata.zip)

**Comment by quiqueck** [comment]
No, that is perfekt. Thank you!

**Comment by quiqueck** [comment]
I did some testing, and while I can open those player files in an external nbt editor, I can not open them using the game APIs. So my guess here, is that those are somehow corrupted.

Are the ones you sent active players in the world?

**Comment by ChristopherJ123** [comment]
Alright, i will try that, thanks!

**Comment by ChristopherJ123** [comment]
It takes a long time to patch the world now for some reasons, probably because of the huge save file. Do you perhaps know how to only load the first 1000 blocks or 100 chunks from the spawn x, z(0, 0)? While deleting the rest of the chunks or something to reduce the huge save file..
![image](https://user-images.githubusercontent.com/86960084/143670286-4e89a7c9-104b-4302-80bf-7574bbacfddf.png)

**Comment by paulevsGitch** [comment]
> Do you perhaps know how to only load the first 1000 blocks or 100 chunks from the spawn x, z(0, 0)?

You can move all far world regions to a separate folder (from world/region) except regions that require fix, and then move them back. Regions with numbers from -2 to 1 will cover central area with 1024 block "radius".

> 1000 blocks or 100 chunks

1000 blocks will be ~63 chunks

**Comment by ChristopherJ123** [comment]
Hello, for some reason in the middle of upgrading i got this error screen... Any ideas.?
![image](https://user-images.githubusercontent.com/86960084/144440460-71c2ae8c-9a92-41b5-847c-3c0766dd0496.png)

**Comment by ChristopherJ123** [comment]
Ci

> Hello, for some reason in the middle of upgrading i got this error screen... Any ideas.? ![image](https://user-images.githubusercontent.com/86960084/144440460-71c2ae8c-9a92-41b5-847c-3c0766dd0496.png)

Could be because i had an electric outage while upgrading the world just before this.. Or i might have deleted the chunks incorrectly from the region folder

![image](https://user-images.githubusercontent.com/86960084/144441657-568b1ec1-15c8-4dbb-96eb-3834cb26035e.png)

**Comment by paulevsGitch** [comment]
> Hello, for some reason in the middle of upgrading i got this error screen... Any ideas.?

Looks like this region file is corrupted

**Comment by quiqueck** [comment]
Did you manage to get the world fixed?

**Comment by quiqueck** [comment]
I am closing it for now. If you need help or have new infos, please re-open the issue.
