### ISSUE TITLE
[Bug] No spawn eggs in BetterNether 1.18

### ISSUE THREAD

**Issue by RavioliCreeper** [paulevsGitch/BetterNether#447]
### What happened?

The actual mods are in the game. However, there aren't any spawn eggs.

Steps to reproduce:
1. Create a world in creative mode with this mod installed
2. Go into the creative inventory
3. Search spawn egg
4. See how there are no BetterNether spawn eggs

### BetterNether

6.0.1

### BCLib

1.0.1

### Fabric API

0.44.0

### Fabric Loader

0.12.8

### Minecraft

1.18

**Comment by quiqueck** [comment]
Should be fixed in 6.0.2 and 5.3.14
