### ISSUE TITLE
[Bug] Structure cut off at Chunkboarder

### ISSUE THREAD

**Issue by Joulanh** [paulevsGitch/BetterNether#448]
### What happened?

Seed:7261508783926493649
Location: 0 / 1200
![2021-12-05_22 01 34](https://user-images.githubusercontent.com/80494384/144764524-bd19089d-d81e-45bb-820f-632f6b68d5c2.png)
![2021-12-05_22 01 40](https://user-images.githubusercontent.com/80494384/144764563-51d4d48d-1305-4ec8-9842-e1a6272432bc.png)

### BetterNether

6.0.1

### BCLib

1.0.2

### Fabric API

0.34.1+1.18

### Fabric Loader

0.12.8

### Minecraft

1.18

**Comment by paulevsGitch** [comment]
This is Minecraft vanilla bug related to async chunk generation. You can see it in vanilla structures too, like trees. It is impossible to fix

![image](https://user-images.githubusercontent.com/17707380/144774723-b306cff7-c2cd-4933-9856-810d19f34f57.png)
