### ISSUE TITLE
[Bug] Spawners dont spawn enemies 

### ISSUE THREAD

**Issue by Joulanh** [paulevsGitch/BetterNether#449]
### What happened?

Spawners in the nether have no enemy type set and spawn no enemies.
Difficulty: Normal
![2021-12-05_23 00 57](https://user-images.githubusercontent.com/80494384/144765607-2c9d4dae-4ec6-40f6-bf36-c5aff8f07611.png)

### BetterNether

6.0.1

### BCLib

1.0.2

### Fabric API

0.35.1+1.18

### Fabric Loader

0.12.8

### Minecraft

1.18

**Comment by paulevsGitch** [comment]
Please don't manually assign tags for issues

**Comment by Joulanh** [comment]
I just filled out your form. It assigned the tag automatically.

**Comment by paulevsGitch** [comment]
Hm, looks like the tag is always applied to any report, well, in this case take my apologies

**Comment by quiqueck** [comment]
Should be working in 6.0.2 (for new generated structures, existing ones are not fixed). If there are still issues, please reopen this issue.
