### ISSUE TITLE
Bug with Walls texture

### ISSUE THREAD

**Issue by Merapyc** [paulevsGitch/BetterNether#45]
Hi, in the last version of your mod (2.0.0) for the last nether snapshot, texture of cincinnasite and bone walls are break.
![2020-02-09_21 43 10](https://user-images.githubusercontent.com/44411030/74109618-41821880-4b85-11ea-9cce-f7d92240517a.png)
Btw, i like your mod ! :)

**Comment by paulevsGitch** [comment]
It is known bug

**Comment by paulevsGitch** [comment]
Fixed
