### ISSUE TITLE
[Bug] Nightmare Texture bug

### ISSUE THREAD

**Issue by TNSGJones** [paulevsGitch/BetterNether#453]
### What happened?

A bug happened!
Nightmares texture issue if you're not using shaders.
![image](https://user-images.githubusercontent.com/82211679/144944580-cf413eee-516c-47ff-8c71-bba13c0103ea.png)

### BetterNether

5.3.12

### BCLib

0.5.5

### Fabric API

0.44.0

### Fabric Loader

0.12.4

### Minecraft

1.17.1

**Comment by quiqueck** [comment]
could you please post your logs?

**Comment by TNSGJones** [comment]
Yeah sorry, the last time i tried to post it, github said it was too long
[2021-12-06-7.log](https://github.com/paulevsGitch/BetterNether/files/7664801/2021-12-06-7.log)

**Comment by quiqueck** [comment]
I don't see any specific error from betternether or bclib. Maybe I don't see it, so why did you think this issue is caused by betternether? 

From the logs I'd assume that there is a problem with iris/sodium or the loaded shaderpack. All of them could cause blank textures. There is a message about a missing texture, that makes me think that it is not the shaders, but a problem with iris/sodium. Could you maybe try without sodium-extras?

Sorry if I missed something obviously related to betternether...

**Comment by TNSGJones** [comment]
Ah, sorry, seems like my original description was removed as well.

I have been running a server for a couple of months now, and today i updated a couple of mods to celebrate that the server theme was up for a few months. the following mods got updated:

- BetterNether
- BetterEnd
- GoFish
- Squirrels
- The Graveyard

Since the update today, while not using shaders the horses are just white. I thought that it might had to do with better nether since its one of the mods that got a major update ( from 5.1.3 to 5.3.12 ). After some fiddling around I thought that I would ask here. 

I have removed Sodium Extra's, which has fixed some major issues I was having, but the horses still are white without shaders.

Without shader
![huge_2021-12-07_04 12 40](https://user-images.githubusercontent.com/82211679/144960092-1fee0c58-a0c1-4abf-b41b-e9a61ac8e0f7.png)
. 
With BSL Shaders
![2021-12-07_04 20 10](https://user-images.githubusercontent.com/82211679/144960216-f94d3d97-c9b1-4cb3-b6de-122400cc5509.png)

If you really think that it's not at BetterNether's fault, then I will trust you on it and will look further. Thank you for taking your time to reply though!

**Comment by paulevsGitch** [comment]
BetterNether don't change entity rendering, it will not affect any entities from vanilla or other mods. Looks like this is a bug of another mod that changes graphics. And looks like there you have bugs with leaf rendering (on your screenshots they are opaque, but they should be transparent)
