### ISSUE TITLE
BetterNether doesn't allow nether build limit above 256

### ISSUE THREAD

**Issue by djmrFunnyMan** [paulevsGitch/BetterNether#455]
In vanilla 1.18 minecraft you can set the nether build limit to whatever you want, but using better nether will ignore the dimension_type folder not allowing you to build above y255
For example heres a modified amplified nether datapack (that puts the nether ceiling at 255 instead of 127)  modified to allow build limit to 384, in vanilla you have an extra 128 blocks above bedrock to build up to y384 but when using better nether you cannot build above 25
[amplified-nether-e3360.zip](https://github.com/paulevsGitch/BetterNether/files/7670397/amplified-nether-e3360.zip)
![2021-12-07_18 08 27](https://user-images.githubusercontent.com/68905776/145077134-d723aaf5-7fd7-4878-9366-b78578ca75a0.png)

5

**Comment by paulevsGitch** [comment]
BN doesn't change how datapcks work, this just means that AmplifiedNether don't give any extra space above 256 world height

**Comment by djmrFunnyMan** [comment]
did you read what I said, this is a version of AmplifiedNether that goes up to 384 and it works in vanilla but using it with BetterNether causes the build limit to stay at 255 regardless of the settings

**Comment by djmrFunnyMan** [comment]
So it's impossible to make better nether suppot build limits above 256 and won't be added in the future?
dang

**Comment by FloridaMen** [comment]
Hi! was wondering what versions you used... I'm attempting to get amplified nether and better nether to play nicely together (1.18.1), but better nether seems to override amplified nether. Strangely enough, if i generate the world first then modify betternether configs, bclib's world repair will end up combining the two and with the correct worldgen.
