### ISSUE TITLE
[Bug] Leaves decay immediately in Upside-Down forest

### ISSUE THREAD

**Issue by FriendlyKnuckle** [paulevsGitch/BetterNether#458]
in mainly the upside down forest biome the leaves of the trees decay because there's no logs near, which looks weird and is a bit dangerous to traverse

**Comment by quiqueck** [comment]
The solution in dev is a quick fix (Will probably appear in 6.0.4) that will stop this from happening. However, we should think about:

- Do we want nether leaves to decay when they are not close to a log
- If so, how do we generate the leaves to fit in with vanilla leaves decay
- Or do we implement our own decay algorithm

**Comment by paulevsGitch** [comment]
> Do we want nether leaves to decay when they are not close to a log

I think yes


> If so, how do we generate the leaves to fit in with vanilla leaves decay

Good solution will be tree branches (if they will be scattered correctly or generated as simple lines from central trunk

> Or do we implement our own decay algorithm

I'm not sure how leaves will work for logs that are above them, so probably yes
