### ISSUE TITLE
[Bug] Crash with Optifacric

### ISSUE THREAD

**Issue by FriendlyKnuckle** [paulevsGitch/BetterNether#459]
### What happened?

whenever i load better nether with amplified nether (im not sure if thats the reason) and optifabric, the game crashes while opening my worlds, doesn't matter if its new or old, it just crashes

The world loads to 100%, then saves and then the game crashes bringing me back to the launcher.

### BetterNether

6.0.2

### BCLib

1.0.2

### Fabric API

0.44.0

### Fabric Loader

0.12.8

### Minecraft

1.18

### Relevant log output

```shell
its a huge list idk what i should add im not a genius
```

### Other Mods

```shell
Amplified Nether
Optifine(just the jar file in the mods folder ofc)
Optifabric
```
[crash-2021-12-10_19.27.10-client.txt](https://github.com/paulevsGitch/BetterNether/files/7695194/crash-2021-12-10_19.27.10-client.txt)
[latest.log](https://github.com/paulevsGitch/BetterNether/files/7695222/latest.log)

**Comment by paulevsGitch** [comment]
Please provide your logs

**Comment by FriendlyKnuckle** [comment]
The actual logs or the crash reports? and if its the normal logs, what part? all of it or just a select bit?

**Comment by paulevsGitch** [comment]
The whole logs before crash. Crash report too

**Comment by FriendlyKnuckle** [comment]
done!

**Comment by FriendlyKnuckle** [comment]
ill add that ive tried both on the normal minecraft launcher and curseforge launcher and both do not work, same thing happens at both

**Comment by paulevsGitch** [comment]
Looks like your Optifine version conflicts with Fabric rendering, can you please try without Optifine?

**Comment by FriendlyKnuckle** [comment]
Without optifine it works fine, ive installed sodium now and it runs like a charm!

**Comment by paulevsGitch** [comment]
This means that this is Optifabric issue and is not related to BetterNether
