### ISSUE TITLE
[Suggestion] make PlayerArmorMixin not removing custom feature renderers

### ISSUE THREAD

**Issue by Diegoddk** [paulevsGitch/BetterNether#46]
PlayerArmorMixin is clearing features making custom features not rendering, it makes the mod incompatible with some other mods that load before better nether.

**Comment by paulevsGitch** [comment]
It can be disabled in the config

**Comment by paulevsGitch** [comment]
I will correct code to remove only vanilla features

**Comment by paulevsGitch** [comment]
Fixed in new version
