### ISSUE TITLE
[Suggestion] [Amplified Nether] Upside-down Forest issues

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#461]
### What happened?

The upside down forest biome has various generation issues with amplified nether:

- Neon equisitum vines stop generating below a certain height. In the screenshot below, the upper layer (about y 165-175) has neon equisitum, while the lower layer (about 135-140) and all layers below it do not.
![2021-12-14_00 55 01](https://user-images.githubusercontent.com/69029346/145966370-1fe8c80e-6cb2-4fa5-9af3-741ab2e770d3.png)

- Small anchor trees also stop generating below a certain height. In the screenshot below, the lower layer (about y 100-115) has no anchor trees, while layers above it do.
![2021-12-14_00 55 12](https://user-images.githubusercontent.com/69029346/145966516-8daa53ab-76e1-414f-a3fc-4306eaea6d9e.png)

- I found this giant anchor tree with no foliage, so it just looks like weird woody vines instead of a tree. Could this be because the topmost part is in a magma land biome?
![2021-12-14_01 02 24](https://user-images.githubusercontent.com/69029346/145966928-562394bc-e84d-44f7-8b5a-b7384f7a249b.png)

### BetterNether

6.0.3

### BCLib

1.0.3

### Fabric API

0.44.0

### Fabric Loader

0.12.11

### Minecraft

1.18.1

### Other Mods

```shell
Amplified Nether 1.0.1
Iris 1.1.3
Sodium 0.4.0-alpha5+build.813
Mod Menu 3.0.0
```

**Comment by quiqueck** [comment]
Everything you describe is on purpose. Vines and smaller trees did never spawn below a certain height. That Height is currently amplified, and we may consider to reduce the min height.

The trees without leaves are an older structure as well, but with amplified they can simply grow larger and are more noticeable. I'll change the topic to suggestion.

**Comment by quiqueck** [comment]
Oh, and the settings are not yet final. So please feel free to suggest changes if you think that something looks odd :)

**Comment by saltyseadoggo** [comment]
Sure thing!
- I feel that the pink ceilings of upside down forest biomes are really barren at the moment below the height at which the equisetum vines generate, which is probably made more visible by the trees not generating down that low either. I suggest letting them generate lower so all layers of the biome are as impressive as the upper ones. The lower areas with no trees are kind of interesting feeling, so you could leave trees out of them if so desired, but the vines definitely break up the monotony of the ceilings.
![2021-12-15_14 38 46](https://user-images.githubusercontent.com/69029346/146276391-bb06a495-2971-4554-81ef-8e091a03ed6a.png)
- Were there ever giant trees *with* leaves? If so, I'm not seeing them, only the leafless ones I mentioned.

**Comment by saltyseadoggo** [comment]
There's also *this thing.* It's one of the leafless giant trees, but, as it goes up, its branches stop curving and form this square of vertical branches, which looks very unnatural. I've seen one more of these in my testing world, but this one is very egregious.
![2021-12-15_14 47 01](https://user-images.githubusercontent.com/69029346/146276804-dfa975ab-11fa-4181-8c76-ea8a3a82bab5.png)
![2021-12-15_14 47 25](https://user-images.githubusercontent.com/69029346/146276817-15ece5ec-7930-4670-826d-2817b089ecc1.png)

**Comment by quiqueck** [comment]
Moving to our Enhancement List.
