### ISSUE TITLE
[Bug] [Amplified Nether](?) Edge biome overkill

### ISSUE THREAD

**Issue by Fireface677** [paulevsGitch/BetterNether#462]
### What happened?

Problem with edge biomes of mushroom forest and wart forest. Main biomes are rare and very small but their edge biomes are big and and just everywhere. Probably compat issue with Starmute's Amplified Nether mod, i did not test BN alone.

### BetterNether

6.0.3

### BCLib

1.0.3

### Fabric API

0.44.0

### Fabric Loader

0.12.11

### Minecraft

1.18.1

### Other Mods

```shell
Amplified Nether 1.0.1
Terralith fabric version 2.0.4
```

**Comment by saltyseadoggo** [comment]
I can confirm. In this picture, compare the massive area of mushroom forest edge to the tiny lil sections of mushroom forest.
(picture taken in a world with amplified nether)
![2021-12-15_14 54 58](https://user-images.githubusercontent.com/69029346/146277520-4262fb78-e2f1-40fc-b03e-ff43c0a21c97.png)

**Comment by quiqueck** [comment]
Is that with the latest 6.0.4 version or also 6.0.3. I think Paulevs fixed the size issue in the latest BCLib builds.

**Comment by saltyseadoggo** [comment]
I took that picture with version 6.0.3.

**Comment by paulevsGitch** [comment]
New Hex generator uses relative biome size unlike old Square generator. When it was created I didn't think about staying with Square gen, so now I will implement "legacy" biome size in it
