### ISSUE TITLE
[Suggestion] Should magma land spikes face different ways?

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterNether#464]
### Description

All of the obsidian spikes in the magma land biome face the same way. I'm wondering if they would look more natural facing different ways.
![2021-12-15_14 53 58](https://user-images.githubusercontent.com/69029346/146303665-070b85b4-6bd8-463f-9dcf-162f6075d394.png)

(this picture was taken in a world generated with amplified nether. if this can't be replicated without that mod, it would be a compat bug)

**Comment by paulevsGitch** [comment]
Technically they should, but this rotation bug exists since I coded these spikes some years ago. Technically spikes can be recoded to use modern SDF from BCLib instead of old legacy code

**Comment by quiqueck** [comment]
Moving to our Enhancement List.
