### ISSUE TITLE
[Bug] [1.18.1]  Server  crash on start up

### ISSUE THREAD

**Issue by kwpugh** [paulevsGitch/BetterNether#467]
### What happened?

Using latest BetterNether and BCLib, crash on start up.

latest log:  https://gist.github.com/kwpugh/3bcb8071d82d8efc2949a8e424f92195

### BetterNether

6.0.5

### BCLib

1.1.2

### Fabric API

0.44.0+1.18

### Fabric Loader

0.12.12

### Minecraft

1.18.1

**Comment by RawPineapple** [comment]
Encountered same issue as well. Server crashed with only BetterNether, BCLib and Fabric API installed, so not a conflict with other mods.

**Comment by quiqueck** [comment]
I'll push an update soon

**Comment by quiqueck** [comment]
Fixed in 6.0.6, thanks for reporting :)
