### ISSUE TITLE
Use of java.awt.Color causes crash when running on macOS

### ISSUE THREAD

**Issue by comp500** [paulevsGitch/BetterNether#47]
In https://github.com/paulevsGitch/BetterNether/blob/master/src/main/java/paulevs/betternether/registers/ItemsRegister.java, `java.awt.Color` is used to register the spawn eggs.

The use of AWT classes in Minecraft mods causes the game to crash when it starts, due to issues with LWJGL 3 and AWT - see more information [here](https://github.com/MinecraftForge/MinecraftForge/pull/5591#issuecomment-470805491). To fix this, `makeEgg` needs to be changed to not use `Color`.

**Comment by paulevsGitch** [comment]
Fixed in new version
