### ISSUE TITLE
Incompatibility with AdventureZ[Bug] 

### ISSUE THREAD

**Issue by Indiglowr** [paulevsGitch/BetterNether#471]
### What happened?

 I was able to fix it by disabling adventureZ(as of this it's 1.4.5). seems to be an issue with the blaze guardian and your spawners. I have also posted this to them since I'm not sure which team to tell about the incompatibility
[crash-2021-12-18_14.53.27-server.txt](https://github.com/paulevsGitch/BetterNether/files/7739881/crash-2021-12-18_14.53.27-server.txt)

### BetterNether

6.0.6

### BCLib

1.1.2

### Fabric API

0.44.0

### Fabric Loader

0.12.12

### Minecraft

1.18.1

**Comment by quiqueck** [comment]
Hm, the log does not mention bclib or betternether. I may be blind (sorry if I am), but as far as I can tell, adventureZ is adding entities to spawners on the wrong thread. Did you post this to the adventureZ team?

**Comment by Indiglowr** [comment]
I did send this to them as well. I think i saw something about spawners and equated it to better nether due to a bug i also had with better nether and disable custom worlds advice and a previous bug report on here about the same issue. the new update for adventureZ seems to have fixed the issue though.

**Comment by quiqueck** [comment]
Thanks for reporting back to us, glad it is fixed now :)
