### ISSUE TITLE
[Bug] Unobtainable block in Nether Jungle

### ISSUE THREAD

**Issue by RawPineapple** [paulevsGitch/BetterNether#476]
### What happened?

I found this unobtainable block 'block.betternether.stalagnate_trunk' in Nether Jungle, which does not show up in Creative Inventory nor /give command. It isn't in localization files either.
![2021-12-20_17 13 19](https://user-images.githubusercontent.com/95847271/146743441-e876a2d5-5c64-4485-8259-069d83e047f6.jpg)

### BetterNether

6.0.7

### BCLib

1.1.3

### Fabric API

0.44.0

### Fabric Loader

0.12.12

### Minecraft

1.18.1

**Comment by paulevsGitch** [comment]
It is intended behaviour
