### ISSUE TITLE
(1.12) Memory Leak: EventsHandler#server

### ISSUE THREAD

**Issue by Meldexun** [paulevsGitch/BetterNether#478]
When joining a singleplayer world the integrated server instance will be assigned to the `EventsHandler#server` field. After leaving the world and joining a dedicated server the `EventsHandler#server` field will still hold the old value. Thus there will be a `WorldServer` instance in memory which can't be garbage collected.

**Comment by paulevsGitch** [comment]
1.12 is outdated and not supported
