### ISSUE TITLE
Mod texture can't load or load error

### ISSUE THREAD

**Issue by JoinChang** [paulevsGitch/BetterNether#48]
game-version: 20w06a (multi-player)
mod-version: 2.0.0
![7}WK6XH3NWD3YRSH T9%C7G](https://user-images.githubusercontent.com/35451392/74505134-4baf6880-4f31-11ea-878d-291dc32440d3.png)
![76_TSDSXMS7BQ`~I`B}IG0G](https://user-images.githubusercontent.com/35451392/74505193-7994ad00-4f31-11ea-9ccf-3a2f382a6b92.png)
![47PUPPYSPSF57PS}~6E(LSP](https://user-images.githubusercontent.com/35451392/74505210-85806f00-4f31-11ea-970f-737fcd66127d.png)
![($2P9R@}{J){~K0ISB)`7`L](https://user-images.githubusercontent.com/35451392/74505218-8ca77d00-4f31-11ea-9a89-a29cc03b5ba7.png)

**Comment by paulevsGitch** [comment]
Looks like mod list or configs on server and client are different

**Comment by JoinChang** [comment]
What should I do to solve this problem? Should I delete something or others?

**Comment by paulevsGitch** [comment]
You should synchronize mod list and configs with server — copy server configs and mods to client
