### ISSUE TITLE
[Suggestion] Need a way to prevent hydrogen jellyfish from exploding.

### ISSUE THREAD

**Issue by JJSax** [paulevsGitch/BetterNether#480]
### Description

Currently, to my knowledge there is no way to get rid of the hydrogen jellyfish without causing nearby block damage.  If one spawns near your portal, or your nether build, you just have to deal with it.  You can't put water in the nether to prevent the explosion damage, and killing it causes the damage.  

My thought to fix this would be to give it more health and require it to die in one hit. If it takes player damage and doesn't die it will explode.  That way the Mojang idea of "anything negative that happens can be avoided" mindset.  It's hard to say what the health should be on it, but my thought is unenchanted diamond sword or higher can one shot it.  Perhaps a critical hit with an iron sword might work too.  

Other ideas might be giving players the ability to place a block to lure them to one spot before killing them.  This might provide a cool farm ideas.  Probably something either rare or player crafted so a player won't just stumble across a bunch of them gathered randomly at a thing.

Perhaps using some item on them could prevent them from exploding when killing them.  There are plenty of items in this mod to choose from that don't appear to have any use other than aesthetic.    Possibly using a water bucket, or potion of water on them could prevent it too.  Possibly use the types of mold to "infect" it and use that as the lore of the mod. 

Just some ideas so it's not just a lazy suggestion without possible solutions.

**Comment by quiqueck** [comment]
Hm, could be an interesting feature for the nether gear, like the ruby sword...

**Comment by quiqueck** [comment]
Moving to our Enhancement List
