### ISSUE TITLE
Possible terraforged incompatibility?[Bug] 

### ISSUE THREAD

**Issue by Mr-Syntax** [paulevsGitch/BetterNether#483]
### What happened?

everytime i find this amazing structure it will have no enemies :-/ i have sometimes seen piglins being dropped off to the side of the structure when i find it, is the mod incompatible with terraforged? or is it something else in my pack thats messing with it?
https://www.curseforge.com/minecraft/modpacks/chosencraft
thats the pack it happens in.
![image](https://user-images.githubusercontent.com/59544236/147506948-0c3be9e9-cb11-4ffa-8a0a-bcdad9cee172.png)

### BetterNether

1.1.1

### BCLib

0

### Minecraft

1.16.5

### Relevant log output

```shell
its on forge 36.2.0
```

### Other Mods

```shell
363 :-| ofc i dont expect you to debug it i would just be happy to know before doing it if its just a terraforged incompatibility
```

**Comment by paulevsGitch** [comment]
BetterNether is a **Fabric** mod, it don't have Forge version

**Comment by Mr-Syntax** [comment]
oh im sorry i might be playing with a fork of it then :-|
