### ISSUE TITLE
CPU Internal Error (WHEA) and Bad Performance in Nether with BetterNether

### ISSUE THREAD

**Issue by TimmyWithTheBat21** [paulevsGitch/BetterNether#485]
### What happened?

This mod in combo with amplified heights mod gets me performance drops only in the nether (mostly near better nethers endless celling vines). shortly after the perf drop hwinfo reports cpu internal error and i close the game manually. my system is set to all core 4,8 (10850k). i am using shaders (seus renewed with 3080). using iris forke with sodium forke from HyperCubeMC. I only have this issue with this nether mod combo your similar mod better end which also adds a ton of flora to the end - no problem there. and no problem in stresstesting/gaming since inital setup in months. plz help would be great. Minecraft 1.18.1 Fabric

### BetterNether

6.0.8 LATEST

### BCLib

1.2.1 LATEST

### Fabric API

LATEST

### Fabric Loader

LATEST

### Minecraft

1.18.1

### Other Mods

```shell
Amplified Nether
BetterNether
BetterEnd
BcLib
Iris
Sodium
Lithium
Terra
and a tone of smaller Mods
```

**Comment by quiqueck** [comment]
Thanks for reporting. I am not a 100% sure if this is a bug. With amplified installed, BN generates a lot of transparent blocks (veins, leaves). Especially around upside-down forests. BE does not have any similar massive vegetation in such a small space.

Could you maybe try a load-test with upside-down forests disabled (you can change the setting sin bclibs biome config)?

**Comment by TimmyWithTheBat21** [comment]
> Thanks for reporting. I am not a 100% sure if this is a bug. With amplified installed, BN generates a lot of transparent blocks (veins, leaves). Especially around upside-down forests. BE does not have any similar massive vegetation in such a small space.
> 
> Could you maybe try a load-test with upside-down forests disabled (you can change the setting sin bclibs biome config)?

what do you mean load test just running mc and looks if it happens again ?

**Comment by TimmyWithTheBat21** [comment]
oh and by the way can seus renewed shader be a culprit ? this happens most of the time with seus renewed which somehow pushes the viewdistance (i beleive) far beyond the normal  view distance (mc setting staying the same but switching shader seams to "fix" it and with seus i can see muc farther away) ( i also set my vcore to auto now insteadt of offset with 4.8 which gives me more vcore for more stability and dont "seam" to encounter it. (but i got/get weird nether sound effect near lavalakes which always plays right before the whea (from my observation) and i still trying to figure out if some other mod/resource pack is messing with the nether more then it should.

**Comment by quiqueck** [comment]
Does the latest update help with this issue?

**Comment by quiqueck** [comment]
6.0.10 contains several fixes that might help with this issue. Please update and re-open if you still have the same problems.
