### ISSUE TITLE
[Suggestion] Allow to override loot tables for ores from data packs.

### ISSUE THREAD

**Issue by dmoklyakov** [paulevsGitch/BetterNether#486]
### Description

I'm making a custom data pack for my server and discovered I can't change loot tables for ores.
Maybe I'm missing something?
[test_datapack.zip](https://github.com/paulevsGitch/BetterNether/files/7797862/test_datapack.zip)

**Comment by quiqueck** [comment]
Thanks for the suggestion. This should work with the next release of BCLib

**Comment by quiqueck** [comment]
This should be working in 6.0.9. If it does not, please re-open this issue.
