### ISSUE TITLE
[Bug] Possible Crash

### ISSUE THREAD

**Issue by SharkieTV** [paulevsGitch/BetterNether#488]
### What happened?

One of my players have reported this crash. The only relevant thing I could find in the crash is
paulevs.betternether.world.structures.plants.StructureAnchorTreeBranch.updateSDFFrom(StructureAnchorTreeBranch.java:236)

### BetterNether

Better Nether 6.0.8

### BCLib

bclib: BCLib 1.2.1

### Fabric API

Fabric API 0.45.0+1.18

### Fabric Loader

0.12.12

### Minecraft

1.18.1

### Relevant log output

```shell
https://pastebin.com/zAZP83Xw
```

### Other Mods

```shell
Medieval Minecraft [FABRIC[ - 1.18.1 Modpack
```

**Comment by SharkieTV** [comment]
I got told by a friend that its possibly Lithium causing an issue

**Comment by paulevsGitch** [comment]
Looks like it happened in mixin of another mod:
> zmc000$customColors

And looks like it is related to Lithium:
> getChunkLithium

Try to update Lithium, it was probably a source of the issue

**Comment by quiqueck** [comment]
Was this issue resolved with a lithium update?
