### ISSUE TITLE
[Bug] Nether not generating fortress 

### ISSUE THREAD

**Issue by Cetins** [paulevsGitch/BetterNether#490]
### What happened?

I'm trying to find nether fortress but I couldn't find any. I've even checked the exact locations from chunkbase seed app and they weren't generated. All the other mod structures have been generated nicely. I'm adding the nbt tree of the my world in case I've don a mistake for the seed generator text. I'm playing on 1.18.1 java, fabric better minecraft modpack V8.5.
![nbt](https://user-images.githubusercontent.com/69481095/148302561-e0e71b7e-c946-4af0-b304-8179ecd0e90b.jpg)

### BetterNether

v6.0.8

### BCLib

v1.2.1

### Fabric API

0.45.0

### Fabric Loader

0.12.12

### Minecraft

1.18.1

### Other Mods

```shell
better minecraft modpack v8.5
```

**Comment by guessmyname** [comment]
I'm having the same issue as well with same versions except using better minecraft 10.5.

**Comment by quiqueck** [comment]
This should be fixed with the next BCLib update

**Comment by B00MxHartShotx** [comment]
@quiqueck do you have any update on this? i just started a server on bisect hosting to play with some friends using this mod. before i got them in here, i wanted to test some things about the full modpack that i have chosen, but then found no fortresses/bastions

**Comment by quiqueck** [comment]
There are still some fixes and tests I want to implement before we can release the next version. But it should be a matter of days.

**Comment by B00MxHartShotx** [comment]
copy that. could you maybe bump this thread with a message when you do release the fixed version? i'd like to get in and test before i bring the gang in here. also, what is my best option here as far as continuing if we did want to play? just load with betternether not in the mods folder and use vanilla generation in the first several hundred blocks?

side note, i'm testing the nether and the entire dragon platform is just pink/black squares but WTHIT says that the block is end stone. end stone DOES drop when mined

**Comment by B00MxHartShotx** [comment]
all platforms in the end*

**Comment by quiqueck** [comment]
Do you have other mods installed? That texture usually means that I  a block-definition or its assigned textures were not found.

**Comment by B00MxHartShotx** [comment]
i have other mods, but none that mess with the end i don't think. there was a suggested datapack on the BetterEnd curseforge page that i got

**Comment by quiqueck** [comment]
I think that Datapack should not mess with BlockTypes.

In the past (but I it got fixed for the 1.17 releases) performance Mods like Dashloader could cause that behavior. So the mod does not have to be related to the End. Could you maybe copy your ModList here so I can have a look. It still could be an issue with BE...

**Comment by B00MxHartShotx** [comment]
what is the correct way to get such a list for you?

i'd love to help however i can, but this is my first foray into any mod stuff. also, most of the mods that i chose were in the BetterMinecraft Fabric 1.18 modpack

**Comment by quiqueck** [comment]
There should be `logs` folder (in the same folder where your `mods`-folder is located). That should contain a `latest.log` file. The first few lines usually list all the mods/submods that fabric did load.

**Comment by B00MxHartShotx** [comment]
i believe that this is the portion that you're looking for?


[01:32:51] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.12.12
[01:32:52] [ForkJoinPool-1-worker-12/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[01:32:52] [ForkJoinPool-1-worker-13/WARN]: The mod "netherchest" contains invalid entries in its mod json:
- Unsupported root entry "includes" at line 46 column 13
[01:32:53] [main/WARN]: Warnings were found!
 - Mod 'Sodium Extra' (sodium-extra) 0.3.8 recommends version 1.2.3 or later of reeses-sodium-options, which is missing!
	 - You should install version 1.2.3 or later of reeses-sodium-options for the optimal experience.
[01:32:53] [main/INFO]: Loading 221 mods:
	- additionaladditions 3.0.1
	- advanced_runtime_resource_pack 0.2.9 via carrier
	- advancementplaques 1.4.3
	- advancements-enlarger 0.2.4
	- amecsapi 1.3.3+mc1.18-pre1 via backslot
	- animal_feeding_trough 1.0.3+1.18.1
	- architectury 3.4.9
	- attributefix 13.0.4
	- backslot 1.2.4
	- backslotaddon 1.0.7
	- balm-fabric 2.4.1+0
	- bcc fabric-1.0.4
	- bclib 1.2.4
	- beaconoverhaul 1.5.0+1.18
	- beehivetooltips 1.4.1
	- betterend 1.0.0
	- betterf3 1.2.2
	- bettermounthud 1.1.3
	- betternether 6.0.8
	- betterthirdperson 1.6.0
	- blue_endless_jankson 1.2.1 via kyrptconfig
	- blur 2.4.1
	- breakprogress 1.0.1
	- caffeineconfig 1.0.0 via sodium-extra
	- cardinal-components-base 4.0.1 via xp_storage
	- cardinal-components-entity 4.0.1 via xp_storage
	- cardinal-components-item 4.0.1 via xp_storage
	- carrier 1.9.0
	- cavetweaks 1.0
	- chalk 1.2.1
	- chat_heads 0.6.0
	- cherishedworlds 2.0.1-1.18
	- chunky 1.2.164
	- cleancut 1.18-4.0-fabric
	- clienttweaks 7.0.0
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.1.48
	- clumps 8.0.4
	- com_electronwill_night-config_core 3.6.5 via beaconoverhaul
	- com_electronwill_night-config_toml 3.6.5 via beaconoverhaul
	- com_moandjiezana_toml_toml4j 0.7.2 via deepslatecutting
	- connectiblechains 2.0.1+1.18.1
	- consistency_plus 0.4.3+1.18
	- continuity 1.0.3+1.18
	- controlling 9.0.11
	- crawl 0.10.1
	- dawn 3.2.0
	- deathlog 0.2.6+1.18
	- deepslatecutting 1.3.0
	- dragonloot 1.0.10
	- dripstone_fluid_lib 1.1.1 via milk_plus
	- dual_riders 1.0.5
	- dungeons_arise 2.1.49c-fabric
	- dynview 1.18-1.5
	- earthtojavamobs 1.7.4+1.18
	- easymagic 3.2.1
	- elytratrinket 3.0.0-1.18.1
	- endgoblintraders 1.4.2
	- enhanced_attack_indicator 1.0.2+1.18
	- equipmentcompare 1.2.11
	- experiencebugfix 18
	- fabric 0.46.1+1.18
	- fabric-api-base 0.4.1+b4f4f6cdc8 via beaconoverhaul
	- fabric-api-lookup-api-v1 1.5.0+17be577f65 via fabric
	- fabric-biome-api-v1 6.0.1+ded849a965 via fabric
	- fabric-blockrenderlayer-v1 1.1.9+3ac43d9565 via fabric
	- fabric-command-api-v1 1.1.6+3ac43d9565 via fabric
	- fabric-commands-v0 0.2.5+b4f4f6cd65 via fabric
	- fabric-containers-v0 0.1.18+d154e2c665 via fabric
	- fabric-content-registries-v0 0.4.5+6f53a73d65 via fabric
	- fabric-crash-report-info-v1 0.1.8+3ac43d9565 via fabric
	- fabric-dimensions-v1 2.1.9+a1d9bbf565 via fabric
	- fabric-entity-events-v1 1.4.5+6b21378a65 via fabric
	- fabric-events-interaction-v0 0.4.16+bfa23f1765 via fabric
	- fabric-events-lifecycle-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-game-rule-api-v1 1.0.10+3ac43d9565 via fabric
	- fabric-item-api-v1 1.3.0+691a79b565 via fabric
	- fabric-item-groups-v0 0.3.3+3ac43d9565 via fabric
	- fabric-key-binding-api-v1 1.0.8+c8aba2f365 via fabric
	- fabric-keybindings-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-language-kotlin 1.7.1+kotlin.1.6.10
	- fabric-lifecycle-events-v1 1.4.10+c15ca33565 via fabric
	- fabric-loot-tables-v1 1.0.8+3ac43d9565 via fabric
	- fabric-mining-level-api-v1 1.0.3+3ac43d9565 via fabric
	- fabric-mining-levels-v0 0.1.8+b4f4f6cd65 via fabric
	- fabric-models-v0 0.3.3+3ac43d9565 via fabric
	- fabric-networking-api-v1 1.0.18+3ac43d9565 via fabric
	- fabric-networking-v0 0.3.5+b4f4f6cd65 via fabric
	- fabric-object-builder-api-v1 1.11.1+3b82842e65 via fabric
	- fabric-object-builders-v0 0.7.9+3ac43d9565 via fabric
	- fabric-particles-v1 0.2.9+526dc1ac65 via fabric
	- fabric-registry-sync-v0 0.9.0+befed49e65 via fabric
	- fabric-renderer-api-v1 0.4.10+b0b66fc365 via fabric
	- fabric-renderer-indigo 0.4.13+b0b66fc365 via fabric
	- fabric-renderer-registries-v1 3.2.7+b4f4f6cd65 via fabric
	- fabric-rendering-data-attachment-v1 0.3.4+7242e9d765 via fabric
	- fabric-rendering-fluids-v1 0.1.18+3ac43d9565 via fabric
	- fabric-rendering-v0 1.1.9+b4f4f6cd65 via fabric
	- fabric-rendering-v1 1.10.3+6b21378a65 via fabric
	- fabric-resource-conditions-api-v1 1.0.1+13eda06565 via fabric
	- fabric-resource-loader-v0 0.4.11+3ac43d95c8 via beaconoverhaul
	- fabric-screen-api-v1 1.0.7+3ac43d9565 via fabric
	- fabric-screen-handler-api-v1 1.1.11+3ac43d9565 via fabric
	- fabric-structure-api-v1 2.1.0+0a73a6c265 via fabric
	- fabric-tag-extensions-v0 1.2.5+3ac43d95c8 via beaconoverhaul
	- fabric-textures-v0 1.0.9+3ac43d9565 via fabric
	- fabric-tool-attribute-api-v1 1.3.5+fb3b57b465 via fabric
	- fabric-transfer-api-v1 1.5.6+b4f4f6cd65 via fabric
	- fabricloader 0.12.12
	- fancymenu 2.5.2
	- farsight 1.18-1.5
	- ferritecore 4.0.0
	- forgeconfigapiport 3.1.1
	- go-fish 1.4.1-1.18.1
	- goblintraders 1.4.1
	- highlighter 1.1.2
	- horseinfo 0.4.1-1.18
	- iceberg 1.0.38
	- imm_ptl_core 1.2.1 via immersive_portals
	- immersive_portals 1.2.1
	- infusion_table 1.0.5
	- inmis 2.4.0-1.18
	- inventoryhud 3.4.2
	- inventorysorter 1.8.4-1.18
	- iris 1.1.5
	- jankson 4.0.0+j1.2.0 via libgui
	- java 17
	- kirin 1.10.0-beta.2 via presencefootsteps
	- kleeslabs 11.0.0
	- konkrete 1.3.3
	- kyrptconfig 1.3.4-1.18 via inventorysorter
	- lambdynlights 2.1.0+1.17
	- libcd 3.0.3+1.16.3 via dawn
	- libgui 5.1.0+1.18 via additionaladditions
	- libninepatch 1.1.0 via libgui
	- libzoomer 0.3.0+1.17.1 via okzoomer
	- lithium 0.7.7
	- logprot 1.18-1.5
	- lovely_snails 1.0.3+1.18
	- maybe-more-data 1.0.0-1.18 via deepslatecutting
	- midnightlib 0.3.1 via blur
	- milk 0.1.5 via milk_plus
	- milk_plus 2.0.1
	- minecraft 1.18.1
	- minieffects 4.0.0
	- mm 2.3 via crawl
	- modmenu 3.0.1
	- morevillagers-fabric 3.1.1-SNAPSHOT
	- mousetweaks 2.22
	- netherchest 3.1
	- notes 1.0.10
	- okzoomer 5.0.0-beta.3+1.17.1
	- omega-config 1.0.8 via inmis
	- onsoulfire 1.18-1
	- openloader 11.0.3
	- org_anarres_jcpp 1.4.14 via iris
	- org_aperlambda_lambdajcommon 1.8.1 via spruceui
	- org_jetbrains_kotlin_kotlin-reflect 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.1 via fabric-language-kotlin
	- org_joml_joml 1.10.2 via sodium
	- org_quiltmc_quilt-json5 1.0.0 via okzoomer
	- org_slf4j_slf4j-api 1.7.12 via iris
	- oro_config 2.1.0 via cavetweaks
	- phosphor 0.8.1
	- pickupnotifier 3.1.0
	- pistorder 1.4.4
	- presencefootsteps 1.4.0
	- pride 1.1.0+1.17 via lambdynlights
	- puzzleslib 3.1.3
	- q_misc_util 1.2.1 via immersive_portals
	- quickshulker 1.3.3-1.18
	- reach-entity-attributes 2.1.1 via beaconoverhaul
	- replanter 1.3
	- rocks 1.5.2
	- roughlyenoughitems 7.1.390
	- rpgdifficulty 1.0.8
	- satin 1.7.0 via blur
	- seedfix 1.0.0 via terralith
	- shulkerutils 1.0.4-1.18 via quickshulker
	- skinlayers 1.3.1
	- sodium 0.4.0-alpha6+build.14
	- sodium-extra 0.3.8
	- spruceui 3.3.0+1.17 via lambdynlights
	- stonecutter_recipe_tags 2.0.0 via consistency_plus
	- stoneholm 1.4.1
	- terraform-shapes-api-v1 2.1.0 via dawn
	- terralith 2.0.12
	- thonkutil 2.7.0+1.18
	- thonkutil-base 1.5.1+31ad4eb1c8 via thonkutil
	- thonkutil-capes-v1 1.2.2+befce073c8 via thonkutil
	- thonkutil-coords-v1 1.0.8+526fd6e5c8 via thonkutil
	- thonkutil-customization-v1 1.0.3+526fd6e5c8 via thonkutil
	- thonkutil-legacy 1.0.9+6fa117f8c8 via thonkutil
	- thonkutil-modchecker-v1 1.0.0+aebf7ba0c8 via thonkutil
	- thonkutil-potions-v0 1.3.1+befce073c8 via thonkutil
	- thonkutil-trades-v1 1.1.7+d1040ec2c8 via thonkutil
	- toolstats 8.0.1
	- tooltipfix 1.0.4-1.18
	- totw_additions 1.1.0
	- towers_of_the_wild_reworked 2.1.0
	- tradingpost 3.1.2
	- trinketofundying 2.0.1-1.18
	- trinkets 3.1.0
	- universal_ores 1.2.1
	- upgradedshulkers 1.1.1-1.18
	- villagernames 2.0.2
	- voidtotem 1.18.1-1.1.0
	- waystones 2.4.1
	- wmitaf 2.2.0
	- wthit 4.4.1
	- xaerominimap 21.23.1
	- xaeroworldmap 1.19.1
	- xp_storage 1.4.3+1.18
	- yigd 1.2.12

**Comment by quiqueck** [comment]
Yes, thank you very much

**Comment by quiqueck** [comment]
Could you please try if installing Indium does help

**Comment by B00MxHartShotx** [comment]
about the time that you sent this, i got it figured out that either indium was a problem or a missing library. i combed through the list from Better Minecraft again and grabbed indium and, i believe, two libraries. something about that combo definitely got me squared away. i meant to update you but my kids woke and i've been a little wrapped up with them and forgot

i've been loading worlds to see terralith 2.0 as well as betternether/end generation and have been thoroughly pleased with the potential for the world i'll be starting with friends. with the nether fortresses and bastions not spawning, we don't want to load chunks in the nether that could have had those structures in them. if we stay in the overworld only and do not light up any portals (i think as long as we don't go through is the key here), we should be fine to start our world up, right?

we've got a skill point system for leveling and it would benefit us to start as we begin the game with only three hearts and have to level attributes to gain access to tiers of armor/tools/weapons/trading/hearts

**Comment by quiqueck** [comment]
The new version is released now so I'll close this issue for now. If you still have this issue, then please reopen it.
