### ISSUE TITLE
[Bug] Missing Blaze Spawners

### ISSUE THREAD

**Issue by RockStone-God** [paulevsGitch/BetterNether#492]
### What happened?

Blaze spawners are missing from the fortress, I am not sure whether that's supposed to happen or not. Its in version 1.16.5
![2022-01-11_10 02 31](https://user-images.githubusercontent.com/70993337/148881556-de1ac6db-7f5b-4fec-9612-f5aa9afc4bd4.png)
![2022-01-11_10 02 18](https://user-images.githubusercontent.com/70993337/148881560-38f89711-e621-4083-820d-1956d0e31c20.png)

### BetterNether

5.0.7

### BCLib

0.1.45

### Fabric API

0.42.0

### Fabric Loader

0.12.12

### Minecraft

1.16.5

**Comment by paulevsGitch** [comment]
Better Nether doesn't change fortress generation, do you have other mod?

**Comment by quiqueck** [comment]
I'll close this issue for now. If you do have some more feedback for us, please re-open this issue.
