### ISSUE TITLE
BetterNether is installed but not shown in server

### ISSUE THREAD

**Issue by Marconlinus** [paulevsGitch/BetterNether#493]
### What happened?

So, recently after I install BetterNether on my new server it breaks my world.

My Minecraft world gravity is likely glitched (Instead of spacebar to jump it floats me higher as I hold it).
And whenever I enter nether it freezes me there but I can still see mob around and none of the chunks are loaded.

I've tried so many ways that possible to fix this.
(Reinstall server/Use an older version of the mod, BCLib and Fabric API/Delete nether file) but sadly none of them worked.

**NOTE**: I've also turned online mode off to allow my friend who uses a cracked Minecraft to enter the server too.
           And update fabric loader but stills doesn't work.
           
           
           https://user-images.githubusercontent.com/86531136/149137737-3ee811ea-99ce-48a6-afb0-aa720e497f3f.png
           
           
           https://user-images.githubusercontent.com/86531136/149138441-b30387b0-993d-4793-86c0-46990c76a767.mp4

### BetterNether

6.0.8

### BCLib

1.2.2

### Fabric API

0.45.2+1.18

### Fabric Loader

0.12.12

### Minecraft

1.18.1

### Relevant log output

```shell
https://mclo.gs/OIWl9h3
```

**Comment by paulevsGitch** [comment]
Are mods on client identical to server side?

**Comment by Marconlinus** [comment]
> Are mods on client identical to server side?

Nope, I don't have any mods other than BetterNether and its requirements installed.

**Comment by paulevsGitch** [comment]
> Nope

Can you please show your client mod list and server mod list?

**Comment by Marconlinus** [comment]
Client mod list: None (Checked in C:\Users\User\AppData\Roaming\.minecraft\mods)

Server mods ![image](https://user-images.githubusercontent.com/86531136/149523408-372ec2b9-c67b-4722-8815-67297d213407.png)

**Comment by Marconlinus** [comment]
> So, you have mods _server side only_, right?

Yep.

**Comment by Marconlinus** [comment]
> 

I've already tried installed mod on client and it stills doesn't work.

**Comment by paulevsGitch** [comment]
This is not how mods works, they should be both client and server side
