### ISSUE TITLE
Biomes in Nether not Spawning, even after fixes.

### ISSUE THREAD

**Issue by mropitzky** [paulevsGitch/BetterNether#498]
### What happened?

Hello! Ive searching the nether for a long time, and while new mobs and some ores are spawning, none of the new biomes are anywhere to be found. i went into the BCLIB and made the spawn rate higher, and did the biome source fix and neither have worked. im running 1.18.1 

### BetterNether

1.18.1

### BCLib

1.18.1

### Fabric API

1.18.1

### Fabric Loader

1.18.1

### Minecraft

1.18.1

**Comment by paulevsGitch** [comment]
You didn't mention any versions that you have. Placing everywhere 1.18.1 is not required information.

**Comment by mropitzky** [comment]
Oh Sorry! everything that's installed is completely up to date to the latest versions.

**Comment by paulevsGitch** [comment]
"Up to date" is not a version, please use numerical versions that each mod have

**Comment by paulevsGitch** [comment]
> Bclib is 1.2.1

It is outdated, latest is 1.2.4

> fabric loader is fabric_1_18_1_1580218.1

Fabric loader have numerical versions like 0.12.12 (latest loader).
Can you please show your level.dat?

**Comment by mropitzky** [comment]
sure just one second

**Comment by mropitzky** [comment]
![leveldat](https://user-images.githubusercontent.com/97724575/149469616-e915affc-e6cf-4f03-8520-055e3b6cc589.png)

**Comment by mropitzky** [comment]
Thats how i have it set up, when its this way the portal just wiggles endlessly when you try to go to the nether, but you cant actually go

**Comment by mropitzky** [comment]
also the Fabric Loader is 0.12.12

**Comment by paulevsGitch** [comment]
I can see wrong biome source on your screen. It should be **bclib:nether_biome_source**

**Comment by mropitzky** [comment]
Okay gotcha, the one i have listed was the one i saw on another post. I'll punch this one in and report back in a few minutes.

**Comment by mropitzky** [comment]
the portal allowed us to travel there, im gonna head out to chunks that have no been explored and report back if the new biomes have spawned or not. Thanks for all your help so far, ill make sure to report back by tomorrow afternoon regardless!

**Comment by mropitzky** [comment]
okay that worked like a charm, thanks man your the best! I also have Better End installed, do i need to do anything for that as well?

**Comment by paulevsGitch** [comment]
> I also have Better End installed, do i need to do anything for that as well?

If you have wrong End biome source - replace it with **bclib:end_biome_source**
