### ISSUE TITLE
[Cross Mod] Crash when "Nether Ex" spore creeper blows up orange mushroom from "Better Nether"

### ISSUE THREAD

**Issue by TeetoKaziim** [paulevsGitch/BetterNether#5]
https://gist.github.com/TeetoKaziim/c952455cebac9787ef8d44327bad959d

Was thrilled to see these mods adding their worldgen in tandem, really spices the nether up, turns it into a psychadelic hellscape.

Then I crashed when a spore creeper blew up an orange mushroom. (I think, I wasn't there.)

Dropping this on both mods' issues pages because not sure who would have to do what, if anything can be done, about this. Thanks so much, and good luck! :D

Issue on their page is: https://github.com/LogicTechCorp/NetherEx/issues/140

**Comment by paulevsGitch** [comment]
I know where the problem was, in next release it would be fixed.

**Comment by paulevsGitch** [comment]
Fixed in new release
