### ISSUE TITLE
[1.12] Saving structures causes server lag spikes on each auto-save

### ISSUE THREAD

**Issue by deNULL** [paulevsGitch/BetterNether#50]
I'm running a Forge server (Minecraft version 1.12.2) with a number of mods, including BetterNether. Currently I'm noticing that there's a lot of "Can't keep up" messages in its log. It happens approximately each 45 seconds, with a duration ranging from 2 to 10 seconds.

When I disable auto-saving (which should happen exactly at each 900's tick, i.e. each 45 seconds), those messages disappear.

Upon further investigation (using a profiler) I noticed that method `paulevs.betternether.structures.big.StructureManager.save()` is being called when world is saved (judging by the code of the mod, it happens on each autosave, even when there's no actual changes to the structure list).

I downloaded a `bn_city.nbt` file (which is being saved, I believe), it is only 330 Kb in size, but NBTExplorer pauses noticeably when I try to open it. I think this is because there's thousands of entries in `chunks` lists, each with long (and empty!) `id` and `meta` fields. Here's that file: [bn_city.zip](https://github.com/paulevsGitch/BetterNether/files/4239995/bn_city.zip).

I think that's the reason of lag spikes on my server. It probably would be better to save structures only when they're "dirty" (i.e. were modified), just like Minecraft does with chunks. Another idea is to optimize the data structure — I don't know how this data is being used, but storing so many entries in NBT is not a best idea.

**Comment by paulevsGitch** [comment]
Fields are not empty, they are filled with blocks of structure. The most blocks are air, so the ID and meta are zero. This file contains only not-generated in world structures.

Support for 1.12 is closed, this structure system is not used in later versions, instead there are vanilla structure save system.

**Comment by deNULL** [comment]
> This file contains only not-generated in world structures.

Does that mean that visiting those structures will reduce the number of entries in this file?

> Support for 1.12 is closed

Isn't it a bit early to stop supporting 1.12? The vast majority of mods is not yet updated to newer versions, so it is impossible for server owners to update in the foreseeable future.

**Comment by paulevsGitch** [comment]
> Does that mean that visiting those structures will reduce the number of entries in this file?

Yes

> Isn't it a bit early to stop supporting 1.12? The vast majority of mods is not yet updated to newer versions, so it is impossible for server owners to update in the foreseeable future.

Supporting more then one version is very hard, especially for different mod loaders. I am already supporting 1.15 and 1.16 branches, 1.12 is already outdated for several years. Many mods from 1.12 will never update to later versions (like on 1.7 and 1.6), but this is not a reason to dwell on this version forever.  Need to move on to the future. Many mods like TechReborn, Terrestia and others are already updated and new mods appears. So I decided to fix most bugs in 1.12 version and continue development. If someone wants to continue 1.12 branch - he can, but official support is closed.

**Comment by paulevsGitch** [comment]
This bug is outdated and will not be fixed, in 1.12 version cities can be disabled in the config
