### ISSUE TITLE
[TerraBlender Compatibility] Biomes are not loading

### ISSUE THREAD

**Issue by mxskedmystery** [paulevsGitch/BetterNether#504]
### What happened?

I went into the nether on a single-player world and used /locatebiome to find one of the new biomes. after multiple failed attempts I loaded a new single-player and had the same issue. I thought it was a mod creating structures (Repurposed Structures (Fabric)) conflicting with it, so I uninstalled it and tried again. the same result "couldn't find biome." So I redownloaded the mod, thinking I accidentally got rid of something, but still had the same issue. I don't know why none of the biomes are spawning. all of the creatures are spawning as well as the nether cities. can someone please help?

### BetterNether

5.0.9

### BCLib

1.2.5

### Fabric API

0.46.1

### Fabric Loader

0.12.12

### Minecraft

1.18.1

### Other Mods

```shell
Adorn
BetterEnd
Cloth API (Fabric)
Cloth Config API (Fabric)
Comforts (Fabric)
Croptopia [FABRIC/FORGE]
End Origins
Enhanced Celestials(Fabric) - Blood Moons & Harvest Moons
Extra Origins
Fabric API
Fabric Language Kotlin
Fabric Waystones
Galacticborn Origin
Grounded Origins [FABRIC]
Iris Shaders
Mob Origins
Mythical Origins
Oh The Biomes You'll Go Refabricated
Origins (Fabric)
Paintings ++
Patchouli (Fabric)
Pehkui
Plushie Mod
Simple Backpack [FABRIC]
Simple Voice Chat
Sodium
TerraBlender (Fabric)
TotalHero's custom origins
Repurposed Structures (Fabric)
```

**Comment by paulevsGitch** [comment]
Try to re-enter into same world again and search for the biomes. Allow BCLib fix biome source on world loading

**Comment by quiqueck** [comment]
Both BCLib and TerraBlender want to change the same thing. Until we come up with a fix, those Mod will be incompatible as either one will override the results of the other.

**Comment by Sunconure11** [comment]
Dumb question, but is there a reason not to use TerraBlender to do the same approach of what you were previously doing?

**Comment by paulevsGitch** [comment]
BetterNether & BetterEnd have different biome generation that is not compatible with Terrablender. Terrablender biomes can be imported into it, but not visa versa

**Comment by OverloadedWithMods** [comment]
Dude Promenade, BYG have nether stuff just sitting there because terrablender and bclib hate eachother

**Comment by paulevsGitch** [comment]
Promenade don't use TerraBlender, it uses Fabric API (at least version that I testes).
BetterNether and BetterEnd can work with BYG, but for Nether/End you need to manually add biomes into config.

Library compat is not an easy thing that can be done with one button press. There is Fabric Biome API that exists since 1.16 and allows mods to add biomes together into Nether and End, BCLib, BN, BE and Promenade uses it and works fine. Terrablender and BYG - not, they work only with their own biome source

**Comment by OverloadedWithMods** [comment]
Promenade requires terrablender for the biomes to spawn so it is essentially dependant on it. This library compat can be done with promenade as well right?

**Comment by OverloadedWithMods** [comment]
How do I even get the biomes into bc lib

**Comment by paulevsGitch** [comment]
> How do I even get the biomes

There are two solutions.
First is activation of "addEndBiomesByCategory" in generator.json:
```json
"addEndBiomesByCategory [default: false]": true,
```

And the second is manual biome adding into forces biomes lists in biomes.json:
```json
"force_include": {
  "end_land_biomes": ["mod:cool_end_land_biome","mod:another_cool_end_land_biome"],
  "end_void_biomes": ["mod:cool_end_void_biome"],
  "nether_biomes": ["mod:nether_biome","mod:another_nether_biome"]
},
```

**Comment by Sunconure11** [comment]
Would this apply to Terralith, too? Given how some oddities have been reported with it and Terrablender and possibly this mod here and there.

**Comment by paulevsGitch** [comment]
BCLib doesn't affect Overworld, so issues of Terralith and Terrablender are not related to it

**Comment by Sunconure11** [comment]
Also, looking through this issue, it would seem BYG uses Terrablender again

**Comment by Sunconure11** [comment]
Is there a similar config option for Better Nether? Either that or I'm not seeing it.

**Comment by paulevsGitch** [comment]
If you mean biomes and generator - these options are BClib options, not BetterNether

**Comment by OverloadedWithMods** [comment]
> > How do I even get the biomes
> 
> There are two solutions. First is activation of "addEndBiomesByCategory" in generator.json:
> 
> ```json
> "addEndBiomesByCategory [default: false]": true,
> ```
> 
> And the second is manual biome adding into forces biomes lists in biomes.json:
> 
> ```json
> "force_include": {
>   "end_land_biomes": ["mod:cool_end_land_biome","mod:another_cool_end_land_biome"],
>   "end_void_biomes": ["mod:cool_end_void_biome"],
>   "nether_biomes": ["mod:nether_biome","mod:another_nether_biome"]
> },
> ```

Thank you so much!
