### ISSUE TITLE
[Bug] Desync sitting on chairs/stools (only on server)

### ISSUE THREAD

**Issue by lordrius** [paulevsGitch/BetterNether#508]
### What happened?

If you try to sit on a chair or stool when playing on a server, player swing hand but does not update his position and remains in the same spot. If you press shift to unmount or relog, then you can see the player sitting on the chair. I tried this in Single Player and does not happen... Only in servers, clean install and clean setup.

Sorry for my english, I'm Spanish.

Thanks!

### BetterNether

6.0.9

### BCLib

1.2.5

### Fabric API

0.46.1

### Fabric Loader

0.12.12

### Minecraft

1.18.1

### Relevant log output

```shell
Client console: Received passengers for unknown entity
```

### Other Mods

```shell
- architectury 3.4.9
- bclib 1.2.5
- betteranimalsplus 1.18.1-11.0.3
- betterend 1.0.1
- betternether 6.0.9
- cavetweaks 1.0
- chunky 1.2.164
- croptopia 1.8.0
- feature_nbt_deadlock_be_gone 1.0.1+1.18.1
- guild 0.3.8
- krypton 0.1.6
- lithium 0.7.7
- morevillagers-fabric 3.1.1-SNAPSHOT
- mostructures 1.3.0-pre1+1.18
- no_null_processors 2.0.1+1.18.1
- patchouli 1.18.1-64-FABRIC
- repurposed_structures 3.3.3+1.18.1
- starlight 1.0.1+fabric.0583973
- terralith 2.0.12
```

**Comment by quiqueck** [comment]
Thank you for reporting this.

**Comment by quiqueck** [comment]
Version 6.0.10 is out with that possible fix, but I think it does not cover all circumstances, as I still get the occasional desync...

**Comment by paulevsGitch** [comment]
Please open this issue on the new BN git tracker if it still exists. Probably it was fixed completely
