### ISSUE TITLE
Terraforge not recognizing BetterNether as a worldgen type

### ISSUE THREAD

**Issue by FlashyCoderDude** [paulevsGitch/BetterNether#509]
TerraForged only recognizes BetterEnd as a world gen type for Nether IF both BetterNether and BetterEnd mods are installed.  BetterNether is not shown.

**Comment by paulevsGitch** [comment]
Isn't TerraForged a Forge mod?

**Comment by FlashyCoderDude** [comment]
Oops. I posted on the wrong forum. So sorry
