### ISSUE TITLE
1.16 nether biomes do not generate correctly

### ISSUE THREAD

**Issue by theishiopian** [paulevsGitch/BetterNether#51]
I was testing the latest release for minecraft 1.16 (2.2.0-20w09a) and it seems vanilla biomes are having trouble generating. At first I thought this was intentional, but I have found generation artifacts consistent with the warped and crimson forests. It appears something in the mod is overwriting these biomes somehow. This makes it impossible to get warped/crimson stems/fungi, or basalt blocks.

![2020-02-29_18 04 12](https://user-images.githubusercontent.com/8585975/75618180-57994e00-5b1f-11ea-8499-44e6ddcfb71d.png)
![2020-02-29_18 04 01](https://user-images.githubusercontent.com/8585975/75618181-59631180-5b1f-11ea-9d01-f74ae711327f.png)
![2020-02-29_18 05 38](https://user-images.githubusercontent.com/8585975/75618182-5a943e80-5b1f-11ea-9804-3f2816cae86b.png)

**Comment by theishiopian** [comment]
Another thing I noticed is that f3 biomes rarely match-up with what is generated.

**Comment by theishiopian** [comment]
It seems that turning off the world fixing and cleanup passes does not fix the issue

**Comment by paulevsGitch** [comment]
This is declared as “use_custom_biome_system” in config, fixing and cleanup passes don’t have influence on this. This is new biome system, that overrides vanilla one. Destructed trees are bug of snapshot itself (as I know)

**Comment by paulevsGitch** [comment]
I figured where problem was. This is a result of misunderstanding Biome Array storage format. Now everything looks ok.

**Comment by paulevsGitch** [comment]
Uploaded new version, should be fixed now. Old config must be rewritten or deleted, as I changed some values.

**Comment by theishiopian** [comment]
That seems to have fixed the issues in the nether, however there is now a new problem in that nether biomes now generate in the overworld. I will open a new issue for this problem.
