### ISSUE TITLE
[Bug] Failed to Create Mob Console Spam

### ISSUE THREAD

**Issue by Fabrieze** [paulevsGitch/BetterNether#512]
### What happened?

The console is spamming "failed to create mob" constantly. The issue happens because I have a few mobs set to "false" in mobs.json. When I enabled it to true, the spam stopped, but setting spawn weight to 0 in biomes.json does nothing as the mobs keep spawning (17+ fireflies, 10+ nagas in about one minute.)

We have a few mods that also throw some errors/warnings, but this is by far the worse and occurs only in the nether. Any insight onto what's causing it would be fantastic.

Pastebin log: https://pastebin.com/WrkwL4aG

### BetterNether

5.3.14

### BCLib

0.5.6

### Fabric API

0.46.1

### Fabric Loader

0.13.1

### Minecraft

1.17.1

**Comment by paulevsGitch** [comment]
Please open this issue on the new BN git tracker if it still exists. 1.17 is also outdated and not supported so please test this on a new version
