### ISSUE TITLE
[Bug] Missing recipes when referenced by ResourceLocation

### ISSUE THREAD

**Issue by TheIllusiveC4** [paulevsGitch/BetterNether#514]
### What happened?

Polymorph developer here again. I was investigating a new issue that popped up on my end (https://github.com/TheIllusiveC4/Polymorph/issues/145) and realized that this is likely the same issue as the one that was discussed for BetterEnd (https://github.com/paulevsGitch/BetterEnd/issues/405).

It's better summarized in the old issue, but just to briefly recap: Due to the way that recipes are stored and merged from BetterNether, any calls to `RecipeManager#byKey(ResourceLocation)` will not return the proper values for BetterNether recipes. The solution is to merge the recipes into the secondary HashMap that holds these references keyed by ResourceLocation, in addition to the current map that is keyed by RecipeType.

### BetterNether

6.0.10

### BCLib

1.3.4

### Fabric API

0.46.4+1.18

### Fabric Loader

0.12.12

### Minecraft

1.18.1

**Comment by paulevsGitch** [comment]
All recipes are already added into second map, is this report for outdated version?

**Comment by paulevsGitch** [comment]
Hm, I just saw 1.3.4 version, this should not happen

**Comment by paulevsGitch** [comment]
All recipes are added into [both maps](https://github.com/paulevsGitch/BCLib/blob/e013f80912e85018b3a52ff8355916d393ad0948/src/main/java/ru/bclib/mixin/common/MinecraftServerMixin.java#L62-L63)

**Comment by paulevsGitch** [comment]
I think I know the reason - BN still uses its own old recipe manager, @quiqueck, please fix this
