### ISSUE TITLE
Can you make Tools compatible with LevelZ - Give them material ID ( Your Armor works fine ) [Suggestion]

### ISSUE THREAD

**Issue by SpigotDE** [paulevsGitch/BetterNether#515]
### Description

I can add the material "cincinnasite" for armor but not for tools

**Comment by paulevsGitch** [comment]
All tools already have materials in their constructor, can you please explain what do you mean?

**Comment by SpigotDE** [comment]
Discord?

**Comment by SpigotDE** [comment]
I wanna make a datapack for LevelZ and Better Nether / Better End 

I can add Armor like 
{
    "replace": true,
    "skill": "defense",
    "level": 5,
    "item": "minecraft:armor",
    "material": "cincinnasite"
}
and it works. Now i can only equip my Cincinnasite Armor when im Level 5 in Defense

I wanna add Swords like
{
    "replace": true,
    "skill": "strength",
    "level": 5,
    "item": "minecraft:sword",
    "material": "cincinnasite"
}
Normally it would work but it doesnt

With Better End 
{
    "replace": true,
    "skill": "strength",
    "level": 5,
    "item": "minecraft:sword",
    "material": "thallasium"
}
it works and i can only use the thallasium sword when im level 5 in Strength

**Comment by paulevsGitch** [comment]
Both Cincinnasite sword and tools use same material, so I'm not sure why it works for tools and not work for sword

**Comment by SpigotDE** [comment]
Let me Double Check that

**Comment by SpigotDE** [comment]
Nope doesnt Work Form all the Tools in Better Nether

**Comment by quiqueck** [comment]
Actually I am not sure why this works for a thallasium sword...

**Comment by paulevsGitch** [comment]
Can this be a tags issue?

**Comment by SpigotDE** [comment]
The LevelZ Author told me he get the material id through "Enum's" - but im not sure about that, i dont even know what that means exactly

**Comment by quiqueck** [comment]
I am not sure how the **thallasium**-name is connected to a tool tier. As far as I can see, that name is only set for the armor  armor-material and as a prefix everything that is related to thallasium (like **thallasium_ore**). 

The enums may be a good lead. BE handles the Materials as enums, BN uses a plain class

**Comment by quiqueck** [comment]
This should be fixed in 6.0.11. Please re-open this issues if you are still having problems.
