### ISSUE TITLE
No mob spawn config on Minecraft 1.18 version

### ISSUE THREAD

**Issue by Factoriac9** [paulevsGitch/BetterNether#517]
### What happened?

When creating a new 1.18.1 world with BetterNether and dependencies installed, no mob spawn settings are generated in config file.
I have tested this with a new world and no other mods installed, there are no instances of "mob" or similar terms in the config file under config\betterNether\biomes.json

when testing a 1.17.1 minecraft world with version 5.3.14 of BetterNether, all mob spawn weights are generated in the config just fine.

### BetterNether

6.0.10

### BCLib

1.3.4

### Fabric API

0.46.4

### Fabric Loader

0.13.3

### Minecraft

1.18.1

**Comment by quiqueck** [comment]
The only config currently available in 1.18 is the mobs.json, where you can disable certain mob types. Per Biome Spawn settings are currently not available.

**Comment by quiqueck** [comment]
Will be in the next release.

**Comment by quiqueck** [comment]
This should be fixed in 6.0.11. Please re-open this issues if you are still having problems.
