### ISSUE TITLE
[Bug] Hammers can't break Better Nether/End ores

### ISSUE THREAD

**Issue by Dekamir** [paulevsGitch/BetterNether#518]
### What happened?

Cincinnasite and Nether Ruby Hammers are unable to harvest ores added by Better Nether and Better End.
The ores report level Iron (1), but still fail, even though they can break any Vanilla / Overworld ores.
Their pickaxes are fine.

### BetterNether

6.0.10

### BCLib

1.3.4

### Fabric API

0.46.4

### Fabric Loader

0.13.3

### Minecraft

1.18.1

### Other Mods

```shell
Vanilla Hammers
Vanilla Excavators
WTHIT
```

**Comment by paulevsGitch** [comment]
Please open this issue on the new BN git tracker if it still exists
