### ISSUE TITLE
[1.16] Vanilla nether biomes generate in the overworld

### ISSUE THREAD

**Issue by theishiopian** [paulevsGitch/BetterNether#52]
I was testing the fixes in 2.2.1-20w09a and I quickly discovered that while they fixed the problems, they also caused this to happen:
![2020-03-02_11 13 50](https://user-images.githubusercontent.com/8585975/75709911-73fcce00-5c78-11ea-95cf-5e6638e8c405.png)

It appears that at least 2 of the three nether biomes are generating in the overworld. 
![2020-03-02_11 21 40](https://user-images.githubusercontent.com/8585975/75709982-9393f680-5c78-11ea-982e-15313f5398ca.png)
![2020-03-02_11 22 08](https://user-images.githubusercontent.com/8585975/75709994-968ee700-5c78-11ea-8634-510f892ffe90.png)
![2020-03-02_11 13 48](https://user-images.githubusercontent.com/8585975/75710003-98f14100-5c78-11ea-99d5-363bd6754f96.png)

The nether, ironically, is now generating correctly.

**Comment by paulevsGitch** [comment]
Couldn't reproduce this, what seed and coordinates are?

**Comment by paulevsGitch** [comment]
Wait, I know the reason, will fix nearly

**Comment by paulevsGitch** [comment]
The reason - I changed biome generation but without check that it is actually Nether or like it

**Comment by paulevsGitch** [comment]
New version uploaded, bug is fixed

**Comment by theishiopian** [comment]
Can confirm, this issue is fixed in 2.2.2, nice work!
