### ISSUE TITLE
After about 15 seconds in the nether my game crashes [Bug] 

### ISSUE THREAD

**Issue by AzuraPDF** [paulevsGitch/BetterNether#520]
### What happened?

A bug happened! After about 15 seconds in the nether my game crashes, could possibly be because I'm using Optifabric for shaders and I am currently using the PwrDown Fabric RPG mod pack, not sure if I'm the only one experiencing this problem.

### BetterNether

5.1.3

### BCLib

0.3.1

### Minecraft

1.17.1

### Other Mods

```shell
I am currently using the PwrDown Fabric RPG mod pack.
```

**Comment by paulevsGitch** [comment]
Please provide your logs

**Comment by quiqueck** [comment]
Could you please try with the latest release (5.3.14) and report back to us (including the logs)...
