### ISSUE TITLE
[Question] Compatibility Issue with Oh The Biomes You'll Go

### ISSUE THREAD

**Issue by Nuclearx86** [paulevsGitch/BetterNether#523]
### What happened?

Compatibility Error with BYG (Oh the biomes you'll go) where after mod uninstallation it causes the game to crash when trying to create a new world.  By compatibility error it works fine with BYG installed, just when uninstalling it can cause crashes when making the new world. This may be an issue with BYG but I though I would mention it here. The issue can be fixed manually by editing the BYG .json files but it would be preferable if there was an autofix, such as preventing BYG from adding BetterNether Biomes into it's Nether_Biomes list. This however could cause issues with BetterNether loading with BYG installed.

### BetterNether

6.0.11

### BCLib

1.3.5

### Fabric API

0.46.4

### Fabric Loader

0.13.3

### Minecraft

1.18.1

### Relevant log output

The game crashed whilst mouseclicked event handler
Error: java.lang.IllegalArgumentException: "ResourceKey[minecraft:worldgen/biome / betternether:gravel_desert]" is not a valid biome in the registry, fix the ID or remove the json entry from the config: "C:\Users\\*******\AppData\Roaming\\.minecraft\config\byg\byg-nether-biomes.json" and relaunch Minecraft...
Exit Code: -1

(The ******* is my user directory.)

### Other Mods

Oh The Biomes You'll Go. (BetterNether doesn't have to be installed for this issue to occur. It just has to be installed once and the game has to be run for this bug to come into action. You also have to generate the Nether Dimension in a Minecraft world. Only is present once BetterNether is un-installed.)

**Comment by Nuclearx86** [comment]
By Compatibility Error it works fine with BYG installed, just when uninstalling it can cause crashes when making the new world. This may be an issue with BYG but I though I would mention it here. The issue can be fixed manually by editing the BYG .json files but it would be preferable if there was an autofix, such as preventing BYG from adding BetterNether Biomes into it's Nether_Biomes list.

**Comment by paulevsGitch** [comment]
Please provide your logs

**Comment by Nuclearx86** [comment]
Okay. I will attempt to replicate the glitch in order to get the logs.

**Comment by Nuclearx86** [comment]
Log added.

**Comment by paulevsGitch** [comment]
Due to
> ResourceKey[minecraft:worldgen/biome / betternether:gravel_desert]" is not a valid biome in the registry, fix the ID or remove the json entry from the config: "C:\Users\*******\AppData\Roaming\.minecraft\config\byg\byg-nether-biomes.json" 

It looks like a BYG config issue
