### ISSUE TITLE
Infinite Whispering Gourd Seeds. 

### ISSUE THREAD

**Issue by RageQuitAmy** [paulevsGitch/BetterNether#525]
I am not sure if this is a big or if it is intended but when you plant Whispering Gourd seeds they grow super quickly and every time you break the plant, it gives you a seed. They are pretty op and you can get infinite bonemeal.

**Comment by quiqueck** [comment]
Thanks for reporting. I'll look into it

**Comment by RageQuitAmy** [comment]
Thanks for your time!

**Comment by quiqueck** [comment]
Thanks again for taking the time to report this. The next release of BN will contain a fix. There is now a 1/8th Chance that the vine will grow in a random Tick.

**Comment by RageQuitAmy** [comment]
Thank you!
