### ISSUE TITLE
[Bug] Weird Flying/Weakness

### ISSUE THREAD

**Issue by infectedw** [paulevsGitch/BetterNether#527]
### What happened?

So, after adding BetterNether from version 5.3.x to 6.1.x I get some sort of "WEIRD" weakness/flying effect which cannot be removed or cleared. This weird behaviour happens only to new people. 

### BetterNether

6.0.11

### BCLib

1.3.5

### Fabric API

0.44.0

### Fabric Loader

0.13.3

### Minecraft

1.18

**Comment by quiqueck** [comment]
A strange flying effect is common when the installed mods on server/client do not match. Could you please compare the mod list of affected players with the ones installed on the server?

**Comment by infectedw** [comment]
Players have none of mods installed on their client side, I'm trying to make everything server side as much as possible.

**Comment by paulevsGitch** [comment]
> Players have none of mods installed on their client side

All content mods (including BetterEnd) should be both client and server side
