### ISSUE TITLE
Not all Nether Ruby items are fire resistant!

### ISSUE THREAD

**Issue by Theobot3782** [paulevsGitch/BetterNether#531]
### Description

Here is a list of the items that do and don't burn in lava and fire!
Burns: 
-Nether Ruby Armor (all of it)
-Nether Ruby 
-Nether Ruby Block, Slab, and Stairs
-Nether Ruby Ore (idk if this would burn or not, lol)

Doesn't Burn:
-Literally just the Nether Ruby Tools

Can you fix this please?

**Comment by Theobot3782** [comment]
the same exact thing happens with cinncinnasite ;-;

**Comment by Theobot3782** [comment]
I eat slimeballs

**Comment by quiqueck** [comment]
Thanks for reporting, I'll have a look at it.

**Comment by quiqueck** [comment]
Fix will be in the next release of BetterNether (for 1.18.2)
