### ISSUE TITLE
Added BetterNether to server and it caused fallingtrees to not work 

### ISSUE THREAD

**Issue by MelZabs** [paulevsGitch/BetterNether#534]
### What happened?

I loaded FallingTree onto my server and it worked fine. Then added BetterNether and BCLib and when starting up, it failed and now FallingTree doesn't work but BetterNether does. Not sure if it's an incompatibility issue?

### BetterNether

6.0.11

### BCLib

1.3.5

### Fabric API

0.44.0

### Fabric Loader

Latest version

### Minecraft

1.18.1

### Other Mods

```shell
Fabric.jar
FallingTree-1.18.1-3.2.1.jar
MouseTweaks-fabric-mc1.18-2.22.jar
fabric-api-0.44.0+1.18.jar
```

**Comment by paulevsGitch** [comment]
Please provide your logs
