### ISSUE TITLE
[suggestion] Bred Fireflies to not Despawn

### ISSUE THREAD

**Issue by GoldenstarArtist** [paulevsGitch/BetterNether#535]
### Description

I do enjoy these as a farmable animal, since it took a lot of effort to get them together and feed them growstone. Just not so much when your hard work despawns. I was half expecting the parents to despawn but was surprised to see the offspring did as well =/

**Comment by quiqueck** [comment]
We will track this in our Nether Enhancement project and update this issues with all relevant information.
