### ISSUE TITLE
[Suggestion] add enchantment description (Better NEth

### ISSUE THREAD

**Issue by HaraldLP** [paulevsGitch/BetterNether#536]
### Description

i found a mod, named enchantment descriptions: https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions
it's like the name says: it adds a description to the enchantments at a book or item etc. can u add the description to the better nether and end mod? i don't wanna open another issue ticket on better end so i ask you for both on here. 
![Screenshot_1](https://user-images.githubusercontent.com/59770470/162834654-68ac8195-5396-4419-be7b-afcb943466ed.png)
have a nice day and keep up with those beautijfull mods :)

**Comment by quiqueck** [comment]
I'll have a look at thar mod.

**Comment by quiqueck** [comment]
Was a small addition, and will be included in the next release
