### ISSUE TITLE
no config available

### ISSUE THREAD

**Issue by CrimsonZenith1** [paulevsGitch/BetterNether#537]
### What happened?

No available config even in newest versions

### BetterNether

6.0.10

### BCLib

1.3.5

### Minecraft

1.18.1

**Comment by CrimsonZenith1** [comment]
I downloaded both 6.0.11 and 6.1.0 and I'm not finding the config file names mentioned in other reports like this one: https://github.com/paulevsGitch/BetterNether/issues/401. Specifically for changing mob spawns

**Comment by quiqueck** [comment]
Just to make sure, did you run the game once. The files generate when BN is loaded. If you did, in what folder did you look for the configs?

**Comment by quiqueck** [comment]
Could you let us know which folders you checked? I just tested, and the configs generated fine, so I need some more info to test.

**Comment by paulevsGitch** [comment]
Tested in fresh Minecraft instance, all configs exists

![image](https://user-images.githubusercontent.com/17707380/165996702-0d79d39b-d6b6-4efd-b46d-43647b8c069e.png)

**Comment by CrimsonZenith1** [comment]
![IMG_20220430_181310](https://user-images.githubusercontent.com/104087084/166111335-5b2fb261-82a9-4b8e-a286-be92b3f29a1e.jpg)
Idk why it's like this then. I searched biomes.json and there's 0 results

**Comment by paulevsGitch** [comment]
Why are you editing mod jar instead of using config folder in Minecraft instance?
I’m closing this
