### ISSUE TITLE
[Bug] Biomes not generating

### ISSUE THREAD

**Issue by WeSeals** [paulevsGitch/BetterNether#539]
### What happened?

None of the biomes from betternether are spawning, but all of the structures are. I know you can change the level.dat, but I still want biomes (AmplifiedNether generation too, but it doesn't seem to be working either)from other mods to still generate. I have toggled a lot of mods that deal with the nether on and off like AwesomeDungeons, Towers of the Wild, and Promenade, yet that hasn't fixed anything. BetterEnd and Nullscape work perfectly together, not sure if that means anything.

I plan on using this modpack to play with my friends and want to know if there is if I could do to fix this problem or not.

### BetterNether

6.0.11

### BCLib

1.3.5

### Fabric API

0.46.6

### Fabric Loader

0.13.3

### Minecraft

1.18.1

### Other Mods

```shell
https://www.modpackindex.com/modpack/45158/hamboning
```

**Comment by quiqueck** [comment]
Could you try if removing **[FABRIC] Disable Custom Worlds Advice** helps and Mods like this disabled the biomesource check in the past. BCLib offers the same feature without an additional mod. You  have can enable it in the config (ModMenu).

**Comment by WeSeals** [comment]
Turns out it was an issue with **The Graveyard Biomes (Fabric)**/**Terrablender (Fabric)**.
