### ISSUE TITLE
[Bug] Magma Flower Seeds & Bone Meal - Quality of Life change

### ISSUE THREAD

**Issue by HacoKavanah** [paulevsGitch/BetterNether#543]
### What happened?

Technically not a bug, but you can actually use bone meal on magma flowers, it just won't do anything. If you would 1. disable the use of bone meal on those 2. enable the bone meal to do something, would be neat!

### BetterNether

 better-nether-6.1.1.jar

### BCLib

 bclib-1.4.5.jar

### Fabric API

fabric-api-0.51.1+1.18.2.jar

### Fabric Loader

0.14.2

### Minecraft

1.18.1

### Relevant log output

```shell
-
```

### Other Mods

```shell
Inform me if this is relevant.
```

**Comment by quiqueck** [comment]
Thank you for reporting. I'll have a look.

**Comment by paulevsGitch** [comment]
If this issue still exist please reopen it on a new BN tracker
