### ISSUE TITLE
Incompatibility with Quilt (uses FAPI impl)

### ISSUE THREAD

**Issue by sisby-folk** [paulevsGitch/BetterNether#544]
```
Minecraft 1.18.2
Quilt Loader 0.16.0-beta.16
bclib-1.4.5
better-nether-6.1.1
qsl-1.1.0-beta.8_qfapi-1.0.0-beta.12_fapi-0.51.1_mc-1.18.2
```
[latest.log](https://0x0.st/oAfN.txt)

Functions correctly with 
```
Fabric 0.14.4
fabric-api-0.51.1+1.18.2.jar
```

Suggested reason: mod uses bits from FAPI's `impl` package (perhaps erroneously)

**Comment by paulevsGitch** [comment]
BetterNether is a Fabric mod, it was not made for Quilt

**Comment by Mg138** [comment]
Doesn't mean one should touch the *impl*?

**Comment by sisby-folk** [comment]
While I understand this - The vast majority of fabric mods work with Quilt by default, and the reason for this incompatibility is very much an edge case. Can you confirm specifically whether you won't support the mod in this way / whether you'll reject relevant pull requests?

**Comment by paulevsGitch** [comment]
There are no plans to make specific Quilt-compatible version at this moment

**Comment by sisby-folk** [comment]
Could you please clarify further on the other parts of the above question?

**Comment by paulevsGitch** [comment]
BetterNether doesn't use impl package.
BetterEnd require specific classes from that package

**Comment by LambdAurora** [comment]
> BetterNether doesn't use impl package. BetterEnd require specific classes from that package

@paulevsGitch excuse me? We very much know how to read `import` of `net.fabricmc.fabric.mixin.object.builder.AbstractBlockSettingsAccessor` **which is an impl class**.

Second, any mixin accessor in Fabric API is considered implementation, you're supposed to recreate the mixin yourself. Or use an access widener, both works. This is an edge-case where for some reason Fabric doesn't support modifying the material of a block settings for an unknown reason.

Finally, your mods regularly cause issues with other mods, it's time to consider a proper cleanup of the codebase.

**Comment by Patbox** [comment]
> Second - any part of the API can be used, that's why it is an API. If there is something that requires usage of API, for example accessors - it can be used, that's why API exists - it used to share same code between mods.

If that was the case, fabric wouldn't split it into `api` and `impl` packages. Everything outside of `api` is intended only for fabric api only. One main version bump and it won't work (without any changes for `api`)

**Comment by LambdAurora** [comment]
The only actual API is what are in the `api` packages.

The rest is implementation only, which means it can change at any time and have no guarantee of stability, this goes for the `impl` and `mixin` package.
And at least, Fabric API was made this way to ensure mods could work on re-implementations of the API.

**Comment by LambdAurora** [comment]
> I don't get what's so hard to get about not touching the impl when using an API.

To be honest, there is valid use cases of using implementation details, but they only highlight the fact that the API fails to provide what modders need.

**Comment by Fishvap** [comment]
> I don't get what's so hard to get about not touching the impl when using an API.

If it's not hard, why don't you fix it then? This is old code. Rewrite if you so wish.
