### ISSUE TITLE
[Suggestion] Allow mushroom foliage (and foliage in general) to be placed on overworld blocks

### ISSUE THREAD

**Issue by AnomalousVoidThing** [paulevsGitch/BetterNether#547]
### Description

The base game nether mushrooms are able to be placed on all blocks in the game regardless of if it is a nether block or even an organic block (ie dirt, mycelium, podzol, nylium, etc). It seems pretty inconsistent and also limiting to builders to only allow the new nether mushrooms and wall spores to be placed on netherrack or specific nether blocks. The added mushroom foliage would be much more exciting to find and collect if it could be used outside of the nether on a variety of materials, and also be more consistent with the base game nether mushrooms and foliage.

**Comment by quiqueck** [comment]
Thanks for reporting. I added this to our list of enhancements and will update this issue once this get's implemented.
