### ISSUE TITLE
[Bug] Attempting to set structure density to 0 will simply duplicate the default density in the config.

### ISSUE THREAD

**Issue by Little8man** [paulevsGitch/BetterNether#549]
### What happened?

In the biome config, setting the density of any structure to 0 will simply add a duplicate of the default density on the next available line, essentially redacting the previous density. Like this.

```
        "floor": {
          "netherrack_stalactite": {
            "density [default: 0.0]": 0.0, < -- density set by me
            "limit [default: true]": true,
            "density [default: 0.05]": 0.05 < -- density reset by the mod
```

This, in turn, results in the structure not being restricted from generating. This could have also resulted from me setting the default value to 0 as well.

(I am using Minecraft version 1.18.2. For some reason it was not selectable as an option.)

### BetterNether

v6.1.1

### BCLib

v1.4.5

### Fabric API

v0.51.1

### Fabric Loader

0.13.3

### Minecraft

1.18.1

### Other Mods

```shell
Architectury (dependency)
Cloth Config (dependency)
Feature NBT Deadlock Be Gone (dependency)
Yungs API (dependency)
Additional Additions
Amplified Nether (Known compatibility)
Appleskin
Bedrockify
Better End  (Known compatibility)
Better F3
Better Than Mending
Better Third Person
Biome Weather Effects
Blockus
Carpet
Carpet Extra
Cave Spelunking
Clumps
Consistency Plus
Cull Leaves
Disable Custom Worlds Advice
Earth 2 Java
Eating Animations
Enchanted Vertical Slabs
Entity Culling
Entity Texture Features
Essential
Extra Sounds
FPS Monitor
Giant Spawn
Global Data & Resourcepacks
Lamb Dynamic Lights
Limitless
Linear XP
Lithium
Milk Plus
Mod Menu
No Fog
Not Enough Crashes
On Soul Fire
Phosphor
Repurposed Structures
Sheep Consistency
Sodium
Sound Physics
YUNGs Better Dungeons
YUNGs Better Mineshafts
YUNGs Better Strongholds
YUNGs Extras
```

**Comment by paulevsGitch** [comment]
You changed part of the name (default: 0.0), and made config entry invalid. Don't change name part of config entires

**Comment by Little8man** [comment]
Alright, I have tried it while leaving the default value as-is. However, this also results in the new config being redacted. Instead of creating a new line with the default values, it simply turns the 0.0 back to the default value. Thus, this issue is still unresolved.

**Comment by paulevsGitch** [comment]
Did you edit your config when the game was inactive? Is your Json syntax correct?

**Comment by Little8man** [comment]
Yes, I have done both of those things.

**Comment by paulevsGitch** [comment]
In this case try to delete config, allow it to be re-created and try edit it after that. If everything will be done correctly - it will work fine

**Comment by Little8man** [comment]
Hey that worked! Sorry for the trouble.
