### ISSUE TITLE
[Snapshots][Question] firefly spawnrates are rather high

### ISSUE THREAD

**Issue by theishiopian** [paulevsGitch/BetterNether#55]
While not specifically a problem, per se, fireflies spawn a LOT. Is this intended behavior? I remember in 1.12 they were somewhat rare.

**Comment by paulevsGitch** [comment]
This is not intended behavior, looks like spawn algorithms changed a lot. I will think how to fix that. They have a half probability than piglins to spawn, maybe I will make it lower.

**Comment by theishiopian** [comment]
In the current version they seem to spawn in small swarms, which is quite nice. Perhaps keep that behavior but lower the frequency of swarms?

**Comment by paulevsGitch** [comment]
I decreased their spawn chance from 50 to 10, now this is fixed
