### ISSUE TITLE
[Suggestion] Config option to add what blocks concidered "obisidian" for obsidian breaker on nether ruby

### ISSUE THREAD

**Issue by Redd56** [paulevsGitch/BetterNether#550]
### Description

This new feature would simple be a list in the config for what blocks are considered for the use of the obsidian breaker enchant. That way if there are modded obsidian blocks in a pack (say chisel) they could be easily added without having to add them in code.

**Comment by quiqueck** [comment]
Thanks for the great suggestion. 
Maybe we should add a BlockTag for that. This would allow other Mods to easily add blocks to the Enchantment as well...

**Comment by Redd56** [comment]
Actualy yeah a block tag c:isObsidian would be useful

**Comment by quiqueck** [comment]
Released with BN 6.1.2

**Comment by Redd56** [comment]
Pog and thanks
