### ISSUE TITLE
Better Nether overrides the generation of Bosses of Mass Destruction Structures

### ISSUE THREAD

**Issue by PannaCottaRasPi** [paulevsGitch/BetterNether#552]
### What happened?

Better Nether generates over bosses of mass destruction structures, making it impossible to fight the bosses. 

### BetterNether

6.1.1

### BCLib

1.4.5

### Fabric API

0.51.1

### Fabric Loader

0.13.3

### Minecraft

1.18.1

### Other Mods

```shell
-better nether
-bosses of mass destruction
-amplified nether
```

**Comment by paulevsGitch** [comment]
If another mod structures are not spawning in any biome - the issue is on mod side. Fabric provides API for mods to add structures into any biomes (including modded) and in 1.18.2 structure generation was changed a lot
