### ISSUE TITLE
[Bug] BetterNether Biomes are not spawning in

### ISSUE THREAD

**Issue by Zunwolf1896** [paulevsGitch/BetterNether#553]
### What happened?

I have BetterNether and BetterEnd both installed, BetterEnd works fine, all the items and mobs are in the server for BetterNether, but none of the Biomes spawn in, I do have other Nether editing mods installed. 

### BetterNether

6.1.1

### BCLib

1.4.6

### Fabric API

0.51.1

### Fabric Loader

0.13.3

### Minecraft

1.18.1

### Other Mods

```shell
- AwesomeDungeonNether-Fabric-1.18.2-1.0.1
- BasicNetherOres-1.18.2-7.2.0
- incendium_v5.0.3
```

**Comment by paulevsGitch** [comment]
> WorldGenSettings: No key seed

This is common error for incorrect datapacks in 1.18.2.
If biomes are not spawning - it can be related to [this](https://github.com/paulevsGitch/BCLib/issues/132). You can try manually fix biome source
