### ISSUE TITLE
[Bug] Any BetterNether vine in large quantities lags out the game

### ISSUE THREAD

**Issue by 5H1NYM3W** [paulevsGitch/BetterNether#554]
### What happened?

Basically, any BetterNether vine in large quantities lags out the game (I'm looking at you, Upside down forest!) and decreases performance by a LOT. You'll go from 50-60 FPS in the modded Nether to 9-20 in these biomes/near the vines in large quantities.
I have no idea how this could happen. Maybe they are registered as block entities or are sending too much data by existing?

### BetterNether

5.3.14

### BCLib

0.5.6

### Fabric Loader

0.46.1

### Minecraft

1.17.1

**Comment by paulevsGitch** [comment]
It is a very outdated BN version and it is not supported. All vine-related bugs were fixed
