### ISSUE TITLE
[BYG Compat] Cincinnasite Shears can't shear BYG Barrel Cactus

### ISSUE THREAD

**Issue by Laifsyn** [paulevsGitch/BetterNether#555]
### Description

Title

**Comment by quiqueck** [comment]
Hi, and thanks for reporting. Shears are hardcoded in Minecraft. Which means, that Mod's need to implement the use of modded shears.

Our shears should have the common fabric tags `c:shears` and `fabric:shears` to mark them as a shear tool. I think BYG would need to add support for those tool-tags. Please let me know if they already have support for it or can't add it. In that case I'll have a look.
