### ISSUE TITLE
[Bug] Recipes can't be deleted

### ISSUE THREAD

**Issue by Laifsyn** [paulevsGitch/BetterNether#557]
### What happened?

Recipes that outputs items like Colored Glass Panes can't be deleted.
This script line from CraftTweaker ```craftingTable.remove(<item:betternether:quartz_glass_framed_pane_orange>);```
should remove any recipe that outputs the set item, but when running it in game, I find out that I can still craft it.

Checking the CTLogs, they do show they're removing the items + the diamond sword I also made it to remove just to be sure.

### BetterNether

6.1.1

### BCLib

1.4.6

### Fabric API

fabric-api-0.53.0+1.18.2

### Fabric Loader

0.14.4

### Minecraft

1.18

**Comment by paulevsGitch** [comment]
To disable any recipe from BN you can disable it in the recipes config
