### ISSUE TITLE
Soul Lily Causing Tick World Crash On Servers 

### ISSUE THREAD

**Issue by LazrProductions** [paulevsGitch/BetterNether#563]
Soul Lily block causes the server to crash due to "Exception ticking world"

`---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 6/16/22, 4:26 AM
Description: Exception ticking world

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2248.method_9564()" because "this.plant" is null
	at org.betterx.betternether.blocks.BaseBlockCommonSapling.method_9652(BlockCommonSapling.java:97)
	at org.betterx.betternether.blocks.BlockSoulLilySapling.method_9652(BlockSoulLilySapling.java:11)
	at org.betterx.betternether.blocks.BaseBlockCommonSapling.method_9588(BlockCommonSapling.java:104)
	at org.betterx.betternether.blocks.BlockSoulLilySapling.method_9588(BlockSoulLilySapling.java:11)
	at net.minecraft.class_4970.method_9514(class_4970.java:366)
	at net.minecraft.class_4970$class_4971.method_26199(class_4970.java:947)
	at net.minecraft.class_3218.method_18203(class_3218.java:495)
	at net.minecraft.class_3215.method_14161(class_3215.java:379)
	at net.minecraft.class_3215.method_12127(class_3215.java:323)
	at net.minecraft.class_3218.method_18765(class_3218.java:318)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at org.betterx.betternether.blocks.BaseBlockCommonSapling.method_9652(BlockCommonSapling.java:97)
	at org.betterx.betternether.blocks.BlockSoulLilySapling.method_9652(BlockSoulLilySapling.java:11)
	at org.betterx.betternether.blocks.BaseBlockCommonSapling.method_9588(BlockCommonSapling.java:104)
	at org.betterx.betternether.blocks.BlockSoulLilySapling.method_9588(BlockSoulLilySapling.java:11)
	at net.minecraft.class_4970.method_9514(class_4970.java:366)
	at net.minecraft.class_4970$class_4971.method_26199(class_4970.java:947)
	at net.minecraft.class_3218.method_18203(class_3218.java:495)
	at net.minecraft.class_3215.method_14161(class_3215.java:379)
	at net.minecraft.class_3215.method_12127(class_3215.java:323)
	at net.minecraft.class_3218.method_18765(class_3218.java:318)

-- Affected level --
Details:
	All players: 1 total; [class_3222['***************'/44140, l='ServerWorld minecraft:the_nether world4', x=-0.44, y=59.00, z=-20.62]]
	Chunk stats: 3721
	Level dimension: minecraft:the_nether
	Derived: true
	Level spawn location: World: (-2,80,12), Section: (at 14,0,12 in -1,5,0; chunk contains blocks -16,0,0 to -1,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 11982412 game time, 12720819 day time
	Level name: world4
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 45569 (now: false), thunder time: 115929 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Linux (amd64) version 4.9.0-13-amd64
	Java Version: 17.0.2, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 2631059176 bytes (2509 MiB) / 5577302016 bytes (5318 MiB) up to 10379526144 bytes (9898 MiB)
	CPUs: 4
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 3900X 12-Core Processor
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: ASPEED Graphics Family
	Graphics card #0 vendor: ASPEED Technology, Inc. (0x1a03)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: 0x2000
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 163025.94
	Virtual memory used (MB): 42346.06
	Swap memory total (MB): 98557.00
	Swap memory used (MB): 0.00
	JVM Flags: 3 total; -XX:+UseSerialGC -Xmx10240M -Xms512M
	Fabric Mods: 
		additionaladditions: Additional Additions 5.0.0
		apocalypse: Apocalypse Origins 0.2.11
		architectury: Architectury 5.6.22
		bclib: BCLib 2.0.5
		betternether: Better Nether 7.0.2
		bookshelf: Bookshelf 14.0.2
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.1-1.19
			maelstrom_library: Maelstrom Library 1.3-1.19-pre1
			multipart_entities: MultipartEntities 1.2-1.19-pre1
		bouncierbeds-fabric: Bouncier Beds (Fabric) 1.2
		byg: Oh The Biomes You'll Go 2.0.0.4
		cardinal-components: Cardinal Components API 5.0.0-beta.1
			cardinal-components-block: Cardinal Components API (blocks) 5.0.0-beta.1
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.0-beta.1
			cardinal-components-item: Cardinal Components API (items) 5.0.0-beta.1
			cardinal-components-level: Cardinal Components API (world saves) 5.0.0-beta.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.0-beta.1
			cardinal-components-world: Cardinal Components API (worlds) 5.0.0-beta.1
		cloth-config: Cloth Config v6 7.0.72
			cloth-basic-math: cloth-basic-math 0.6.1
		collective-fabric: Collective (Fabric) 4.27
			fiber: fiber 0.23.0-2
		croptopia: Croptopia 2.0.5
			com_typesafe_config: config 1.4.1
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		darkutils: DarkUtilities 11.0.1
		edenring: EdenRing 0.6.1
		fabric: Fabric API 0.56.0+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.13+b2a4a624a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.5+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.1+cda9839ba9
			fabric-commands-v0: Fabric Commands (v0) 0.2.22+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.0+4a3ec384a9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.0.1+2a5b9210a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.27+72da3b3da9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.25+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.23+9ff28f40a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.0.1+9e7660c6a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.1+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.8+33fbc738a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.5+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.16+92cf9a3ea9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.3+9e7660c6a9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabric-language-kotlin: Fabric Language Kotlin 1.8.0+kotlin.1.7.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.17.3
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.2
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.7
		fishofthieves: Fish of Thieves 2.0.1
		geckolib3: Geckolib 3.1.2
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		iconicwands: Iconic Wands 1.0.4
		immersive_portals: Immersive Portals 2.0.1
			imm_ptl_core: Immersive Portals Core 2.0.1
			q_misc_util: QMiscUtil 2.0.1
		java: OpenJDK 64-Bit Server VM 17
		mcda: MC Dungeons Armors 2.1.0
		midnightlib: MidnightLib 0.5.2
		minecraft: Minecraft 1.19
		numismatic-overhaul: Numismatic Overhaul 0.2.2+1.19
			stacc: Stacc 1.3.3
		origins: Origins 1.6.1
			apoli: Apoli 2.5.0
				additionalentityattributes: Additionalentityattributes 1.0.0+1.19
				calio: Calio 1.7.0
				playerabilitylib: Pal 1.6.0
			reach-entity-attributes: Reach Entity Attributes 2.3.0-SNAPSHOT
		origins-classes: Origins: Classes 1.4.0
		owo: oωo 0.7.3+1.19
		pehkui: Pehkui 3.3.2+1.14.4-1.19
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		pigpen: PigPen 9.0.1
		rainbegoneritual-fabric: Rain Be Gone Ritual (Fabric) 1.9
		random_ring: Random Ring 1.1.13
		realisticfirespread: Realistic Fire Spread 1.19-1
			cardinal-components-base: Cardinal Components API (base) 5.0.0-beta.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.0-beta.1
		roughlyenoughitems: Roughly Enough Items 9.0.475
		runelic: Runelic 12.0.1
		sculksieg: Sculker 1.0.0
		sizeshiftingpotions: Size Shifting Potions 1.4.2
		skylorlib: SkyLib 1.4.0
		stoneholm: Stoneholm 1.4.4
		sync: Sync (Fabric) 4.1
			crowdin-translate: CrowdinTranslate 1.4+1.19-pre2
			smart-recipes: Smart Recipes 0.2.1+1.19
			team_reborn_energy: Energy 2.2.0
		terrablender: TerraBlender 2.0.0.112
			com_electronwill_night-config_core: core 3.6.4
			com_electronwill_night-config_toml: toml 3.6.4
		things: Things 0.2.19+1.19
		transportables: Transportables 1.2.1
		trinkets: Trinkets 3.4.0
		yigd: You're in Grave Danger 1.4.1-beta.1
	Server Running: true
	Player Count: 3 / 999; ******
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)`

**Comment by paulevsGitch** [comment]
This is an old repo, please reopen your issue in the new one
