### ISSUE TITLE
I recently upgrade to 1.19.2 and this mod is the only one that hasn't worked for me, yet. I get this error when I try and launch the game.

### ISSUE THREAD

**Issue by shawncouch88** [paulevsGitch/BetterNether#565]
[main/ERROR]: Minecraft has crashed![main/ERROR]: Minecraft has crashed!net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.8) ~[?:?] at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.9.jar:?] at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?] at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]Caused by: java.lang.ExceptionInInitializerError at org.betterx.betternether.registry.NetherBlocks.<clinit>(NetherBlocks.java:762) ~[better-nether-7.1.0.jar:?] at org.betterx.betternether.entity.EntityFirefly.<clinit>(EntityFirefly.java:549) ~[better-nether-7.1.0.jar:?] at org.betterx.betternether.registry.NetherEntities.<clinit>(NetherEntities.java:152) ~[better-nether-7.1.0.jar:?] at net.minecraft.entity.attribute.DefaultAttributeRegistry.handler$bbg000$hasDefinition(DefaultAttributeRegistry:531) ~[?:?] at net.minecraft.entity.attribute.DefaultAttributeRegistry.hasDefinitionFor(DefaultAttributeRegistry) ~[?:?] at net.minecraft.entity.attribute.DefaultAttributeRegistry.method_26876(DefaultAttributeRegistry:176) ~[?:?] at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?] at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?] at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] at net.minecraft.entity.attribute.DefaultAttributeRegistry.checkMissing(DefaultAttributeRegistry:178) ~[?:?] at net.minecraft.Bootstrap.logMissing(Bootstrap:136) ~[?:?] at net.minecraft.client.main.Main.main(Main:162) ~[fabric-loader-0.14.9-1.19.2.jar:?] at net.minecraft.client.main.Main.main(Main:51) ~[fabric-loader-0.14.9-1.19.2.jar:?] at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?] ... 2 moreCaused by: java.lang.IllegalStateException: Feature configuration for betternether:temp_patch_twisting_vine can not be null! at org.betterx.bclib.api.v3.levelgen.features.BCLFeatureBuilder.buildAndRegister(BCLFeatureBuilder.java:226) ~[bclib-2.1.0.jar:?] at org.betterx.bclib.api.v3.levelgen.features.BCLFeatureBuilder.build(BCLFeatureBuilder.java:238) ~[bclib-2.1.0.jar:?] at org.betterx.bclib.api.v3.levelgen.features.BCLFeatureBuilder.inlinePlace(BCLFeatureBuilder.java:242) ~[bclib-2.1.0.jar:?] at org.betterx.betternether.registry.features.configured.NetherVines.<clinit>(NetherVines.java:113) ~[better-nether-7.1.0.jar:?] at org.betterx.betternether.registry.NetherBlocks.<clinit>(NetherBlocks.java:762) ~[better-nether-7.1.0.jar:?] at org.betterx.betternether.entity.EntityFirefly.<clinit>(EntityFirefly.java:549) ~[better-nether-7.1.0.jar:?] at org.betterx.betternether.registry.NetherEntities.<clinit>(NetherEntities.java:152) ~[better-nether-7.1.0.jar:?] at net.minecraft.entity.attribute.DefaultAttributeRegistry.handler$bbg000$hasDefinition(DefaultAttributeRegistry:531) ~[?:?] at net.minecraft.entity.attribute.DefaultAttributeRegistry.hasDefinitionFor(DefaultAttributeRegistry) ~[?:?] at net.minecraft.entity.attribute.DefaultAttributeRegistry.method_26876(DefaultAttributeRegistry:176) ~[?:?] at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?] at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?] at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] at net.minecraft.entity.attribute.DefaultAttributeRegistry.checkMissing(DefaultAttributeRegistry:178) ~[?:?] at net.minecraft.Bootstrap.logMissing(Bootstrap:136) ~[?:?] at net.minecraft.client.main.Main.main(Main:162) ~[fabric-loader-0.14.9-1.19.2.jar:?] at net.minecraft.client.main.Main.main(Main:51) ~[fabric-loader-0.14.9-1.19.2.jar:?] at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?] ... 2 more

**Comment by paulevsGitch** [comment]
Please don't use old issue tracker for new mod versions, use [new issue tracker](https://github.com/quiqueck/BetterNether/issues)

**Comment by shawncouch88** [comment]
Sorry, I just clicked on the issue tracker link.
