### ISSUE TITLE
server crashes on boot with better nether and end

### ISSUE THREAD

**Issue by jakhlaghi** [paulevsGitch/BetterNether#566]
[betternetherservercrash.txt](https://github.com/paulevsGitch/BetterNether/files/10291755/betternetherservercrash.txt)
[2022-12-22-6.log](https://github.com/paulevsGitch/BetterNether/files/10291758/2022-12-22-6.log)

**Comment by TheFinalMinerz** [comment]
After updating BCLib and BetterEnd, I tested those versions without BetterNether and my 1.19.3 server booted up. When adding Better Nether 8.1.0-8.1.2, they all crash the server.

**Comment by paulevsGitch** [comment]
Please don't report issues of newer versions od BetterNether into an old repo, use only [the new one](https://github.com/quiqueck/BetterNether)
