### ISSUE TITLE
[SUGGESTION] Make netherrack stalactite/stalagmite farmable

### ISSUE THREAD

**Issue by HungryBoy02** [paulevsGitch/BetterNether#568]
Hello, I feel like the inability to farm the stalactite is a major missed opportunity.

You could farm them similar to vanilla dripstone stalactites
![image](https://user-images.githubusercontent.com/9499543/221431668-c401c727-601c-4dfa-be1b-90985c595f25.png)

**Comment by paulevsGitch** [comment]
Hi, this is an old repo, for suggestions please use a [new git repo](https://github.com/quiqueck/BetterNether)
