### ISSUE TITLE
Crossing through Portal to black world

### ISSUE THREAD

**Issue by SaphiraHaze** [paulevsGitch/BetterNether#569]
I have tried to load into the nether 4 times now and every time, it loads, then brings me into the game with all my stuff missing, everything is black and I am falling rapidly from what my coordinates show. Nothing ever loads and then the game just freezes until I end everything in the task manager. I have this mod added from the Better MC {FABRIC} 1.19.2 v16.5.zip

**Comment by paulevsGitch** [comment]
Hi, this is an old repo, for issues please use a [new git repo](https://github.com/quiqueck/BetterNether)
