### ISSUE TITLE
[Suggestion] biome particles

### ISSUE THREAD

**Issue by theishiopian** [paulevsGitch/BetterNether#57]
Similar to my last suggestion, in 1.16 nether biomes have ambient particle effects. I imagine adding some for BN biomes wouldn't be to difficult. For example, mushroom forests could have white, red, blue and brown particles corresponding to the spores of each large fungus. 

Sorry for all the suggestions, I really like this mod lol.

**Comment by paulevsGitch** [comment]
I changed biome constructor a bit, so this will not be difficult

**Comment by theishiopian** [comment]
Yay!

**Comment by paulevsGitch** [comment]
This is how particles looks like in mushroom biome
https://youtu.be/ioyl32z9NkA

**Comment by theishiopian** [comment]
that looks pretty good!

**Comment by paulevsGitch** [comment]
Now this is in game
