### ISSUE TITLE
[Suggestion] More alternatives to iron from cincinnasite

### ISSUE THREAD

**Issue by theishiopian** [paulevsGitch/BetterNether#58]
Currently, it is not possible to create a brewing setup entirely in the nether. However, this isnt hard to fix, all the basic ingredients are available. I propose the following minor additions/changes:

- Nether brick brewing stand: identical to the normal brewing stand, crafted with nether brick items. 
- Cincinnasite Cauldron: crafted from cincinnasite ingots, otherwise identical to an iron cauldron
- Bottles can now be crafted from quartz glass
- Barrel Cacti can now be dried out in a furnace, similar to sponges. The smelting result is barrel cactus seeds, which can be planted on gravel.
- Buckets can be made from cincinnasite

The purpose of the last two changes is to let you get water in the nether, for the purpose of making potions. Unlike in the overworld, water is now a limited resource due to the nature of cauldrons. This means that you have to get the water as well as the ingredients, making potions harder to get. Considering their usefulness in the nether, this is justified.

**Comment by paulevsGitch** [comment]
I think anvil from cincinnasite will also be a good addition. Water, maybe, can be replaced to something identical in crafts, or can be obtained from some organic, I will think about it.

**Comment by theishiopian** [comment]
I suggested cactus because in real life cacti often have water inside. Other possibilities are eye plants, a new mushroom, or even those glowing things on the willow trees. And I agree about the anvil

**Comment by paulevsGitch** [comment]
There is Nether Brewing Stand in new version, bottles can be crafted from Quartz glass as well. I'm still thinking about potion source for Nether and think that barrel cactus will fit perfectly, but this part is not fully done.

**Comment by theishiopian** [comment]
Fair enough, i just saw the brewing stand, nice job!

**Comment by paulevsGitch** [comment]
Actually must-have things:
- Buckets - WIP
- Shears - WIP
- Anvil - Not started yet
- Rails - WIP
- Recipes for water potion from cactus (not actual suggestion theme, but will be here) - WIP

Probably more if I missed something

**Comment by paulevsGitch** [comment]
- Cincinnasite shields from #80 

Will be added as a recipe for vanilla shields

**Comment by theishiopian** [comment]
Other things that would be nice:

-Minecarts
-Pistons

**Comment by paulevsGitch** [comment]
**Done:**

✔ Buckets [Recipe]
✔ Shears [Custom Item]
✔ Shields [Recipe]
✔ Rails [Recipe]


**WIP:**
- Anvil
- Water Potion
- Minecarts
- Pistons

**Comment by paulevsGitch** [comment]
**Done:**

✔ Buckets [Recipe]
✔ Shears [Custom Item]
✔ Shields [Recipe]
✔ Rails [Recipe]
✔ Anvil [Custom Block]
✔ Minecarts [Recipe]
✔ Pistons [Recipe]

**WIP:**
- Water Potion

![2020-04-30_08 43 22](https://user-images.githubusercontent.com/17707380/80677367-6d94a200-8ac1-11ea-8708-357676dcedfe.png)

**Comment by paulevsGitch** [comment]
All except water potion are in actual version

**Comment by theishiopian** [comment]
The water thing ideally should be its own issue. I can open one if you want.

**Comment by paulevsGitch** [comment]
I opened it under #95

**Comment by paulevsGitch** [comment]
Probably there may be some another recipes that need to be added
