### ISSUE TITLE
fireflies naming broken

### ISSUE THREAD

**Issue by Linguardium** [paulevsGitch/BetterNether#59]
https://github.com/paulevsGitch/BetterNether/blob/a8e0276b340b65fa30ee7ca003ce88c8ecd4873d/src/main/resources/assets/betternether/lang/en_us.json#L5

This may need to be entity.betternether.firefly

**Comment by paulevsGitch** [comment]
Thanks, will be fixed in new release. This is left over from old versions.

**Comment by paulevsGitch** [comment]
Fixed
