### ISSUE TITLE
[1.12] Nether City Generation

### ISSUE THREAD

**Issue by CalaMariGold** [paulevsGitch/BetterNether#60]
![image](https://user-images.githubusercontent.com/57605926/77129745-82ded100-6a2b-11ea-9011-dcac62dd2beb.png)

Can this be fixed please? Generation is very wonky.

**Comment by paulevsGitch** [comment]
This looks like 1.12 version

**Comment by CalaMariGold** [comment]
Rebirth of the Night is on 1.12. Would you consider updating the 1.12 version for Rebirth of the Night?

**Comment by paulevsGitch** [comment]
This bug most likely cannot be fixed, as it is related to Forge chunk events. The development of version 1.12 was stopped some months ago.

This bug can be fixed manually, after making a backup of the world. To do this use MCEdit to remove chunks with the city and then delete the file "world_folder/data/bn_city.nbt". City chunks will be regenerated, possibly correctly. If not - this can be repeated.
