### ISSUE TITLE
[Crash] crash on attempting to load dedicated server

### ISSUE THREAD

**Issue by theishiopian** [paulevsGitch/BetterNether#61]
Attempting to create a fabric server with the latest snapshot version (2.5.0 at the time of writing) does not work, the server crashes on startup.

Log: [https://pastebin.com/GhEjE1kU](url)

**Comment by theishiopian** [comment]
Interestingly, LAN mode still works

**Comment by paulevsGitch** [comment]
This is my fault, I forgot mark LavaFluidMixin as client-side, will fix it

**Comment by paulevsGitch** [comment]
Now all mixins are separated to client and common, server will work correctly
