### ISSUE TITLE
[1.12] Eyevines won't grow on blocks tagged as Netherrack

### ISSUE THREAD

**Issue by V-Boy** [paulevsGitch/BetterNether#63]
![2020-03-19_19 14 21](https://user-images.githubusercontent.com/40730042/77235699-17f5dd00-6b86-11ea-916d-0fe0562f781b.png)
Eyevines won't grow on blocks tagged as Netherrack, it will only grow on specifically netherrack. The eyevines end up looking like this.

**Comment by paulevsGitch** [comment]
This 1.12, right?

**Comment by paulevsGitch** [comment]
They grow on everything that is instance of netherrack

**Comment by V-Boy** [comment]
Are you sure? I brought it up with the NEX discord and they said that there is a forge netherrack tag, and the netherrack from that mod is in that tag, so Better Nether should be checking for the netherrack block tag not the netherrack block itself.

I understand you don't work with Forge 1.12.2 anymore though and if that's the case that's okay.

**Comment by paulevsGitch** [comment]
Looks like eye vines check only vanilla netherrack. this is not surprising since it is very old code not designed to be compatible with anything.

**Comment by paulevsGitch** [comment]
This bug is outdated and will not be fixed, in 1.16+ versions all plants use tag system
