### ISSUE TITLE
[Suggestion] Making the terrain smoothing feature into its own mod as an option

### ISSUE THREAD

**Issue by V-Boy** [paulevsGitch/BetterNether#64]
The terrain smoothing feature for nether fortresses in my opinion is very useful. However if you want to get it, you would have to get an entire nether overhaul mod. This mod is very good, but I think it would be good to have the terrain smoothing feature as a mod for people who don't want to get the full package.

**Comment by paulevsGitch** [comment]
Probably this will never be done, sorry. Someone else could make it
