### ISSUE TITLE
(suggestion) Config option for respawn statue catalyst?

### ISSUE THREAD

**Issue by DragonmasterDJ** [paulevsGitch/BetterNether#65]
As the title says, maybe there could be a new config option to change what you need to activate the respawn statue? (for instance, changing it from glowstone to a diamond, etc

**Comment by paulevsGitch** [comment]
Technically it is possible, I will think about it

**Comment by paulevsGitch** [comment]
Some months later...

![2020-07-22_18-01-07](https://user-images.githubusercontent.com/17707380/88193057-e54c1600-cc45-11ea-9212-22ce6e5fc1de.png)

![2020-07-22_18 02 53](https://user-images.githubusercontent.com/17707380/88193041-e2e9bc00-cc45-11ea-8eee-1e2d933c091f.png)

**Comment by paulevsGitch** [comment]
Implemented in 3.4.1
