### ISSUE TITLE
Problem met with Vanilla Hammers mod

### ISSUE THREAD

**Issue by linzexin022** [paulevsGitch/BetterNether#66]
in version 2.5.1, you just fixed the bug that using a sword in the third person is like holding an object, while you didn't fix the same bug on hammers. Hope you can fix this problem!
![image](https://user-images.githubusercontent.com/59003232/77851039-20df5200-7209-11ea-8775-e9c4fff80afa.png)

**Comment by paulevsGitch** [comment]
Fixed
