### ISSUE TITLE
Some blocks don’t have drop

### ISSUE THREAD

**Issue by milkev** [paulevsGitch/BetterNether#68]
found and nether city from this mod, explored for a bit
all the chests were empty and the few furnaces i found dissapeared upon breaking them, but didnt give me the block. tried mining out more of the place and random types of blocks seemed to just, not drop when mined for some reason.
on 2.5.1-1.15.X (latest for 1.15.2)

**Comment by paulevsGitch** [comment]
Please write a list of blocks without drop. I already know about furnaces and chests of drawers, they are already fixed in the code and will be in the update.

**Comment by milkev** [comment]
Bones Tiles
Flora from the pot with 3 tall mushrooms (pot drops, flora doesnt)
clarification: both netherrack furnaces and cincinnasite forges dont drop when broken, though im sure you are aware
i couldnt find any other blocks in the nether city i couldnt pick up, but i may have missed some.

idk if this is a bug or not... but all the cool flora on the ground literally everywhere isnt pick up able, with silk touch or shears. Aside from the ones that grow (seeds) and have material drops for smelting or crafting, i havent found any that drop. Most of it doesnt even show up in HYWLA so i dont know what any of it is.

**Comment by paulevsGitch** [comment]
Thank you, I will look why plants don't have drop (they must be shareable), bone tiles drop is already fixed in code as furnaces. I will try to publish new release during the week.

**Comment by milkev** [comment]
list of plants i couldnt pick up using shears:
Grey/Red Mold
Nether Grass
Egg Plant
Black Bush
2-3 block tall red/black/orange mushrooms. couldnt find the name
Soul Grass

**Comment by paulevsGitch** [comment]
Grey/Red Mold, Nether Grass, Egg Plant, Black Bush, Soul Grass — will be fixed, they are all instance of same class (this also fix other plants drop).
2-3 block tall red/black/orange mushrooms are soul lilies, they don't have drop yet (I'm still working on them).

**Comment by paulevsGitch** [comment]
Fixed
