### ISSUE TITLE
[1.12] Lag with better nether

### ISSUE THREAD

**Issue by arnaullfe** [paulevsGitch/BetterNether#70]
My issue with the betterNether is that this mod generate me a lot of lag. But, the lag is when i'm in the world dimension 0, not when i'm in the nether. The reason of the lag is this:

Better Nether::EventsHandler_onWorldSavecount(35)  total(55.33% 7.667s, 383.36% of tick)avg(219.06ms per - 191.68ms/0.88 per tick)

I don't know how solvate this issue, thanks for your help ;)

**Comment by paulevsGitch** [comment]
What version do you use?

**Comment by paulevsGitch** [comment]
Looks like you use 1.12 (EventsHandler was only in it). So, this is duplicate issue. Disable Nether City generation in the config and all must be fine.

**Comment by paulevsGitch** [comment]
Duplicate of #50
