### ISSUE TITLE
[Bug] Default generators ignoring other biomes and features

### ISSUE THREAD

**Issue by theishiopian** [paulevsGitch/BetterNether#72]
basalt deltas seem to generate very commonly in the latest version (2.6.0 for 20w15a as of writing) and even other biomes seem to have frequent pockets of basalt deltas. as a result basalt often generates on top of trees and mushrooms

**Comment by paulevsGitch** [comment]
I found that populators for biomes in new version works in different way, I'm working on it (it will also optimize world generation a bit)

**Comment by paulevsGitch** [comment]
Now they also have a mixin limiting their spawn below 42 blocks (they are spawning on all heights by default)
![2020-04-09_21 01 52](https://user-images.githubusercontent.com/17707380/78926531-e47fe180-7aa5-11ea-930b-a7d1665064d3.png)

**Comment by paulevsGitch** [comment]
Now this is fixed

**Comment by theishiopian** [comment]
Just loaded up 2.6.1, and while the frequency of the deltas has indeed been reduced, it still seems that they are overwriting other biomes. 
![2020-04-09_12 07 41](https://user-images.githubusercontent.com/8585975/78931415-c6d95a80-7a5a-11ea-9df5-93008caa8c8a.png)
This screenshot was taken in version 2.6.1.

**Comment by paulevsGitch** [comment]
Yes, Mojang feature and surface generators ignore most things. This is a big problem at now, I want to deal it in generalized way, but actually don’t know how. In theory, I can replace it with my own generators (not good for compatibility) or mixin something.

**Comment by paulevsGitch** [comment]
Proper solution for surface generator is vertical biome limiting. This will also work with structures (probably). I will try this.

**Comment by paulevsGitch** [comment]
Seems like Mojang fix their generators themselves in the latest snapshot, looks like everything is correct.

![2020-04-15_23 04 30](https://user-images.githubusercontent.com/17707380/79383657-375a0d00-7f6e-11ea-964c-9d774e744f61.png)

**Comment by paulevsGitch** [comment]
Looks like fixed, probably needs more work later
