### ISSUE TITLE
[Suggestion] upside-down forests

### ISSUE THREAD

**Issue by theishiopian** [paulevsGitch/BetterNether#73]
I recently watched Made in Abyss, and there was a biome in that show that featured upside-down forest. That could make a cool warped-forest variant, with upside-down blue wart trees and maybe a blue variant of the hydrogen jellyfish.

**Comment by paulevsGitch** [comment]
Thank you, I will think about it.

**Comment by paulevsGitch** [comment]
Some ideas:

Most trees will have massive roots covering large areas. This will create a support for small plants as a side effect.

Concept for trees:
— Willow-like tree, that looks like chandelier. Probably with glowing leaves (light blue?)
— Ball-like tree with spherical crown, supporting with many branches.
— Inverted-spruce shape (or more like equisetum) — branches form umbrellas from the biggest on top to the smallest on bottom.
— Umbrella-shaped — looks like inverted mushroom, can be a good support for other plants and constructions (probably small piglin villages and player structures)

Other plants probably will be supported with large tree roots and will not have big roots it selves. Instead, they probably will have large amount of foliage ang will look like glicinia or similar plants. Smaller plants will have very thin stems, supporting glowing organs on the ends (to attract insects)

Animals — possibly some good climbing animals with large amount of legs (like spiders), flying animals and jumping animals.

**Comment by theishiopian** [comment]
I like the way you think! As a further idea, the ball-like trees could rarely act as hives for a subspecies of ghast.

**Comment by paulevsGitch** [comment]
Progress - the largest of known nether trees - Anchor Tree, that forms the support of the Upside-Down Forest

![2020-09-14_15 28 27](https://user-images.githubusercontent.com/17707380/93086223-7916ed00-f69f-11ea-8461-d6caf4c49f1b.png)

![2020-09-14_15 28 03](https://user-images.githubusercontent.com/17707380/93086170-61d7ff80-f69f-11ea-84f5-e4debb3ad242.png)

![2020-09-14_15 22 36](https://user-images.githubusercontent.com/17707380/93086064-348b5180-f69f-11ea-9e85-b9ad939dbecb.png)

**Comment by theishiopian** [comment]
The vines are very pretty! And those trees are huge! I'll be building a treehouse for sure!

**Comment by paulevsGitch** [comment]
Aboveland ecosystem

![2020-09-15_21 34 40](https://user-images.githubusercontent.com/17707380/93250547-a3e66b80-f79b-11ea-9806-829c4b514226.png)

**Comment by paulevsGitch** [comment]
If you are interested I have discord server where I post the most recent updates

**Comment by paulevsGitch** [comment]
Added in 4.0.0

**Comment by theishiopian** [comment]
I love it! My only complaint is there should be some more grass on the ceilings. everything else is perfect. Also, I joined the discord, see you tehre!

**Comment by paulevsGitch** [comment]
I have plans to add more plants into Upside-Down forest, including some grasses and at least one tree
