### ISSUE TITLE
What will happen if i erade BetterNether mod?

### ISSUE THREAD

**Issue by AlvaroN1997** [paulevsGitch/BetterNether#74]
Hi, just got a question, so i already installed this mod and i also visited the nether, took some items, ores, and plants of the BetterNether mod, but i would like to erase the mod because is laggy for me.
Will there be any problem if i erase it? Thanks

**Comment by theishiopian** [comment]
Likely the items and blocks from the mod will disappear. Make a world backup just in case

**Comment by paulevsGitch** [comment]
In most cases, nothing bad will happen. You probably need to regenerate Nether or delete its folder (dim -1). Make world backup first.
