### ISSUE TITLE
[Bug] fireflies render behind mobs

### ISSUE THREAD

**Issue by theishiopian** [paulevsGitch/BetterNether#79]
In the latest version (2.6.3 for 20w16a) fireflies render "behind" other mobs. 
![2020-04-16_13 56 20](https://user-images.githubusercontent.com/8585975/79506298-92314a00-7fea-11ea-87e1-f5c5e1cdcfb0.png)
![2020-04-16_13 56 16](https://user-images.githubusercontent.com/8585975/79506302-92c9e080-7fea-11ea-98ee-7ea1f3b1d02c.png)

**Comment by paulevsGitch** [comment]
They use one of default render layers, and their layer get me the best result (it was always buggy, but has fewer bugs than others). I will try to find another solution, probably a custom render layer.

**Comment by paulevsGitch** [comment]
Technically it is fixed, but glass and water couldn't be seen through their glow... It's an old problem. Not in 95% cases they will render correctly (except glass and water, but only in front of these blocks)

**Comment by paulevsGitch** [comment]
Fixed
