### ISSUE TITLE
[Suggestion] Locate Command for Nether Cities

### ISSUE THREAD

**Issue by CritFlaw** [paulevsGitch/BetterNether#8]
Similar to how the vanilla game has it for fortresses and end cities, would help packdevs figure out if it's working correctly.

**Comment by paulevsGitch** [comment]
All Nether cities (for now) generation in a grid with 512 blocks (with small randomization and place check) distance between them. Adding function for finding them is semi-impossible, as it requires custom world type (which my mod doesn't use), or some asm hacks, that can cause incompatibility issues.

**Comment by CritFlaw** [comment]
Ah, ok, that's unfortunate.

**Comment by paulevsGitch** [comment]
New type of generation actually has this command, but this is not released yet

**Comment by paulevsGitch** [comment]
Added /findNetherCity
