### ISSUE TITLE
Nether music not playing.

### ISSUE THREAD

**Issue by MrBellic** [paulevsGitch/BetterNether#81]
I use the snapshot version of BetterNether, and I think something is causing an issue considering I hear NO new music.

If I remove BetterNether, it's fine.

I think it's related to the new biome related music system, and because your biomes don't have a specific music attached, it defaults to Overworld music.

Please fix it.

**Comment by paulevsGitch** [comment]
Mojang hardcoded music for the Nether and split it for their biomes. It is not related to my biome system. I will create mixin and allow other biomes have music for the Nether.

**Comment by paulevsGitch** [comment]
Some addition - sometimes nether music plays. This is strange

**Comment by paulevsGitch** [comment]
It probably can be partly related with [this](https://bugs.mojang.com/browse/MC-177819)

**Comment by paulevsGitch** [comment]
I updated mappings & loader and everything seems to be fixed (or the bug is floating). Probably this bug is not related with mod. I will mark this as questionable and will look later if it will appear in next snapshots and releases.

**Comment by paulevsGitch** [comment]
Bug is still present, I think I should try to fix it

**Comment by paulevsGitch** [comment]
Finally, it was fixed. Now each biome can have unique music
