### ISSUE TITLE
[Suggestion] New tree

### ISSUE THREAD

**Issue by Fireface677** [paulevsGitch/BetterNether#82]
I have an idea for a new tree:

- small, only 3-4 blocks tall. Looks more like a bigger bush than a real tree.
- stem similar to warped/crimson fungi but with purple pulsing effect instead of red/blue 
- deep purple wood
- orange leaves (maybe glowing a bit)
- grows with low density in soul plains or a sub biome of them

**Comment by paulevsGitch** [comment]
It can be a new variant for Soul Lily

**Comment by Fireface677** [comment]
Where are those soul lilies growing? I have never seen them before.

**Comment by paulevsGitch** [comment]
They are growing in wart forest

**Comment by Fireface677** [comment]
Oh, those things that cannot be planted. There is a soul lily sappling in the creative inventory but it cannot grow to those big flowers. Is this a bug?

**Comment by paulevsGitch** [comment]
No, they are just unfinished yet. I made their shape, but not their application. I'm still thinking.

**Comment by Fireface677** [comment]
Have you considered my tree idea?

**Comment by paulevsGitch** [comment]
Yes, I have considered your idea. I will probably implement it as a new big bush/small tree, probably in different variations. I think it shouldn't have any wood and plants, but it can get some other use in future

**Comment by Fireface677** [comment]
I thougt it would be cool to have some deep purple wood because it would look awsome with obsidian bricks.

**Comment by quiqueck** [comment]
Moving to our Enhancement List.
