### ISSUE TITLE
[Suggestion] Some small suggestions

### ISSUE THREAD

**Issue by EnderBro123** [paulevsGitch/BetterNether#83]
![speleothems](https://user-images.githubusercontent.com/51277766/80288632-04daad80-86ee-11ea-8194-f526ca36e2d0.jpg)
Similar to these from Quark, BetterNether could have nether variants of these. More uses for Netherite and Cincinnasite would also be nice to see. I would also like to see some sort of way to make tools unbreakable using the obsidian glass, or having obsidian glass tools/armor maybe, and maybe even rare cases of nether coal, iron, etc ores.

**Comment by paulevsGitch** [comment]
Stalactites are planned, I will start working on them. I'm also planning add some small rocks.

Tool unbreaking in my opinion is too unbalanced feature, I don't think that I will implement it.

Nether ores is an old idea, I'm still thinking. Sometimes it is very necessary to get some ore materials int the Nether, but if I just add ores like diamonds this will break the game lore. I can probably add coal, but when you have much more powerful sources around, like lava or blazerods, this seems to be a bit of waste, except some other mods use coal in crafts. Cincinnasite is an iron replacement for the Nether, I will add more crafts from it — buckets, shears and others. I will also add some craft stations like anvils from cincinnasite.

**Comment by EnderBro123** [comment]
It could be a toggle-able option in the config.

**Comment by EnderBro123** [comment]
Also, Stalagnate can't be MMBed on. Also, I don't think there needs to be a full bark version for the thin wood type blocks, it could easily just give you 2 planks per recipe.

**Comment by paulevsGitch** [comment]
Stalagnate will get their items. Full blocks will stay, they are firstly decorative blocks.

**Comment by EnderBro123** [comment]
Oh.

**Comment by paulevsGitch** [comment]
Stalagnate now have click items, stalagnate block crafting chain was updated a bit

**Comment by EnderBro123** [comment]
Cool. Also had a few Cincinnasite ideas.

1. Mining the ore would give you Raw Cincinnasite (A rename of the normal item)
2. Smelting 4 Raw Cincinnasite in a Netherrack Furnace would give you 1 Cincinnasite Ingot (2 Raw Cincinnasite in a Blast Furnace (This would remove the need to craft Cincinnasite blocks, smelt them, then uncraft them into ingots))

**Comment by paulevsGitch** [comment]
Cincinnasite can be processed into ingots directly from its item

**Comment by EnderBro123** [comment]
Well, you have to do the whole crafting process to do so. I was just suggesting to change it a bit

**Comment by paulevsGitch** [comment]
I mean that it is already implemented

**Comment by EnderBro123** [comment]
Alright then.

**Comment by paulevsGitch** [comment]
Large mushrooms can now be timbered like cactuses or chorus trees. It was in another suggestion thread but I forgot where

**Comment by EnderBro123** [comment]
Oh. What about the small mushrooms (The really tall but mini ones) and the Molds

**Comment by paulevsGitch** [comment]
All mushrooms can be timbered except largest (that are structures from vanilla blocks)

**Comment by EnderBro123** [comment]
Oh.

**Comment by paulevsGitch** [comment]
Stalactites, stalagmites and stalagnates. They are one block and can be placed in creative.
I think I will add more variants of them.

![2020-05-05_10 26 17](https://user-images.githubusercontent.com/17707380/81043519-0741c200-8ebb-11ea-9129-150ed71d5c0e.png)

**Comment by paulevsGitch** [comment]
Here is another one

![2020-05-05_11 02 16](https://user-images.githubusercontent.com/17707380/81071257-1c374900-8eed-11ea-80e1-0facda62c615.png)
