### ISSUE TITLE
[Suggestion] Naga suggestions

### ISSUE THREAD

**Issue by theishiopian** [paulevsGitch/BetterNether#85]
I noticed that a new mob was in the works, so I decided to build the latest commit and see what it was like. And I really like the concept! However, I have some suggestions on how to make it look better.

1. the tail currently sways back and forth, when really it should undulate when it moves and be still otherwise. A good example of this kind of movement can be seen in MO' Creature's snakes.

2. The glowing spines are really neat, but they would be even cooler if they moved a bit. i imagine them moving like a millipede's legs.

3. the head is quite large in proportion to its body. reducing its size by maybe 20% would help a lot

Overall, I really like the design, it just needs some tweaks to be really excellent!

**Comment by paulevsGitch** [comment]
Thank you, I will try to improve tail movement.

Movement of spikes will be a good addition.

The head is a bit bigger than normal mobs have (10 instead of 8) because when I tried to use vanilla head it looked to small. Probably I should try it again but after new release, I think.

**Comment by theishiopian** [comment]
Hmm, interesting. Maybe try 9 for the head size?

**Comment by paulevsGitch** [comment]
Ok, I will try

**Comment by Nathan22211** [comment]
it's wither attack also doesn't do any damage as it lasts less than a second

**Comment by paulevsGitch** [comment]
It is bug only in snapshots, other wither things like wither rose also don’t have damage (I use the same values as it). I think this is MC bug, that will be fixed. 1.15 version works fine.

**Comment by paulevsGitch** [comment]
I fixed naga projectiles, now they work as intended

**Comment by paulevsGitch** [comment]
Most things from this suggestion was implemented (except of Naga head, smaller size still looks strange, so I will remain the current one), I think this branch can be closed
