### ISSUE TITLE
[From old issue] Few bugs I noticed

### ISSUE THREAD

**Issue by EnderBro123** [paulevsGitch/BetterNether#86]
Clicking customize when making a new world crashes the game.

[crash-2020-04-26_09.00.25-client.txt](https://github.com/paulevsGitch/BetterNether/files/4535801/crash-2020-04-26_09.00.25-client.txt)

Also,
![2020-04-26_09 09 49](https://user-images.githubusercontent.com/51277766/80313083-c3094000-879d-11ea-8780-e4c72d026f12.png)

Also, there's no Willow Leaves yet apparently. And, when cutting down Willow Wood/Logs, the logs should have the same sort of skinny shape like Stalagnate (Same goes for  its other varients).

Killing a Naga crashes the game.
[OK.txt](https://github.com/paulevsGitch/BetterNether/files/4535886/OK.txt)

_Originally posted by @EnderBro123 in https://github.com/paulevsGitch/BetterNether/issues/71#issuecomment-619574294_

**Comment by paulevsGitch** [comment]
Presets bug looks simple, will fix soon.
Willow leaves was not added yet.
The bug with naga is not related to it (or looks like so), the error is in minecraft:experience_orb, which is a vanilla entity. Try to kill other mobs or gain XP other ways, if the bug will be presented - this is MC bug.

**Comment by paulevsGitch** [comment]
Naga test, all works fine.

![2020-04-27_02 45 17](https://user-images.githubusercontent.com/17707380/80322992-2e502200-8831-11ea-86c1-040942779d5b.png)

**Comment by paulevsGitch** [comment]
> when cutting down Willow Wood/Logs, the logs should have the same sort of skinny shape like Stalagnate"

Did you mean that they need thin variant, like mushroom or stalagnate stems have? If yes, I just simplified that moment, as their trunk is only a bit thinner than normal block.

**Comment by paulevsGitch** [comment]
Fixed

**Comment by EnderBro123** [comment]
> > when cutting down Willow Wood/Logs, the logs should have the same sort of skinny shape like Stalagnate"
> 
> Did you mean that they need thin variant, like mushroom or stalagnate stems have? If yes, I just simplified that moment, as their trunk is only a bit thinner than normal block.

They could have the same thin varients like the actual tree.

**Comment by paulevsGitch** [comment]
> Also (Not sure if its a rendering bug with the new entity distance setting, which I never touched), but nether jellyfish have a very short render distance. Like 15 or 20 blocks away and they disappear.

All modded entities have it, I think this is an API bug. If it will not be fixed to next snapshot I will try do it myself

**Comment by EnderBro123** [comment]
Alright.

**Comment by EnderBro123** [comment]
Stalagnate can't be MMBed on to get the stem/bark.

**Comment by EnderBro123** [comment]
Stalagnate can't be MMed on. Also, I don't think there needs to be a full bark version for the thin wood type blocks, it could easily just give you 2 planks per recipe.
