### ISSUE TITLE
[Bug] Some bugs I noticed

### ISSUE THREAD

**Issue by Fireface677** [paulevsGitch/BetterNether#87]
- No soul soil generating on the surface of soul sand valleys.
- There are still some plants that do not drop anything when destroyed. (vines, swamp gras, egg plants etc.) Maybe you should check them all. 

I really love the new biome generation. It looks really good now.

**Comment by paulevsGitch** [comment]
Plants and vines needs shears to collect them.
I will fix soul soil generation

**Comment by paulevsGitch** [comment]
The only plant that cannot be collected with shears is egg plant, I will fix it

**Comment by paulevsGitch** [comment]
Fixed
