### ISSUE TITLE
Incompatibility with Apotheosis

### ISSUE THREAD

**Issue by Shadows-of-Fire** [paulevsGitch/BetterNether#9]
Somewhere in your mod you are directly setting a `TileEntityMobSpawner` into the world.  This makes your mod incompatible with Apotheosis or any other mod that may override the type of tile entity the spawner uses.  There is no reason to ever directly instantiate that class (or set a tile into the world, since setting a block into the world will spawn it's proper tile).  

If you are certain you need to instantiate a spawner's tile instead of using one in-world, use `Blocks.MOB_SPAWNER.createTileEntity` instead.

Until that change is made, crashes such as this will result https://hastebin.com/izedaxogix.sql

**Comment by paulevsGitch** [comment]
My mod doesn’t create mob spawners anywhere. Structures used structure block for placement. So this is not issue of my mod.

**Comment by Shadows-of-Fire** [comment]
This is not a non-issue.  You are loading your structure blocks in preinit (before block registration) and as a result are pulling the wrong spawner block from the registry, caching that value.

At runtime, you are generating an incorrect tile entity into the world as a result. 
![](https://i.imgur.com/kX5qOTi.png)

You need to move the loading of your structures to init.

**Comment by paulevsGitch** [comment]
Ok, I will change it in next release

**Comment by CritFlaw** [comment]
Any ETA on this change?

**Comment by Pival81** [comment]
Any updates on this?

**Comment by paulevsGitch** [comment]
This issue is not closed, so — no updates. The solution to the problem is known, but at the moment I don’t have time to remove this bug.
