### ISSUE TITLE
[Suggestion] Nether beekeeping, redstone, and flying machines

### ISSUE THREAD

**Issue by theishiopian** [paulevsGitch/BetterNether#90]
Flying machines, in case you didn't know, are built out of slime or honey blocks, pistons and observers, and are self propelled redstone contraptions. Built correctly, they can be a great way of traversing the nether. However, it is currently impossible to make them in the nether without materials imported from the overworld. I propose a new mob to provide the needed resources: red bees.

A red bee is similar to a bee, but is closer to a wasp in temperament. unlike normal bees, the do not die after stinging, and they cannot be pacified with smoke. They live in hives in the nether jungle, and are immediately hostile to players, as well as piglins. Like regular bees, they will inhabit player made beehives, but only those made from nether materials. They pollinate nether plants, and their hives produce both honey and redstone.

Why bees, and not some form of redstone ore? Well, bees are more interesting, and specifically for airships, honey is a better material than slime, due to its ability to carry players along. As for HOW the bees are getting the redstone, I kinda assume its a byproduct, like beeswax, but more useful.

Due to their hostility, the bees can also be used as a defense system. Smoking their hives will have the opposite effect than to normal bees, causing the bees to swarm. With clever use of dispensers, you could make an automatic swarming system.

**Comment by quiqueck** [comment]
Moving to our Enhancement List.
