### ISSUE TITLE
[Suggestion] Implement earlier concept of Nether biome

### ISSUE THREAD

**Issue by paulevsGitch** [paulevsGitch/BetterNether#91]
Try to implement this as a biome with orange ground cover and orange fluffy trees (with very dense leaves) with white trunk.

![image](https://user-images.githubusercontent.com/17707380/80447977-a434b600-8923-11ea-923c-e628db9f9b16.png)

**Comment by theishiopian** [comment]
those big orange things look solid to me. Like gargantuan orange nether warts. They could be hollow and have little ecosystems in them, like a bromeliad flower.

**Comment by paulevsGitch** [comment]
Probably they are wart trees or something like that, but they are shown a bit fluffy. I think that it can be interpreted like this.

The idea of hollow trees is interesting, but they need to be very large. I think I will reserve it for upside-down forest.

**Comment by theishiopian** [comment]
interesting, so maybe they have a solid core and a fluffy exterior. you could do that with a modified version of the red grass that grows on the sides of blocks. From a distance it will give them a sort of "fuzzy" look, similar to the better foliage mod.

**Comment by quiqueck** [comment]
Moving to our Enhancement List.
