### ISSUE TITLE
[Suggestion] Nether Volcano Structure

### ISSUE THREAD

**Issue by quantum-ranger** [paulevsGitch/BetterNether#96]
A Nether Volcano would be a large structure or sub-biome made up of blackstone, basalt, and magma blocks, that would generate primarily in Basalt Deltas and similar biomes. It would consist primarily of a large crater/entrance on the surface, a vent which travels down and branches off into different side vents/caves, and a giant magma chamber at the very bottom underground.

A Nether Volcano would be the most dangerous of areas in the Nether, containing its own ecosystem including ghasts, blazes, creepers, magma cubes, hydrogen jellyfish, and other explosive and fire/lava-based mobs. Side vents would contain loot and nests for mobs to spawn, and the magma chamber would be a huge cavern filled nearly to the brim with lava. Players would have to be cautious when digging straight down as a result. Mobs would be able to spawn near the outside crater of the Nether Volcano as well.

Overall, the danger of exploring a Nether Volcano would be worth it, as the loot would consist of very valuable materials like obsidian, diamonds, netherite items, and enchanted books. These would be found more commonly than they would be in the much less dangerous Nether Fortresses and Bastion Remnants, as to not make it seem too unfair or unbalanced for players.

**Comment by paulevsGitch** [comment]
I think it is strange to have a volcano in a cave-world filled with lava. Biomes like Magma Lands and Basalt Deltas could replace it as well
