### ISSUE TITLE
[Suggestion] New types of vanilla blocks

### ISSUE THREAD

**Issue by witheredsteve** [paulevsGitch/BetterNether#98]
Please add Warped Wart, Basalt Slabs, Walls and Stairs, Polished Basalt Slabs and Stairs, Polished Basalt Bricks Slabs, Walls and Stairs, Chiseled Polished Basalt, Soul Sandstone Slabs, Walls and Stairs, Smooth Soul Sandstone, Chiseled Soul Sandstone, Polished Soul Sandstone

**Comment by paulevsGitch** [comment]
The idea with **Warped Wart** is not very clear to me, there are already such blocks in the game.

This blocks I will probably add but I'm afraid of intersections with official Mojang content:

**Basalt blocks:**
• Slabs
• Walls
• Stairs

**Polished Basalt blocks:**
• Slabs
• Walls
• Stairs
• Bricks

**Polished Basalt Bricks blocks:**
• Slabs
• Walls
• Stairs

I personally like this idea, I will probably add this into next large update:

**Sandstone**
• Soul Sandstone
• Smooth Soul Sandstone
• Chiseled Soul Sandstone
• Polished Soul Sandstone

**Comment by paulevsGitch** [comment]
![2020-06-19_01 48 34](https://user-images.githubusercontent.com/17707380/85083135-87a55380-b1d9-11ea-8424-a9fea2eef7cb.png)

**Comment by paulevsGitch** [comment]
Soul Sandstone is now in mod

**Comment by paulevsGitch** [comment]
Basalt bricks
![2020-06-22_17 01 42](https://user-images.githubusercontent.com/17707380/85307414-8feede80-b4b8-11ea-910d-b4e15feef72b.png)
