### ISSUE TITLE
[suggestion] some suggestions

### ISSUE THREAD

**Issue by ASingleMelon** [paulevsGitch/BetterNether#99]
hello! i really like this mod and its probably my favorite environmental mod on minecraft

theres an issue where when i try to break the nether woods with any axe they break at the same speed as my fist, except the cincinnasite-diamond axe

your plants have inspired me to make my own, and i wanted to share an idea for a mushroom aswell as some suggestions,

- **the devil's palm** A giant mushroom whose red branches stretch forth releasing a pungent smell that could attract creatures like hoglins and fireflies. this mushroom would look similar to a palm tree except with red tentacles and inky goo on them instead of fronds, like [this](https://en.wikipedia.org/wiki/Clathrus_archeri) and they could have logs with white bark and black wood

- You could pick up willow cones and hang them like rubeus cones, and use their branches like chains for both

- Lucis mushrooms could give you glowing wood when chopped

- nether / obsidian tiles could be made in the stone cutter

anyway this mod is amazing, your doing a great job!

**Comment by paulevsGitch** [comment]
Some things from this suggestion needs to be implemented

**Comment by paulevsGitch** [comment]
Willow torches are in 4.1.0.
Lucis mushrooms now have a block of giant lucis, it will be probably growable.
Planned: stonecutter recipes and the devil's palm (probably)

**Comment by quiqueck** [comment]
Stonecutter for Obsidian Variants is in v5.3.5, Others will be added in later updates.

**Comment by quiqueck** [comment]
Moving to our Enhancement List.
